export default {
    SET_TASKS:"SET_TASKS",
    BPM_USER_LIST:"BPM_USER_LIST",
    SET_USER_GROUPS:"SET_USER_GROUPS",
    SET_USER_DETAILS: "SET_USER_DETAILS",
    ERROR: "ERROR",
    IS_PROCESS_STATUS_LOADING:"IS_PROCESS_STATUS_LOADING",
    SET_USER_ROLES: "SET_USER_ROLES",
    BPM_LIST_TASKS: "BPM_LIST_TASKS",
    BPM_TASKS_COUNT: "BPM_TASKS_COUNT",
    IS_BPM_TASK_LOADING: "IS_BPM_TASK_LOADING",
    BPM_VISSIBLE_ATTRIBUTES: "BPM_VISSIBLE_ATTRIBUTES",
    UPDATE_LIST_PARAMS: "UPDATE_LIST_PARAMS",
    BPM_TASK_LIST_ACTIVE_PAGE: "BPM_TASK_LIST_ACTIVE_PAGE",
    DEFAULT_FILTER: "DEFAULT_FILTER",
    BPM_FILTER_LIST: "BPM_FILTER_LIST",
    IS_BPM_FILTERS_LOADING: "IS_BPM_FILTERS_LOADING",
    BPM_SELECTED_FILTER: "BPM_SELECTED_FILTER",


}