export default {
  SET_TASKS: "SET_TASKS",
  TASKLIST: "TASKLIST",
  TASK_LIST_LIMIT_CHANGE: "TASK_LIST_LIMIT_CHANGE",
  TASK_LIST_PAGE_CHANGE: "TASK_LIST_PAGE_CHANGE",
  TASK_LIST_SORT_CHANGE: "TASK_LIST_SORT_CHANGE",
  TASK_SORT: "TASK_SORT",
};
