/* eslint-disable max-len */
// Portuguese
export const RESOURCE_BUNDLES_PT ={
  "Latest Submission": "Submissões",
  "Filter Created by": "Filtro criado por",
  "Submit Form": "Enviar Formulário",
  "Changes Applied Successfully": "Alterações Aplicadas com Sucesso",
  "Filter Deleted Successfully": "Filtro Excluído com Sucesso",
  "Save Filter": "Salvar Filtro",
  "Filter Name": "Nome do filtro",
  "Create new filter": "Criar novo filtro",
  "Definition Key": "Chave de definição",
  "Permission": "Permissão",
  "Enter your text here": "Digite seu texto aqui",
  "Accessible for all users": "Acessível para todos os usuários",
  "Private (Only You)": "Privado (só você)",
  "Specific Group": "Grupo Específico",
  "Select Elements": "Selecionar Elementos",
  " Task Attributes Selected": " Atributos da Tarefa Selecionados",
  "Delete Filter": "Excluir Filtro",
  "Add Value": "Adicionar valor",
  "Show only current user assigned task": "Mostrar apenas tarefas atribuídas ao usuário atual",
  "Show task based on logged user roles": "Mostrar tarefas com base nos papéis do usuário conectado",
  "Create Filter": "Criar filtro",
  "Task Attributes": "Atributos da Tarefa",
  "Only selected task attributes will be available on task list view": "Apenas os atributos selecionados da tarefa estarão disponíveis na visualização da lista de tarefas",
  "Show undefined variables": "Mostrar variáveis indefinidas",
  "Label": "Etiqueta",
  "Variables": "Variáveis",
  "Task Title": "Título da Tarefa",
  "List View": "Visualização em Lista",
  "Card View": "Visualização em Cartões",
  "Create New Filter": "Criar Novo Filtro",
  "Sort by": "Ordenar por",
  "Collapse All": "Recolher Tudo",
  "Expand All": "Expandir Tudo",
  "Application Id": "ID da Aplicação",
  "Back to task": "Voltar para a tarefa",
  "Filters": "Filtros",
  "Assignee": "Cessionária",
  "Select a user": "Selecionar um usuário",
  "Create DMN": "Criar DMN",
  "Create Process": "Criar Processo",
  "Edit DMN": "Editar DMN",
  "More options": "Mais opções",
  "Form Description": "Descrição do Formulário",
  "Saved to Submissions/Drafts": "Salvo em Submissões/Rascunhos",
  "Unfinished submissions will be saved to Submissions/Drafts.": "Submissões inacabadas serão salvas em Submissões/Rascunhos.",
  "Edit Process": "Editar Processo",
  "Add filter name": "Adicionar nome do filtro",
  "This section is aimed to set the parameters\nused to filter the tasks": "Esta seção tem como objetivo definir os parâmetros\nusados para filtrar as tarefas",
  "This section is aimed to set read\npermissions for the filter": "Esta seção tem como objetivo definir permissões\nde leitura para o filtro",
  "This section is aimed to set select\ntask attributes that will be visible in\nthe task list view": "Esta seção tem como objetivo definir\nos atributos da tarefa que serão visíveis\nna visualização da lista de tarefas",
  "Task Attribute": "Atributo da Tarefa",
  "You can define variables shown in the list": "Você pode definir variáveis mostradas na lista",
  "results": "resultados",
  "Enter role name": "Digite o nome da função",
  "Public": "Público",
  "View Submitted Form": "Ver Formulário Enviado",
  "View Draft Details": "Ver Detalhes do Rascunho",
  "Edit Draft": "Editar Rascunho",
  "Draft Title": "Título do Rascunho",
  "Filter": "Filtro",
  "Advanced Options": "Opções Avançadas",
  "Enter the path name": "Digite o nome do caminho",
  "Search by form title": "Buscar por título de formulário",
  "Associate Workflow": "Associar Fluxo de Trabalho",
  "Search by workflow name": "Buscar por nome de fluxo de trabalho",
  "View Details": "Ver Detalhes",
  "Visibility": "Visibilidade",
  "Form Title": "Título do Formulário",
  "Access restricted by its designer..!": "Acesso restrito pelo designer..!",
  "and you will no longer have the access to this form in bundles": "e você não terá mais acesso a este formulário em pacotes",
  "You will no longer have the access to this form in bundles": "Você não terá mais acesso a este formulário em pacotes",
  "Bad Request": "Pedido ruim",
  "Select the form to be displayed based on the  above criteria": "Selecione o formulário a ser exibido com base nos critérios acima.",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "Crie os critérios usando a chave API de qualquer componente de formulário e uma notação condicional. Por exemplo, 'age > 18', onde 'age' é a chave API de um componente de formulário.",
  "Select form version": "Selecione a versão do formulário",
  "Please remove the special characters...!": "Remova os caracteres especiais...!",
  "No histories found": "Nenhum histórico encontrado",
  "Continue": "Prosseguir",
  "This will create a new version of the form without changing the path name but with new form id.": "Isso criará uma nova versão do formulário sem alterar o nome do caminho, mas com o novo ID do formulário.",
  "Save as a new version": "Salvar como uma nova versão",
  "Save New Version": "Salvar nova versão",
  "Do you want to save a new version of this form?": "Deseja salvar uma nova versão deste formulário?",
  "Do you want to create a duplicate form and associated workflow from existing form ?": "Deseja criar um formulário duplicado e um fluxo de trabalho associado a partir de um formulário existente?",
  "New version created": "New version created",
  "Create a duplicate form": "Criar um formulário duplicado",
  "Show more": "Mostre mais",
  "Modified By": "Modificado por",
  "Created On": "Criado em",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "O Formsflow salva automaticamente os dados do formulário anterior. Agora você pode mudar para o estágio anterior e editar.",
  "Duplicate Form": "Formulário Duplicado",
  "Form History": "Histórico do formulário",
  "No file chosen": "Nenhum arquivo selecionado",
  "Choose File": "Escolher arquivo",
  "Choose any": "Escolha qualquer",
  "Sort by form name": "Classificar por nome do formulário",
  "select form type": "selecione o tipo de formulário",
  "Draft Deleted Successfully": "Rascunho excluído com sucesso",
  "Saved to Applications/Drafts": "Salvo em Aplicações/Rascunhos",
  "Unfinished applications will be saved to Applications/Drafts.": "Os aplicativos inacabados serão salvos em Aplicativos/Rascunhos.",
  "Discard Draft": "Descartar Rascunho",
  "with ID": "com identidade",
  "Please change the selected filters to view Forms": "Por favor, altere os filtros selecionados para visualizar os formulários",
  "Search by form name": "Pesquisar pelo nome do formulário",
  "Click to search": "Clique para pesquisar",
  "No submissions found": "Nenhum envio encontrado",
  "No submission avaliable in the selected date. Please select another date range": "Nenhuma submissão disponível na data selecionada. Selecione outro intervalo de datas",
  "Dashboards": "Painéis",
  "Form field": "Campo do formulário",
  "Enter Label": "Digite o rótulo",
  "Select form field": "Selecione o campo do formulário",
  "Latest Version": "Última versão",
  "Submission Status": "Status de submissão",
  "No submission status": "Sem status de envio",
  "No Public url found": "Nenhum URL público encontrado",
  "Show in list": "Mostrar na lista",
  "Select Task Variable": "Selecione a variável de tarefa",
  "Enter your Label": "Digite seu rótulo",
  "Please select from one of the following workflows.": "Selecione um dos fluxos de trabalho a seguir.",
  "Select Key": "Selecionar chave",
  "Create Your Task Variable": "Crie sua variável de tarefa",
  "No task variable selected": "Nenhuma variável de tarefa selecionada",
  "Workflow Associate": "Associado de fluxo de trabalho",
  "Task variable": "Variável de tarefa",
  "Enter pathname": "Digite o nome do caminho",
  "Submission Saved": "Envio salvo.",
  "Error while Submission.": "Erro durante o envio.",
  "Submission cannot be done.": "O envio não pode ser feito.",
  "Error in getting Workflow Process.": "Erro ao obter o processo de fluxo de trabalho.",
  "Form saved": "Formulário salvo.",
  "Error while saving Form.": "Erro ao salvar o formulário.",
  "Forms": "Formulários",
  "Edit": "Editar",
  "Text Field": "Campo de texto",
  "Do you want to associate form with a workflow ?": "Você deseja associar o formulário a um fluxo de trabalho?",
  "Yes": "sim",
  "Type": "Tipo",
  "No": "Não",
  "Form Name": "Nome do formulario ",
  "Workflow Name": "Nome do fluxo de trabalho",
  "Publish this form for Client Users.": "Publique este formulário para usuários clientes.",
  "Comments": "Comentários",
  "Back": "Voltar",
  "Edit Form": "Editar Formulário",
  "Next": "Próxima",
  "Save": "Salve ",
  "Back to Form List": "Voltar para a lista de formulários",
  "Submit New": "Enviar novo",
  "View Submissions": "Ver os envios",
  "View/Edit Form": "Ver / Editar Formulário",
  "Delete Form": "Apagar Formulário",
  "Delete": "Excluir",
  "Print As PDF": "Imprimir como PDF",
  "Applications": "Formulários",
  "Tasks": "Tarefas",
  "Dashboard": "Painel",
  "Logout": "Sair",
  "No tasks found": "Nenhuma tarefa encontrada",
  "Please change the selected filters to view tasks": "Por favor, mude os filtros selecionados para ver as tarefas",
  "Clear all filters": "Limpar todos os filtros",
  "Created": "Criada",
  "Task Variables": "Variáveis de Tarefa",
  "Process Variables": "Variáveis de Processo",
  "Process Definition Name": "Nome da Definição do Processo",
  "Assigne": "Cessionária",
  "Candidate Group": "Grupo de Candidatos",
  "Candidate User": "Usuário candidato",
  "Name": "Nome",
  "Description": "Descrição",
  "Priority": "Prioridade",
  "Due Date": "Data de vencimento",
  "Follow up Date": "Data de Acompanhamento",
  "Task name": "Nome da tarefa",
  "Remove sorting": "Remover classificação",
  "Asending": "Ascendente",
  "Descending": "descendente",
  "Add sorting": "Adicionar classificação",
  "of the criteria are met.": "dos critérios são atendidos.",
  "For Variable, ignore case of": "Para variável, ignore o caso de",
  "name": "nome",
  "value": "valor",
  "No task matching filters found.": "Nenhum filtro de correspondência de tarefa encontrado.",
  "Set follow-up Date": "Definir data de acompanhamento",
  "Set Due date": "Definir data de vencimento",
  "Add groups": "Adicionar grupos",
  "Claim": "Alegar",
  "Search By Last Name": "Pesquisar por Sobrenome",
  "Search By First Name": "Pesquisar pelo primeiro nome",
  "Search By Email": "Pesquisa por e-mail",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Você pode adicionar um grupo digitando um ID de grupo no campo de entrada e, em seguida, clicando no botão com o sinal de mais.",
  "Add a group": "Adicionar um grupo",
  "Process Name": "Nome do processo",
  "Set FollowUp Date": "Definir data de acompanhamento",
  "Groups": "grupos",
  "Click to Change Assignee": "Clique para alterar o responsável",
  "Reset Assignee": "Reiniciar cessionário",
  "Update User": "Atualizar usuário",
  "Close": "Fechar",
  "Remove search": "Remover pesquisa",
  "Property": "Propriedade",
  "Operator": "Operadora",
  "Total number of results": "Número total de resultados",
  "Filter Tasks": "Filtrar tarefas",
  "ANY": "ALGUMA",
  "Task assignee": "Responsável pela tarefa",
  "Application History": "Histórico da Aplicação",
  "View Submission": "Ver o envio",
  "Showing": "Mostrando",
  "Results": "resultados",
  "Acknowledge": "Reconhecer",
  "Select a task in the list.": "Selecione uma tarefa na lista.",
  "No Filters Found": "Nenhum filtro encontrado",
  "Loading": "Carregando",
  "Form": "Forma",
  "History": "História",
  "Diagram": "Diagrama",
  "Delete Confirmation": "Confirmação de exclusão",
  "All tasks": "Todas as tarefas",
  "Manage Groups": "Gerenciar grupos",
  "Group ID": "ID do grupo",
  "Due": "Devida",
  "Follow-up": "Acompanhamento",
  "Please fix the errors before submitting again.": "Corrija os erros antes de enviar novamente.",
  "Form-Workflow association saved.": "Associação formulário-fluxo de trabalho salva.",
  "Form-Workflow association failed.": "Falha na associação Formulário-Fluxo de trabalho.",
  "Application Status": "Status do aplicativo",
  "Request Status": "Status da Solicitação",
  "Request Name": "Nome da Solicitação",
  "Submitted On": "Enviado em",
  "Modified On": "Modificado em",
  "No History Found": "Nenhum histórico encontrado",
  "Process Diagram": "Diagrama de Processo",
  "Details": "Detalhes",
  "example": "Exemplo",
  "Path": "Caminho",
  "Status": "Status",
  "Submissions": "Submissões",
  "No Application History found": "Nenhum histórico de aplicativo encontrado",
  "Link To Form Submission": "Link para o envio do formulário",
  "Last Modified": "Última modificação",
  "All": "Tudo",
  "view": "Visualizar",
  "Insights": "Intuições",
  "Metrics": "Métricas",
  "No dashboard found": "Nenhum painel encontrado",
  "to": "para",
  "of": "do",
  "Application ID": "ID do aplicativo",
  "Total Submissions": "Total de inscrições",
  "Operations": "Operações",
  "Access Groups": "Grupos de acesso",
  "Action": "Açao",
  "Add": "Adicionar",
  "Admin": "Administrador",
  "Create Form": "Criar formulário",
  "Upload Form": "Carregar formulário",
  "Download Form": "Baixar formulário",
  "Upload json form only": "Carregar apenas o formulário json",
  "Select atleast one form": "Selecione pelo menos um formulário",
  "Select All": "Selecionar tudo",
  "Created Date": "Data de criação",
  "Modified Date": "Data modificada",
  "File Upload Status": "Status de upload de arquivo",
  "Forms Completed": "Formulários preenchidos",
  "Form Completed": "Formulário preenchido",
  "No forms found": "Nenhum formulário encontrado",
  "Powered by ": "Distribuído por ",
  "No Process Diagram found": "Nenhum diagrama de processo encontrado",
  "No applications found": "Nenhum aplicativo encontrado",
  "Successfully Updated": "Atualizado com sucesso",
  "Failed": "Fracassada",
  "Press Enter key or click here to search": "Pressione a tecla Enter ou clique aqui para pesquisar",
  "Click to clear": "Clique para limpar",
  "Search...": "Procurar...",
  "Click here to back": "Clique aqui para voltar",
  "Enter the form title": "Digite o título do formulário",
  "Enter the form machine name": "Digite o nome da máquina do formulário",
  "Title": "Título",
  "Display as": "Mostrar como",
  "Anonymous Form ": "Formulário anônimo?",
  "Make this form public ?": "Tornar este formulário público?",
  "Save & Preview": "Salvar e visualizar",
  "Select Dashboard": "Selecionar painel",
  "Design Form": "Formulário de Design",
  "Associate this form with a workflow?": "Associar este formulário a um fluxo de trabalho?",
  "Preview and Confirm": "Pré-visualizar e confirmar",
  "All steps completed - you're finished": "Todas as etapas concluídas - você terminou",
  "Downloaded Successfully": "Baixado com sucesso",
  "Error in JSON file structure": "Erro na estrutura do arquivo JSON",
  "Loading...": "Carregando...",
  "Wizard": "Mago",
  "Save Form": "Salvar formulário",
  "Confirm": "confirme",
  "Cancel": "Cancelar",
  "Please change the selected filters to view applications": "Por favor, altere os filtros selecionados para visualizar os aplicativos",
  "No submissions available for the selected date range": "Nenhum envio disponível para o período selecionado",
  "Ok": "OK",
  "Form not available": "Formulário não disponível",
  "Thank you for your response.": "Obrigado pela sua resposta.",
  "saved successfully": "Salvo com sucesso",
  "Copy anonymous form URL": "Copiar URL de formulário anônimo",
  "Submitted By": "Enviado por",
  "Confirmation": "Confirmação",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Alterar o título do formulário não afetará os aplicativos existentes. Ele só será atualizado nos aplicativos recém-criados. Pressione Salvar alterações para continuar ou cancelar as alterações.",
  "Error while saving Form": "Erro ao salvar o formulário",
  "Click here to go back": "Clique aqui para voltar",
  " Applications are submitted against": " As candidaturas são apresentadas contra",
  " Application is submitted against": " As candidaturas são apresentadas contra",
  "Are you sure to delete the": "Tem certeza de que deseja excluir",
  "Are you sure to delete the draft": "Tem certeza de que deseja excluir o rascunho",
  "Are you sure to delete this submission ?": "Tem certeza de que deseja excluir esta submissão?",
  " Submissions are made against": " As submissões são feitas contra",
  " Submission is made against": " A submissão é feita contra",
  "Save Changes": "Salvar alterações",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Alterar o fluxo de trabalho do formulário não afetará os aplicativos existentes. Ele só será atualizado nos aplicativos recém-criados. Pressione Salvar alterações para continuar ou cancelar as alterações.",
  "Form deletion unsuccessful": "Falha na exclusão do formulário",
  "Form deleted successfully": "Formulário excluído com sucesso",
  "Bundle deleted successfully": "Pacote excluído com sucesso",
  "Form process failed": "Falha no processo do formulário",
  "Form unpublishing Failed": "Falha ao cancelar a publicação do formulário",
  "All groups have access to the dashboard": "Todos os grupos têm acesso ao painel",
  "Export PDF": "Exportar PDF",
  "Something went wrong. Please try again!": "Algo deu errado. Por favor, tente novamente!",
  "No Dashboards Found": "Nenhum painel encontrado",
  "Processes": "Processos",
  "Please select an existing workflow.": "Selecione um fluxo de trabalho existente.",
  "Create New": "Crie um novo",
  "Or create new workflow or import a workflow from a local directory.": "Ou crie um novo fluxo de trabalho ou importe um fluxo de trabalho de um diretório local.",
  "The operation couldn't be completed. Please try after sometime": "A operação não pôde ser concluída. Por favor, tente depois de algum tempo",
  "Select...": "Selecionar...",
  "No Drafts Found": "Nenhum rascunho encontrado",
  "Help": "Ajuda",
  "Draft Id": "ID de rascunho",
  "Draft Name": "Nome do rascunho",
  "Link To Draft Submission": "Link para envio de rascunho",
  "Drafts": "Rascunhos",
  "You can't submit this form until it is published": "Você não pode enviar este formulário até que ele seja publicado",
  "Form not published": "Formulário não publicado",
  "Access Denied": "Acesso negado",
  "By default, the tenant key would be prefixed to form": "Por padrão, a chave do locatário seria prefixada para formar",
  "go back": "volte",
  "No Applications Found": "Nenhum aplicativo encontrado",
  "Submission saved to draft.": "Envio salvo como rascunho.",
  "Saved to draft": "Salvo no rascunho",
  "Saving...": "Salvando...",
  "Resource": "Recurso",
  "Error in creating form process mapper": "Erro ao criar mapeador de processo de formulário",
  "Select the date": "Selecione a data",
  "Diagram deployed": "Diagrama implantado",
  "Deployment failed": "Falha na implantação",
  "form uploaded": "formulário carregado",
  "forms uploaded": "formulários carregados",
  "Failed to upload": "Falha ao carregar",
  "forms...!": "formas...!",
  "form...!": "forma...!",
  "Process name(s) must not be empty": "O(s) nome(s) do processo não deve(m) estar vazio(s)",
  "URL copied": "URL copiado",
  "Click Here to Copy": "Clique aqui para copiar",
  "Resources": "Recursos",
  "Duplicate form created successfully": "Formulário duplicado criado com sucesso",
  "Revert": "Reverter",
  "Overview": "Visão geral",
  "Design Permission": "Permissão de design",
  "Application Permission": "Permissão de aplicativo",
  "All Designers": "Todos os Designers",
  "Private(only you)": "Privado(só você)",
  "Specific Designer Group": "Grupo específico de designers",
  "Submission Permission": "Permissão de envio",
  "All Users": "Todos os usuários",
  "Specific User Group": "Grupo de usuários específico",
  "Specific Reviewers": "Revisores Específicos",
  "All Reviewers": "Todos os revisores",
  "Permission for application tracking.": "Permissão para rastreamento de aplicativos.",
  "Criteria": "Critério",
  "Select Form": "Selecione o formulário",
  "Create Condition": "Criar condição",
  "Enter criteria": "Insira os critérios",
  "Make this form public": "Tornar este formulário público",
  "Enable bundling": "Ativar agrupamento",
  "Applicable for Designer Roled Users only.": "Aplicável apenas para usuários com função de designer.",
  "Applicable for Client and Reviewer Roled Users only.": "Aplicável apenas para usuários com função de cliente e revisor.",
  "Bundle Name": "Nome do pacote",
  "View/Edit": "Visualizar edição",
  "Create Bundle": "Criar pacote",
  "Rows per page": "Linhas por página",
  "Items per page": "Itens por página",
  "entries": "entradas",
  "Form Bundle": "Pacote de formulários",
  "No bundles found": "Nenhum pacote encontrado",
  "Please change the selected filters to view Bundles": "Por favor, altere os filtros selecionados para ver os pacotes",
  "Select all to download forms": "Selecione tudo para baixar os formulários",
  "Select for download": "Selecione para baixar",
  "Bundle Description": "Descrição do Pacote",
  "Conditions": "condições",
  "Enter name": "Insira o nome",
  "Enter Description": "Insira a descrição",
  "You can change the form order by drag and drop": "Você pode alterar a ordem do formulário arrastando e soltando",
  "Form Order": "Pedido de formulário",
  "Form Type": "Tipo de formulário",
  "Add Forms Launch together": "Adicionar formulários lançados juntos",
  "Form bundles can save your time by grouping forms together": "Pacotes de formulários podem economizar seu tempo agrupando formulários",
  "Add Forms": "Adicionar formulários",
  "Create Conditions": "Criar Condições",
  " Add Conditions": "Adicionar condições",
  "Select Forms": "Selecionar formulários",
  "Insert": "Inserir",
  "View Form": "Ver formulário",
  "Publish this Bundle for Client Users.": "Publique este pacote para usuários clientes",
  "Total Forms": "Formulários totais",
  "Edit Bundle": "Editar pacote",
  "Next Form": "Próximo formulário",
  "Previous Form": "Formulário anterior",
  "Forms included under the package": "Formulários incluídos no pacote",
  "Submit": "Enviar",
  "Reset Zoom": "Redefinir zoom",
  "Zoom In": "Mais Zoom",
  "Zoom Out": "Reduzir o zoom",
  "Deploy": "Implantar",
  "Export": "Exportar",
  "Design Bundle": "Pacote de design",
  "Workflow": "fluxo de trabalho",
  "Bundle Name and Description is Required": "O nome e a descrição do pacote são obrigatórios",
  "Bundle Description is Required": "A descrição do pacote é obrigatória",
  "Bundle Create Successfully": "Pacote criado com sucesso",
  "Bundle updated successfully": "Pacote atualizado com sucesso",
  "Select": "Selecionar",
  "Unselect": "Desmarcar",
  "Done": "Feito",
  "Failed to update permission!": "Falha ao atualizar a permissão!",
  "Failed to fetch roles!": "Falha ao buscar papéis!",
  "Failed to update role!": "Falha ao atualizar função!",
  "Permission updated successfully!": "Permissão atualizada com sucesso!",
  "Role updated successfully!": "Função atualizada com sucesso!",
  "Update failed!": "Atualização falhou!",
  "Clear": "Claro",
  "Are you sure deleting the role": "Tem certeza de que está excluindo a função",
  "Confirm Delete": "Confirmar exclusão",
  "All roles": "Todas as funções",
  "Filter By:": "Filtrar por:",
  "Create": "Criar",
  "Eg: Account Manager": "Ex: Gerente de contas",
  "View": "Visualizar",
  "Search by name, username or email": "Pesquise por nome, nome de usuário ou e-mail",
  "No data Found": "Nenhum dado encontrado",
  "Roles": "Funções",
  "Users": "Usuários",
  "Create New Role": "Criar nova função",
  "Search by role name": "Pesquise pelo nome da função",
  "Role Name": "Nome do papel",
  "Actions": "Ações",
  "Create Role": "Criar função",
  "Email": "E-mail",
  "Role": "Papel",
  "Add Role": "Adicionar Função",
  "Role deleted successfully!": "Função excluída com sucesso!",
  "Failed to delete role!": "Falha ao excluir a função!",
  "Role created successfully!": "Função criada com sucesso!",
  "Failed to create role!": "Falha ao criar função!",
  "Update success!": "Atualização feita com sucesso!",
  "No results found": "Nenhum resultado encontrado",
  "Edit Role": "Editar função",
  "Failed to fetch users!": "Falha ao buscar usuários!",
  "Role names cannot contain special characters except   _ , -": "Os nomes das funções não podem conter caracteres especiais, exceto _ , -",
  "Role names cannot contain special characters except _ , - , / ": "Os nomes das funções não podem conter caracteres especiais, exceto _ , - , /",
  "Rules deployed successfully": "Regras implantadas com sucesso",
  "Choose From Template": "Escolher a partir de um modelo",
  "Back to forms": "Voltar aos formulários",
  "Choose From Templates": "Escolher a partir de modelos",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Explore a nossa Biblioteca de Modelos para encontrar a combinação perfeita de formulários e fluxos de trabalho. Clique para visualizar um modelo e, se ele atender às suas necessidades, personalize-o ao seu gosto. Depois de ajustá-lo às suas necessidades específicas, você estará pronto para criar o seu caso de negócio",
  "All templates": "Todos os modelos",
  "Template count": "Contagem de modelos",
  "Learn more": "Saiba mais",
  "Template Details": "Detalhes do modelo",
  "Template Title": "Título do modelo",
  "Preview Form": "Visualizar formulário",
  "Connected Workflow": "Fluxo de trabalho conectado",
  "Delete Template": "Excluir modelo",
  "Use Template": "Usar modelo",
  "Template created successfully": "Modelo criado com sucesso",
  "Template deleted successfully": "Modelo excluído com sucesso",
  "Template updated successfully": "Modelo atualizado com sucesso",
  "Category": "Categoria",
  "Search category...": "Pesquisar categoria...",
  "Save as Template": "Salvar como modelo",
  "Create Template": "Criar modelo",
  "Select or Create Category": "Selecionar ou criar categoria",
  "Short Intro": "Introdução curta",
  "Enter short intro": "Digite uma introdução curta",
  "Enter description": "Digite uma descrição",
  "Select or create": "Selecionar ou criar",
  "Update Template": "Atualizar modelo",
  "Form created successfully": "Formulário criado com sucesso",
  "select or create": "Selecionar ou criar",
  "Update Associated Form": "Atualizar Formulário Associado",
  "Update Associated Workflow": "Atualizar Fluxo de Trabalho Associado",
  "Enter title": "Inserir título",
  "No Templates Found": "Nenhum modelo encontrado",
  "No Category Found": "Nenhuma categoria encontrada",
  "Save Template": "Salvar Modelo",
  "You can type and click the": "Você pode digitar e clicar em",
  "to create the category.": "para criar a categoria.",
  "select or type to create": "selecione ou digite para criar",
  "BPMN": "BPMN",
  "DMN": "DMN",
  "Advanced Designer": "Designer Avançado",
  "Basic Designer": "Designer Básico",
  "Search": "Pesquisar",
  "Key": "Chave",
  "No Process Found": "Processo Não Encontrado",
  "Search workflow": "Pesquisar Fluxo de Trabalho",
  "No Dmn Found": "DMN Não Encontrado",
  "Submission ID": "ID da Submissão",
  "Submission Name": "Nome da Submissão",
  "Submission History": "Histórico da Submissão",
  "No Submission History found": "Nenhum Histórico de Submissão Encontrado",
  "Error in submission count": "Erro na contagem de submissões",
  "Permission for submission tracking.": "Permissão para rastreamento de submissões.",
  "Reviewer permission to view submissions": "Permissão do revisor para visualizar envios",
  "Permission to create new submission": "Permissão para criar novo envio",
  "Back to Bundle List": "Voltar para a Lista de Pacotes",
  "Bundle": "Pacote",
  "You can drag these nodes to the pane on the right.": "Você pode arrastar esses nós para o painel à direita.",
  "You can delete the element by select and click the backspace": "Você pode excluir o elemento selecionando e clicando na tecla backspace",
  "Workflow Id": "ID do Fluxo de Trabalho",
  "Enter Workflow Id": "Insira o ID do Fluxo de Trabalho",
  "Back to Submissions": "Voltar para as Submissões",
  "Back to Drafts": "Voltar para os Rascunhos",
  "Choose Your Workflow Option": "Escolha sua Opção de Fluxo de Trabalho",
  "Create New Workflow": "Criar Novo Fluxo de Trabalho",
  "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "Escolha esta opção quando desejar criar um novo fluxo de trabalho com base no modelo. O sistema irá gerar e implantar um novo fluxo de trabalho e, em seguida, conectá-lo ao formulário selecionado. Opte por isso se o seu formulário exigir um conjunto distinto de etapas de fluxo de trabalho adaptadas às suas necessidades específicas.",
  "Reuse Existing Workflow": "Reutilizar Fluxo de Trabalho Existente",
  "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "Selecione esta opção para vincular o formulário a um fluxo de trabalho já estabelecido. Quaisquer modificações feitas no fluxo de trabalho existente serão refletidas automaticamente neste formulário. Isso é ideal quando você deseja aproveitar o fluxo de trabalho existente para atender às necessidades do seu formulário",
  "Are you sure you wish to delete the Template?": "Tem certeza de que deseja excluir o Modelo?",
  "Enter Workflow Name": "Inserir Nome do Fluxo de Trabalho",
  "Create Workflow": "Criar Fluxo de Trabalho",
  "Upload Workflow": "Carregar Fluxo de Trabalho",
  "Edit Workflow": "Editar Fluxo de Trabalho",
  "Published": "Publicado",
  "Unpublished": "Não Publicado",
  "Private": "Privado",
  "Anonymous": "Anônimo",
  "Edit Processes": "Editar Processos",
  "Create Processes": "Criar Processos",
  "tasks": "tarefas",
  "Submission Id": "ID da Submissão",
  "Clear All Filters": "Limpar Todos os Filtros",
  "Show results": "Mostrar resultados",
  "Delete Draft": "Excluir Rascunho",
  "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "Posso ajudar você a projetar formulários sem esforço - tudo o que você precisa fazer é me fornecer uma descrição clara e concisa do que o formulário deve fazer. Vou criar os campos e o layout para você, que você pode personalizar ainda mais.",
  "I am": "Eu sou",
  "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "Por exemplo 'Nos dê um formulário que servirá como um formulário de admissão de pacientes para clínicas sem necessidade de agendamento'.",
  "Enter your prompt here": "Digite o prompt aqui",
  "Would you like to continue?": "Gostaria de continuar?",
  "Restart": "Reiniciar",
  "I'm here to provide further assistance. Thank you!": "Estou aqui para fornecer assistência adicional. Obrigado!",
  "Generate Form Design": "Gerar Design do Formulário",
  "Preview": "Visualizar",
  "Your form is now ready!": "Seu formulário está pronto!",
  "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description, hit send.": "Por favor, nos forneça todas as especificações e requisitos que você tem em mente para o seu formulário. Depois de terminar a descrição, pressione Enter.",
  "Choose template": "Escolher modelo",
  "Search by bundle name": "Pesquisar por nome do pacote",
  "Save Bundle": "Salvar Bundle",
  "Id": "Id",
  "Enable bundling ?": "Ativar agrupamento?",
  "Select a task in the List.": "Selecione uma tarefa na lista.",
  "Add Date": "Adicionar data",
  "Assign to Me": "Atribuir para mim",
  "Filter count:": "Contagem de filtros:",
  "Selected Forms": "Formulários Selecionados",
  "Template Used:": "Modelo Utilizado:",
  "Select a task from the List.": "Selecione uma tarefa da lista.",
  "Choose a task from the list; your selection directs your current activity.": "Escolha uma tarefa da lista; sua seleção direciona sua atividade atual.",
  "Please change the selected filters to view submissions": "Por favor, altere os filtros selecionados para ver as submissões",
  "Please change the selected filters to view drafts": "Por favor, altere os filtros selecionados para ver os rascunhos",
  "No drafts found": "Nenhum rascunho encontrado",
  "Flow-E helps to build faster": "Flow-E ajuda a construir mais rápido",
  "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "Flow-E não está disponível para demonstração na instância de teste. Você pode experimentar o Flow-E em qualquer um dos pacotes premium do produto",
  "Get in touch with formsflow.ai team": "Entre em contato com a equipe da formsflow.ai",
  "Premium": "Prêmio",
  "Select a status": "Selecione um status",
  "Group": "Grupo",
  "Form description": "Descrição do Formulário",
  "Select all forms": "Selecionar todos os formulários",
  "Bold": "Negrito",
  "Italic": "Itálico",
  "Underline": "Sublinhado",
  "Align left": "Alinhar à esquerda",
  "Align center": "Alinhar ao centro",
  "Align right": "Alinhar à direita",
  "Align justify": "Justificar",
  "Insert Link": "Inserir Link",
  "Clean": "Limpar",
  "Click for task variables": "Clique para ver as variáveis da tarefa",
  "Upload DMN": "Carregar DMN",
  "DMN Name": "Nome do DMN",
  "Search by DMN name": "Pesquisar por nome do DMN",
  "Display authorized tasks based on user roles": "Exibir tarefas autorizadas com base nas funções do usuário",
  "You are currently using a test instance.The trial period ends in": "Você está usando atualmente uma instância de teste. O período de teste termina em",
  "days.": "dias.",
  "Are you sure to delete": "Tem certeza de que deseja excluir",
  "filter?": "filtro?",
  "Select Workflow": "Selecionar fluxo de trabalho",
  "Select Assignee": "Selecionar destinatário",
  "Click here to select attributes": "Clique aqui para selecionar atributos",
  "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "Selecione os atributos predefinidos e as variáveis de tarefa personalizadas criadas como parte do envio do formulário que deseja exibir na lista de tarefas",
  "Task variables": "Variáveis da tarefa",
  "User Role": "Função do usuário",
  "User Group": "Grupo de usuários",
  "Select User Role": "Selecionar função do usuário",
  "Select User Group": "Selecionar grupo de usuários",
  "To display task variables, select a form as part of the filter": "Para exibir as variáveis da tarefa, selecione um formulário como parte do filtro",
  "select a form": "selecione um formulário",
  "No task variables found": "Nenhuma variável de tarefa encontrada",
  "Edit filter": "Editar filtro",
  "Select form fields to display in task list": "Selecionar campos do formulário para exibir na lista de tarefas",
  "Select all fields": "Selecionar todos os campos",
  "Edit Label": "Editar Rótulo",
  "Selecting all form fields may affect performance. For the best performance, just pick the form fields you really need.": "Selecionar todos os campos do formulário pode afetar o desempenho. Para obter o melhor desempenho, selecione apenas os campos do formulário que você realmente precisa.",
  "User Added successfully!": "Usuário adicionado com sucesso!",
  "Failed to create user!": "Falha ao criar usuário!",
  "Add Registered Users": "Adicionar Usuários Registrados",
  "Username or Email": "Nome de usuário ou Email",
  "Add User": "Adicionar Usuário",
  "User doesn't exist!": "Utilizador não existe!",
  "Success": "Sucesso",
  "User added": "Utilizador adicionado",
  "From": "De",
  "To": "Para",
  "Premium Subscription": "Assinatura Premium",
  " For further insights on this exclusive premium feature, kindly connect": "Para mais informações sobre este recurso premium exclusivo, por favor, conecte-se",
  " with our dedicated marketing team for detailed information.": "com nossa equipe de marketing dedicada para informações detalhadas.",
  "Get Connected With Us Now!": "Conecte-se conosco agora!",
  "Visit our": "Visite nosso",
  "Pricing page": "página de preços",
  "for more details.": "para mais detalhes.",
  "Integration": "Integração",
  "Recipes": "Receitas",
  "Connected Apps": "Aplicativos Conectados",
  "Library": "Biblioteca",
  "Add group": "Adicionar grupo",
  "Add task label": "Adicionar rótulo de tarefa",
  "Integrations": "Integrações",
  "We facilitate hundreds of native integrations via our ‘Native Integrations Pro’ package.": "Facilitamos centenas de integrações nativas através do nosso pacote ‘Integrações Nativas Pro’.",
  " This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "Esta funcionalidade não está disponível por padrão no período de 14 dias de avaliação. Se o seu período de avaliação exigir esta funcionalidade, você pode nos informar e podemos ativá-la para você.",
  "Upgrade to unlock Native Integrations Pro": "Atualize para desbloquear as Integrações Nativas Pro",
  "We facilitate hundreds of native integrations via our ": "Facilitamos centenas de integrações nativas através do nosso ",
  "Native Integrations Pro": "Integrações Nativas Pro",
  " package. This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": ". Esta funcionalidade não está disponível por padrão no teste de 14 dias. Se o seu teste exigir esta funcionalidade, você pode nos informar e podemos ativá-la para você.",
  "To learn more about Native Integrations Pro": "Para saber mais sobre as Integrações Nativas Pro",
  "Check out Integrations Feature": "Confira a funcionalidade de Integrações",
  "Connect with": "Entre em contato com",
  "team for requests or queries.": "a equipe para solicitações ou dúvidas.",
  "Learn more about the feature": "Saiba mais sobre o recurso",
  " team.": "equipe.",
  "Connect with formsflow.ai team.": "Conecte-se com a equipe da formsflow.ai.",
  "You don't have permission to access this page.": "Você não tem permissão para acessar esta página.",
  "Please contact your administrator or try again later.": "Por favor, entre em contato com o seu administrador ou tente novamente mais tarde.",
  "Return to login": "Voltar ao login",
  "Default filter removed": "Filtro padrão removido",
  "Set default filter": "Definir filtro padrão",
  "added as default filter": "adicionado como filtro padrão",
  "Are you sure you wish to delete the draft": "Tem certeza de que deseja excluir o rascunho",
  "Are you sure you wish to delete the form ": "Tem certeza de que deseja excluir o formulário",
  "Are you sure you wish to delete the form?": "Tem certeza de que deseja excluir o formulário?",
  ". Are you sure want to delete ?": ". Tem certeza de que deseja excluir?",
  "Add form fields to display in task list": "Adicionar campos de formulário para exibir na lista de tarefas",
  "Version": "Versão",
  "Created By": "Criado por",
  "Text Area": "Área de texto",
  "Number": "Número",
  "Password": "Senha",
  "Checkbox": "Caixa de seleção",
  "Select Boxes": "Selecionar caixas",
  "Radio": "Rádio",
  "Button": "Botão",
  "Text Area With Analytics": "Área de texto com análise",
  "Data": "Dadas",
  "Display": "Exibição",
  "on": "sobre",
  "Url": "URL",
  "Phone Number": "Número de telefone",
  "Tags": "Tags",
  "Address": "Endereço",
  "Date / Time": "Data hora",
  "Day": "Dia",
  "Time": "Tempo",
  "Currency": "Moeda",
  "Survey": "Pesquisa",
  "Signature": "Assinatura",
  "HTML": "HTML",
  "Content": "Contente",
  "Columns": "Colunas",
  "Field Set": "Conjunto de campos",
  "Panel": "Painel",
  "Table": "Mesa",
  "Tabs": "Abas",
  "Well": "Nós vamos",
  "Hidden": "Escondida",
  "Container": "Recipiente",
  "Data Map": "Mapa de dados",
  "Data Grid": "Grade de dados",
  "Edit Grid": "Editar grade",
  "Tree": "Árvore",
  "reCAPTCHA": "reCAPTCHA",
  "File": "Arquivo",
  "Nested": "Aninhada",
  "Custom": "Personalizada",
  "Basic": "Básica",
  "Advanced": "Avançada",
  "Layout": "Esquema",
  "Drag and Drop a form component": "Arraste e solte um componente de formulário",
  "The minimum length requirement this field must meet.": "O requisito de comprimento mínimo que este campo deve atender.",
  "The label for this field that will appear next to it.": "O rótulo para este campo que aparecerá ao lado dele.",
  "Label Position": "Posição do rótulo",
  "Position for the label for this field.": "Posição do rótulo para este campo.",
  "Placeholder": "Espaço reservado",
  "The placeholder text that will appear when this field is empty.": "O texto do espaço reservado que aparecerá quando este campo estiver vazio.",
  "The description is text that will appear below the input field.": "A descrição é um texto que aparecerá abaixo do campo de entrada.",
  "Tooltip": "Dica de ferramenta",
  "Adds a tooltip to the side of this field.": "Adiciona uma dica de ferramenta ao lado deste campo.",
  "To add a tooltip to this field, enter text here.": "Para adicionar uma dica de ferramenta a este campo, digite o texto aqui.",
  "Description for this field.": "Descrição para este campo.",
  "Prefix": "Prefixo",
  "Suffix": "Sufixo",
  "Widget": "Ferramenta",
  "The widget is the display UI used to input the value of the field.": "O widget é a interface do usuário de exibição usada para inserir o valor do campo.",
  "Right (Left-aligned)": "Direita (alinhado à esquerda)",
  "Left (Left-aligned)": "Esquerda (alinhado à esquerda)",
  "Left (Right-aligned)": "Esquerda (alinhado à direita)",
  "Right (Right-aligned)": "Direita (alinhado à direita)",
  "Bottom": "Fundo",
  "Component": "Componente",
  "Top": "Principal",
  "Label Width": "Largura do rótulo",
  "The width of label on line in percentages.": "A largura do rótulo na linha em porcentagens.",
  "Label Margin": "Margem do rótulo",
  "The width of label margin on line in percentages.": "A largura da margem do rótulo na linha em porcentagens.",
  "Rows": "Linhas",
  "Input Field": "Campo de entrada",
  "Calendar Picker": "Seletor de calendário",
  "Select a widget": "Selecione um widget",
  "Input Mask": "Máscara de entrada",
  "Widget Settings": "Configurações do widget",
  "Allow Multiple Masks": "Permitir várias máscaras",
  "Input Masks": "Máscaras de entrada",
  "Mask": "mascarar",
  "Add Another": "Adicionar outro",
  "Custom CSS Class": "Classe CSS personalizada",
  "Custom CSS class to add to this component.": "Classe CSS personalizada para adicionar a este componente.",
  "Tab Index": "Índice da guia",
  "Sets the tabindex attribute of this component to override the tab order of the form. See the MDN documentation on tabindex for more information.": "Define o atributo tabindex deste componente para substituir a ordem de tabulação do formulário. Consulte a documentação do MDN no tabindex para obter mais informações.",
  "Autocomplete": "autocompletar",
  "Indicates whether input elements can by default have their values automatically completed by the browser. See the MDN documentation on autocomplete for more information.": "Indica se os elementos de entrada podem, por padrão, ter seus valores preenchidos automaticamente pelo navegador. Consulte a documentação do MDN sobre preenchimento automático para obter mais informações.",
  "A hidden field is still a part of the form, but is hidden from view.": "Um campo oculto ainda faz parte do formulário, mas fica oculto.",
  "Hide Label": "Ocultar etiqueta",
  "Show Word Counter": "Mostrar contador de palavras",
  "Show a live count of the number of words.": "Mostrar uma contagem ao vivo do número de palavras.",
  "Hide the label (title, if no label) of this component. This allows you to show the label in the form builder, but not when it is rendered.": "Oculte o rótulo (título, se não houver rótulo) deste componente. Isso permite que você mostre o rótulo no construtor de formulários, mas não quando ele é renderizado.",
  "Show Character Counter": "Mostrar contador de caracteres",
  "Show a live count of the number of characters.": "Mostrar uma contagem ao vivo do número de caracteres.",
  "Hide Input": "Ocultar entrada",
  "Hide the input in the browser. This does not encrypt on the server. Do not use for passwords.": "Oculte a entrada no navegador. Isso não criptografa no servidor. Não use para senhas.",
  "Initial Focus": "Foco inicial",
  "Make this field the initially focused element on this form.": "Faça deste campo o elemento inicialmente focado neste formulário.",
  "Allow Spellcheck": "Permitir verificação ortográfica",
  "Disabled": "Desativada",
  "Disable the form input.": "Desabilite a entrada do formulário.",
  "Table View": "Vista de mesa",
  "Shows this value within the table view of the submissions.": "Mostra esse valor na exibição de tabela dos envios.",
  "Modal Edit": "Edição Modal",
  "Opens up a modal to edit the value of this component.": "Abre um modal para editar o valor deste componente.",
  "Multiple Values": "Vários valores",
  "Allows multiple values to be entered for this field.": "Permite que vários valores sejam inseridos para este campo.",
  "Default Value": "Valor padrão",
  "The will be the value for this field, before user interaction. Having a default value will override the placeholder text.": "O será o valor para este campo, antes da interação do usuário. Ter um valor padrão substituirá o texto do espaço reservado.",
  "Persistent": "Persistente",
  "A persistent field will be stored in database when the form is submitted.": "Um campo persistente será armazenado no banco de dados quando o formulário for enviado.",
  "None": "Nenhum",
  "Server": "Servidora",
  "Client": "Cliente",
  "Input Format": "Formato de entrada",
  "Force the output of this field to be sanitized in a specific format.": "Força a saída deste campo a ser higienizada em um formato específico.",
  "Plain": "Plana",
  "Type to search": "Escreva para pesquisar",
  "Raw (Insecure)": "Bruto (inseguro)",
  "Protected": "Protegida",
  "A protected field will not be returned when queried via API.": "Um campo protegido não será retornado quando consultado via API.",
  "Database Index": "Índice do banco de dados",
  "Set this field as an index within the database. Increases performance for submission queries.": "Defina este campo como um índice no banco de dados. Aumenta o desempenho para consultas de envio.",
  "Text Case": "Caixa de texto",
  "When data is entered, you can change the case of the value.": "Quando os dados são inseridos, você pode alterar as maiúsculas e minúsculas do valor.",
  "Mixed (Allow upper and lower case)": "Misto (Permitir maiúsculas e minúsculas)",
  "Uppercase": "Maiúsculas",
  "Lowercase": "Minúsculas",
  "Encrypted (Enterprise Only)": "Criptografado (somente Enterprise)",
  "Encrypt this field on the server. This is two way encryption which is not suitable for passwords.": "Criptografe este campo no servidor. Esta é uma criptografia bidirecional que não é adequada para senhas.",
  "Redraw On": "Redesenhado em",
  "Redraw this component if another component changes. This is useful if interpolating parts of the component like the label.": "Redesenhe este componente se outro componente for alterado. Isso é útil ao interpolar partes do componente como o rótulo.",
  "Any Change": "Qualquer mudança",
  "Clear Value When Hidden": "Limpar valor quando oculto",
  "When a field is hidden, clear the value.": "Quando um campo estiver oculto, limpe o valor.",
  "The following variables are available in all scripts.": "As seguintes variáveis ​​estão disponíveis em todos os scripts.",
  "Custom Default Value": "Valor padrão personalizado",
  "form": "Formato",
  "The complete form JSON object": "O objeto JSON de formulário completo",
  "submission": "submissão",
  "The complete submission object.": "O objeto de envio completo.",
  "data": "dadas",
  "The complete submission data object.": "O objeto de dados de envio completo.",
  "row": "fileira",
  "Contextual \"row\" data, used within DataGrid, EditGrid, and Container components": "Dados de \"linha\" contextuais, usados ​​nos componentes DataGrid, EditGrid e Container",
  "component": "component",
  "The current component JSON": "O componente atual JSON",
  "instance": "instância",
  "The current component instance.": "A instância do componente atual.",
  "Value": "Valor",
  "The current value of the component.": "O valor atual do componente.",
  "moment": "momento",
  "The moment.js library for date manipulation.": "A biblioteca moment.js para manipulação de datas.",
  "utils": "útil",
  "util": "útil",
  "An alias for \"utils\".": "Um alias para \"utils\".。",
  "JavaScript": "JavaScript",
  "Enter custom javascript code.": "Insira o código javascript personalizado.",
  "Example:": "Exemplo:",
  "JSONLogic": "JSONLogic",
  "Execute custom logic using ": "Execute a lógica personalizada usando",
  "support is provided using an \"_\" before each operation, such as {\"_sum\": {var: \"data.a\"}}": "o suporte é fornecido usando um \"_\" antes de cada operação, como {\"_sum\": {var: \"data.a\"}}",
  "Full": "Completa",
  "Calculated Value": "Valor calculado",
  "token": "símbolo",
  "The decoded JWT token for the authenticated user.": "O token JWT decodificado para o usuário autenticado.",
  "Calculate Value on server": "Calcular valor no servidor",
  "Checking this will run the calculation on the server. This is useful if you wish to override the values submitted with the calculations performed on the server.": "Marcar isso executará o cálculo no servidor. Isso é útil se você deseja substituir os valores enviados pelos cálculos realizados no servidor.",
  "Allow Manual Override of Calculated Value": "Permitir substituição manual do valor calculado",
  "When checked, this will allow the user to manually override the calculated value.": "Quando marcado, isso permitirá que o usuário substitua manualmente o valor calculado.",
  "Remove": "Remover",
  "Validate On": "Validar em",
  "Determines when this component should trigger front-end validation.": "Determina quando esse componente deve acionar a validação de front-end.",
  "Change": "Mudar",
  "Blur": "Borrão",
  "Required": "Requeridos",
  "A required field must be filled in before the form can be submitted.": "Um campo obrigatório deve ser preenchido antes que o formulário possa ser enviado.",
  "Unique": "Única",
  "Makes sure the data submitted for this field is unique, and has not been submitted before.": "Garante que os dados enviados para este campo sejam exclusivos e não tenham sido enviados antes.",
  "Minimum Length": "Comprimento mínimo",
  "The maximum length requirement this field must meet.": "O requisito de comprimento máximo que este campo deve atender.",
  "Maximum Length": "Comprimento máximo",
  "Minimum Word Length": "Comprimento Mínimo da Palavra",
  "The minimum amount of words that can be added to this field.": "A quantidade mínima de palavras que podem ser adicionadas a este campo.",
  "Maximum Word Length": "Comprimento Máximo da Palavra",
  "The maximum amount of words that can be added to this field.": "A quantidade máxima de palavras que podem ser adicionadas a este campo.",
  "Regular Expression Pattern": "Padrão de Expressão Regular",
  "The regular expression pattern test that the field value must pass before the form can be submitted.": "O teste padrão de expressão regular que o valor do campo deve passar antes que o formulário possa ser enviado.",
  "Error Label": "Etiqueta de erro",
  "The label for this field when an error occurs.": "O rótulo para este campo quando ocorre um erro.",
  "Custom Error Message": "Mensagem de erro personalizada",
  "Error message displayed if any error occurred.": "Mensagem de erro exibida se ocorrer algum erro.",
  "Custom Validation": "Validação personalizada",
  "input": "entrada",
  "The value that was input into this component": "O valor que foi inserido neste componente",
  "Enter custom validation code.": "Insira o código de validação personalizado.",
  "You must assign the valid variable as either true or an error message if validation fails.": "Você deve atribuir a variável válida como verdadeira ou uma mensagem de erro se a validação falhar.",
  "Secret Validation": "Validação secreta",
  "Check this if you wish to perform the validation ONLY on the server side. This keeps your validation logic private and secret.": "Marque isso se desejar realizar a validação SOMENTE no lado do servidor. Isso mantém sua lógica de validação privada e secreta.",
  "JSONLogic Validation": "Validação JSONLogic",
  "Execute custom logic using": "Execute a lógica personalizada usando",
  "Validation": "Validação",
  "API": "API",
  "Property Name": "Nome da propriedade",
  "The name of this field in the API endpoint.": "O nome desse campo no endpoint da API.",
  "Field Tags": "Tags de campo",
  "Tag the field for use in custom logic.": "Marque o campo para uso na lógica personalizada.",
  "Custom Properties": "Propriedades personalizadas",
  "This allows you to configure any custom properties for this component.": "Isso permite configurar quaisquer propriedades personalizadas para este componente.",
  "Conditional": "Condicional",
  "Simple": "Simples",
  "This component should Display:": "Este componente deve exibir:",
  "True": "Verdadeira",
  "False": "Falsa",
  "When the form component:": "Quando o componente de formulário:：",
  "Submit (submit)": "Enviar (enviar)",
  "Has the value:": "Tem o valor:：",
  "Advanced Conditions": "Condições avançadas",
  "Advanced Logic": "Lógica avançada",
  "Advanced Logic Configured": "Lógica avançada configurada",
  "Logic": "Lógica",
  "Add Logic": "Adicionar lógica",
  "Trigger": "Acionar",
  "JSON Logic": "Lógica JSON",
  "\"row\", \"data\", and \"component\" variables are available. Return \"result\".": "As variáveis ​​\"linha\", \"dados\" e \"componente\" estão disponíveis. Retorna \"resultado\".",
  "Action Name": "Nome da ação",
  "Schema Defenition": "Definição do Esquema",
  "\"row\", \"data\", \"component\", and \"result\" variables are available. Return the schema.": "As variáveis ​​\"linha\", \"dados\", \"componente\" e \"resultado\" estão disponíveis. Devolva o esquema.",
  "Merge Component Schema": "Mesclar Esquema de Componente",
  "Custom Action": "Ação personalizada",
  "You must assign the show variable a boolean result.": "Você deve atribuir à variável show um resultado booleano.",
  "Note: Advanced Conditional logic will override the results of the Simple Conditional logic.": "Observação: a lógica condicional avançada substituirá os resultados da lógica condicional simples.",
  "Example": "Exemplo",
  "\"row\", \"data\", \"component\" and \"_\" variables are available. Return the result to be passed to the action if truthy.": "As variáveis ​​\"row\", \"data\", \"component\" e \"_\" estão disponíveis. Retorna o resultado a ser passado para a ação se for verdadeiro.",
  "Add Action": "Adicionar ação",
  "Save Logic": "Salvar lógica",
  "Logic Name": "Nome lógico",
  "Event": "Evento",
  "The event that will trigger this logic. You can trigger events externally or via a button.": "O evento que acionará essa lógica. Você pode acionar eventos externamente ou por meio de um botão.",
  "Save Action": "Salvar ação",
  "HTML Attributes": "Atributos HTML",
  "Attribute Name": "Nome do Atributo",
  "Attribute Value": "Valor do atributo",
  "Add Attribute": "Adicionar atributo",
  "The settings inside apply only to the PDF forms.": "As configurações internas se aplicam apenas aos formulários PDF.",
  "PDF Overlay": "Sobreposição de PDF",
  "Style": "Estilo",
  "Custom styles that should be applied to this component when rendered in PDF.": "Estilos personalizados que devem ser aplicados a este componente quando renderizados em PDF.",
  "Page": "Página",
  "The PDF page to place this component.": "A página PDF para colocar este componente.",
  "Left": "Esquerda",
  "The left margin within a page to place this component.": "A margem esquerda dentro de uma página para colocar este componente.",
  "The top margin within a page to place this component.": "A margem superior dentro de uma página para colocar este componente.。",
  "Width": "Largura",
  "The width of the component (in pixels).": "A largura do componente (em pixels).",
  "Height": "Altura",
  "The height of the component (in pixels).": "A altura do componente (em pixels).",
  "Use Thousands Separator": "Use o separador de milhares",
  "Separate thousands by local delimiter.": "Separe milhares por delimitador local.",
  "Decimal Places": "Casas decimais",
  "The maximum number of decimal places.": "O número máximo de casas decimais.",
  "Require Decimal": "Exigir Decimal",
  "Always show decimals, even if trailing zeros.": "Sempre mostre decimais, mesmo se zeros à direita.",
  "Minimum Value": "Valor mínimo",
  "The minimum value this field must have before the form can be submitted.": "O valor mínimo que este campo deve ter antes que o formulário possa ser enviado.",
  "Maximum Value": "Valor máximo",
  "The maximum value this field can have before the form can be submitted.": "O valor máximo que este campo pode ter antes que o formulário possa ser enviado.",
  "Editor": "Editora",
  "Select the type of WYSIWYG editor to use for this text area.": "Selecione o tipo de editor WYSIWYG a ser usado para esta área de texto.",
  "ACE": "ÁS",
  "Save As": "Salvar como",
  "This setting determines how the value should be entered and stored in the database.": "Essa configuração determina como o valor deve ser inserido e armazenado no banco de dados.",
  "String": "Corda",
  "JSON": "JSON",
  "Input Type": "Tipo de entrada",
  "This is the input type used for this checkbox.": "Este é o tipo de entrada usado para esta caixa de seleção.",
  "Shortcut": "Atalho",
  "Shortcut for this component.": "Atalho para este componente.",
  "Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API.": "Os campos de senha são criptografados automaticamente usando hashes bcrypt salgados unidirecionais. Esses hashes também são protegidos e não são retornados na API.",
  "Options Label Position": "Posição do rótulo de opções",
  "Position for the label for options for this field.": "Posição para o rótulo de opções para este campo.",
  "Right": "Certa",
  "Inline Layout": "Layout embutido",
  "Displays the checkboxes/radios horizontally.": "Exibe as caixas de seleção/rádios horizontalmente.",
  "Allow only available values": "Permitir apenas valores disponíveis",
  "Minimum checked number": "Número mínimo verificado",
  "Minimum checkboxes required before form can be submitted.": "Caixas de seleção mínimas necessárias antes que o formulário possa ser enviado.",
  "Maximum checked number": "Número máximo verificado",
  "Maximum checkboxes possible before form can be submitted.": "Máximo de caixas de seleção possíveis antes que o formulário possa ser enviado.",
  "Minimum checked error message": "Mensagem de erro mínima verificada",
  "Error message displayed if minimum number of items not checked.": "Mensagem de erro exibida se o número mínimo de itens não for verificado.",
  "Maximum checked error message": "Máximo de mensagens de erro verificadas",
  "Error message displayed if maximum number of items checked.": "Mensagem de erro exibida se o número máximo de itens for verificado.",
  "ChoicesJS": "ChoicesJS",
  "HTML 5": "HTML 5",
  "Unique Options": "Opções únicas",
  "Display only unique dropdown options.": "Exiba apenas opções de lista suspensa exclusivas.",
  "Data Source Type": "Tipo de fonte de dados",
  "The source to use for the select data. Values lets you provide your own values and labels. JSON lets you provide raw JSON data. URL lets you provide a URL to retrieve the JSON data from.": "fonte a ser usada para os dados selecionados. Valores permite que você forneça seus próprios valores e rótulos. JSON permite fornecer dados JSON brutos. URL permite que você forneça um URL para recuperar os dados JSON.",
  "Values": "Valores",
  "Raw JSON": "JSON bruto",
  "IndexedDB": "BD indexado",
  "Database name": "Nome do banco de dados",
  "The name of the indexeddb database.": "O nome do banco de dados indexeddb.",
  "Storage Type": "Tipo de armazenamento",
  "The type to store the data. If you select something other than autotype, it will force it to that type.": "O tipo para armazenar os dados. Se você selecionar algo diferente de autotype, ele o forçará a esse tipo.",
  "Autotype": "Autotipo",
  "Boolean": "boleano",
  "Object": "Objeto",
  "ID Path": "Caminho de ID",
  "Path to the select option id.": "Caminho para o ID da opção de seleção.",
  "Table name": "Nome da tabela",
  "The name of table in the indexeddb database.": "O nome da tabela no banco de dados indexeddb.",
  "Row Filter": "Filtro de linha",
  "Filter table items that match the object.": "Filtre os itens da tabela que correspondem ao objeto.",
  "Item Template": "Modelo de item",
  "The HTML template for the result data items.": "O modelo HTML para os itens de dados de resultado.",
  "Enable Static Search ": "Ativar pesquisa estática",
  "When checked, the select dropdown will allow for searching within the static list of items provided.": "Quando marcada, a lista suspensa de seleção permitirá a pesquisa na lista estática de itens fornecidos.",
  "Search Threshold": "Limite de pesquisa",
  "At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match, a threshold of 1.0 would match anything.": "Em que ponto o algoritmo de correspondência desiste. Um limite de 0,0 requer uma correspondência perfeita, um limite de 1,0 corresponderia a qualquer coisa.",
  "Read Only Value": "Valor somente leitura",
  "Check this if you would like to show just the value when in Read Only mode.": "Marque isso se você quiser mostrar apenas o valor quando estiver no modo Somente leitura.",
  "Choices.js options": "Opções de Choices.js",
  "A raw JSON object to use as options for the Select component (Choices JS).": "Um objeto JSON bruto para usar como opções para o componente Select (Choices JS).",
  "Use exact search": "Usar pesquisa exata",
  "Disables search algorithm threshold.": "Desativa o limite do algoritmo de pesquisa.",
  "Theme": "Tema",
  "The color theme of this button.": "O tema de cores deste botão.",
  "Size": "Tamanho",
  "The size of this button": "O tamanho deste botão",
  "Block Button": "Botão de bloqueio",
  "This control should span the full width of the bounding container.": "Esse controle deve abranger toda a largura do contêiner delimitador.",
  "Left Icon": "Ícone esquerdo",
  "This is the full icon class string to show the icon.": "Esta é a string de classe de ícone completa para mostrar o ícone.",
  "Right Icon": "Ícone direito",
  "This is the full icon class string to show the icon. Example:": "Esta é a string de classe de ícone completa para mostrar o ícone. Exemplo:",
  "Primary": "Primária",
  "Secondary": "Secundária",
  "Info": "Informações",
  "Danger": "Perigo",
  "Warning": "Warning",
  "The size of this button.": "O tamanho deste botão.",
  "Medium": "Média",
  "Extra Small": "Muito pequeno",
  "Small": "Pequena",
  "Large": "Grande",
  "Disable on Form Invalid": "Desativar no formulário inválido",
  "This will disable this field if the form is invalid.": "Isso desativará este campo se o formulário for inválido.",
  "Key topics for Sentiment Analysis": "Tópicos-chave para Análise de Sentimentos",
  "Enter topics to use in sentiment Analysis": "Insira os tópicos a serem usados ​​na Análise de sentimento",
  "Kickbox": "Kickbox",
  "Enable": "Habilitar",
  "Enable Kickbox validation for this email field.": "Habilite a validação Kickbox para este campo de e-mail.",
  "Validate this email using the Kickbox email validation service.": "Valide este e-mail usando o serviço de validação de e-mail Kickbox.",
  "Input Mask Placeholder Char": "Caractere de espaço reservado para máscara de entrada",
  "Enable Manual Mode": "Ativar modo manual",
  "Should Manual Mode be enabled for that component or not.": "O modo manual deve estar habilitado para esse componente ou não.",
  "Switch To Manual Mode Label": "Mudar para o rótulo do modo manual",
  "The label for the checkbox used to switch to manual mode.": "O rótulo da caixa de seleção usada para alternar para o modo manual.",
  "Disable Clear Icon": "Desativar ícone Limpar",
  "Clear Icon allows easily clear components value.": "Clear Icon permite limpar facilmente o valor dos componentes.",
  "Provider": "Fornecedor",
  "Which address search service should be used.": "Qual serviço de pesquisa de endereços deve ser usado.",
  "Manual Mode View String": "Cadeia de visualização do modo manual",
  "Specify template which should be when quering view string for the component value entered in manual mode. This string is used in table view, CSV export and email rendering. When left blank combined value of all components joined with comma will be used.": "Especifique o modelo que deve ser ao consultar a string de visualização para o valor do componente inserido no modo manual. Essa string é usada na visualização de tabela, exportação CSV e renderização de e-mail. Quando deixado em branco, o valor combinado de todos os componentes unidos por vírgula será usado.",
  "Azure Maps": "Mapas do Azure",
  "Google Maps": "Google Maps",
  "API Key": "Chave API",
  "Use your Google API key here.": "Use sua chave de API do Google aqui.",
  "Provider options": "Opções do provedor",
  "Delimiter": "Delimitador",
  "What is used to separate the tags.": "O que é usado para separar as tags.",
  "Max Tags": "Máximo de tags",
  "The maximum amount of tags that can be added. 0 for infinity.": "A quantidade máxima de tags que podem ser adicionadas. 0 para infinito.",
  "Store As": "Armazenar como",
  "String (CSV)": "Cadeia de caracteres (CSV)",
  "Array of Tags": "Matriz de tags",
  "Display in Timezone": "Exibir no fuso horário",
  "This will display the captured date time in the select timezone.": "Isso exibirá a data e hora capturada no fuso horário selecionado.",
  "of Viewer": "do Visualizador",
  "of Submission": "de submissão",
  "of Location": "de Localização",
  "UTC": "UTC",
  "Use Locale Settings": "Usar configurações de localidade",
  "Use locale settings to display date and time.": "Use as configurações de localidade para exibir data e hora.",
  "Allow Manual Input": "Permitir entrada manual",
  "Check this if you would like to allow the user to manually enter in the date.": "Marque esta opção se desejar permitir que o usuário insira manualmente a data.",
  "Format": "Formato",
  "The date format for displaying the datetime value.": "O formato de data para exibir o valor de data e hora.",
  "Shortcut Buttons": "Botões de atalho",
  "You can specify few buttons which will be shown above the calendar. Use Label to specify the name of the button and onClick to specify which date/time will be set when user clicks the button. ": "Você pode especificar alguns botões que serão mostrados acima do calendário. Use Label para especificar o nome do botão e onClick para especificar qual data/hora será definida quando o usuário clicar no botão.",
  "onClick": "ao clicar",
  "Enable Date Input": "Ativar entrada de data",
  "Enables date input for this field.": "Habilita a entrada de data para este campo.",
  "Use Input to add moment.js for minDate": "Use Input para adicionar moment.js para minDate",
  "Enables to use input for moment functions instead of calendar.": "Permite usar entrada para funções de momento em vez de calendário.",
  "Use calendar to set minDate": "Use o calendário para definir minDate",
  "Enables to use calendar to set date.": "Permite usar o calendário para definir a data.",
  "Use Input to add moment.js for maxDate": "Use Input para adicionar moment.js para maxDate",
  "Use calendar to set maxDate": "Use o calendário para definir maxDate",
  "Disable specific dates or dates by range": "Desativar datas ou datas específicas por intervalo",
  "Add dates that you want to blacklist. For example:": "Adicione datas que você deseja colocar na lista negra. Por exemplo:",
  "Custom Disabled Dates": "Datas de desativação personalizadas",
  "date": "encontro",
  "The date object.": "O objeto de data.",
  "Data Format": "Formato de dados",
  "The moment.js format for saving the value of this field.": "O formato moment.js para salvar o valor deste campo.",
  "HTML5 Time Input": "Entrada de hora HTML5",
  "Text Input with Mask": "Entrada de texto com máscara",
  "Disable weekends": "Desativar fins de semana",
  "Disable weekdays": "Desativar dias da semana",
  "Check to disable weekends": "Marque para desativar fins de semana",
  "Check to disable weekdays": "Marque para desativar os dias da semana",
  "Enable Time Input": "Ativar entrada de tempo",
  "Enables time input for this field": "Habilita a entrada de tempo para este campo",
  "Hour Step Size": "Tamanho do passo de hora",
  "The number of hours to increment/decrement in the time picker.": "O número de horas para incrementar/diminuir no seletor de tempo.",
  "Minute Step Size": "Tamanho do Passo Minuto",
  "The number of minutes to increment/decrement in the time picker.": "O número de minutos para incrementar/diminuir no seletor de tempo.",
  "Display time in 12 hour time with AM/PM.": "Exibe o tempo em 12 horas com AM/PM.",
  "12 Hour Time (AM/PM)": "Horário de 12 horas (AM/PM)",
  "Default Date": "Data padrão",
  "You can use Moment.js functions to set the default value to a specific date. For example:": "Você pode usar as funções Moment.js para definir o valor padrão para uma data específica. Por exemplo:",
  "Flatpickr options": "Opções do Flatpickr",
  "HTML Tag": "Tag HTML",
  "The tag of this HTML element.": "A tag deste elemento HTML.",
  "CSS Class": "Classe CSS",
  "Attributes": "Atributos",
  "The attributes for this HTML element. Only safe attributes are allowed, such as src, href, and title.": "Os atributos para este elemento HTML. Apenas atributos seguros são permitidos, como src, href e title.",
  "Attribute": "Atributo",
  "Refresh On Change": "Atualizar na mudança",
  "HTML Element": "Elemento HTML",
  "Column Properties": "Propriedades da coluna",
  "The width, offset, push, and pull settings for each column.": "As configurações de largura, deslocamento, empurrar e puxar para cada coluna.",
  "Offset": "Desvio",
  "Push": "Empurre",
  "Pull": "Puxar",
  "Auto adjust columns": "Colunas de ajuste automático",
  "Will automatically adjust columns based on if nested components are hidden.": "Ajustará automaticamente as colunas com base se os componentes aninhados estiverem ocultos.",
  "Hide Column when Children Hidden": "Ocultar coluna quando os filhos estiverem ocultos",
  "Check this if you would like to hide any column when the children within that column are also hidden": "Assinale isto se desejar ocultar alguma coluna quando os filhos dessa coluna também estiverem ocultos",
  "Legend": "Lenda",
  "The legend for this Fieldset.": "A legenda para este Fieldset.",
  "Default": "Padrão",
  "Collapsible": "Dobrável",
  "If checked, this will turn this Panel into a collapsible panel.": "Se marcado, isso transformará este Painel em um painel dobrável.",
  "Number of Rows": "Numero de linhas",
  "Enter the number or rows that should be displayed by this table.": "Insira o número ou as linhas que devem ser exibidas por esta tabela.",
  "Number of Columns": "Numero de colunas",
  "Enter the number or columns that should be displayed by this table.": "Insira o número ou colunas que devem ser exibidas por esta tabela.",
  "Clone Row Components": "Clonar componentes de linha",
  "Check this if you would like to": "Marque isso se você quiser",
  "Cell Alignment": "Alinhamento de Células",
  "Horizontal alignment for cells of the table.": "Alinhamento horizontal para células da tabela.",
  "Center": "Centro",
  "Striped": "Listrado",
  "This will stripe the table if checked.": "Isso irá riscar a tabela se estiver marcado.",
  "Bordered": "Delimitada",
  "This will border the table if checked.": "Isso fará a borda da tabela se estiver marcado.",
  "Hover": "Flutuar",
  "Highlight a row on hover.": "Realce uma linha ao passar o mouse.",
  "Condensed": "Condensada",
  "Condense the size of the table.": "Condense o tamanho da mesa.",
  "Label for Key column": "Rótulo para a coluna Chave",
  "Provide a label text for Key column (otherwise Key will be used)": "Forneça um texto de rótulo para a coluna Chave (caso contrário, a chave será usada)",
  "Disable Adding / Removing Rows": "Desativar adição/remoção de linhas",
  "Check if you want to hide Add Another button and Remove Row button": "Verifique se você deseja ocultar o botão Adicionar outro e o botão Remover linha",
  "Show key column before value": "Mostrar coluna chave antes do valor",
  "Check if you would like to show the Key before the Value column.": "Verifique se você gostaria de mostrar a Chave antes da coluna Valor.",
  "Type of event": "Tipo de evento",
  "Specify type of event that this reCAPTCHA would react to": "Especifique o tipo de evento ao qual este reCAPTCHA reagiria",
  "Form Load": "Carregamento de formulário",
  "Button Click": "Clique no botão",
  "The form to load within this form component.": "O formulário a ser carregado nesse componente de formulário.",
  "Form Revision": "Revisão do formulário",
  "You can lock the nested form to a specific revision by entering the revision number here.": "Você pode bloquear o formulário aninhado para uma revisão específica inserindo o número da revisão aqui.",
  "Use Original Revision while Submissions Viewing": "Use a revisão original durante a visualização de envios",
  "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission.": "Usar esta opção fará com que o formulário carregue a revisão original (a que foi usada para fazer um envio) ao visualizar um envio.",
  "Save as reference": "Salvar como referência",
  "Using this option will save this field as a reference and link its value to the value of the origin record.": "O uso desta opção salvará este campo como referência e vinculará seu valor ao valor do registro de origem.",
  "Select Fields": "Selecionar campos",
  "The properties on the resource to return as part of the options. If left blank, all properties will be returned.": "As propriedades no recurso a serem retornadas como parte das opções. Se deixado em branco, todas as propriedades serão retornadas.",
  "Search Fields": "Campos de pesquisa",
  "Filter Query": "Filtrar consulta",
  "Use this to provide additional filtering using query parameters.": "Use isso para fornecer filtragem adicional usando parâmetros de consulta.",
  "The filter query for results.": "A consulta de filtro para resultados.",
  "Sort Query": "Classificar consulta",
  "Use this to provide additional sorting using query parameters": "Use isso para fornecer classificação adicional usando parâmetros de consulta",
  "The sort query for results": "A consulta de classificação para resultados",
  "Add Resource": "Adicionar recurso",
  "Allows to create a new resource while entering a submission.": "Permite criar um novo recurso ao inserir um envio.",
  "Add Resource Label": "Adicionar rótulo de recurso",
  "Set the text of the Add Resource button.": "Defina o texto do botão Adicionar recurso.",
  "Auto Expand": "Expansão automática",
  "Are you sure you wish to delete the form": "Tem certeza que deseja deletar o formulário",
  "Are you sure you wish to delete this submission?": "Tem certeza de que deseja excluir este envio?",
  "Ascending": "Ascendente",
  "groups": "grupos",
  "Diagram Deployed": "Diagrama implantado",
  "Deployment Failed": "Falha na implantação",
  "Unfinished Submissions will be saved to Submissions/Drafts.": "As Submissões não concluídas serão salvas em Submissões/Rascunhos.",
  "Changing the form workflow will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Mudar o fluxo de trabalho do formulário não afetará as submissões existentes. Isso só será atualizado nas submissões recém-criadas. Pressione Salvar Alterações para continuar ou cancelar as alterações.",
  "Submissions are made against": "As Submissões são feitas contra",
  "Submission is made against": "A Submissão é feita contra",
  "Changing the form title will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Mudar o título do formulário não afetará as submissões existentes. Isso só será atualizado nas submissões recém-criadas. Pressione Salvar Alterações para continuar ou cancelar as alterações.",
  "No submissions Found": "Nenhuma submissão encontrada",
  "Asignee": "Cessionário",
  "Include Assigned Task": "Incluir tarefa atribuída",
  "Variable": "Variável",
  "Name of variable": "Nome da variável",
  "Readable name": "nome legível",
  "Specific User/ Group": "Usuário/Grupo Específico",
  "User": "Do utilizador",
  "Identifier": "identificador",
  "Enter role ID": "Digite o ID da função",
  "Select a task in the List": "Selecione uma tarefa na Lista",
  "Select a specific task from the provided list of options. Your selection will determine the task you will be working on or interacting with.": "Selecione uma tarefa específica na lista de opções fornecida. Sua seleção determinará a tarefa na qual você estará trabalhando ou interagindo.",
  "Create Form, workflow designs": "Criar Formulário, designs de fluxo de trabalho",
  "Access to design": "Acesso ao design",
  "Create submissions": "Criar submissões",
  "Access to submissions": "Acesso às submissões",
  "Access to dashboards": "Acesso aos painéis",
  "Access to tasks": "Acesso às tarefas",
  "Can claim and work on tasks": "Pode reivindicar e trabalhar em tarefas",
  "Manage all filters": "Gerenciar todos os filtros",
  "Access to create filters": "Acesso para criar filtros",
  "Access to view filters": "Acesso para visualizar filtros",
  "Access to Integrations": "Acesso às Integrações",
  "Manage Dashboard Authorization": "Gerenciar Autorização do Painel",
  "Manage Users": "Gerenciar Usuários",
  "Manage Roles": "Gerenciar Funções" ,
  "Permissions": "Permissões",
  "Edit Permissions": "Editar Permissões",
  "Select Permissions": "Selecionar Permissões",
  "Proceed to Sign In": "Prosseguir para Entrar",
  "Contact formsflow.ai support": "Contactar suporte formsflow.ai",
  "Please provide your tenant name to sign in": "Por favor, forneça o nome do seu inquilino para entrar",
  "Tenant not found":"Inquilino não encontrado",
  "Access Roles": "Funções de Acesso",
  "Description of the new form": "Descrição do novo formulário",
  "Name of the form": "Nome do formulário",
  "Duplicate": "Duplicar",
  "New Form Name": "Novo nome do formulário",
  "New Form Description": "Nova descrição do formulário",
  "Save and Edit form": "Salvar e Editar formulário",
  "Build New Form": "Criar novo formulário",
  "Settings": "Configurações",
  "Live": "Ao vivo",
  "Draft": "Rascunho",
  "Publish": "Publicar",
  "Unpublish": "Despublicar",
  "Save Layout": "Salvar layout",
  "Discard Changes": "Descartar alterações",
  "Flow": "Fluxo",
  "You Have Unsaved Changes": "Você tem alterações não salvas",
  "You have made changes that are not saved yet. The unsaved changes could be either on the Layout or the Flow side.": "Você fez alterações que ainda não foram salvas. As alterações não salvas podem estar no Layout ou no Fluxo",
  "Note": "Nota",
  "Stay in the Editor": "Permanecer no editor",
  "Discard Changes and Leave the Page": "Descartar alterações e sair da página",
  "Confirm Unpublish": "Confirmar despublicação",
  "This form is currently live. To save changes to form edits, you need to unpublish it first. By Unpublishing this form, you will make it unavailable for new submissions to those who currently have access to it. You can republish the form after making your edits.": "Este formulário está atualmente ativo. Para salvar as alterações feitas nas edições do formulário, você precisa despublicá-lo primeiro. Ao despublicar este formulário, ele ficará indisponível para novas submissões para aqueles que atualmente têm acesso a ele. Você pode republicar o formulário após fazer suas edições.",
  "Unpublish and Edit This Form": "Despublicar e editar este formulário",
  "Cancel, Keep This Form Unpublished": "Cancelar, manter este formulário não publicado",
  "Confirm Publish": "Confirmar publicação",
  "Publishing will save any unsaved changes and lock the entire form, including the layout and the flow. To perform any additional changes you will need to unpublish the form again.": "Publicar salvará quaisquer alterações não salvas e bloqueará o formulário inteiro, incluindo o layout e o fluxo. Para realizar alterações adicionais, você precisará despublicar o formulário novamente.",
  "Publish This Form": "Publicar este formulário",
  "Import": "Importar",
  "Allowing the addition of multiple pages in a single form will prevent you from using this form in a bundle later.": "Autoriser l'ajout de plusieurs pages dans un seul formulaire vous empêchera d'utiliser ce formulaire dans un lot ultérieurement.",
  "Allow adding multiple pages in this form": "Autoriser l'ajout de plusieurs pages dans ce formulaire",
  "Who Can View/Edit This Form": "Qui peut voir/modifier ce formulaire",
  "Only You": "Seulement vous",
  "You and specified roles": "Vous et les rôles spécifiés",
  "Who Can Create Submissions": "Qui peut créer des soumissions",
  "Anonymous users": "Utilisateurs anonymes",
  "Registered users": "Utilisateurs enregistrés",
  "Specific roles": "Rôles spécifiques",
  "Who Can View Submissions": "Qui peut voir les soumissions",
  "Submitter": "Soumettant",
  "Submitter and specified roles": "Soumettant et rôles spécifiés",
  "Link for this form": "Lien pour ce formulaire",
  "Making changes to your form URL will make your form inaccessible from your current URL.": "Modifier l'URL de votre formulaire le rendra inaccessible depuis votre URL actuelle.",
  "Save Your Changes": "Salve suas alterações",
  "Saving as an incremental version will affect previous submissions. Saving as a new full version will not affect previous submissions.": "Salvar como uma versão incremental afetará os envios anteriores. Salvar como uma nova versão completa não afetará os envios anteriores.",
  "Save as Version": "Salvar como versão",
  "Discard Layout Changes?": "Descartar alterações no layout?",
  "Are you sure you want to discard all the changes to the layout of the form?": "Tem certeza de que deseja descartar todas as alterações no layout do formulário?",
  "This action cannot be undone.": "Esta ação não pode ser desfeita.",
  "Yes, Discard Changes": "Sim, descartar alterações",
  "No, Keep My Changes": "Não, manter minhas alterações",
  "Save Flow": "Salvar fluxo",
  "Revert To This": "Reverter para este",
  "Last Edit On": "Última edição em",
  "Last Edit By": "Última edição por",
  "Variables for Flow, Submissions, and Tasks": "Variáveis para fluxo, envios e tarefas",
  "To use variables in the flow, as well as sorting by them in the submissions and tasks you need to specify which variables you want to import from the layout. Variables get imported into the system at the time of the submission, if the variables that are needed are not selected prior to the form submission THEY WILL NOT BE AVAILABLE in the flow, submissions, and tasks.": "Para usar variáveis no fluxo, bem como ordená-las nos envios e tarefas, você precisa especificar quais variáveis deseja importar do layout. As variáveis são importadas para o sistema no momento da submissão. Se as variáveis necessárias não forem selecionadas antes da submissão do formulário, ELAS NÃO ESTARÃO DISPONÍVEIS no fluxo, envios e tarefas.",
  "Selected Variables": "Variáveis selecionadas",
  "Pick variables below": "Escolha variáveis abaixo",
  "Select a form field on the left": "Selecione um campo de formulário à esquerda",
  "Discard Flow Changes?": "Descartar alterações no fluxo?",
  "Are you sure you want to discard all unsaved changes to the flow of the form?": "Tem certeza de que deseja descartar todas as alterações não salvas no fluxo do formulário?",
  "Yes, Discard All Unsaved Changes": "Sim, descartar todas as alterações não salvas",
  "No, Keep The Changes": "Não, manter as alterações",
  "Import File": "Importar arquivo",
  "Click or drag a file to this area to import (form, layout or bpmn)": "Clique ou arraste um arquivo para esta área para importar (formulário, layout ou BPMN)",
  "Support for a single .json, .bpmn file upload. Maximum file size 20MB.": "Suporte para um único arquivo .json ou .bpmn. Tamanho máximo do arquivo: 20 MB.",
  "Confirm And Replace": "Confirmar e substituir",
  "Export Form": "Exportar formulário",
  "Export in Progress": "Exportação em andamento",
  "Export Successful": "Exportação bem-sucedida",
  "Are You Sure You Want to Delete This Form?": "Tem certeza de que deseja excluir este formulário?",
  "No, Keep This Form": "Não, manter este formulário",
  "Yes, Delete the Form": "Sim, excluir o formulário",
  "Importing and deleting is not available when the form is published. You must unpublish the form first if you wish to make any changes.": "A importação e exclusão não estão disponíveis quando o formulário está publicado. Você deve despublicar o formulário primeiro se desejar fazer alterações.",
  "Search Form Name and Description": "Pesquisar Nome e Descrição do Formulário",
  "New Form": "Novo Formulário",
  "Add Form": "Adicionar Formulário",
  "Build": "Construir",
  "Create the form from scratch": "Criar o formulário do zero",
  "Upload form from a file": "Carregar formulário de um arquivo",
  "Last Edited": "Última Edição",
  "ID": "ID",
  "New BPMN": "Novo BPMN",
  "Create the BPMN from scratch": "Criar o BPMN do zero",
  "Upload BPMN from a file": "Carregar BPMN de um arquivo",
  "Search BPMN Name": "Pesquisar Nome BPMN",
  "New DMN": "Novo DMN",
  "Import New Form": "Importar Novo Formulário",
  "Confirm and Edit form": "Confirmar e Editar formulário",
  "Click or drag a file to this area to import": "Clique ou arraste um arquivo para esta área para importar",
  "Search Decision Table": "Pesquisar Tabela de Decisão",
  "Create the DMN from scratch": "Criar o DMN do zero",
  "Upload DMN from a file": "Carregar DMN de um arquivo",
  "Create And Edit BPMN": "Criar e Editar BPMN",
  "Create And Edit DMN": "Criar e Editar DMN",
  "Import New": "Importar Novo",
  "Search DMN Name": "Pesquisar nome DMN",
  "cancel": "cancelar",
  "previous": "anterior",
  "next": "próximo", 
  "Month": "Mês", 
  "Year": "Ano",
  "Sort": "Ordenar",
  "Sort Results": "Resultados da Ordenação",
  "Sort By": "Ordenar Por",
  "In a": "Em uma",
  "Sort By Dropdown": "Menu suspenso de Ordenar Por",
  "Sort By Input": "Entrada de Ordenar Por",
  "Order Dropdown": "Menu suspenso de Ordem",
  "Order Input": "Entrada de Ordem",
  "Apply sorting": "Aplicar ordenação",
  "build new form with AI": "Criar novo formulário com IA",
  "Flow-E": "Flow-E",
  "Message Flow-E": "Enviar mensagem para Flow-E",
  "Select this Layout": "Selecionar este layout",
  "Your form is now ready": "Seu formulário está pronto",
  "For further customization, please provide specifications.": "Para mais personalização, forneça especificações.",
  "Regenerate": "Regenerar",
  "Start Over": "Recomeçar",
  "Undo": "Desfazer",
  "I am Flow-E.": "Eu sou Flow-E.",
  "I can help you design forms effortlessly. I will build out the fields and layout for you, which you can further customize or you can": "Posso ajudá-lo a criar formulários sem esforço. Construirei os campos e o layout para você, que poderá personalizar ainda mais, ou você pode",
  "Try an Example Prompt": "Tente um exemplo de prompt",
  "Select Template For New Form": "Selecionar modelo para novo formulário",
  "Select This Template": "Selecionar este modelo",
  "flow": "fluxo",
  "all templates": "todos os modelos",
  "Nothing is found. Please try again.": "Nada encontrado. Tente novamente.",
  "Search ...": "Pesquisar ...",
  "Use AI": "Usar IA",
  "Build form using Flow-E AI chatbot": "Criar formulário usando o chatbot IA Flow-E",
  "Start off from a template": "Começar com um modelo",
  "Export Failed": "Falha na exportação",
  "Create Duplicate": "Criar Duplicado",
  "Are you sure you want to duplicate the current BPMN?": "Tem certeza de que deseja duplicar o BPMN atual?",
  "Yes, Duplicate This BPMN": "Sim, duplicar este BPMN",
  "No, Do Not Duplicate This BPMN": "Não, não duplicar este BPMN",
  "Export BPMN": "Exportar BPMN",
  "Publish This BPMN": "Publicar este BPMN",
  "Are you sure you want to duplicate the current DMN?": "Tem certeza de que deseja duplicar o DMN atual?",
  "Yes, Duplicate This DMN": "Sim, duplicar este DMN",
  "No, Do Not Duplicate This DMN": "Não, não duplicar este DMN",
  "Publish This DMN": "Publicar este DMN",
  "Publishing will lock the {{type}}. To save changes on further edits, you will need to unpublish the {{type}} first.": "A publicação bloqueará o {{type}}. Para salvar as alterações em edições futuras, você precisará despublicar o {{type}} primeiro.",
  "Unpublish and Edit This BPMN": "Despublicar e editar este BPMN",
  "Cancel, Keep This BPMN published": "Cancelar, mantener este BPMN publicado",
  "This {{type}} is currently live. To save changes to {{type}} edits, you need to unpublish it first.": "Este {{type}} está atualmente ao vivo. Para salvar as alterações nas edições de {{type}}, você precisa despublicá-lo primeiro.",
  "Unpublish and Edit This DMN": "Despublicar y editar este DMN",
  "Cancel, Keep This DMN published": "Cancelar, mantener este DMN publicado",
  "You Cannot Delete This Form": "Você não pode excluir este formulário",
  "But you may unpublish it if you wish to not receive any more submissions.": "Mas você pode despublicá-lo se não quiser mais receber envios.",
  "You may not delete a form that has submissions associated with it.": "Você não pode excluir um formulário que tenha envios associados.",
  "Keep This Form": "Manter este formulário",
  "Unpublish This Form": "Despublicar este formulário",
  "A system error occurred during export. Please try again.": "Ocorreu um erro no sistema durante a exportação. Por favor, tente novamente.",
  "Try Again": "Tente novamente",
  "No forms have been found. Create a new form by clicking the \"New Form\" button in the top right.": "Nenhum formulário foi encontrado. Crie um novo formulário clicando no botão 'Novo Formulário' no canto superior direito.",
  "No subflows have been found. Create a new subflow by clicking \"New BPMN\" button in the top right.": "Nenhum subfluxo foi encontrado. Crie um novo subfluxo clicando no botão 'Novo BPMN' no canto superior direito.",
  "No decision tables have been found. Create a new decision table by clicking \"New DMN\" button in the top right.": "Nenhuma tabela de decisão foi encontrada. Crie uma nova tabela de decisão clicando no botão 'Novo DMN' no canto superior direito.",
  "Form Submitted": "Formulário enviado",
  "Sample form submitted": "Formulário de exemplo enviado",
  "Type of Block to Add": "Tipo de bloco a adicionar",
  "Blocks that do something": "Blocos que fazem algo",
  "Condition": "Condição",
  "Decision making expression": "Expressão de tomada de decisão",
  "Send email": "Enviar e-mail",
  "Sends a pre-defined email": "Envia um e-mail predefinido",
  "Action: send Email": "Ação: enviar e-mail",
  "Recipient": "Destinatário",
  "Subject": "Assunto",
  "Body": "Corpo",
  "Select a Variable": "Selecionar uma variável",
  "Search Available Variable": "Pesquisar variável disponível",
  "More Variables from Form’s Layout": "Mais variáveis do layout do formulário",
  "Use This Variable": "Utiliser cette variable",
  "Use integration": "Utiliser l'intégration",
  "Sends or gets data from an integration through a recipe (workato)": "Envoie ou reçoit des données d'une intégration via une recette (Workato)",
  "Action: Use Integration Modal": "Action : Utiliser la fenêtre d'intégration",
  "Recipe": "Recette",
  "Exclude Fields": "Exclure les champs",
  "Create task": "Créer une tâche",
  "Creates a task for a specific user or a user role": "Crée une tâche pour un utilisateur spécifique ou un rôle d'utilisateur",
  "Action: Create Task": "Action : Créer une tâche",
  "Create a task for": "Créer une tâche pour",
  "Specific Roles": "Funções específicas",
  "Set/update variable value": "Definir/atualizar valor da variável",
  "Assigns value to a specified variable": "Atribui um valor a uma variável específica",
  "Action: Set/Update Variable Value": "Ação: Definir/Atualizar valor da variável",
  "Variable to update": "Variável a atualizar",
  "New value for the variable": "Novo valor para a variável",
  "Variable to update is required.": "É necessária uma variável para atualizar.",
  "Action Name is required": "O nome da ação é obrigatório",
  "Action Name is required.": "O nome da ação é obrigatório.",
  "New value for the variable is required.": "É necessário um novo valor para a variável.",
  "Condition Name": "Nome da condição",
  "Expression": "Expressão",
  "Expression Builder": "Construtor de Expressões",
  "Condition Name is required": "O nome da condição é obrigatório",
  "Pick Variable": "Selecionar variável",
  "Form variable": "Variável do formulário",
  "Custom Value": "Valor personalizado",
  "Empty Expression": "Expressão vazia",
  "Search Form Variable": "Pesquisar variável do formulário",
  "Set Value": "Definir valor",
  "Enter Custom Value": "Insira um valor personalizado",
  "Pick An Operator": "Escolha um operador",
  "(add) Adds values together": "(somar) Soma os valores",
  "(subtract) Subtracts values": "(subtrair) Subtrai os valores",
  "(divide) Divides values": "(dividir) Divide os valores",
  "(multiply) Multiplies values": "(multiplicar) Multiplica os valores",
  "(or) Evaluates true if value on the left OR on the right is not empty": "(ou) Avalia como verdadeiro se o valor à esquerda OU à direita não estiver vazio",
  "(and) Evaluates true if value on the left AND on the right is not empty": "(e) Avalia como verdadeiro se os valores à esquerda E à direita não estiverem vazios",
  "(less than) Evaluates true if the value on the left is less than value on the right": "(menor que) Avalia como verdadeiro se o valor à esquerda for menor que o da direita",
  "(larger than) Evaluates true if the value on the left is larger than value on the right": "(maior que) Avalia como verdadeiro se o valor à esquerda for maior que o da direita",
  "(less than or equal) Evaluates true if the value on the left is less than or equal to the value on the right": "(menor ou igual) Retorna verdadeiro se o valor à esquerda for menor ou igual ao valor à direita",
  "(larger than or equal) Evaluates true if the value on the left is larger than or equal to the value on the right": "(maior ou igual) Retorna verdadeiro se o valor à esquerda for maior ou igual ao valor à direita",
  "(equals) Evaluates true if the value on the left is equal to the value on the right": "(igual) Retorna verdadeiro se o valor à esquerda for igual ao valor à direita",
  "(contains) Evaluates true if text contains some specified text (not case sensitive)": "(contém) Retorna verdadeiro se o texto contiver um texto especificado (sem distinção entre maiúsculas e minúsculas)",
  "Add your condition": "Adicione sua condição",
  "Are you sure you want to Delete the Node ?": "Tem certeza de que deseja excluir o nó?",
  "If you delete this node , you won't be able to undo this action. Are you sure you want to proceed?": "Se você excluir este nó, não poderá desfazer esta ação. Tem certeza de que deseja continuar?",
  "No, Keep This Node": "Não, manter este nó",
  "Yes, Delete the Node": "Sim, excluir o nó",
  "Recipient is required.": "O destinatário é obrigatório.",
  "Switch to BPMN ": "Mudar para BPMN",
  "Switch to Bpmn": "Mudar para BPMN",
  "Keep Editing My Flow in No-Code": "Continuar editando meu fluxo no No-Code",
  "Pick No-code version": "Escolher a versão No-Code",
  "Return to No-code": "Retornar ao No-Code",
  "Delete All Changes and Pick No-Code Version": "Excluir todas as alterações e escolher a versão No-Code",
  "Stay in BPMN": "Permanecer no BPMN",
  "This will copy the flow from Version 1.1 overwriting your existing flow.": "Isso copiará o fluxo da versão 1.1 sobrescrevendo seu fluxo existente.",
  "Use Flow from Version 1.1": "Usar o fluxo da versão 1.1",
  "Keep Current Flow": "Manter o fluxo atual",
  "Replace Current flow": "Substituir o fluxo atual",
  "Load More": "Carregar mais",
  "Invalid expression": "Expressão inválida",
  "Add Alternative Label": "Adicionar rótulo alternativo",
  "Add Variable": "Adicionar variável",
};
