/* eslint-disable max-len */
export const RESOURCE_BUNDLES_ZH = {
  "Filter Created by": "筛选器创建者",
  "Submit Form": "提交表单",
  "Changes Applied Successfully": "更改成功应用",
  "Filter Deleted Successfully": "成功删除过滤器",
  "Save Filter": "保存过滤器",
  "Filter Name": "过滤器名称",
  "Create new filter": "创建新过滤器",
  "Definition Key": "定义键",
  "Permission": "权限",
  "Enter your text here": "在此输入文本",
  "Accessible for all users": "所有用户可访问",
  "Private (Only You)": "私密 (仅限您)",
  "Specific Group": "特定群组",
  "Select Elements": "选择元素",
  " Task Attributes Selected": " 已选择的任务属性",
  "Delete Filter": "删除过滤器",
  "Add Value": "添加值",
  "Show only current user assigned task": "仅显示当前用户分配的任务",
  "Show task based on logged user roles": "根据已登录用户角色显示任务",
  "Create Filter": "创建过滤器",
  "Task Attributes": "任务属性",
  "Only selected task attributes will be available on task list view": "只有选定的任务属性将在任务列表视图中可用",
  "Show undefined variables": "显示未定义的变量",
  "Label": "标签",
  "Variables": "变量",
  "Task Title": "任务标题",
  "List View": "列表视图",
  "Card View": "卡片视图",
  "Create New Filter": "创建新过滤器",
  "Sort by": "排序方式",
  "Collapse All": "全部折叠",
  "Expand All": "全部展开",
  "Application Id": "申请 ID",
  "Back to task": "返回任务",
  "Filters": "过滤器",
  "Select a user": "选择用户",
  "Create DMN": "创建 DMN",
  "Create Process": "创建流程",
  "Edit DMN": "编辑 DMN",
  "More options": "更多选项",
  "Form Description": "表单描述",
  "Saved to Submissions/Drafts": "保存到提交/草稿",
  "Unfinished submissions will be saved to Submissions/Drafts.": "未完成的提交将保存到提交/草稿。",
  "Edit Process": "编辑流程",
  "Add filter name": "添加过滤器名称",
  "This section is aimed to set the parameters\nused to filter the tasks": "此部分旨在设置用于过滤任务的参数",
  "This section is aimed to set read\npermissions for the filter": "此部分旨在设置过滤器的读取权限",
  "This section is aimed to set select\ntask attributes that will be visible in\nthe task list view": "此部分旨在设置在任务列表视图中可见的选择任务属性",
  "Task Attribute": "任务属性",
  "You can define variables shown in the list": "您可以定义在列表中显示的变量",
  "results": "结果",
  "Enter role name": "输入角色名称",
  "Public": "公开",
  "View Submitted Form": "查看已提交的表单",
  "View Draft Details": "查看草稿详情",
  "Edit Draft": "编辑草稿",
  "Draft Title": "草稿标题",
  "Filter": "过滤器",
  "Advanced Options": "高级选项",
  "Enter the path name": "输入路径名称",
  "Search by form title": "按表单标题搜索",
  "Associate Workflow": "关联工作流程",
  "Search by workflow name": "按工作流程名称搜索",
  "View Details": "查看详细信息",
  "Visibility": "可见性",
  "Form Title": "表单标题",
  "Access restricted by its designer..!": "访问受设计者限制..!",
  "and you will no longer have the access to this form in bundles": "而且您将不再能够在包裹中访问此表单",
  "You will no longer have the access to this form in bundles": "您将不再能够在包裹中访问此表单",
  "Bad Request": "错误的请求",
  "Select the form to be displayed based on the  above criteria": "根据上述条件选择要显示的表单。",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "使用任何表单组件的API密钥和条件符号创建条件。例如，'age > 18'，其中'age'是表单组件的API密钥。",
  "Select form version": "选择表格版本",
  "Please remove the special characters...!": "请删除特殊字符...！",
  "No histories found": "没有找到历史记录",
  "Continue": "继续",
  "This will create a new version of the form without changing the path name but with new form id.": "这将创建一个新版本的表单而不更改路径名但具有新的表单 ID。",
  "Save as a new version": "另存为新版本",
  "Save New Version": "保存新版本",
  "Do you want to save a new version of this form?": "您要保存此表单的新版本吗？",
  "Do you want to create a duplicate form and associated workflow from existing form ?": "您要从现有表单创建重复表单和关联工作流吗？",
  "New version created": "已创建新版本",
  "Create a duplicate form": "创建一个重复的表单",
  "Show more": "展示更多",
  "Modified By": "修改者",
  "Created On": "创建于",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "Formsflow 会自动保存您以前的表单数据。现在您可以切换到上一个阶段并进行编辑。",
  "Duplicate Form": "复制表格",
  "Form History": "表单历史",
  "No file chosen": "没有选中任何文件",
  "Choose File": "选择文件",
  "Choose any": "选择任何",
  "Sort by form name": "按表格名称排序",
  "select form type": "选择表格类型",
  "Draft Deleted Successfully": "草稿删除成功",
  "Saved to Applications/Drafts": "保存到申请/草稿",
  "Unfinished applications will be saved to Applications/Drafts.": "未完成的申请将被保存到申请/草稿.",
  "Discard Draft": " 丢弃草稿",
  "with ID": "带身份证",
  "Please change the selected filters to view Forms": "请更改所选过滤器以查看表格",
  "Search by form name": "按表格名称搜索",
  "Click to search": "点击搜索",
  "No submissions found": "未找到任何提交",
  "No submission avaliable in the selected date. Please select another date range": "在所选日期内没有可用的提交。请选择其他日期范围",
  "Dashboards": "仪表板",
  "Form field": "表单域",
  "Enter Label": "输入标签",
  "Select form field": "选择表单域",
  "Latest Version": "最新版本",
  "Submission Status": "提交状态",
  "No submission status": "无提交状态",
  "No Public url found": "未找到公共网址",
  "Show in list": "显示在列表中",
  "Select Task Variable": "选择任务变量",
  "Enter your Label": "输入您的标签",
  "Please select from one of the following workflows.": "请从以下工作流程之一中选择。",
  "Select Key": "选择键",
  "Create Your Task Variable": "创建您的任务变量",
  "No task variable selected": "未选择任务变量",
  "Workflow Associate": "工作流助理",
  "Task variable": "任务变量",
  "Enter pathname": "输入路径名",
  "Submission Saved": "提交已保存。",
  "Error while Submission.": "提交时出错。",
  "Form saved": "表格已保存。",
  "Submission cannot be done.": "无法提交。 ",
  "Forms": "表格  ",
  "Edit": "编辑",
  "Text Field": "文本域",
  "Do you want to associate form with a workflow ?": "您想将表单与工作流相关联吗？",
  "Yes": "是的",
  "No": "否",
  "Form Name": "表格名称 ",
  "Workflow Name": "工作流程名称",
  "Publish this form for Client Users.": "为客户用户发布此表单.",
  "Comments": "评论",
  "Back": "返回",
  "Edit Form": "编辑表格  ",
  "Next": "下一个",
  "Save": "保存  ",
  "Back to Form List": "返回表格列表  ",
  "Submit New": "提交新的  ",
  "View Submissions": "查看提交  ",
  "View/Edit Form": "查看/编辑表单  ",
  "Delete Form": "删除表格  ",
  "Delete": "删除",
  "Print As PDF": "打印为 PDF  ",
  "Applications": "应用",
  "Tasks": "任务",
  "Insights": "洞察力",
  "Dashboard": "仪表盘  ",
  "Logout": "登出",
  "No tasks found": "没有找到任务 ",
  "Please change the selected filters to view tasks": "请更改所选过滤器以查看任务",
  "Clear all filters": "清除所有过滤器",
  "Created": "已创建",
  "Task Variables": "任务变量",
  "Process Variables": "过程变量",
  "Process Definition Name": "进程定义名称",
  "Assignee": "受让人 ",
  "Candidate Group": "候选组",
  "Candidate User": "候选用户",
  "Name": "姓名",
  "Description": "描述",
  "Priority": "优先事项",
  "Due Date": "到期日",
  "Follow up Date": "跟进日期",
  "Task name": "任务名称",
  "Remove sorting": "删除排序",
  "Ascending": "上升",
  "Descending": "降序",
  "Add sorting": "添加排序",
  "of the criteria are met.": "的标准得到满足。",
  "For Variable, ignore case of": "对于变量，忽略大小写",
  "name": "姓名",
  "value": "价值",
  "No task matching filters found.": "未找到匹配过滤器的任务。",
  "Application ID": "应用编号",
  "Set follow-up Date": "设置随访日期",
  "Set Due date": "设置截止日期",
  "Add groups": "添加群组",
  "Claim": "宣称",
  "Search By Last Name": "按姓氏搜索",
  "Search By First Name": "按名字搜索",
  "Search By Email": "通过电子邮件搜索",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "您可以通过在输入字段中输入组 ID，然后单击带加号的按钮来添加组。",
  "Add a group": "添加群组",
  "Process Name": "进程名称",
  "Set FollowUp Date": "设置跟进日期",
  "Groups": "团体",
  "Click to Change Assignee": "单击以更改受让人",
  "Reset Assignee": "重置受让人",
  "Update User": "更新用户",
  "Close": "关闭",
  "Remove search": "删除搜索",
  "Property": "财产",
  "Operator": "操作员",
  "Total number of results": "结果总数",
  "Filter Tasks": "过滤任务",
  "All": "全部",
  "ANY": "任何",
  "Task assignee": "任务受让人",
  "Application History": "应用历史",
  "View Submission": "查看提交",
  "Showing": "显示",
  "to": "到",
  "Results": "结果",
  "Acknowledge": "承认",
  "View": "看法",
  "Select a task in the list.": "在列表中选择一个任务。",
  "No Filters Found": "未找到过滤器。",
  "Loading": "加载中",
  "Form": "形式",
  "History": "历史",
  "Diagram": "图表",
  "Delete Confirmation": "删除确认",
  "All tasks": "所有任务",
  "Manage Groups": "管理群组",
  "Group ID": "组ID",
  "Due": "到期的",
  "Follow-up": "跟进",
  "Application Name": "应用名称",
  "Created By": "由...制作",
  "Application Status": "申请状态",
  "Request Status": "请求状态",
  "Request Name": "请求名称",
  "Submitted On": "提交日期",
  "Modified On": "修改时间",
  "No History Found": "未找到历史记录",
  "Process Diagram": "流程图",
  "Details": "细节",
  "Status": "地位",
  "Submissions": "提交",
  "No Application History found": "未找到应用历史",
  "Link To Form Submission": "表单提交链接",
  "Last Modified": "最后修改",
  "Metrics": "指标",
  "No dashboard found": "未找到仪表板",
  "of": "的",
  "Select Dashboard": "选择仪表板",
  "Total Submissions": "提交总数",
  "Operations": "运营",
  "Access Groups": "访问组",
  "Action": "行动",
  "Add": "添加",
  "Admin": "行政",
  "Create Form": "创建表格  ",
  "Upload Form": "上传表格",
  "Download Form": "下载表格",
  "Upload json form only": "仅上传 json 表单",
  "Select atleast one form": "选择至少一种形式",
  "Select All": "全选",
  "Created Date": "创建日期",
  "Modified Date": "修改日期",
  "File Upload Status": "文件上传状态",
  "Forms Completed": "完成的表格",
  "Form Completed": "表格完成",
  "No forms found": "没有找到表格",
  "Powered by ": "供电 ",
  "No Process Diagram found": "未找到流程图",
  "No applications found": "未找到任何应​​用程序",
  "Successfully Updated": "成功更新",
  "Failed": "失败的",
  "Submission Failed.": "提交失败。",
  "Press Enter key or click here to search": "按 Enter 键或点击此处搜索",
  "Click to clear": "点击清除",
  "Search...": "搜索...",
  "Click here to back": "点击这里返回",
  "Enter the form title": "输入表格标题",
  "Enter the form machine name": "输入表格机器名称",
  "Display as": "显示为",
  "Title": "标题",
  "Type": "类型",
  "Path": "小路",
  "example": "例子",
  "Anonymous Form ": "匿名表格",
  "Make this form public ?": "将此表格公开？",
  "Save & Preview": "保存和预览",
  "Design Form": "设计形式  ",
  "Associate this form with a workflow?": "将此表单与工作流相关联？",
  "Preview and Confirm": "预览并确认",
  "All steps completed - you're finished": "已完成所有步骤 - 您已完成",
  "Downloaded Successfully": "下载成功",
  "Error in JSON file structure": "JSON文件结构错误",
  "Please fix the errors before submitting again.": "请在重新提交之前修复错误。",
  "Loading...": "正在加载...",
  "Wizard": "向导",
  "Save Form": "保存表格",
  "Confirm": "确认",
  "Cancel": "取消",
  "Please change the selected filters to view applications": "请更改所选过滤器以查看应用程序",
  "No submissions available for the selected date range": "所选日期范围内没有可用的提交",
  "Ok": "好的",
  "Form not available": "不适用公式",
  "Thank you for your response.": "谢谢您的答复。",
  "saved successfully": "保存成功",
  "Copy anonymous form URL": "复制匿名表单 URL",
  "Submitted By": "由...所提交",
  "Confirmation": "确认",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "更改表单标题不会影响现有应用程序。它只会在新创建的应用程序中更新。按保存更改以继续或取消更改。",
  "Error while saving Form": "保存表单时出错",
  "Click here to go back": "点击此处回去",
  " Applications are submitted against": " 申请是针对",
  " Application is submitted against": " 申请是针对",
  "Are you sure to delete the": "您确定要删除",
  "Are you sure to delete the draft": "您确定要删除草稿吗",
  "Are you sure to delete this submission ?": "您确定要删除此提交吗？",
  " Submissions are made against": " 提交是针对的",
  " Submission is made against": " 提交是针对的",
  "Save Changes": "保存更改",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "更改表单工作流程不会影响现有应用程序。它只会在新创建的应用程序中更新。按保存更改以继续或取消更改。",
  "Form-Workflow association saved.": "表单-工作流程关联已保存。",
  "Form-Workflow association failed.": "表单-工作流关联失败。",
  "Form deletion unsuccessful": "表单删除失败",
  "Form deleted successfully": "表格删除成功",
  "Bundle deleted successfully": "捆绑包删除成功",
  "Form process failed": "表单处理失败",
  "Form unpublishing Failed": "表单取消发布失败",
  "All groups have access to the dashboard": "所有组都可以访问仪表板",
  "Export PDF": "导出 PDF",
  "Something went wrong. Please try again!": "出问题了。请再试一次！",
  "No Dashboards Found": "未找到仪表板",
  "Processes": "流程",
  "Please select an existing workflow.": "请选择现有工作流程。",
  "Create New": "创建新的",
  "Or create new workflow or import a workflow from a local directory.": "或创建新工作流或从本地目录导入工作流。",
  "The operation couldn't be completed. Please try after sometime": "操作无法完成。请稍后再试",
  "Select...": "选择...",
  "No Drafts Found": "未找到草稿",
  "Help": "帮助",
  "Draft Id": "草稿 ID",
  "Draft Name": "草稿名称",
  "Link To Draft Submission": "链接到草稿提交",
  "Drafts": "草稿",
  "You can't submit this form until it is published": "在此表单发布之前，您无法提交此表单",
  "Form not published": "表格未发布",
  "Access Denied": "拒绝访问",
  "By default, the tenant key would be prefixed to form": "默认情况下，租户键的前缀为 form",
  "go back": "回去",
  "No Applications Found": "未找到任何应​​用程序",
  "Submission saved to draft.": "提交已保存到草稿。",
  "Saved to draft": "已保存到草稿",
  "Saving...": "保存...",
  "Resource": "资源",
  "Error in creating form process mapper": "创建表单流程映射器时出错",
  "Select the date": "选择日期",
  "Diagram deployed": "部署图",
  "Deployment failed": "部署失败",
  "form uploaded": "表格已上传",
  "forms uploaded": "表格已上传",
  "Failed to upload": "上传失败",
  "forms...!": "形式...！",
  "form...!": "形式...！",
  "Process name(s) must not be empty": "进程名称不能为空",
  "URL copied": "已复制网址",
  "Click Here to Copy": "点击这里复制",
  "Resources": "资源",
  "Duplicate form created successfully": "成功创建重复表单",
  "Revert": "恢复",
  "Select Form": "选择表格",
  "Create Condition": "创造条件",
  "Enter criteria": "输入标准",
  "Make this form public": "公开此表格",
  "Enable bundling": "启用捆绑",
  "Bundle Name": "捆绑名称",
  "View/Edit": "查看/编辑",
  "Create Bundle": "创建捆绑包",
  "Rows per page": "每页行数",
  "Items per page": "每页项目数",
  "entries": "条目",
  "Form Bundle": "表格捆绑",
  "No bundles found": "找不到捆绑包",
  "Please change the selected filters to view Bundles": "请更改所选过滤器以查看捆绑包",
  "Select all to download forms": "全选下载表格",
  "Select for download": "选择下载",
  "Bundle Description": "捆绑包说明",
  "Conditions": "状况",
  "Enter name": "输入名字",
  "Enter Description": "输入说明",
  "You can change the form order by drag and drop": "您可以通过拖放更改表单顺序",
  "Form Order": "表格订单",
  "Form Type": "表单类型",
  "Add Forms Launch together": "添加表单一起启动",
  "Form bundles can save your time by grouping forms together": "表单包可以通过将表单分组在一起来节省您的时间",
  "Add Forms": "添加表格",
  "Criteria": "标准",
  "Create Conditions": "创造条件",
  " Add Conditions": "添加条件",
  "Select Forms": "选择表格",
  "Insert": "插入",
  "View Form": "查看表格",
  "Publish this Bundle for Client Users.": "为客户端用户发布这个包",
  "Total Forms": "总表格",
  "Edit Bundle": "编辑捆绑包",
  "Next Form": "下一个表格",
  "Previous Form": "以前的表格",
  "Forms included under the package": "包中包含的表格",
  "Submit": "提交",
  "Reset Zoom": "重置缩放",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "Deploy": "部署",
  "Export": "出口",
  "Overview": "概述",
  "Design Permission": "设计许可",
  "Application Permission": "申请许可",
  "All Designers": "所有设计师",
  "Private(only you)": "私人（只有你）",
  "Specific Designer Group": "特定设计师组",
  "Submission Permission": "提交许可",
  "All Users": "全部用户",
  "Specific User Group": "特定用户群",
  "Specific Reviewers": "具体审稿人",
  "All Reviewers": "所有审稿人",
  "Permission for application tracking.": "应用程序跟踪的权限。",
  "Design Bundle": "设计包",
  "Workflow": "工作流程",
  "Bundle Name and Description is Required": "捆绑包名称和描述为必填项",
  "Bundle Description is Required": "捆绑包描述为必填项",
  "Bundle Create Successfully": "捆绑包创建成功",
  "Bundle updated successfully": "捆绑包更新成功",
  "Select": "选择",
  "Unselect": "取消选择",
  "Applicable for Designer Roled Users only.": "仅适用于设计师角色用户。",
  "Applicable for Client and Reviewer Roled Users only.": "仅适用于客户和审阅者角色用户。",
  "Done": "完毕",
  "Failed to update permission!": "更新权限失败！",
  "Failed to fetch roles!": "获取角色失败！",
  "Failed to update role!": "更新角色失败！",
  "Permission updated successfully!": "权限更新成功！",
  "Role updated successfully!": "角色更新成功！",
  "Update failed!": "更新失败！",
  "Clear": "清除",
  "Are you sure deleting the role": "您确定要删除该角色吗",
  "Confirm Delete": "确认删除",
  "All roles": "所有角色",
  "Filter By:": "过滤：",
  "Create": "创造",
  "Eg: Account Manager": "例如：客户经理",
  "Search by name, username or email": "按姓名、用户名或电子邮件搜索",
  "No data Found": "没有找到数据",
  "Roles": "角色",
  "Users": "用户",
  "Create New Role": "创建新角色",
  "Search by role name": "按角色名称搜索",
  "Role Name": "角色名称",
  "Actions": "行动",
  "Create Role": "创建角色",
  "Email": "电子邮件",
  "Role": "角色",
  "Add Role": "添加角色",
  "Role deleted successfully!": "角色删除成功",
  "Failed to delete role!": "删除角色失败！",
  "Role created successfully!": "角色创建成功！",
  "Failed to create role!": "创建角色失败",
  "Update success!": "更新成功",
  "No results found": "未找到结果",
  "Edit Role": "编辑角色",
  "Failed to fetch users!": "获取用户失败！",
  "Role names cannot contain special characters except   _ , -": "角色名称不能包含除 _ 、 - 之外的特殊字符",
  "Role names cannot contain special characters except _ , - , / ": "角色名称不能包含除 _ 、 - 、 / 之外的特殊字符",
  "Rules deployed successfully": "规则部署成功",
  "Choose From Template": "从模板中选择",
  "Back to forms": "返回表单",
  "Choose From Templates": "从模板中选择",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "浏览我们的模板库，找到适合的表单和工作流程的完美组合。点击预览模板，如果符合您的需求，定制它以满足您的喜好。一旦按照您的具体要求进行了定制，您就可以创建您的业务案例了",
  "All templates": "所有模板",
  "Template count": "模板数量",
  "Learn more": "了解更多",
  "Template Details": "模板详细信息",
  "Template Title": "模板标题",
  "Preview Form": "预览表单",
  "Connected Workflow": "连接的工作流程",
  "Delete Template": "删除模板",
  "Use Template": "使用模板",
  "Template created successfully": "成功创建模板",
  "Template deleted successfully": "成功删除模板",
  "Template updated successfully": "成功更新模板",
  "Category": "类别",
  "Search category...": "搜索类别...",
  "Save as Template": "另存为模板",
  "Create Template": "创建模板",
  "Select or Create Category": "选择或创建类别",
  "Short Intro": "简短介绍",
  "Enter short intro": "输入简短介绍",
  "Enter description": "输入描述",
  "Select or create": "选择或创建",
  "Update Template": "更新模板",
  "Form created successfully": "成功创建表单",
  "select or create": "选择或创建",
  "Update Associated Form": "更新关联表单",
  "Update Associated Workflow": "更新关联工作流程",
  "Enter title": "输入标题",
  "No Templates Found": "未找到模板",
  "No Category Found": "未找到类别",
  "Save Template": "保存模板",
  "You can type and click the": "您可以输入并单击",
  "to create the category.": "以创建该类别。",
  "select or type to create": "选择或输入以创建",
  "BPMN": "BPMN",
  "DMN": "DMN",
  "Advanced Designer": "高级设计师",
  "Basic Designer": "基础设计师",
  "Search": "搜索",
  "Key": "钥匙",
  "No Process Found": "未找到流程",
  "Search workflow": "搜索工作流程",
  "No Dmn Found": "未找到DMN",
  "Submission ID": "提交编号",
  "Submission Name": "提交名称",
  "Submission History": "提交历史",
  "No Submission History found": "未找到提交历史",
  "Error in submission count": "提交计数错误",
  "Permission for submission tracking.": "提交跟踪权限",
  "Reviewer permission to view submissions": "审阅者查看提交的权限",
  "Permission to create new submission": "创建新提交的权限",
  "Back to Bundle List": "返回捆绑包列表",
  "Bundle": "包",
  "You can drag these nodes to the pane on the right.": "您可以将这些节点拖动到右侧窗格。",
  "You can delete the element by select and click the backspace": "您可以通过选择并单击退格键来删除元素",
  "Workflow Id": "工作流 ID",
  "Enter Workflow Id": "输入工作流 ID",
  "Back to Submissions": "返回提交",
  "Back to Drafts": "返回草稿",
  "Choose Your Workflow Option": "选择您的工作流选项",
  "Create New Workflow": "创建新工作流",
  "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "当您希望基于模板创建全新工作流时，请选择此选项。系统将生成并部署新工作流，然后将其连接到所选表单。如果您的表单需要根据其特定需求定制的一组不同的工作流步骤，请选择此选项。",
  "Reuse Existing Workflow": "重用现有工作流",
  "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "选择此选项以将表单链接到已建立的工作流程。对现有工作流程进行的任何修改将自动反映在此表单中。当您希望利用现有工作流程满足表单要求时，这是理想选择",
  "Are you sure you wish to delete the Template?": "您确定要删除模板吗？",
  "Enter Workflow Name": "输入工作流名称",
  "Create Workflow": "创建工作流",
  "Upload Workflow": "上传工作流",
  "Edit Workflow": "编辑工作流",
  "Published": "已发布",
  "Unpublished": "未发布",
  "Private": "私有",
  "Anonymous": "匿名",
  "Edit Processes": "编辑流程",
  "Create Processes": "创建流程",
  "tasks": "任务",
  "Submission Id": "提交编号",
  "Clear All Filters": "清除所有筛选",
  "Show results": "显示结果",
  "Delete Draft": "删除草稿",
  "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "我可以帮助您轻松设计表单-您只需清晰简洁地描述表单的预期用途即可。我将为您构建字段和布局，您可以进一步自定义。",
  "I am": "我是",
  "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "例如'给我们一个作为门诊诊所患者接诊表的表单'",
  "Enter your prompt here": "在此输入您的提示",
  "Would you like to continue?": "您想继续吗？",
  "Restart": "重新启动",
  "I'm here to provide further assistance. Thank you!": "我在这里提供进一步的帮助。谢谢！",
  "Generate Form Design": "生成表单设计",
  "Preview": "预览",
  "Your form is now ready!": "您的表单现在已准备好！",
  "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description, hit send.": "请告诉我您对表单的所有规格和要求。完成描述后，请按发送。",
  "Choose template": "选择模板",
  "Search by bundle name": "按包名称搜索",
  "Save Bundle": "保存 Bundle",
  "Id": "Id",
  "Enable bundling ?": "启用捆绑？",
  "Select a task in the List.": "选择列表中的任务。",
  "Add Date": "添加日期",
  "Assign to Me": "分配给我",
  "Filter count:": "过滤器计数：",
  "Selected Forms": "已选择的表单",
  "Template Used:": "使用的模板：",
  "Select a task from the List.": "从列表中选择一个任务。",
  "Choose a task from the list; your selection directs your current activity.": "从列表中选择一个任务；您的选择将指导您当前的活动。",
  "Please change the selected filters to view submissions": "请更改所选过滤器以查看提交",
  "Please change the selected filters to view drafts": "请更改所选过滤器以查看草稿",
  "No drafts found": "未找到草稿",
  "Flow-E helps to build faster": "Flow-E有助于更快地构建",
  "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "在试用实例中，无法演示Flow-E。您可以在产品的任何高级套餐中体验Flow-E",
  "Get in touch with formsflow.ai team": "与formsflow.ai团队取得联系",
  "Premium": "优质的",
  "Select a status": "选择一个状态",
  "Group": "群组",
  "Form description": "表单描述",
  "Select all forms": "选择所有表单",
  "Bold": "加粗",
  "Italic": "斜体",
  "Underline": "下划线",
  "Align left": "居左对齐",
  "Align center": "居中对齐",
  "Align right": "居右对齐",
  "Align justify": "两端对齐",
  "Insert Link": "插入链接",
  "Clean": "清除格式",
  "Click for task variables": "点击查看任务变量",
  "Upload DMN": "上传 DMN",
  "DMN Name": "DMN 名称",
  "Search by DMN name": "按 DMN 名称搜索",
  "Display authorized tasks based on user roles": "显示基于用户角色的授权任务",
  "You are currently using a test instance.The trial period ends in": "您当前正在使用测试实例。试用期结束于",
  "days.": "天。",
  "Are you sure to delete": "您确定要删除吗",
  "filter?": "过滤器？",
  "Select Workflow": "选择工作流程",
  "Select Assignee": "选择受让人",
  "Click here to select attributes": "单击此处选择属性",
  "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "选择要在任务列表中显示的预定义属性和自定义任务变量，这些变量是作为表单提交的一部分创建的",
  "Task variables": "任务变量",
  "User Role": "用户角色",
  "User Group": "用户组",
  "Select User Role": "选择用户角色",
  "Select User Group": "选择用户组",
  "To display task variables, select a form as part of the filter": "要显示任务变量，请将表单选择为筛选器的一部分",
  "select a form": "选择一个表单",
  "No task variables found": "未找到任何任务变量",
  "Edit filter": "编辑过滤器",
  "Select form fields to display in task list": "选择要在任务列表中显示的表单字段",
  "Select all fields": "选择所有字段",
  "Edit Label": "编辑标签",
  "Selecting all form fields may affect performance. For the best performance, just pick the form fields you really need.": "选择所有表单字段可能会影响性能。为了获得最佳性能，请只选择您真正需要的表单字段。",
  "User Added successfully!": "用户添加成功！",
  "Failed to create user!": "用户创建失败！",
  "Add Registered Users": "添加注册用户",
  "Username or Email": "用户名或邮箱",
  "Add User": "添加用户",
  "User doesn't exist!": "用户不存在！",
  "Success": "成功",
  "User added": "用户已添加",
  "From": "从",
  "To": "到",
  "Premium Subscription": "高级订阅",
  " For further insights on this exclusive premium feature, kindly connect": "有关此独家高级功能的更多见解，请联系",
  " with our dedicated marketing team for detailed information.": "联系我们专业的营销团队获取详细信息。",
  "Get Connected With Us Now!": "立即与我们联系！",
  "Visit our": "访问我们的",
  "Pricing page": "定价页面",
  "for more details.": "获取更多详细信息。",
  "Integration": "集成",
  "Recipes": "食谱",
  "Connected Apps": "已连接的应用",
  "Library": "库",
  "Add group": "添加组",
  "Add task label": "添加任务标签",
  "Integrations": "集成",
  "We facilitate hundreds of native integrations via our ‘Native Integrations Pro’ package.": "我们通过我们的“原生集成专业版”套餐，可以提供数百种本地集成。",
  " This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "该功能在14天试用期内默认不可用。如果您的试用需要此功能，您可以告诉我们，我们可以为您启用此功能。",
  "Upgrade to unlock Native Integrations Pro": "升级以解锁原生集成专业版",
  "We facilitate hundreds of native integrations via our ": "我们通过我们的原生集成专业版 ",
  "Native Integrations Pro": "原生集成专业版",
  " package. This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "包。该功能在14天试用期内默认情况下不可用。如果您的试用需要此功能，请告诉我们，我们可以为您启用。",
  "To learn more about Native Integrations Pro": "查看原生集成专业版功能",
  "Check out Integrations Feature": "查看集成功能",
  "Connect with": "联系",
  "team for requests or queries.": "团队以获取请求或查询。",
  "Learn more about the feature": "了解更多功能",
  " team.": "团队。",
  "Connect with formsflow.ai team.": "与 formsflow.ai 团队联系。",
  "You don't have permission to access this page.": "您没有权限访问此页面。",
  "Please contact your administrator or try again later.": "请联系您的管理员或稍后再试。",
  "Return to login": "返回登录",
  "Default filter removed": "默认筛选器已移除",
  "Set default filter": "设置默认筛选器",
  "added as default filter": "添加为默认筛选器",
  "Are you sure you wish to delete the draft": "您确定要删除草稿吗",
  ". Are you sure want to delete ?": ".确定要删除吗？",
  "Are you sure you wish to delete the form ": "您确定要删除表格吗 ",
  "Are you sure you wish to delete the form?": "您确定要删除表格吗?",
  "Add form fields to display in task list": "添加表单域以显示在任务列表中",
  "Version": "版本",
  "Are you sure you wish to delete the form": "您确定要删除表格吗",
  "Are you sure you wish to delete this submission?": "您确定要删除此提交吗？",
  "Value": "价值",
  "submission History": "应用历史",
  "Error in getting Workflow Process.": "获取工作流过程时出错。",
  "Error while saving Form.": "保存表单时出错。",
  "Text Area": "文本区",
  "Number": "数字",
  "Password": "密码",
  "Checkbox": "复选框",
  "Select Boxes": "选择框",
  "Radio": "收音机",
  "Button": "按钮",
  "Text Area With Analytics": "带有分析的文本区域",
  "Data": "数据",
  "Display": "展示",
  "Url": "网址",
  "Phone Number": "电话号码",
  "Tags": "标签",
  "Address": "地址",
  "Date / Time": "约会时间",
  "Day": "日",
  "Time": "时间",
  "Currency": "货币",
  "Survey": "民意调查",
  "Signature": "签名",
  "HTML": "HTML",
  "Content": "内容",
  "Columns": "列",
  "Field Set": "字段集",
  "Panel": "控制板",
  "Table": "桌子",
  "Tabs": "标签",
  "Well": "好",
  "Hidden": "隐",
  "Container": "容器",
  "Data Map": "数据地图",
  "Data Grid": "数据网格",
  "Edit Grid": "编辑网格",
  "Tree": "树",
  "reCAPTCHA": "验证码",
  "File": "文件",
  "Nested": "嵌套",
  "Custom": "风俗",
  "Basic": "基本的",
  "Advanced": "先进的",
  "Layout": "布局",
  "Drag and Drop a form component": "拖放表单组件",
  "The minimum length requirement this field must meet.": "此字段必须满足的最小长度要求",
  "The label for this field that will appear next to it.": "此字段旁边将显示的标签。",
  "Label Position": "标签位置",
  "Position for the label for this field.": "此字段的标签位置。",
  "Placeholder": "占位符",
  "The placeholder text that will appear when this field is empty.": "此字段为空时将显示的占位符文本。",
  "The description is text that will appear below the input field.": "描述是将出现在输入字段下方的文本。",
  "Tooltip": "工具提示",
  "Adds a tooltip to the side of this field.": "在此字段的一侧添加工具提示。",
  "To add a tooltip to this field, enter text here.": "要向该字段添加工具提示，请在此处输入文本。",
  "Description for this field.": "此字段的说明。",
  "Prefix": "字首",
  "Suffix": "后缀",
  "Widget": "小工具",
  "The widget is the display UI used to input the value of the field.": "小部件是用于输入字段值的显示 UI。",
  "Right (Left-aligned)": "右（左对齐）",
  "Left (Left-aligned)": "左（左对齐）",
  "Left (Right-aligned)": "左（右对齐）",
  "Right (Right-aligned)": "右（右对齐）",
  "Bottom": " 底部",
  "Component": "零件",
  "Top": "最佳",
  "Label Width": "标签宽度",
  "The width of label on line in percentages.": "在线标签的宽度（以百分比表示）。",
  "Label Margin": "标签页边距",
  "The width of label margin on line in percentages.": "线上标签边距的宽度，以百分比表示。",
  "Rows": "行",
  "Input Field": "输入字段",
  "Calendar Picker": "日历选择器",
  "Select a widget": "选择一个小部件",
  "Input Mask": "输入掩码",
  "Widget Settings": "小工具设置",
  "Allow Multiple Masks": "允许多个掩码",
  "Input Masks": "输入掩码",
  "Mask": "面具",
  "Add Another": "加上另一个",
  "Custom CSS Class": "自定义 CSS 类",
  "Custom CSS class to add to this component.": "要添加到此组件的自定义 CSS 类。",
  "Tab Index": "标签索引",
  "Sets the tabindex attribute of this component to override the tab order of the form. See the MDN documentation on tabindex for more information.": "设置此组件的 tabindex 属性以覆盖表单的 Tab 键顺序。有关更多信息，请参阅有关 tabindex 的 MDN 文档。",
  "Autocomplete": "自动完成",
  "Indicates whether input elements can by default have their values automatically completed by the browser. See the MDN documentation on autocomplete for more information.": "指示默认情况下输入元素是否可以由浏览器自动完成其值。有关更多信息，请参阅有关自动完成的 MDN 文档。",
  "A hidden field is still a part of the form, but is hidden from view.": "隐藏字段仍然是表单的一部分，但在视图中是隐藏的。",
  "Hide Label": "隐藏标签",
  "Show Word Counter": "显示字计数器",
  "Show a live count of the number of words.": "显示字数的实时计数。",
  "Hide the label (title, if no label) of this component. This allows you to show the label in the form builder, but not when it is rendered.": "隐藏该组件的标签（标题，如果没有标签）。这允许您在表单构建器中显示标签，但在呈现时不显示",
  "Show Character Counter": "显示字符计数器",
  "Show a live count of the number of characters.": "显示字符数的实时计数。",
  "Hide Input": "隐藏输入",
  "Hide the input in the browser. This does not encrypt on the server. Do not use for passwords.": "在浏览器中隐藏输入。这不会在服务器上加密。不要用于密码。",
  "Initial Focus": "初始焦点",
  "Make this field the initially focused element on this form.": "使该字段成为此表单上最初关注的元素。",
  "Allow Spellcheck": "允许拼写检查",
  "Disabled": "残障人士",
  "Disable the form input.": "禁用表单输入。",
  "Table View": "表格视图",
  "Shows this value within the table view of the submissions.": "在提交的表格视图中显示此值。",
  "Modal Edit": "模态编辑",
  "Opens up a modal to edit the value of this component.": "打开一个模式来编辑这个组件的值。",
  "Multiple Values": "多个值",
  "Allows multiple values to be entered for this field.": "允许为此字段输入多个值。",
  "Default Value": "默认值",
  "The will be the value for this field, before user interaction. Having a default value will override the placeholder text.": "将是用户交互之前该字段的值。具有默认值将覆盖占位符文本。",
  "Persistent": "执着的",
  "A persistent field will be stored in database when the form is submitted.": "提交表单时，持久性字段将存储在数据库中。",
  "None": "没有任何",
  "Server": "服务器",
  "Client": "客户",
  "Input Format": "输入格式",
  "Force the output of this field to be sanitized in a specific format.": "强制以特定格式清理此字段的输出。",
  "Plain": "清楚的",
  "Type to search": "输入搜索",
  "Raw (Insecure)": "原始（不安全）",
  "Protected": "受保护",
  "A protected field will not be returned when queried via API.": "通过 API 查询时不会返回受保护的字段。",
  "Database Index": "数据库索引",
  "Set this field as an index within the database. Increases performance for submission queries.": "将此字段设置为数据库中的索引。提高提交查询的性能。",
  "Text Case": "文本大小写",
  "When data is entered, you can change the case of the value.": "输入数据时，可以更改值的大小写。",
  "Mixed (Allow upper and lower case)": "混合（允许大小写）",
  "Uppercase": "大写",
  "Lowercase": "小写",
  "Encrypted (Enterprise Only)": "加密（仅限企业）",
  "Encrypt this field on the server. This is two way encryption which is not suitable for passwords.": "在服务器上加密此字段。这是不适合密码的双向加密。",
  "Redraw On": "重绘",
  "Redraw this component if another component changes. This is useful if interpolating parts of the component like the label.": "如果另一个组件发生变化，则重绘该组件。如果插入组件的部分（如标签），这很有用。",
  "Any Change": "任何改变",
  "Clear Value When Hidden": "隐藏时清除值",
  "When a field is hidden, clear the value.": "隐藏字段时，清除该值。",
  "The following variables are available in all scripts.": "以下变量在所有脚本中都可用。",
  "Custom Default Value": "自定义默认值",
  "The complete form JSON object": "完整的表单 JSON 对象",
  "submission": "提交",
  "The complete submission object.": "完整的提交对象。",
  "data": "数据",
  "The complete submission data object.": "完整的提交数据对象。",
  "row": "排",
  "Contextual \"row\" data, used within DataGrid, EditGrid, and Container components": "上下文“行”数据，在 DataGrid、EditGrid 和 Container 组件中使用",
  "component": "零件",
  "The current component JSON": "当前组件 JSON",
  "instance": "实例",
  "The current component instance.": "当前组件实例。",
  "The current value of the component.": "组件的当前值。",
  "moment": "片刻",
  "The moment.js library for date manipulation.": "用于日期操作的 moment.js 库。",
  "utils": "实用程序",
  "util": "实用程序",
  "An alias for \"utils\".": "“utils”的别名。",
  "JavaScript": "JavaScript",
  "Enter custom javascript code.": "输入自定义 JavaScript 代码。",
  "Example:": "例子：",
  "JSONLogic": "JSON逻辑",
  "Execute custom logic using ": "使用执行自定义逻辑",
  "support is provided using an \"_\" before each operation, such as {\"_sum\": {var: \"data.a\"}}": "在每个操作之前使用“_”提供支持，例如 {\"_sum\": {var: \"data.a\"}}",
  "Full": "满的",
  "Calculated Value": "计算值",
  "token": "令牌",
  "The decoded JWT token for the authenticated user.": "经过身份验证的用户的解码 JWT 令牌。",
  "Calculate Value on server": "在服务器上计算值",
  "Checking this will run the calculation on the server. This is useful if you wish to override the values submitted with the calculations performed on the server.": "选中此项将在服务器上运行计算。如果您希望使用在服务器上执行的计算来覆盖提交的值，这将很有用。",
  "Allow Manual Override of Calculated Value": "允许手动覆盖计算值",
  "When checked, this will allow the user to manually override the calculated value.": "选中后，这将允许用户手动覆盖计算值。",
  "Remove": "消除",
  "Validate On": "验证开启",
  "Determines when this component should trigger front-end validation.": "确定此组件何时应触发前端验证。",
  "Change": "改变",
  "Blur": "模糊",
  "Required": "必需的",
  "A required field must be filled in before the form can be submitted.": "必须先填写必填字段，然后才能提交表格。",
  "Unique": "独特的",
  "Makes sure the data submitted for this field is unique, and has not been submitted before.": "确保为此字段提交的数据是唯一的，并且之前没有提交过。",
  "Minimum Length": "最小长度",
  "The maximum length requirement this field must meet.": "此字段必须满足的最大长度要求。",
  "Maximum Length": "最大长度",
  "Minimum Word Length": "最小字长",
  "The minimum amount of words that can be added to this field.": "可以添加到此字段的最小字数。",
  "Maximum Word Length": "最大字长",
  "The maximum amount of words that can be added to this field.": "可以添加到该字段的最大字数。",
  "Regular Expression Pattern": "正则表达式模式",
  "The regular expression pattern test that the field value must pass before the form can be submitted.": "表单提交前字段值必须通过的正则表达式模式测试。",
  "Error Label": "错误标签",
  "The label for this field when an error occurs.": "发生错误时该字段的标签。",
  "Custom Error Message": "自定义错误消息",
  "Error message displayed if any error occurred.": "如果发生任何错误，则会显示错误消息。",
  "Custom Validation": "自定义验证",
  "input": "输入",
  "The value that was input into this component": "输入此组件的值",
  "Enter custom validation code.": "输入自定义验证码。",
  "You must assign the valid variable as either true or an error message if validation fails.": "如果验证失败，您必须将有效变量分配为 true 或错误消息。",
  "Secret Validation": "秘密验证",
  "Check this if you wish to perform the validation ONLY on the server side. This keeps your validation logic private and secret.": "如果您希望仅在服务器端执行验证，请选中此项。这使您的验证逻辑保持私密和保密。",
  "JSONLogic Validation": "JSON逻辑验证",
  "Execute custom logic using": "使用执行自定义逻辑",
  "Validation": "验证",
  "API": "API",
  "Property Name": "属性名称",
  "The name of this field in the API endpoint.": "API 端点中此字段的名称。",
  "Field Tags": "字段标签",
  "Tag the field for use in custom logic.": "标记字段以在自定义逻辑中使用。",
  "Custom Properties": "自定义属性",
  "This allows you to configure any custom properties for this component.": "这允许您为此组件配置任何自定义属性。",
  "Conditional": "有条件的",
  "Simple": "简单的",
  "This component should Display:": "该组件应显示：",
  "True": "真的",
  "False": "错误的",
  "When the form component:": "当表单组件：",
  "Submit (submit)": "提交（提交）",
  "Has the value:": "具有价值：",
  "Advanced Conditions": "高级条件",
  "Advanced Logic": "高级逻辑",
  "Advanced Logic Configured": "高级逻辑配置",
  "Logic": "逻辑",
  "Add Logic": "添加逻辑",
  "Trigger": "扳机",
  "JSON Logic": "JSON 逻辑",
  "\"row\", \"data\", and \"component\" variables are available. Return \"result\".": "“行”、“数据”和“组件”变量可用。返回“结果”。",
  "Action Name": "动作名称",
  "Schema Defenition": "模式定义",
  "\"row\", \"data\", \"component\", and \"result\" variables are available. Return the schema.": "“行”、“数据”、“组件”和“结果”变量可用。返回架构。",
  "Merge Component Schema": "合并组件架构",
  "Custom Action": "自定义操作",
  "You must assign the show variable a boolean result.": "您必须为 show 变量分配一个布尔结果。",
  "Note: Advanced Conditional logic will override the results of the Simple Conditional logic.": "注意：高级条件逻辑将覆盖简单条件逻辑的结果。",
  "Example": "例子",
  "\"row\", \"data\", \"component\" and \"_\" variables are available. Return the result to be passed to the action if truthy.": "“行”、“数据”、“组件”和“_”变量可用。如果为真，则返回要传递给操作的结果。",
  "Add Action": "添加操作",
  "Save Logic": "保存逻辑",
  "Logic Name": "逻辑名称",
  "Event": "事件",
  "The event that will trigger this logic. You can trigger events externally or via a button.": "将触发此逻辑的事件。您可以在外部或通过按钮触发事件。",
  "Save Action": "保存操作",
  "HTML Attributes": "HTML 属性",
  "Attribute Name": "属性名称",
  "Attribute Value": "属性值",
  "Add Attribute": "添加属性",
  "The settings inside apply only to the PDF forms.": "里面的设置仅适用于 PDF 表单。",
  "PDF Overlay": "PDF 叠加",
  "Style": "风格",
  "Custom styles that should be applied to this component when rendered in PDF.": "在 PDF 中呈现时应应用于此组件的自定义样式。",
  "Page": "页",
  "The PDF page to place this component.": "放置此组件的 PDF 页面。",
  "Left": "剩下",
  "The left margin within a page to place this component.": "页面内用于放置此组件的左边距。",
  "The top margin within a page to place this component.": "页面内用于放置此组件的上边距。",
  "Width": "宽度",
  "The width of the component (in pixels).": "组件的宽度（以像素为单位）。",
  "Height": "高度",
  "The height of the component (in pixels).": "组件的高度（以像素为单位）。",
  "Use Thousands Separator": "使用千位分隔符",
  "Separate thousands by local delimiter.": "用本地分隔符分隔数千。",
  "Decimal Places": "小数位",
  "The maximum number of decimal places.": "最大小数位数。",
  "Require Decimal": "需要十进制",
  "Always show decimals, even if trailing zeros.": "始终显示小数，即使尾随零。",
  "Minimum Value": "最小值",
  "The minimum value this field must have before the form can be submitted.": "在提交表单之前该字段必须具有的最小值。",
  "Maximum Value": "最大值",
  "The maximum value this field can have before the form can be submitted.": "在提交表单之前该字段可以具有的最大值。",
  "Editor": "编辑",
  "Select the type of WYSIWYG editor to use for this text area.": "选择用于此文本区域的 WYSIWYG 编辑器类型。",
  "ACE": "高手",
  "Save As": "另存为",
  "This setting determines how the value should be entered and stored in the database.": "此设置确定应如何输入值并将其存储在数据库中。",
  "String": "细绳",
  "JSON": "JSON",
  "Input Type": "输入类型",
  "This is the input type used for this checkbox.": "这是用于此复选框的输入类型。",
  "Shortcut": "捷径",
  "Shortcut for this component.": "此组件的快捷方式。",
  "Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API.": "密码字段使用单向加盐 bcrypt 哈希自动加密。这些哈希值也受到保护，不会在 API 中返回。",
  "Options Label Position": "选项标签位置",
  "Position for the label for options for this field.": "此字段选项标签的位置。",
  "Right": "对",
  "Inline Layout": "内联布局",
  "Displays the checkboxes/radios horizontally.": "水平显示复选框/单选框。",
  "Allow only available values": "仅允许可用值",
  "Minimum checked number": "最小检查数",
  "Minimum checkboxes required before form can be submitted.": "提交表单之前需要最少的复选框。",
  "Maximum checked number": "最大检查数",
  "Maximum checkboxes possible before form can be submitted.": "在提交表单之前可能的最大复选框。",
  "Minimum checked error message": "最小检查错误消息",
  "Error message displayed if minimum number of items not checked.": "如果未检查最小项目数，则会显示错误消息。",
  "Maximum checked error message": "最大检查错误消息",
  "Error message displayed if maximum number of items checked.": "如果检查了最大项目数，则会显示错误消息。",
  "ChoicesJS": "选择JS",
  "HTML 5": "HTML 5",
  "Unique Options": "独特的选择",
  "Display only unique dropdown options.": "仅显示唯一的下拉选项。",
  "Data Source Type": "数据源类型",
  "The source to use for the select data. Values lets you provide your own values and labels. JSON lets you provide raw JSON data. URL lets you provide a URL to retrieve the JSON data from.": "用于选择数据的源。值允许您提供自己的值和标签。 JSON 允许您提供原始 JSON 数据。 URL 允许您提供一个 URL 以从中检索 JSON 数据。",
  "Values": "价值观",
  "on": "在",
  "Raw JSON": "原始 JSON",
  "IndexedDB": "索引数据库",
  "Database name": "数据库名称",
  "The name of the indexeddb database.": "indexeddb 数据库的名称。",
  "Storage Type": "存储类型",
  "The type to store the data. If you select something other than autotype, it will force it to that type.": "存储数据的类型。如果您选择自动输入以外的其他内容，它将强制它使用该类型。",
  "Autotype": "复写",
  "Boolean": "布尔值",
  "Object": "目的",
  "ID Path": "标识路径",
  "Path to the select option id.": "选择选项 ID 的路径。",
  "Table name": "表名",
  "The name of table in the indexeddb database.": "indexeddb 数据库中的表名。",
  "Row Filter": "行过滤器",
  "Filter table items that match the object.": "筛选与对象匹配的表项。",
  "Item Template": "物品模板",
  "The HTML template for the result data items.": "结果数据项的 HTML 模板。",
  "Enable Static Search ": "启用静态搜索",
  "When checked, the select dropdown will allow for searching within the static list of items provided.": "选中后，选择下拉菜单将允许在提供的静态项目列表中进行搜索。",
  "Search Threshold": "搜索阈值",
  "At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match, a threshold of 1.0 would match anything.": "匹配算法在什么时候放弃。 0.0 的阈值需要完美匹配，1.0 的阈值可以匹配任何内容。",
  "Read Only Value": "只读值",
  "Check this if you would like to show just the value when in Read Only mode.": "如果您只想在只读模式下显示值，请选中此项。",
  "Choices.js options": "Choices.js 选项",
  "A raw JSON object to use as options for the Select component (Choices JS).": "用作 Select 组件 (Choices JS) 选项的原始 JSON 对象。",
  "Use exact search": "使用精确搜索",
  "Disables search algorithm threshold.": "禁用搜索算法阈值。",
  "Theme": "主题",
  "The color theme of this button.": "此按钮的颜色主题。",
  "Size": "尺寸",
  "The size of this button": "此按钮的大小",
  "Block Button": "阻止按钮",
  "This control should span the full width of the bounding container.": "此控件应跨越边界容器的整个宽度。",
  "Left Icon": "左图标",
  "This is the full icon class string to show the icon.": "这是显示图标的完整图标类字符串。例子：",
  "Right Icon": "右图标",
  "This is the full icon class string to show the icon. Example:": "这是显示图标的完整图标类字符串。例子：",
  "Primary": "基本的",
  "Secondary": "中学",
  "Info": "信息",
  "Danger": "危险",
  "Warning": "警告",
  "The size of this button.": "此按钮的大小。",
  "Medium": "中等的",
  "Extra Small": "超小号",
  "Small": "小的",
  "Large": "大",
  "Disable on Form Invalid": "禁用表单无效",
  "This will disable this field if the form is invalid.": "如果表单无效，这将禁用此字段。",
  "Key topics for Sentiment Analysis": "情绪分析的关键主题",
  "Enter topics to use in sentiment Analysis": "输入要在情绪分析中使用的主题",
  "Kickbox": "跆拳道",
  "Enable": "使能够",
  "Enable Kickbox validation for this email field.": "为此电子邮件字段启用 Kickbox 验证。",
  "Validate this email using the Kickbox email validation service.": "使用 Kickbox 电子邮件验证服务验证此电子邮件。",
  "Input Mask Placeholder Char": "输入掩码占位符字符",
  "Enable Manual Mode": "启用手动模式",
  "Should Manual Mode be enabled for that component or not.": "是否应该为该组件启用手动模式。",
  "Switch To Manual Mode Label": "切换到手动模式标签",
  "The label for the checkbox used to switch to manual mode.": "用于切换到手动模式的复选框的标签。",
  "Disable Clear Icon": "禁用清除图标",
  "Clear Icon allows easily clear components value.": "清除图标可以轻松清除组件的值。",
  "Provider": "提供者",
  "Which address search service should be used.": "应该使用哪个地址搜索服务。",
  "Manual Mode View String": "手动模式查看字符串",
  "Specify template which should be when quering view string for the component value entered in manual mode. This string is used in table view, CSV export and email rendering. When left blank combined value of all components joined with comma will be used.": "指定在查询手动模式下输入的组件值的视图字符串时应使用的模板。此字符串用于表格视图、CSV 导出和电子邮件呈现。当留空时，将使用用逗号连接的所有组件的组合值。",
  "Azure Maps": "Azure 地图",
  "Google Maps": "谷歌地图",
  "API Key": "API 密钥",
  "Use your Google API key here.": "在此处使用您的 Google API 密钥。",
  "Provider options": "提供者选项",
  "Delimiter": "分隔符",
  "What is used to separate the tags.": "什么是用来分隔标签的。",
  "Max Tags": "最大标签",
  "The maximum amount of tags that can be added. 0 for infinity.": "可以添加的最大标签数量。 0 表示无穷大。",
  "Store As": "存储为",
  "String (CSV)": "字符串 (CSV)",
  "Array of Tags": "标签数组",
  "Display in Timezone": "时区显示",
  "This will display the captured date time in the select timezone.": "这将在选择的时区显示捕获的日期时间。",
  "of Viewer": "观看者",
  "of Submission": "提交的",
  "of Location": "地点",
  "UTC": "世界标准时间",
  "Use locale settings to display date and time.": "使用区域设置显示日期和时间。",
  "Use Locale Settings": "使用区域设置",
  "Allow Manual Input": "允许手动输入",
  "Check this if you would like to allow the user to manually enter in the date.": "如果您希望允许用户手动输入日期，请​​选中此项。",
  "Format": "格式",
  "The date format for displaying the datetime value.": "用于显示日期时间值的日期格式。",
  "Shortcut Buttons": "快捷按钮",
  "You can specify few buttons which will be shown above the calendar. Use Label to specify the name of the button and onClick to specify which date/time will be set when user clicks the button. ": "您可以指定几个将显示在日历上方的按钮。使用 Label 指定按钮的名称，使用 onClick 指定用户单击按钮时将设置的日期/时间。",
  "onClick": "点击",
  "Enable Date Input": "启用日期输入",
  "Enables date input for this field.": "启用此字段的日期输入。",
  "Use Input to add moment.js for minDate": "使用 Input 为 minDate 添加 moment.js",
  "Enables to use input for moment functions instead of calendar.": "允许将输入用于时刻功能而不是日历。",
  "Use calendar to set minDate": "使用日历设置 minDate",
  "Enables to use calendar to set date.": "允许使用日历来设置日期。",
  "Use Input to add moment.js for maxDate": "使用 Input 为 maxDate 添加 moment.js",
  "Use calendar to set maxDate": "使用日历设置 maxDate",
  "Disable specific dates or dates by range": "按范围禁用特定日期或日期",
  "Add dates that you want to blacklist. For example:": "添加要列入黑名单的日期。例如:",
  "Custom Disabled Dates": "自定义禁用日期",
  "date": "日期",
  "The date object.": "日期对象。",
  "Data Format": "数据格式",
  "The moment.js format for saving the value of this field.": "用于保存该字段值的 moment.js 格式。",
  "HTML5 Time Input": "HTML5 时间输入",
  "Text Input with Mask": "带掩码的文本输入",
  "Disable weekends": "禁用周末",
  "Disable weekdays": "禁用工作日",
  "Check to disable weekends": "检查以禁用周末",
  "Check to disable weekdays": "检查以禁用工作日",
  "Enable Time Input": "启用时间输入",
  "Enables time input for this field": "启用此字段的时间输入",
  "Hour Step Size": "小时步长",
  "The number of hours to increment/decrement in the time picker.": "在时间选择器中增加/减少的小时数。",
  "Minute Step Size": "分钟步长",
  "The number of minutes to increment/decrement in the time picker.": "在时间选择器中增加/减少的分钟数。",
  "Display time in 12 hour time with AM/PM.": "以上午/下午的 12 小时时间显示时间。",
  "12 Hour Time (AM/PM)": "12 小时制（上午/下午）",
  "Default Date": "默认日期",
  "You can use Moment.js functions to set the default value to a specific date. For example:": "您可以使用 Moment.js 函数将默认值设置为特定日期。例如：",
  "Flatpickr options": "Flatpickr 选项",
  "HTML Tag": "HTML 标签",
  "The tag of this HTML element.": "此 HTML 元素的标记。",
  "CSS Class": "CSS 类",
  "Attributes": "属性",
  "The attributes for this HTML element. Only safe attributes are allowed, such as src, href, and title.": "此 HTML 元素的属性。只允许使用安全属性，例如 src、href 和 title。",
  "Attribute": "属性",
  "Refresh On Change": "更改时刷新",
  "HTML Element": "HTML 元素",
  "Column Properties": "列属性",
  "The width, offset, push, and pull settings for each column.": "每列的宽度、偏移、推和拉设置。",
  "Offset": "抵消",
  "Push": "推",
  "Pull": "拉",
  "Auto adjust columns": "自动调整列",
  "Will automatically adjust columns based on if nested components are hidden.": "将根据嵌套组件是否隐藏自动调整列。",
  "Hide Column when Children Hidden": "隐藏子项时隐藏列",
  "Check this if you would like to hide any column when the children within that column are also hidden": "如果您想在该列中的子项也被隐藏时隐藏任何列，请选中此项",
  "Legend": "传奇",
  "The legend for this Fieldset.": "此字段集的图例。",
  "Default": "默认",
  "Collapsible": "可折叠",
  "If checked, this will turn this Panel into a collapsible panel.": "如果选中，这将把这个面板变成一个可折叠的面板。",
  "Number of Rows": "行数",
  "Enter the number or rows that should be displayed by this table.": "输入此表应显示的数字或行数。",
  "Number of Columns": "列数",
  "Enter the number or columns that should be displayed by this table.": "输入此表应显示的数字或列。",
  "Clone Row Components": "克隆行组件",
  "Check this if you would like to": "如果您愿意，请选中此项",
  "Cell Alignment": "单元格对齐",
  "Horizontal alignment for cells of the table.": "表格单元格的水平对齐方式。",
  "Center": "中心",
  "Striped": "有条纹的",
  "This will stripe the table if checked.": "如果选中，这将对表格进行条带化。",
  "Bordered": "有边框的",
  "This will border the table if checked.": "如果选中，这将使表格边框。",
  "Hover": "徘徊",
  "Highlight a row on hover.": "悬停时突出显示一行。",
  "Condensed": "浓缩的",
  "Condense the size of the table.": "压缩表的大小。",
  "Label for Key column": "键列的标签",
  "Provide a label text for Key column (otherwise Key will be used)": "为 Key 列提供标签文本（否则将使用“Key”）",
  "Disable Adding / Removing Rows": "禁用添加/删除行",
  "Check if you want to hide Add Another button and Remove Row button": "检查是否要隐藏添加另一个按钮和删除行按钮",
  "Show key column before value": "在值之前显示键列",
  "Check if you would like to show the Key before the Value column.": "检查您是否想在 Value 列之前显示 Key。",
  "Type of event": "活动类型",
  "Specify type of event that this reCAPTCHA would react to": "指定此 reCAPTCHA 将响应的事件类型",
  "Form Load": "表单加载",
  "Button Click": "按钮点击",
  "The form to load within this form component.": "要在此表单组件中加载的表单。",
  "Form Revision": "表格修订",
  "You can lock the nested form to a specific revision by entering the revision number here.": "您可以通过在此处输入修订号将嵌套表单锁定到特定修订。",
  "Use Original Revision while Submissions Viewing": "查看提交时使用原始修订",
  "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission.": "使用此选项将使表单在查看提交时加载原始修订（用于提交的修订）。",
  "Save as reference": "另存为参考",
  "Using this option will save this field as a reference and link its value to the value of the origin record.": "使用此选项会将此字段保存为参考，并将其值链接到原始记录的值。",
  "Select Fields": "选择字段",
  "The properties on the resource to return as part of the options. If left blank, all properties will be returned.": "作为选项的一部分返回的资源的属性。如果留空，将返回所有属性。",
  "Search Fields": "搜索字段",
  "Filter Query": "过滤查询",
  "Use this to provide additional filtering using query parameters.": "使用它来提供使用查询参数的附加过滤。",
  "The filter query for results.": "结果的过滤器查询。",
  "Sort Query": "排序查询",
  "Use this to provide additional sorting using query parameters": "使用它来使用查询参数提供额外的排序",
  "The sort query for results": "结果的排序查询",
  "Add Resource": "添加资源",
  "Allows to create a new resource while entering a submission.": "允许在输入提交时创建新资源。",
  "Add Resource Label": "添加资源标签",
  "Set the text of the Add Resource button.": "设置添加资源按钮的文本。",
  "Auto Expand": "自动展开",
  "Diagram Deployed": "已部署的图表",
  "Deployment Failed": "部署失败",
  "Unfinished Submissions will be saved to Submissions/Drafts.": "未完成的提交将保存到提交/草稿。",
  "Changing the form workflow will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "更改表单工作流程不会影响现有的提交。它只会更新在新创建的提交中。按 Save Changes 继续或取消更改。",
  "Submissions are made against": "提交是针对的",
  "Submission is made against": "提交是针对的",
  "Changing the form title will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "更改表单标题不会影响现有的提交。它只会在新创建的提交中更新。按 Save Changes 继续或取消更改。",
  "No submissions Found": "未找到提交",
  "Create Form, workflow designs": "创建表单，工作流设计",
  "Access to design": "访问设计",
  "Create submissions": "创建提交",
  "Access to submissions": "访问提交",
  "Access to dashboards": "访问仪表板",
  "Access to tasks": "访问任务",
  "Can claim and work on tasks": "可以认领并处理任务",
  "Manage all filters": "管理所有过滤器",
  "Access to create filters": "访问创建过滤器",
  "Access to view filters": "访问查看过滤器",
  "Access to Integrations": "访问集成",
  "Manage Dashboard Authorization": "管理仪表板授权",
  "Manage Users": "管理用户",
  "Manage Roles": "管理角色" ,
  "Permissions": "权限",
  "Edit Permissions": "编辑权限",
  "Select Permissions": "选择权限" ,
  "Proceed to Sign In": "继续登录",
  "Contact formsflow.ai support": "联系 formsflow.ai 支持",
  "Please provide your tenant name to sign in": "请提供您的租户名称以登录",
  "Tenant not found":"未找到租户",
  "Access Roles": "访问角色",
  "Description of the new form": "新表单的描述",
  "Name of the form": "表单名称",
  "Duplicate": "复制",
  "New Form Name": "新表单名称",
  "New Form Description": "新表单描述",
  "Save and Edit form": "保存并编辑表单",
  "Build New Form": "创建新表单",
  "cancel": "取消",
  "previous": "上一页",
  "next": "下一页",
  "Month": "月",
  "Year": "年",
  "Sort": "排序",
  "Sort Results": "排序结果",
  "Sort By": "排序依据",
  "In a": "以",
  "Sort By Dropdown": "排序依据下拉菜单",
  "Sort By Input": "排序依据输入框",
  "Order Dropdown": "排序顺序下拉菜单",
  "Order Input": "排序顺序输入框",
  "Apply sorting": "应用排序",
  "Last Edited": "最后编辑",
}
