/* eslint-disable max-len */
export const RESOURCE_BUNDLES_ZH = {
  "Access restricted by its designer..!": "访问受设计者限制..!",
  "and you will no longer have the access to this form in bundles": "而且您将不再能够在包裹中访问此表单",
  "You will no longer have the access to this form in bundles": "您将不再能够在包裹中访问此表单",
  "Bad Request":"错误的请求",
  "Select the form to be displayed based on the  above criteria":"根据上述条件选择要显示的表单。",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component":"使用任何表单组件的API密钥和条件符号创建条件。例如，'age > 18'，其中'age'是表单组件的API密钥。",
  "Select form version":"选择表格版本",
  "Please remove the special characters...!":"请删除特殊字符...！",
  "No histories found":"没有找到历史记录",
  "Continue":"继续",
  "This will create a new version of the form without changing the path name but with new form id.":"这将创建一个新版本的表单而不更改路径名但具有新的表单 ID。",
  "Save as a new version":"另存为新版本",
  "Save New Version":"保存新版本",
  "Do you want to save a new version of this form?":"您要保存此表单的新版本吗？",
  "Do you want to create a duplicate form and associated workflow from existing form ?":"您要从现有表单创建重复表单和关联工作流吗？",
  "New version created":"已创建新版本",
  "Create a duplicate form":"创建一个重复的表单",
  "Show more":"展示更多",
  "Modified By":"修改者",
  "Created On" : "创建于",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.":"Formsflow 会自动保存您以前的表单数据。现在您可以切换到上一个阶段并进行编辑。",
  "Duplicate Form":"复制表格",
  "Form History":"表单历史",
  "No file chosen":"没有选中任何文件",
  "Choose File":"选择文件",
  "Choose any":"选择任何",
  "Sort by form name":"按表格名称排序",
  "select form type":"选择表格类型",
  "Draft Deleted Successfully":"草稿删除成功",
  "Saved to Applications/Drafts":"保存到申请/草稿",
  "Unfinished applications will be saved to Applications/Drafts.":"未完成的申请将被保存到申请/草稿.",
  "Discard Draft":" 丢弃草稿",
  "Are you sure you wish to delete the draft":"您确定要删除草稿吗",
  "with ID":"带身份证",
  "Please change the selected filters to view Forms":"请更改所选过滤器以查看表格",
  "Search by form name":"按表格名称搜索",
  "Click to search":"点击搜索",
  "No submissions found":"未找到任何提交",
  "No submission avaliable in the selected date. Please select another date range":"在所选日期内没有可用的提交。请选择其他日期范围",
  "Dashboards":"仪表板",
  "Form field":"表单域",
  "Enter Label":"输入标签",
  "Select form field":"选择表单域",
  "Add form fields to display in task list":"添加表单域以显示在任务列表中",
  "Latest Version":"最新版本",
  "Submission Status":"提交状态",
  "No submission status":"无提交状态",
  "No Public url found":"未找到公共网址",
  "Show in list":"显示在列表中",
  "Select Task Variable":"选择任务变量",
  "Enter your Label":"输入您的标签",
  "Please select from one of the following workflows.":"请从以下工作流程之一中选择。",
  "Select Key":"选择键",
  "Create Your Task Variable":"创建您的任务变量",
  "No task variable selected": "未选择任务变量",
  "Workflow Associate":"工作流助理",
  "Task variable":"任务变量",
  "Enter pathname":"输入路径名",
  "Submission Saved": "提交已保存。",
  "Error while Submission.": "提交时出错。",
  "Form saved": "表格已保存。",
  "Submission cannot be done.": "无法提交。 ",
  "Are you sure you wish to delete the form": "您确定要删除表格吗",
  "Are you sure you wish to delete the form?":"您确定要删除表格吗?",
  "Forms": "表格  ",
  "Edit": "编辑",
"Text Field": "文本域",
  "Do you want to associate form with a workflow ?": "您想将表单与工作流相关联吗？",
  "Yes": "是的",
  "No": "否",
  "Form Name": "表格名称 ",
  "Workflow Name": "工作流程名称",
  "Publish this form for Client Users.": "为客户用户发布此表单.",
  "Comments": "评论",
  "Back": "返回",
  "Edit Form": "编辑表格  ",
  "Next": "下一个",
  "Save": "保存  ",
  "Back to Form List": "返回表格列表  ",
  "Submit New": "提交新的  ",
  "View Submissions": "查看提交  ",
  "View/Edit Form": "查看/编辑表单  ",
  "Delete Form": "删除表格  ",
  "Delete": "删除",
  "Print As PDF": "打印为 PDF  ",
  "Applications": "应用",
  "Tasks": "任务",
  "Insights": "洞察力",
  "Dashboard": "仪表盘  ",
  "Logout": "登出",
  "No tasks found": "没有找到任务 ",
  "Please change the selected filters to view tasks": "请更改所选过滤器以查看任务",
  "Clear all filters": "清除所有过滤器",
  "Created": "已创建",
  "Task Variables": "任务变量",
  "Process Variables": "过程变量",
  "Process Definition Name": "进程定义名称",
  "Assignee": "受让人 ",
  "Candidate Group": "候选组",
  "Candidate User": "候选用户",
  "Name": "姓名",
  "Description": "描述",
  "Priority": "优先事项",
 "Due Date": "到期日",
  "Follow up Date": "跟进日期",
 "Task name": "任务名称",
  "Remove sorting": "删除排序",
  "Ascending": "上升",
  "Descending": "降序",
  "Add sorting": "添加排序",
  "of the criteria are met.": "的标准得到满足。",
  "For Variable, ignore case of": "对于变量，忽略大小写",
  "name": "姓名",
  "value": "价值",
  "No task matching filters found.": "未找到匹配过滤器的任务。",
   "Application ID": "应用编号",
  "Set follow-up Date": "设置随访日期",
  "Set Due date": "设置截止日期",
  "Add groups": "添加群组",
  "Claim": "宣称",
  "Search By Last Name": "按姓氏搜索",
  "Search By First Name": "按名字搜索",
   "Search By Email": "通过电子邮件搜索",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "您可以通过在输入字段中输入组 ID，然后单击带加号的按钮来添加组。",
  "Add a group": "添加群组",
  "Process Name": "进程名称",
  "Set FollowUp Date": "设置跟进日期",
  "Groups": "团体",
  "Click to Change Assignee": "单击以更改受让人",
  "Reset Assignee": "重置受让人",
  "Update User": "更新用户",
  "Close": "关闭",
  "Remove search": "删除搜索",
  "Property": "财产",
  "Operator": "操作员",
  "Total number of results": "结果总数",
  "Filter Tasks": "过滤任务",
  "All": "全部",
  "ANY": "任何",
  "Task assignee": "任务受让人",
  "Application History": "应用历史",
 "View Submission": "查看提交",
  "Showing": "显示",
  "to": "到",
  "results": "结果",
  "Acknowledge": "承认",
  "View": "看法",
  "Select a task in the list.": "在列表中选择一个任务。",
  "No Filters Found": "未找到过滤器",
  "Loading": "加载中",
  "Form": "形式",
  "History": "历史",
  "Diagram": "图表",
  "Delete Confirmation": "删除确认",
  "All tasks": "所有任务",
  "Manage Groups": "管理群组",
  "Group ID": "组ID",
  "Due": "到期的",
  "Follow-up": "跟进",
  "Application Name": "应用名称",
  "Created By": "由...制作",
  "Application Status": "申请状态",
  "Request Status": "请求状态",
  "Request Name": "请求名称",
  "Submitted On": "提交日期",
  "Modified On": "修改时间",
  "No History Found": "未找到历史记录",
  "Process Diagram": "流程图",
  "Details": "细节",
  "Status": "地位",
  "Submissions": "提交",
  "No Application History found": "未找到应用历史",
  "Link To Form Submission": "表单提交链接",
  "Last Modified": "最后修改",
  "Metrics": "指标",
  "No dashboard found": "未找到仪表板",
  "of": "的",
  "Select Dashboard": "选择仪表板",
  "Total Submissions": "提交总数",
  "Operations": "运营",
  "Access Groups": "访问组",
  "Action": "行动",
  "Add": "添加",
  "Admin": "行政",
  "Create Form": "创建表格  ",
  "Upload Form": "上传表格",
  "Download Form": "下载表格",
  "Upload json form only": "仅上传 json 表单",
  "Select atleast one form": "选择至少一种形式",
  "Select All": "全选",
  "Created Date": "创建日期",
 "Modified Date": "修改日期",
  "File Upload Status": "文件上传状态",
  "Forms Completed": "完成的表格",
  "Form Completed" : "表格完成",
  "No forms found": "没有找到表格",
  "Powered by ": "供电 ",
  "No Process Diagram found": "未找到流程图",
  "No applications found": "未找到任何应​​用程序",
  "Successfully Updated": "成功更新",
  "Failed": "失败的",
  "Submission Failed.": "提交失败。",
  "Press Enter key or click here to search": "按 Enter 键或点击此处搜索",
  "Click to clear": "点击清除",
  "Search...": "搜索...",
  "Click here to back": "点击这里返回",
  "Enter the form title": "输入表格标题",
  "Enter the form machine name": "输入表格机器名称",
  "Display as": "显示为",
  "Title": "标题",
  "Type": "类型",
  "Path": "小路",
  "example": "例子",
  "Anonymous Form ": "匿名表格",
  "Make this form public ?": "将此表格公开？",
  "Save & Preview": "保存和预览",
  "Design Form": "设计形式  ",
  "Associate this form with a workflow?": "将此表单与工作流相关联？",
  "Preview and Confirm": "预览并确认",
  "All steps completed - you're finished": "已完成所有步骤 - 您已完成",
  "Downloaded Successfully":"下载成功",
  "Error in JSON file structure":"JSON文件结构错误",
  "Please fix the errors before submitting again.":"请在重新提交之前修复错误。",
  "Loading...":"正在加载...",
  "Wizard":"向导",
  "Save Form":"保存表格",
  "Confirm":"确认",
  "Cancel":"取消",
  "Please change the selected filters to view applications":"请更改所选过滤器以查看应用程序",
  "No submissions available for the selected date range":"所选日期范围内没有可用的提交",
  "Ok":"好的",
  "Form not available": "不适用公式",
  "Thank you for your response.":"谢谢您的答复。",
  "saved successfully":"保存成功",
  "Copy anonymous form URL":"复制匿名表单 URL",
  "Submitted By":"由...所提交",
  "Confirmation":"确认",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"更改表单标题不会影响现有应用程序。它只会在新创建的应用程序中更新。按保存更改以继续或取消更改。",
  "Error while saving Form":"保存表单时出错",
  "Click here to go back":"点击此处回去",
  " Applications are submitted against":" 申请是针对",
  " Application is submitted against":" 申请是针对",
  ". Are you sure want to delete ?":".确定要删除吗？",
  "Are you sure you wish to delete the form ":"您确定要删除表格吗 ",
  "Save Changes":"保存更改",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"更改表单工作流程不会影响现有应用程序。它只会在新创建的应用程序中更新。按保存更改以继续或取消更改。",
  "Form-Workflow association saved.": "表单-工作流程关联已保存。",
  "Form-Workflow association failed.": "表单-工作流关联失败。",
  "Form deletion unsuccessful":"表单删除失败",
  "Form deleted successfully":"表格删除成功",
  "Bundle deleted successfully":"捆绑包删除成功",
  "Form process failed":"表单处理失败",
  "Form unpublishing Failed":"表单取消发布失败",
  "All groups have access to the dashboard":"所有组都可以访问仪表板",
  "Export PDF":"导出 PDF",
  "Something went wrong. Please try again!":"出问题了。请再试一次！",
  "No Dashboards Found":"未找到仪表板",
  "Processes":"流程",
  "Please select an existing workflow.":"请选择现有工作流程。",
  "Create New":"创建新的",
  "Or create new workflow or import a workflow from a local directory.":"或创建新工作流或从本地目录导入工作流。",
  "The operation couldn't be completed. Please try after sometime":"操作无法完成。请稍后再试",
  "Select...":"选择...",
  "No Drafts Found":  "未找到草稿",
  "Help":"帮助",
  "Draft Id":"草稿 ID",
  "Draft Name":"草稿名称",
  "Link To Draft Submission":"链接到草稿提交",
  "Drafts":"草稿",
  "You can't submit this form until it is published":"在此表单发布之前，您无法提交此表单",
  "Form not published":"表格未发布",
  "Access Denied" : "拒绝访问",
  "By default, the tenant key would be prefixed to form":"默认情况下，租户键的前缀为 form",
  "go back":"回去",
  "No Applications Found":"未找到任何应​​用程序",
  "Submission saved to draft.":"提交已保存到草稿。",
  "Saved to draft":"已保存到草稿",
  "Saving...":"保存...",
  "Resource":"资源",
  "Error in creating form process mapper":"创建表单流程映射器时出错",
  "Select the date":"选择日期",
  "Diagram deployed":"部署图",
  "Deployment failed":"部署失败",
  "form uploaded":"表格已上传",
  "forms uploaded":"表格已上传",
  "Failed to upload":"上传失败",
  "forms...!":"形式...！",
  "form...!":"形式...！",
  "Process name(s) must not be empty":"进程名称不能为空",
  "URL copied":"已复制网址",
  "Click Here to Copy":"点击这里复制",
  "Resources":"资源",
  "Duplicate form created successfully":"成功创建重复表单",
  "Revert": "恢复",

  "Are you sure you wish to delete the bundle ":"您确定要删除捆绑包吗 ",
  "Select Form":"选择表格",
  "Create Condition":"创造条件",
  "Enter criteria":"输入标准",
  "Make this form public":"公开此表格",
  "Enable bundling":"启用捆绑",
  "Bundle Name":"捆绑名称",
  "View/Edit": "查看/编辑",
  "Create Bundle": "创建捆绑包",
  "Rows per page": "每页行数",
  "entries": "条目",
  "Form Bundle": "表格捆绑",
  "No bundles found": "找不到捆绑包",
  "Please change the selected filters to view Bundles": "请更改所选过滤器以查看捆绑包",
  "Select all to download forms": "全选下载表格",
  "Select for download": "选择下载",
  "Bundle Description": "捆绑包说明",
  "Conditions": "状况",
  "Enter name": "输入名字",
  "Enter Description": "输入说明",
  "You can change the form order by drag and drop": "您可以通过拖放更改表单顺序",
  "Form Order": "表格订单",
  "Form Type": "表单类型",
  "Add Forms Launch together": "添加表单一起启动",
  "Form bundles can save your time by grouping forms together": "表单包可以通过将表单分组在一起来节省您的时间",
  "Add Forms": "添加表格",
  "Criteria": "标准",
  "Create Conditions": "创造条件",
  " Add Conditions": "添加条件",
  "Select Forms": "选择表格",
  "Insert": "插入",
  "View Form": "查看表格",
  "Publish this Bundle for Client Users.": "为客户端用户发布这个包",
  "Total Forms": "总表格",
  "Edit Bundle": "编辑捆绑包",
  "Next Form": "下一个表格",
  "Previous Form": "以前的表格",
  "Forms included under the package": "包中包含的表格",
  "Submit": "提交",
  "Reset Zoom": "重置缩放",
  "Zoom In": "放大",
  "Zoom Out": "缩小",
  "Deploy": "部署",
  "Export": "出口",
  "Overview": "概述",
  "Design Permission": "设计许可",
  "Application Permission":"申请许可",
  "All Designers": "所有设计师",
  "Private(only you)": "私人（只有你）",
  "Specific Designer Group": "特定设计师组",
  "Submission Permission": "提交许可",
  "All Users": "全部用户",
  "Specific User Group": "特定用户群",
  "Specific Reviewers":"具体审稿人",
  "All Reviewers":"所有审稿人",
  "Permission for application tracking.":"应用程序跟踪的权限。",
  "Design Bundle": "设计包",
  "Workflow": "工作流程",
  "Bundle Name and Description is Required": "捆绑包名称和描述为必填项",
  "Bundle Description is Required": "捆绑包描述为必填项",
  "Bundle Create Successfully": "捆绑包创建成功",
  "Bundle updated successfully": "捆绑包更新成功",
  "Select": "选择",
  "Unselect": "取消选择",
  "Applicable for Designer Roled Users only.": "仅适用于设计师角色用户。",
  "Applicable for Client and Reviewer Roled Users only.": "仅适用于客户和审阅者角色用户。",
  "Done":"完毕",
  "Failed to update permission!":"更新权限失败！",
  "Failed to fetch roles!":"获取角色失败！",
  "Failed to update role!":"更新角色失败！",
  "Permission updated successfully!":"权限更新成功！",
  "Role updated successfully!":"角色更新成功！",
  "Update failed!":"更新失败！",
  "Clear":"清除",
  "Are you sure deleting the role":"您确定要删除该角色吗",
  "Confirm Delete":"确认删除",
  "All roles":"所有角色",
  "Filter By:":"过滤：",
  "Create":"创造",
  "Eg: Account Manager":"例如：客户经理",
  "Search by name, username or email":"按姓名、用户名或电子邮件搜索",
  "No data Found":"没有找到数据",
  "Roles": "角色",
  "Users": "用户",
  "Create New Role": "创建新角色",
  "Search by role name": "按角色名称搜索",
  "Role Name": "角色名称",
  "Actions": "动作",
  "Create Role": "创建角色",
  "Email": "电子邮件",
  "Role": "角色",
  "Add Role": "添加角色",
  "Role deleted successfully!": "角色删除成功",
  "Failed to delete role!": "删除角色失败！",
  "Role created successfully!": "角色创建成功！",
  "Failed to create role!": "创建角色失败",
  "Update success!":"更新成功",
  "No results found":"未找到结果",
  "Edit Role":"编辑角色",
  "Failed to fetch users!":"获取用户失败！",
  "Role names cannot contain special characters except   _ , -": "角色名称不能包含除 _ 、 - 之外的特殊字符",
  "Role names cannot contain special characters except _ , - , / ": "角色名称不能包含除 _ 、 - 、 / 之外的特殊字符",
  "Rules deployed successfully": "规则部署成功",
  "Choose From Template": "从模板中选择",
  "Back to forms": "返回表单",
  "Choose From Templates": "从模板中选择",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "浏览我们的模板库，找到适合的表单和工作流程的完美组合。点击预览模板，如果符合您的需求，定制它以满足您的喜好。一旦按照您的具体要求进行了定制，您就可以创建您的业务案例了",
  "All templates": "所有模板",
  "Template count": "模板数量",
  "Learn more": "了解更多",
  "Template Details": "模板详细信息",
  "Template Title": "模板标题",
  "Preview Form": "预览表单",
  "Connected Workflow": "连接的工作流程",
  "Delete Template": "删除模板",
  "Use Template": "使用模板",
  "Template created successfully": "成功创建模板",
  "Template deleted successfully": "成功删除模板",
  "Template updated successfully": "成功更新模板",
  "Category": "类别",
  "Search category...": "搜索类别...",
  "Save as Template": "另存为模板",
  "Create Template": "创建模板",
  "Select or Create Category": "选择或创建类别",
  "Short Intro": "简短介绍",
  "Enter short intro": "输入简短介绍",
  "Enter description": "输入描述",
  "Select or create": "选择或创建",
  "Update Template": "更新模板",
  "Form created successfully": "成功创建表单",
  "select or create": "选择或创建",
  "Update Associated Form": "更新关联表单",
  "Update Associated Workflow": "更新关联工作流程",
  "Enter title": "输入标题",
  "No Templates Found": "未找到模板",
  "No Category Found": "未找到类别",
  "Save Template": "保存模板",
  "You can type and click the": "您可以输入并单击",
  "to create the category.": "以创建该类别。",
  "select or type to create": "选择或输入以创建"


};

