export const RESOURCE_BUNDLES_ES = {
 "No histories found":"No se encontraron historias",
 "Continue":"Continuar",
 "This will create a new version of the form without changing the path name but with new form id.":"Esto creará una nueva versión del formulario sin cambiar el nombre de la ruta pero con un nuevo ID de formulario.",
 "Save as a new version":"Guardar como una nueva versión",
 "Save New Version":"Guardar Nueva Versión",
 "Do you want to save a new version of this form?":"¿Quieres guardar una nueva versión de este formulario?",
 "Do you want to create a duplicate form and associated workflow from existing form ?":"¿Quieres crear un formulario duplicado y un flujo de trabajo asociado a partir de un formulario existente?",
 "New version created":"Nueva versión creada",
 "Create a duplicate form":"Crear un formulario duplicado",
 "Show more":"Mostrar más",
 "Modified By":"Modificado por",
 "Created On" : "Creado el",
 "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.":"Formsflow guarda automáticamente los datos de su formulario anterior. Ahora puede cambiar a la etapa anterior y editar.",
 "Duplicate Form":"Formulario Duplicado",
 "Form History":"Historial del Formulario",
 "No file chosen":"Ningún archivo seleccionado",
 "Choose File":"Seleccionar Archivo",
 "Choose any":"Seleccionar cualquiera",
 "Sort by form name":"Ordenar por nombre de formulario",
 "select form type":"seleccionar tipo de formulario",
 "Draft Deleted Successfully":"Borrador eliminado correctamente",
 "Saved to Applications/Drafts":"Guardado en Aplicaciones/Borradores",
 "Unfinished applications will be saved to Applications/Drafts.":"Las aplicaciones no finalizadas se guardarán en Aplicaciones/Borradores.",
 "Discard Draft":"Descartar borrador",
 "Are you sure you wish to delete the draft":"¿Estás seguro de que deseas eliminar el borrador",
 "with ID":"con ID",
 "Please change the selected filters to view Forms":"Por favor, cambie los filtros seleccionados para ver Formularios",
 "Search by form name":"Buscar por nombre de formulario",
 "Click to search":"Click to search",
 "No submissions found":"No submissions found",
 "No submission available in the selected date. Please select another date range":"No submission available in the selected date. Please select another date range",
 "Form field":"Campo de formulario",
 "Enter Label":"Ingresar etiqueta",
 "Select form field":"Seleccionar campo de formulario",
 "Add form fields to display in task list":"Agregar campos de formulario para mostrar en la lista de tareas",
 "Version":"Versión",
 "Submission Status":"Estado de envío",
 "No submission status":"Sin estado de envío",
 "No Public url found":"No se encontró URL pública",
 "Show in list":"Mostrar en la lista",
 "Select Task Variable":"Seleccionar variable de tarea",
 "Enter your Label":"Ingresar etiqueta",
 "Please select from one of the following workflows.":"Por favor seleccione uno de los siguientes flujos de trabajo.",
 "Select Key":"Seleccionar clave",
 "Create Your Task Variable":"Crear su variable de tarea",
 "No Task variable selected":"No se ha seleccionado ninguna variable de tarea",
 "Workflow Associate":"Asociar flujo de trabajo",
 "Task variable":"Variable de tarea",
 "Enter pathname":"Ingresar nombre de ruta",
 "Name": "Nombre",
 "Title": "Título",
 "Display as": "Mostrar como",
 "Anonymous Form ": "Formulario anónimo",
 "Submission Saved": "Envío guardado.",
 "Error while Submission.": "Error durante el envío.",
 "Message": "Por favor corrija los errores antes de volver a enviar.",
 "Submission cannot be done.": "No se puede realizar el envío.",
 "No Process Diagram found": "No se encontró diagrama de proceso",
 "Are you sure you wish to delete the form": "¿Está seguro que desea eliminar el formulario?",
 "Are you sure you wish to delete the form?":"¿Está seguro que desea eliminar el formulario?",
 'Forms': "Formularios",
 'Form':"Formulario",
 "Downloaded Successfully":"Descargado exitosamente",
 "Edit": "Editar",
 "Do you want to associate form with a workflow ?": "¿Desea asociar el formulario con un flujo de trabajo?",
 "Yes": "Sí",
 "No": "No",
 "Form Name": "Nombre del Formulario",
 "Workflow Name": "Nombre del Flujo de Trabajo",
 "Publish this form for Client Users.": "Publicar este formulario para usuarios del cliente.",
 "Comments":"Comentarios",
 "Back": "Volver",
 "Edit Form": "Editar formulario",
 "Next": "Siguiente",
 "Are you sure you wish to delete this submission?": "¿Está seguro de que desea eliminar esta presentación?",
 "Save": "Guardar",
 "Back to Form List": "Volver a la lista de formularios",
 "Submit New": "Enviar nuevo",
 "View Submissions": "Ver envíos",
 "View/Edit Form": "Ver/Editar formulario",
 "Delete Form": "Eliminar formulario",
 "Delete": "Eliminar",
 "Print As PDF": "Imprimir como PDF",
 "Applications": "Aplicaciones",
 "Tasks": "Tareas",
 "Metrics": "Métricas",
 "Logout": "Cerrar sesión",
 "No tasks found": "No se encontraron tareas",
 "Please change the selected filters to view tasks": "Por favor, cambie los filtros seleccionados para ver las tareas",
 "Clear all filters": "Limpiar todos los filtros",
 "Created": "Creado",
 "Task Variables": "Variables de tarea",
 "Process Variables": "Variables de proceso",
 "Process Definition Name": "Nombre de la definición de proceso",
 "Assigne": "Asignado",
 "Candidate Group": "Grupo de candidatos",
 "Candidate User": "Usuario candidato",
 "Description": "Descripción",
 "Priority": "Prioridad",
 "Due Date": "Fecha de vencimiento",
 "Follow up Date": "Fecha de seguimiento",
 "Task name": "Nombre de la tarea",
 "Remove sorting": "Eliminar ordenamiento",
 "Ascending": "Ascendente",
 "Descending": "Descendente",
 "Add sorting": "Agregar ordenamiento",
 "of the criteria are met.": "si se cumplen los criterios.",
 "For Variable, ignore case of": "Para la variable, ignorar mayúsculas y minúsculas de",
 "name": "nombre",
 "value": "valor",
 "No task matching filters found.": "No se encontraron tareas que coincidan con los filtros.",
 "Application Id": "Id. de aplicación",
 "Set follow-up Date": "Establecer fecha de seguimiento",
 "Set Due date": "Establecer fecha límite",
 "Add groups": "Agregar grupos",
 "Claim": "Reclamar",
 "Search By Last Name": "Buscar por apellido",
 "Search By First Name": "Buscar por nombre",
 "Search By Email": "Buscar por correo electrónico",
 "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Puede agregar un grupo escribiendo un ID de grupo en el campo de entrada y haciendo clic en el botón con el signo más después.",
 "Add a group": "Agregar un grupo",
 "Process Name": "Nombre del proceso",
 "Set FollowUp Date": "Establecer fecha de seguimiento",
 "Groups": "grupos",
 "Click to Change Assignee": "Haga clic para cambiar el asignatario",
 "Reset Assignee": "Restablecer asignatario",
 "Update User": "Actualizar usuario",
 "Close": "Cerrar",
 "Type": "Tipo",
 "Remove search": "Eliminar búsqueda",
 "Property": "Propiedad",
 "Operator": "Operador",
 "Total number of results": "Número total de resultados",
 "Filter Tasks": "Filtrar tareas",
 "All": "Todos",
 "ANY": "Cualquiera",
 "Task assignee": "Asignado a",
 "Application History": "Historial de aplicación",
 "View Submission": "Ver envío",
 "Showing": "Mostrando",
 "to": "a",
 "Results": "Resultados",
 "Acknowledge": "Aceptar",
 "View": "Ver",
 "Select a task in the list.": "Seleccione una tarea en la lista.",
 "No Filters Found": "No se encontraron filtros",
 "Loading": "Cargando",
 "Loading...": "Cargando...",
 "History": "Historial",
 "Diagram": "Diagrama",
 "Delete Confirmation": "Confirmación de eliminación",
 "All tasks": "Todas las tareas",
 "Manage Groups": "Administrar grupos",
 "Group ID": "ID de grupo",
 "Due": "Fecha límite",
 "Follow-up": "Seguimiento",
 "Application Name": "Nombre de la aplicación",
 "Created By": "Creado por",
 "Application Status": "Estado de la aplicación",
 "Submitted On": "Enviado en",
 "Modified On": "Modificado en",
 "No History Found": "No se encontró historial",
 "Process Diagram": "Diagrama del proceso",
 "Details": "Detalles",
 "Status": "Estado",
 "Submissions": "Envíos",
 "No Application History found": "No se encontró historial de la aplicación",
 "Link To Form Submission": "Enlace al envío del formulario",
 "Last Modified": "Última modificación",
 "Insights": "Perspectivas",
 "No dashboard found": "No se encontró ningún panel de control",
 "of": "de",
 "results": "resultados",
 "Dashboard": "Panel de control",
 "Dashboards": "Paneles de control",
 "Select Dashboard": "Seleccionar panel de control",
 "Total Submissions": "Total de envíos",
 "Save & Preview": "Guardar y previsualizar",
 "Operations": "Operaciones",
 "Access Groups": "Grupos de acceso",
 "Action": "Acción",
 "Add": "Agregar",
 "Admin": "Administrador",
 "Create Form": "Crear formulario",
 "Upload Form": "Subir formulario",
 "Download Form": "Descargar formulario",
 "Upload json form only": "Solo cargar formulario json",
 "Select atleast one form": "Seleccionar al menos un formulario",
 "Select All": "Seleccionar todo",
 "Created Date": "Fecha de creación",
 "Modified Date": "Fecha de modificación",
 "File Upload Status": "Estado de carga de archivos",
 "Forms Completed": "Formularios completados",
 "Form Completed": "Formulario completado",
 "No forms found": "No se encontraron formularios",
 "Powered by ": "Desarrollado por ",
 "Press Enter key or click here to search": "Presionar la tecla Enter o hacer clic aquí para buscar",
 "Click to clear": "Hacer clic para limpiar",
 "No applications found": "No se encontraron aplicaciones",
 "Successfully Updated": "Actualizado exitosamente",
 "Failed": "Falló",
 "Submission Failed.": "Falló la presentación.",
 "Click here to back": "Hacer clic aquí para volver",
 "Path": "Ruta",
 "Make this form public ?": "¿Hacer público este formulario?",
 "Design Form": "Diseñar formulario",
 "Associate this form with a workflow?": "¿Asociar este formulario con un flujo de trabajo?",
 "Preview and Confirm": "Previsualizar y confirmar",
 "All steps completed - you're finished": "Todos los pasos completados - has terminado",
 "Enter the form machine name": "Ingrese el nombre de la máquina del formulario",
 "Enter the form title": "Ingrese el título del formulario",
 "Error in JSON file structure": "Error en la estructura del archivo JSON",
 "example": "ejemplo",
 "Please fix the errors before submitting again.": "Por favor, corrija los errores antes de volver a enviar.",
 "Wizard": "Asistente",
 "Save Form": "Guardar formulario",
 "Confirm": "Confirmar",
 "Cancel": "Cancelar",
 "Please change the selected filters to view applications": "Por favor, cambie los filtros seleccionados para ver las aplicaciones",
 "No submissions available for the selected date range": "No hay envíos disponibles para el rango de fechas seleccionado",
 "Ok": "Aceptar",
 "Form not available": "Formulario no disponible",
 "Thank you for your response.": "Gracias por su respuesta.",
 "saved successfully": "guardado exitosamente",
 "Copy anonymous form URL": "Copiar URL del formulario anónimo",
 "Submitted By": "Enviado por",
 "Confirmation": "Confirmación",
 "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Cambiar el título del formulario no afectará las aplicaciones existentes. Solo se actualizará en las aplicaciones recién creadas. Presione Guardar cambios para continuar o cancelar los cambios.",
 "Error while saving Form": "Error al guardar el formulario",
 "Click here to go back": "Haga clic aquí para volver",
 "Are you sure you wish to delete the form ": "¿Está seguro de que desea eliminar el formulario ",
 "Applications are submitted against": "Las aplicaciones se envían contra",
 "Application is submitted against": "La aplicación se envía contra",
 ". Are you sure want to delete ?": ". ¿Está seguro de que desea eliminar?",
 "Save Changes": "Guardar cambios",
 "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Cambiar el flujo de trabajo del formulario no afectará las aplicaciones existentes. Solo se actualizará en las aplicaciones recién creadas. Presione Guardar cambios para continuar o cancelar los cambios.",
 "Form Workflow Association Saved.": "Asociación de flujo de trabajo del formulario guardada.",
 "Form deleted successfully": "Formulario eliminado correctamente",
 "Form process failed": "Proceso de formulario fallido",
 "Form unpublishing Failed": "La eliminación de publicación del formulario falló",
 "All groups have access to the dashboard": "Todos los grupos tienen acceso al panel",
 "Export PDF": "Exportar a PDF",
 "Something went wrong. Please try again!": "Algo salió mal. ¡Por favor, inténtelo de nuevo!",
 "No Dashboards Found": "No se encontraron paneles",
 "Processes": "Procesos",
 "Please select an existing workflow.": "Por favor, seleccione un flujo de trabajo existente.",
 "Create New": "Crear nuevo",
 "Or create new workflow or import a workflow from a local directory.": "O cree un nuevo flujo de trabajo o importe un flujo de trabajo desde un directorio local.",
 "The operation couldn't be completed. Please try after sometime":"La operación no se pudo completar. Por favor, inténtalo de nuevo más tarde.",
 "Select...":"Seleccionar...",
 "No Drafts Found":  "No se encontraron borradores",
 "Help":"Ayuda",
 "Draft Id":"ID del borrador",
 "Draft Name":"Nombre del borrador",
 "Link To Draft Submission":"Enlace al envío del borrador",
 "Drafts":"Borradores",
 "You can't submit this form until it is published":"No puedes enviar este formulario hasta que sea publicado",
 "Form not published":"Formulario no publicado",
 "Access Denied" : "Acceso denegado",
 "By default, the tenant key would be prefixed to form":"Por defecto, la clave del inquilino se prefijará al formulario",
 "go back":"Volver",
 "No Applications Found":"No se encontraron aplicaciones",
 "Submission saved to draft.":"El envío se guardó en borrador.",
 "Saved to draft":"Guardado en borrador",
 "Saving...":"Guardando...",
 "Resource":"Recurso",
 "Error in creating form process mapper":"Error al crear el mapeador de procesos del formulario",
 "Select the date":"Seleccionar la fecha",
 "Diagram Deployed":"Diagrama desplegado",
 "Deployment Failed":"Error al desplegar",
 "Process name(s) must not be empty":"El nombre del proceso no debe estar vacío",
 "URL copied":"URL copiada",
 "Click Here to Copy":"Haz clic aquí para copiar",
 "Resources":"Recursos",
 "Duplicate form created successfully":"Formulario duplicado creado exitosamente",
 "You don't have permission to access this page.": "No tienes permiso para acceder a esta página.",
 "Please contact your administrator or try again later.": "Por favor, contacta a tu administrador o intenta nuevamente más tarde.",
 "Return to login": "Volver a iniciar sesión"
  };
  
  
  
  