export const RESOURCE_BUNDLES_ES = {
    "No histories found": "No se encontraron historias",
    "Continue": "Continuar",
    "This will create a new version of the form without changing the path name but with new form id.": "Esto creará una nueva versión del formulario sin cambiar el nombre de la ruta pero con un nuevo ID de formulario.",
    "Save as a new version": "Guardar como una nueva versión",
    "Save New Version": "Guardar Nueva Versión",
    "Do you want to save a new version of this form?": "¿Quieres guardar una nueva versión de este formulario?",
    "Do you want to create a duplicate form and associated workflow from existing form ?": "¿Quieres crear un formulario duplicado y un flujo de trabajo asociado a partir de un formulario existente?",
    "New version created": "Nueva versión creada",
    "Create a duplicate form": "Crear un formulario duplicado",
    "Show more": "Mostrar más",
    "Modified By": "Modificado por",
    "Created On": "Creado el",
    "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "Formsflow guarda automáticamente los datos de su formulario anterior. Ahora puede cambiar a la etapa anterior y editar.",
    "Duplicate Form": "Formulario Duplicado",
    "Form History": "Historial del Formulario",
    "No file chosen": "Ningún archivo seleccionado",
    "Choose File": "Seleccionar Archivo",
    "Choose any": "Seleccionar cualquiera",
    "Sort by form name": "Ordenar por nombre de formulario",
    "select form type": "seleccionar tipo de formulario",
    "Draft Deleted Successfully": "Borrador eliminado correctamente",
    "Saved to Applications/Drafts": "Guardado en Aplicaciones/Borradores",
    "Unfinished applications will be saved to Applications/Drafts.": "Las aplicaciones no finalizadas se guardarán en Aplicaciones/Borradores.",
    "Discard Draft": "Descartar borrador",
    "Are you sure you wish to delete the draft": "¿Estás seguro de que deseas eliminar el borrador",
    "with ID": "con ID",
    "Please change the selected filters to view Forms": "Por favor, cambie los filtros seleccionados para ver Formularios",
    "Search by form name": "Buscar por nombre de formulario",
    "Click to search": "Click to search",
    "No submissions found": "No submissions found",
    "Form field": "Campo de formulario",
    "Enter Label": "Ingresar etiqueta",
    "Select form field": "Seleccionar campo de formulario",
    "Add form fields to display in task list": "Agregar campos de formulario para mostrar en la lista de tareas",
    "Version": "Versión",
    "Submission Status": "Estado de envío",
    "No submission status": "Sin estado de envío",
    "No Public url found": "No se encontró URL pública",
    "Show in list": "Mostrar en la lista",
    "Select Task Variable": "Seleccionar variable de tarea",
    "Enter your Label": "Ingresar etiqueta",
    "Please select from one of the following workflows.": "Por favor seleccione uno de los siguientes flujos de trabajo.",
    "Select Key": "Seleccionar clave",
    "Create Your Task Variable": "Crear su variable de tarea",
    "No Task variable selected": "No se ha seleccionado ninguna variable de tarea",
    "Workflow Associate": "Asociar flujo de trabajo",
    "Task variable": "Variable de tarea",
    "Enter pathname": "Ingresar nombre de ruta",
    "Name": "Nombre",
    "Title": "Título",
    "Display as": "Mostrar como",
    "Anonymous Form ": "Formulario anónimo",
    "Submission Saved": "Envío guardado.",
    "Error while Submission.": "Error durante el envío.",
    "Message": "Por favor corrija los errores antes de volver a enviar.",
    "Submission cannot be done.": "No se puede realizar el envío.",
    "No Process Diagram found": "No se encontró diagrama de proceso",
    "Are you sure you wish to delete the form": "¿Está seguro que desea eliminar el formulario?",
    "Are you sure you wish to delete the form?": "¿Está seguro que desea eliminar el formulario?",
    "Forms": "Formularios",
    "Form": "Formulario",
    "Downloaded Successfully": "Descargado exitosamente",
    "Edit": "Editar",
    "Do you want to associate form with a workflow ?": "¿Desea asociar el formulario con un flujo de trabajo?",
    "Yes": "Sí",
    "No": "No",
    "Form Name": "Nombre del Formulario",
    "Workflow Name": "Nombre del Flujo de Trabajo",
    "Publish this form for Client Users.": "Publicar este formulario para usuarios del cliente.",
    "Comments": "Comentarios",
    "Back": "Volver",
    "Edit Form": "Editar formulario",
    "Next": "Siguiente",
    "Are you sure you wish to delete this submission?": "¿Está seguro de que desea eliminar esta presentación?",
    "Save": "Guardar",
    "Back to Form List": "Volver a la lista de formularios",
    "Submit New": "Enviar nuevo",
    "View Submissions": "Ver envíos",
    "View/Edit Form": "Ver/Editar formulario",
    "Delete Form": "Eliminar formulario",
    "Delete": "Eliminar",
    "Print As PDF": "Imprimir como PDF",
    "Applications": "Aplicaciones",
    "Tasks": "Tareas",
    "Metrics": "Métricas",
    "Logout": "Cerrar sesión",
    "No tasks found": "No se encontraron tareas",
    "Please change the selected filters to view tasks": "Por favor, cambie los filtros seleccionados para ver las tareas",
    "Clear all filters": "Limpiar todos los filtros",
    "Created": "Creado",
    "Task Variables": "Variables de tarea",
    "Process Variables": "Variables de proceso",
    "Process Definition Name": "Nombre de la definición de proceso",
    "Assigne": "Asignado",
    "Candidate Group": "Grupo de candidatos",
    "Candidate User": "Usuario candidato",
    "Description": "Descripción",
    "Priority": "Prioridad",
    "Due Date": "Fecha de vencimiento",
    "Follow up Date": "Fecha de seguimiento",
    "Task name": "Nombre de la tarea",
    "Remove sorting": "Eliminar ordenamiento",
    "Ascending": "Ascendente",
    "Descending": "Descendente",
    "Add sorting": "Agregar ordenamiento",
    "of the criteria are met.": "si se cumplen los criterios.",
    "For Variable, ignore case of": "Para la variable, ignorar mayúsculas y minúsculas de",
    "name": "nombre",
    "value": "valor",
    "No task matching filters found.": "No se encontraron tareas que coincidan con los filtros.",
    "Application Id": "Id. de aplicación",
    "Set follow-up Date": "Establecer fecha de seguimiento",
    "Set Due date": "Establecer fecha límite",
    "Add groups": "Agregar grupos",
    "Claim": "Reclamar",
    "Search By Last Name": "Buscar por apellido",
    "Search By First Name": "Buscar por nombre",
    "Search By Email": "Buscar por correo electrónico",
    "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Puede agregar un grupo escribiendo un ID de grupo en el campo de entrada y haciendo clic en el botón con el signo más después.",
    "Add a group": "Agregar un grupo",
    "Process Name": "Nombre del proceso",
    "Set FollowUp Date": "Establecer fecha de seguimiento",
    "Groups": "grupos",
    "Click to Change Assignee": "Haga clic para cambiar el asignatario",
    "Reset Assignee": "Restablecer asignatario",
    "Update User": "Actualizar usuario",
    "Close": "Cerrar",
    "Type": "Tipo",
    "Remove search": "Eliminar búsqueda",
    "Property": "Propiedad",
    "Operator": "Operador",
    "Total number of results": "Número total de resultados",
    "Filter Tasks": "Filtrar tareas",
    "All": "Todos",
    "ANY": "Cualquiera",
    "Task assignee": "Asignado a",
    "Application History": "Historial de aplicación",
    "View Submission": "Ver envío",
    "Showing": "Mostrando",
    "to": "a",
    "Results": "Resultados",
    "Acknowledge": "Aceptar",
    "View": "Ver",
    "Select a task in the list.": "Seleccione una tarea en la lista.",
    "No Filters Found": "No se encontraron filtros",
    "Loading": "Cargando",
    "Loading...": "Cargando...",
    "History": "Historial",
    "Diagram": "Diagrama",
    "Delete Confirmation": "Confirmación de eliminación",
    "All tasks": "Todas las tareas",
    "Manage Groups": "Administrar grupos",
    "Group ID": "ID de grupo",
    "Due": "Fecha límite",
    "Follow-up": "Seguimiento",
    "Application Name": "Nombre de la aplicación",
    "Created By": "Creado por",
    "Application Status": "Estado de la aplicación",
    "Submitted On": "Enviado en",
    "Modified On": "Modificado en",
    "No History Found": "No se encontró historial",
    "Process Diagram": "Diagrama del proceso",
    "Details": "Detalles",
    "Status": "Estado",
    "Submissions": "Envíos",
    "No Application History found": "No se encontró historial de la aplicación",
    "Link To Form Submission": "Enlace al envío del formulario",
    "Last Modified": "Última modificación",
    "Insights": "Perspectivas",
    "No dashboard found": "No se encontró ningún panel de control",
    "of": "de",
    "results": "resultados",
    "Dashboards": "Paneles de control",
    "Select Dashboard": "Seleccionar panel de control",
    "Total Submissions": "Total de envíos",
    "Save & Preview": "Guardar y previsualizar",
    "Operations": "Operaciones",
    "Access Groups": "Grupos de acceso",
    "Action": "Acción",
    "Add": "Agregar",
    "Admin": "Administrador",
    "Create Form": "Crear formulario",
    "Upload Form": "Subir formulario",
    "Download Form": "Descargar formulario",
    "Upload json form only": "Solo cargar formulario json",
    "Select atleast one form": "Seleccionar al menos un formulario",
    "Select All": "Seleccionar todo",
    "Created Date": "Fecha de creación",
    "Modified Date": "Fecha de modificación",
    "File Upload Status": "Estado de carga de archivos",
    "Forms Completed": "Formularios completados",
    "Form Completed": "Formulario completado",
    "No forms found": "No se encontraron formularios",
    "Powered by ": "Desarrollado por ",
    "Press Enter key or click here to search": "Presionar la tecla Enter o hacer clic aquí para buscar",
    "Click to clear": "Hacer clic para limpiar",
    "No applications found": "No se encontraron aplicaciones",
    "Successfully Updated": "Actualizado exitosamente",
    "Failed": "Falló",
    "Submission Failed.": "Falló la presentación.",
    "Click here to back": "Hacer clic aquí para volver",
    "Path": "Ruta",
    "Make this form public ?": "¿Hacer público este formulario?",
    "Design Form": "Diseñar formulario",
    "Associate this form with a workflow?": "¿Asociar este formulario con un flujo de trabajo?",
    "Preview and Confirm": "Previsualizar y confirmar",
    "All steps completed - you're finished": "Todos los pasos completados - has terminado",
    "Enter the form machine name": "Ingrese el nombre de la máquina del formulario",
    "Enter the form title": "Ingrese el título del formulario",
    "Error in JSON file structure": "Error en la estructura del archivo JSON",
    "example": "ejemplo",
    "Please fix the errors before submitting again.": "Por favor, corrija los errores antes de volver a enviar.",
    "Wizard": "Asistente",
    "Save Form": "Guardar formulario",
    "Confirm": "Confirmar",
    "Cancel": "Cancelar",
    "Please change the selected filters to view applications": "Por favor, cambie los filtros seleccionados para ver las aplicaciones",
    "No submissions available for the selected date range": "No hay envíos disponibles para el rango de fechas seleccionado",
    "Ok": "Aceptar",
    "Form not available": "Formulario no disponible",
    "Thank you for your response.": "Gracias por su respuesta.",
    "saved successfully": "guardado exitosamente",
    "Copy anonymous form URL": "Copiar URL del formulario anónimo",
    "Submitted By": "Enviado por",
    "Confirmation": "Confirmación",
    "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Cambiar el título del formulario no afectará las aplicaciones existentes. Solo se actualizará en las aplicaciones recién creadas. Presione Guardar cambios para continuar o cancelar los cambios.",
    "Error while saving Form": "Error al guardar el formulario",
    "Click here to go back": "Haga clic aquí para volver",
    "Are you sure you wish to delete the form ": "¿Está seguro de que desea eliminar el formulario ",
    ". Are you sure want to delete ?": ". ¿Está seguro de que desea eliminar?",
    "Save Changes": "Guardar cambios",
    "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Cambiar el flujo de trabajo del formulario no afectará las aplicaciones existentes. Solo se actualizará en las aplicaciones recién creadas. Presione Guardar cambios para continuar o cancelar los cambios.",
    "Form Workflow Association Saved.": "Asociación de flujo de trabajo del formulario guardada.",
    "Form deleted successfully": "Formulario eliminado correctamente",
    "Form process failed": "Proceso de formulario fallido",
    "Form unpublishing Failed": "La eliminación de publicación del formulario falló",
    "All groups have access to the dashboard": "Todos los grupos tienen acceso al panel",
    "Export PDF": "Exportar a PDF",
    "Something went wrong. Please try again!": "Algo salió mal. ¡Por favor, inténtelo de nuevo!",
    "No Dashboards Found": "No se encontraron paneles",
    "Processes": "Procesos",
    "Please select an existing workflow.": "Por favor, seleccione un flujo de trabajo existente.",
    "Create New": "Crear nuevo",
    "Or create new workflow or import a workflow from a local directory.": "O cree un nuevo flujo de trabajo o importe un flujo de trabajo desde un directorio local.",
    "The operation couldn't be completed. Please try after sometime": "La operación no se pudo completar. Por favor, inténtalo de nuevo más tarde.",
    "Select...": "Seleccionar...",
    "No Drafts Found": "No se encontraron borradores",
    "Help": "Ayuda",
    "Draft Id": "ID del borrador",
    "Draft Name": "Nombre del borrador",
    "Link To Draft Submission": "Enlace al envío del borrador",
    "Drafts": "Borradores",
    "You can't submit this form until it is published": "No puedes enviar este formulario hasta que sea publicado",
    "Form not published": "Formulario no publicado",
    "Access Denied": "Acceso denegado",
    "By default, the tenant key would be prefixed to form": "Por defecto, la clave del inquilino se prefijará al formulario",
    "go back": "Volver",
    "No Applications Found": "No se encontraron aplicaciones",
    "Submission saved to draft.": "El envío se guardó en borrador.",
    "Saved to draft": "Guardado en borrador",
    "Saving...": "Guardando...",
    "Resource": "Recurso",
    "Error in creating form process mapper": "Error al crear el mapeador de procesos del formulario",
    "Select the date": "Seleccionar la fecha",
    "Diagram Deployed": "Diagrama desplegado",
    "Deployment Failed": "Error al desplegar",
    "Process name(s) must not be empty": "El nombre del proceso no debe estar vacío",
    "URL copied": "URL copiada",
    "Click Here to Copy": "Haz clic aquí para copiar",
    "Resources": "Recursos",
    "Duplicate form created successfully": "Formulario duplicado creado exitosamente",
    "You don't have permission to access this page.": "No tienes permiso para acceder a esta página.",
    "Please contact your administrator or try again later.": "Por favor, contacta a tu administrador o intenta nuevamente más tarde.",
    "Return to login": "Volver a iniciar sesión",
    "Submit Form": "Enviar Formulario",
    "Changes Applied Successfully": "Cambios Aplicados Exitosamente",
    "Filter Deleted Successfully": "Filtro Eliminado Exitosamente",
    "Save Filter": "Guardar Filtro",
    "Filter Name": "Nombre del Filtro",
    "Create new filter": "Crear Nuevo Filtro",
    "Definition Key": "Clave de Definición",
    "Permission": "Permiso",
    "Enter your text here": "Ingrese su texto aquí",
    "Accessible for all users": "Accesible para todos los usuarios",
    "Private (Only You)": "Privado (Solo Tú)",
    "Specific Group": "Grupo Específico",
    "Select Elements": "Seleccionar Elementos",
    "Task Attributes Selected": "Atributos de Tarea Seleccionados",
    "Delete Filter": "Eliminar Filtro",
    "Add Value": "Agregar Valor",
    "Show only current user assigned task": "Mostrar solo tareas asignadas al usuario actual",
    "Show task based on logged user roles": "Mostrar tareas según los roles del usuario registrado",
    "Create Filter": "Crear Filtro",
    "Task Attributes": "Atributos de Tarea",
    "Only selected task attributes will be available on task list view": "Solo los atributos de tarea seleccionados estarán disponibles en la vista de lista de tareas",
    "Show undefined variables": "Mostrar variables indefinidas",
    "Label": "Etiqueta",
    "Variables": "Variables",
    "Task Title": "Título de la Tarea",
    "List View": "Vista de Lista",
    "Card View": "Vista de Tarjetas",
    "Create New Filter": "Crear Nuevo Filtro",
    "Sort by": "Ordenar por",
    "Collapse All": "Colapsar Todo",
    "Expand All": "Expandir Todo",
    "Back to task": "Volver a la tarea",
    "Filters": "Filtros",
    "Assignee": "Asignado a",
    "Select a user": "Seleccionar un usuario",
    "Create DMN": "Crear DMN",
    "Create Process": "Crear Proceso",
    "Edit DMN": "Editar DMN",
    "More options": "Más opciones",
    "Form Description": "Descripción del Formulario",
    "Saved to Submissions/Drafts": "Guardado en Envíos/Borradores",
    "Unfinished submissions will be saved to Submissions/Drafts.": "Las presentaciones incompletas se guardarán en Envíos/Borradores.",
    "Edit Process": "Editar Proceso",
    "Add filter name": "Agregar nombre del filtro",
    "This section is aimed to set the parameters\nused to filter the tasks": "Esta sección está destinada a establecer los parámetros\nutilizados para filtrar las tareas",
    "This section is aimed to set read\npermissions for the filter": "Esta sección está destinada a establecer permisos de lectura\npara el filtro",
    "This section is aimed to set select\ntask attributes that will be visible in\nthe task list view": "Esta sección está destinada a establecer los atributos de tarea seleccionados\nque serán visibles en la vista de lista de tareas",
    "Task Attribute": "Atributo de Tarea",
    "You can define variables shown in the list": "Puede definir las variables que se mostrarán en la lista",
    "Enter role name": "Ingrese el nombre del rol",
    "Public": "Público",
    "View Submitted Form": "Ver Formulario Enviado",
    "View Draft Details": "Ver Detalles del Borrador",
    "Edit Draft": "Editar Borrador",
    "Draft Title": "Título del Borrador",
    "Filter": "Filtro",
    "Advanced Options": "Opciones Avanzadas",
    "Enter the path name": "Ingrese el nombre del camino",
    "Search by form title": "Buscar por título del formulario",
    "Associate Workflow": "Asociar Flujo de Trabajo",
    "Search by workflow name": "Buscar por nombre del flujo de trabajo",
    "View Details": "Ver Detalles",
    "Visibility": "Visibilidad",
    "Form Title": "Título del Formulario",
    "Access restricted by its designer..!": "Acceso restringido por su diseñador..!",
    "and you will no longer have the access to this form in bundles": "y ya no tendrá acceso a este formulario en paquetes",
    "You will no longer have the access to this form in bundles": "Ya no tendrá acceso a este formulario en paquetes",
    "Bad Request": "Solicitud Incorrecta",
    "Select the form to be displayed based on the  above criteria": "Seleccione el formulario que se mostrará según los criterios anteriores",
    "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "Cree los criterios utilizando la clave API de cualquier componente del formulario y una notación condicional. Por ejemplo, 'edad > 18' donde 'edad' es la clave API de un componente del formulario",
    "Select form version": "Seleccionar versión del formulario",
    "Please remove the special characters...!": "¡Por favor, elimine los caracteres especiales...!",
    "No submission available in the selected date. Please select another date range": "No hay envíos disponibles en la fecha seleccionada. Por favor, seleccione otro rango de fechas",
    "Latest Version": "Última Versión",
    "No task variable selected": "No se ha seleccionado ninguna variable de tarea",
    "Form saved": "Formulario guardado.",
    "Request Status": "Estado de la Solicitud",
    "Request Name": "Nombre de la Solicitud",
    "Applications are submitted against": "Las solicitudes se presentan contra",
    "Application is submitted against": "La solicitud se presenta contra",
    "Are you sure to delete the": "¿Está seguro de eliminar el",
    "Are you sure to delete the draft": "¿Está seguro de que desea eliminar el borrador",
    "Are you sure to delete this submission ?": "¿Está seguro de que desea eliminar este envío?",
    "Submissions are made against": "Las presentaciones se realizan contra",
    "Submission is made against": "La presentación se realiza contra",
    "Form-Workflow association saved.": "Asociación Formulario-Flujo de Trabajo guardada.",
    "Form-Workflow association failed.": "Fallo en la asociación Formulario-Flujo de Trabajo.",
    "Form deletion unsuccessful": "Eliminación del formulario fallida",
    "Bundle deleted successfully": "Paquete eliminado con éxito",
    "Diagram deployed": "Diagrama desplegado",
    "Deployment failed": "Despliegue fallido",
    "form uploaded": "formulario subido",
    "forms uploaded": "formularios subidos",
    "Failed to upload": "Error al subir",
    "forms...!": "¡formularios...!",
    "form...!": "¡formulario...!",
    "Revert": "Revertir",
    "Criteria": "Criterios",
    "Select Form": "Seleccionar Formulario",
    "Create Condition": "Crear Condición",
    "Enter criteria": "Ingresar criterios",
    "Make this form public": "Hacer este formulario público",
    "Enable bundling": "Habilitar agrupamiento",
    "Bundle Name": "Nombre del Paquete",
    "View/Edit": "Ver/Editar",
    "Create Bundle": "Crear Paquete",
    "Rows per page": "Filas por página",
    "Items per page": "Ítems por página",
    "entries": "entradas",
    "Form Bundle": "Paquete de Formularios",
    "No bundles found": "No se encontraron paquetes",
    "Please change the selected filters to view Bundles": "Por favor, cambie los filtros seleccionados para ver Paquetes",
    "Select all to download forms": "Seleccionar todo para descargar formularios",
    "Select for download": "Seleccionar para descargar",
    "Bundle Description": "Descripción del Paquete",
    "Conditions": "Condiciones",
    "Enter name": "Ingresar nombre",
    "Enter Description": "Ingresar Descripción",
    "You can change the form order by drag and drop": "Puede cambiar el orden del formulario arrastrando y soltando",
    "Form Order": "Orden del Formulario",
    "Form Type": "Tipo de Formulario",
    "Add Forms Launch together": "Agregar Formularios Lanzados Juntos",
    "Form bundles can save your time by grouping forms together": "Los paquetes de formularios pueden ahorrar tiempo agrupando formularios",
    "Add Forms": "Agregar Formularios",
    "Create Conditions": "Crear Condiciones",
    "Add Conditions": "Agregar Condiciones",
    "Select Forms": "Seleccionar Formularios",
    "Insert": "Insertar",
    "View Form": "Ver Formulario",
    "Publish this Bundle for Client Users.": "Publicar este Paquete para Usuarios Clientes.",
    "Total Forms": "Total de Formularios",
    "Edit Bundle": "Editar Paquete",
    "Next Form": "Formulario Siguiente",
    "Previous Form": "Formulario Anterior",
    "Forms included under the package": "Formularios incluidos en el paquete",
    "Submit": "Enviar",
    "Reset Zoom": "Restablecer Zoom",
    "Zoom In": "Acercar",
    "Zoom Out": "Alejar",
    "Deploy": "Desplegar",
    "Export": "Exportar",
    "Overview": "Visión General",
    "Design Permission": "Permiso de Diseño",
    "Application Permission": "Permiso de Aplicación",
    "All Designers": "Todos los Diseñadores",
    "Private(only you)": "Privado(solo tú)",
    "Specific Designer Group": "Grupo de Diseñadores Específico",
    "Submission Permission": "Permiso de Envío",
    "All Users": "Todos los Usuarios",
    "Specific User Group": "Grupo de Usuarios Específico",
    "Specific Reviewers": "Revisores Específicos",
    "All Reviewers": "Todos los Revisores",
    "Permission for application tracking.": "Permiso para el seguimiento de aplicaciones.",
    "Design Bundle": "Diseñar Paquete",
    "Workflow": "Flujo de Trabajo",
    "Bundle Name and Description is Required": "Se Requiere Nombre y Descripción del Paquete",
    "Bundle Description is Required": "Se Requiere Descripción del Paquete",
    "Bundle Create Successfully": "Paquete Creado Exitosamente",
    "Bundle updated successfully": "Paquete actualizado exitosamente",
    "Select": "Seleccionar",
    "Unselect": "Deseleccionar",
    "Applicable for Designer Roled Users only.": "Aplicable solo para Usuarios con Rol de Diseñador.",
    "Applicable for Client and Reviewer Roled Users only.": "Aplicable solo para Usuarios con Rol de Cliente y Revisor.",
    "Done": "Hecho",
    "Failed to update permission!": "¡Fallo al actualizar el permiso!",
    "Failed to fetch roles!": "¡Fallo al obtener roles!",
    "Failed to update role!": "¡Fallo al actualizar el rol!",
    "Permission updated successfully!": "¡Permiso actualizado con éxito!",
    "Role updated successfully!": "¡Rol actualizado con éxito!",
    "Update failed!": "¡Actualización fallida!",
    "Clear": "Limpiar",
    "Are you sure deleting the role": "¿Está seguro de eliminar el rol",
    "Confirm Delete": "Confirmar Eliminación",
    "All roles": "Todos los roles",
    "Filter By:": "Filtrar Por:",
    "Create": "Crear",
    "Eg: Account Manager": "Ej: Gerente de Cuenta",
    "Search by name, username or email": "Buscar por nombre, nombre de usuario o correo electrónico",
    "No data Found": "No se encontraron datos",
    "Dashboard": "Tablero",
    "Roles": "Roles",
    "Users": "Usuarios",
    "Create New Role": "Crear Nuevo Rol",
    "Search by role name": "Buscar por nombre del rol",
    "Role Name": "Nombre del Rol",
    "Actions": "Acciones",
    "Create Role": "Crear Rol",
    "Email": "Correo Electrónico",
    "Role": "Rol",
    "Add Role": "Agregar Rol",
    "Role deleted successfully!": "¡Rol eliminado con éxito!",
    "Failed to delete role!": "¡Fallo al eliminar el rol!",
    "Role created successfully!": "¡Rol creado con éxito!",
    "Failed to create role!": "¡Fallo al crear el rol!",
    "Update success!": "¡Actualización exitosa!",
    "No results found": "No se encontraron resultados",
    "Edit Role": "Editar Rol",
    "Failed to fetch users!": "¡Fallo al obtener usuarios!",
    "Role names cannot contain special characters except _ , -": "Los nombres de rol no pueden contener caracteres especiales excepto _ , -",
    "Role names cannot contain special characters except _ , - , / ": "Los nombres de rol no pueden contener caracteres especiales excepto _ , - , / ",
    "Rules deployed successfully": "Reglas desplegadas con éxito",
    "Choose From Template": "Elegir de la Plantilla",
    "Back to forms": "Volver a los formularios",
    "Choose From Templates": "Elegir de las Plantillas",
    "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Explore nuestra Biblioteca de Plantillas para encontrar la combinación perfecta de formularios y flujos de trabajo. Haga clic para ver una plantilla y, si se ajusta a sus necesidades, personalícela a su gusto. Una vez que la haya adaptado a sus requisitos específicos, estará listo para crear su caso de negocio",
    "All templates": "Todas las plantillas",
    "Template count": "Cantidad de plantillas",
    "Learn more": "Aprender más",
    "Template Details": "Detalles de la Plantilla",
    "Template Title": "Título de la Plantilla",
    "Preview Form": "Vista Previa del Formulario",
    "Connected Workflow": "Flujo de Trabajo Conectado",
    "Delete Template": "Eliminar Plantilla",
    "Use Template": "Usar Plantilla",
    "Template created successfully": "Plantilla creada con éxito",
    "Template deleted successfully": "Plantilla eliminada con éxito",
    "Template updated successfully": "Plantilla actualizada con éxito",
    "Category": "Categoría",
    "Search category...": "Buscar categoría...",
    "Save as Template": "Guardar como Plantilla",
    "Create Template": "Crear Plantilla",
    "Select or Create Category": "Seleccionar o Crear Categoría",
    "Short Intro": "Breve Introducción",
    "Enter short intro": "Ingresar breve introducción",
    "Enter description": "Ingresar descripción",
    "Select or create": "Seleccionar o crear",
    "Update Template": "Actualizar Plantilla",
    "Form created successfully": "Formulario creado con éxito",
    "select or create": "Seleccionar o crear",
    "Update Associated Form": "Actualizar Formulario Asociado",
    "Update Associated Workflow": "Actualizar Flujo de Trabajo Asociado",
    "Enter title": "Ingresar título",
    "No Templates Found": "No se encontraron plantillas",
    "No Category Found": "No se encontró la categoría",
    "Save Template": "Guardar Plantilla",
    "You can type and click the": "Puede escribir y hacer clic en",
    "to create the category.": "para crear la categoría.",
    "select or type to create": "Seleccionar o escribir para crear",
    "BPMN": "BPMN",
    "DMN": "DMN",
    "Advanced Designer": "Diseñador Avanzado",
    "Basic Designer": "Diseñador Básico",
    "Search": "Buscar",
    "Key": "Clave",
    "No Process Found": "No se encontró proceso",
    "Search workflow": "Buscar flujo de trabajo",
    "No Dmn Found": "No se encontró DMN",
    "Submission ID": "ID de Envío",
    "Submission Name": "Nombre de Envío",
    "Submission History": "Historial de Envío",
    "No Submission History found": "No se encontró historial de envío",
    "Error in submission count": "Error en el recuento de envíos",
    "Permission for submission tracking.": "Permiso para el seguimiento de envíos.",
    "Reviewer permission to view submissions": "Permiso de revisor para ver envíos",
    "Permission to create new submission": "Permiso para crear nuevo envío",
    "Back to Bundle List": "Volver a la Lista de Paquetes",
    "Bundle": "Paquete",
    "You can drag these nodes to the pane on the right.": "Puede arrastrar estos nodos al panel de la derecha.",
    "You can delete the element by select and click the backspace": "Puede eliminar el elemento seleccionándolo y haciendo clic en la tecla de retroceso",
    "Workflow Id": "ID del Flujo de Trabajo",
    "Enter Workflow Id": "Ingresar ID del Flujo de Trabajo",
    "Back to Submissions": "Volver a Envíos",
    "Back to Drafts": "Volver a Borradores",
    "Choose Your Workflow Option": "Elija Su Opción de Flujo de Trabajo",
    "Create New Workflow": "Crear Nuevo Flujo de Trabajo",
    "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "Elija esta opción cuando desee crear un nuevo flujo de trabajo basado en la plantilla. El sistema generará y desplegará un nuevo flujo de trabajo, luego lo conectará al formulario seleccionado. Opte por esta opción si su formulario requiere un conjunto distinto de pasos de flujo de trabajo adaptados a sus necesidades específicas.",
    "Reuse Existing Workflow": "Reutilizar Flujo de Trabajo Existente",
    "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "Seleccione esta opción para vincular el formulario con un flujo de trabajo ya establecido. Cualquier modificación realizada en el flujo de trabajo existente se reflejará automáticamente en este formulario también. Esto es ideal cuando desea aprovechar el flujo de trabajo existente para los requisitos de su formulario.",
    "Are you sure you wish to delete the Template?": "¿Está seguro de que desea eliminar la Plantilla?",
    "Enter Workflow Name": "Ingresar Nombre del Flujo de Trabajo",
    "Create Workflow": "Crear Flujo de Trabajo",
    "Upload Workflow": "Subir Flujo de Trabajo",
    "Edit Workflow": "Editar Flujo de Trabajo",
    "Published": "Publicado",
    "Unpublished": "No Publicado",
    "Private": "Privado",
    "Anonymous": "Anónimo",
    "Edit Processes": "Editar Procesos",
    "Create Processes": "Crear Procesos",
    "tasks": "tareas",
    "Submission Id": "ID de Envío",
    "Clear All Filters": "Limpiar Todos los Filtros",
    "Show results": "Mostrar resultados",
    "Delete Draft": "Eliminar Borrador",
    "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "Puedo ayudarte a diseñar formularios sin esfuerzo, todo lo que tienes que hacer es darme una descripción clara y concisa de lo que se supone que debe hacer el formulario. Construiré los campos y el diseño para ti, que luego podrás personalizar más.",
    "I am": "Yo soy",
    "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "Por ejemplo 'Danos un formulario que sirva como formulario de admisión de pacientes para clínicas sin cita previa'",
    "Enter your prompt here": "Ingrese su solicitud aquí",
    "Would you like to continue?": "¿Te gustaría continuar?",
    "Restart": "Reiniciar",
    "I'm here to provide further assistance. Thank you!": "Estoy aquí para brindarte más asistencia. ¡Gracias!",
    "Generate Form Design": "Generar Diseño de Formulario",
    "Preview": "Vista Previa",
    "Your form is now ready!": "¡Tu formulario está listo!",
    "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description,  hit send.": "Por favor, dime todas las especificaciones y requisitos que tienes en mente para tu formulario. Después de que hayas terminado la descripción, presiona enviar.",
    "Choose template": "Elegir plantilla",
    "Search by bundle name": "Buscar por nombre del paquete",
    "Save Bundle": "Guardar Paquete",
    "Id": "Id",
    "Enable bundling ?": "¿Habilitar agrupamiento?",
    "Select a task in the List.": "Seleccione una tarea en la Lista.",
    "Add Date": "Agregar Fecha",
    "Assign to Me": "Asignar a Mí",
    "Filter count:": "Conteo de filtros:",
    "Selected Forms": "Formularios Seleccionados",
    "Template Used:": "Plantilla Utilizada:",
    "Select a task from the List.": "Seleccione una tarea de la Lista.",
    "Choose a task from the list; your selection directs your current activity.": "Elija una tarea de la lista; su selección dirige su actividad actual.",
    "Please change the selected filters to view submissions": "Por favor, cambie los filtros seleccionados para ver los envíos",
    "Please change the selected filters to view drafts": "Por favor, cambie los filtros seleccionados para ver los borradores",
    "No drafts found": "No se encontraron borradores",
    "Flow-E helps to build faster": "Flow-E ayuda a construir más rápido",
    "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "Flow-E no está disponible para demostración en la instancia de prueba. Puede experimentar Flow-E en cualquiera de los paquetes premium del producto",
    "Get in touch with formsflow.ai team": "Póngase en contacto con el equipo de formsflow.ai",
    "Premium": "Premium",
    "Select a status": "Seleccionar un estado",
    "Group": "Grupo",
    "Form description": "Descripción del formulario",
    "Select all forms": "Seleccionar todos los formularios",
    "Bold": "Negrita",
    "Italic": "Cursiva",
    "Underline": "Subrayado",
    "Align left": "Alinear a la izquierda",
    "Align center": "Alinear al centro",
    "Align right": "Alinear a la derecha",
    "Align justify": "Justificar",
    "Insert Link": "Insertar Enlace",
    "Clean": "Limpiar",
    "Click for task variables": "Hacer clic para variables de tarea",
    "Upload DMN": "Subir DMN",
    "DMN Name": "Nombre del DMN",
    "Search by DMN name": "Buscar por nombre de DMN",
    "Display authorized tasks based on user roles": "Mostrar tareas autorizadas según roles de usuario",
    "You are currently using a test instance.The trial period ends in": "Actualmente está utilizando una instancia de prueba. El período de prueba termina en",
    "days.": "días.",
    "Are you sure to delete": "¿Está seguro de eliminar",
    "filter?": "filtro?",
    "Select Workflow": "Seleccionar Flujo de Trabajo",
    "Select Assignee": "Seleccionar Asignado",
    "Click here to select attributes": "Haga clic aquí para seleccionar atributos",
    "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "Seleccione los atributos predefinidos y las variables de tarea personalizadas creadas como parte de la presentación del formulario que desea mostrar en la lista de tareas",
    "Task variables": "Variables de tarea",
    "User Role": "Rol del Usuario",
    "User Group": "Grupo de Usuarios",
    "Select User Role": "Seleccionar Rol del Usuario",
    "Select User Group": "Seleccionar Grupo de Usuarios",
    "To display task variables, select a form as part of the filter": "Para mostrar variables de tarea, seleccione un formulario como parte del filtro",
    "select a form": "seleccionar un formulario",
    "No task variables found": "No se encontraron variables de tarea",
    "Edit filter": "Editar filtro",
    "Select form fields to display in task list": "Seleccionar campos de formulario para mostrar en la lista de tareas",
    "Select all fields": "Seleccionar todos los campos",
    "Edit Label": "Editar Etiqueta",
    "Selecting all form fields may affect performance. For the best performance, just pick the form fields you really need.": "Seleccionar todos los campos del formulario puede afectar el rendimiento. Para un mejor rendimiento, elija solo los campos del formulario que realmente necesita.",
    "User Added successfully!": "¡Usuario agregado con éxito!",
    "Failed to create user!": "¡Error al crear el usuario!",
    "Add Registered Users": "Agregar Usuarios Registrados",
    "Username or Email": "Nombre de usuario o correo electrónico",
    "Add User": "Agregar Usuario",
    "User doesn't exist!": "¡El usuario no existe!",
    "Success": "Éxito",
    "User added": "Usuario agregado",
    "From": "De",
    "To": "A",
    "Premium Subscription": "Suscripción Premium",
    "For further insights on this exclusive premium feature, kindly connect": "Para más información sobre esta exclusiva función premium, por favor contacte",
    "with our dedicated marketing team for detailed information.": "con nuestro equipo de marketing dedicado para obtener información detallada.",
    "Get Connected With Us Now!": "¡Conéctese con nosotros ahora!",
    "Visit our": "Visite nuestro",
    "Pricing page": "Página de precios",
    "for more details.": "para más detalles.",
    "Integration": "Integración",
    "Recipes": "Recetas",
    "Connected Apps": "Aplicaciones Conectadas",
    "Library": "Biblioteca",
    "Add group": "Agregar grupo",
    "Add task label": "Agregar etiqueta de tarea",
    "Integrations": "Integraciones",
    "We facilitate hundreds of native integrations via our ‘Native Integrations Pro’ package.": "Facilitamos cientos de integraciones nativas a través de nuestro paquete ‘Native Integrations Pro’.",
    "This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "Esta función no está disponible por defecto en la prueba de 14 días. Si su prueba requiere esta función, puede informarnos y podemos habilitarla para usted.",
    "Upgrade to unlock Native Integrations Pro": "Actualice para desbloquear Native Integrations Pro",
    "We facilitate hundreds of native integrations via our ": "Facilitamos cientos de integraciones nativas a través de nuestro ",
    "Native Integrations Pro": "Native Integrations Pro",
    "package. This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "paquete. Esta función no está disponible por defecto en la prueba de 14 días. Si su prueba requiere esta función, puede informarnos y podemos habilitarla para usted.",
    "To learn more about Native Integrations Pro": "Para obtener más información sobre Native Integrations Pro",
    "Check out Integrations Feature": "Consulte la Función de Integraciones",
    "Connect with": "Conéctese con",
    "team for requests or queries.": "equipo para solicitudes o consultas.",
    "Learn more about the feature": "Aprender más sobre la función",
    "team.": "equipo.",
    "Connect with formsflow.ai team.": "Conéctese con el equipo de formsflow.ai.",
    "Default filter removed": "Filtro predeterminado eliminado",
    "Set default filter": "Establecer filtro predeterminado",
    "added as default filter": "agregado como filtro predeterminado"
}