export default {
    UPDATE_SUBMISSION_SORT_PARAMS:"UPDATE_SUBMISSION_SORT_PARAMS",
    UPDATE_SUBMISSION_PAGE: "UPDATE_SUBMISSION_PAGE",
    UPDATE_SUBMISSION_LIMIT: "UPDATE_SUBMISSION_LIMIT",
    APPLICATION_DETAIL:"APPLICATION_DETAIL",
    SET_APP_DETAILS_LOADING:"SET_APP_DETAILS_LOADING",


    //need to add the reducers
    CUSTOM_SUBMISSION:"CUSTOM_SUBMISSION",
    LIST_APPLICATION_HISTORY:"LIST_APPLICATION_HISTORY",
    IS_HISTORY_LOADING:"IS_HISTORY_LOADING",
    ERROR:"ERROR",
    SET_USER_ROLES:"SET_USER_ROLES",
    SET_LANGUAGE:"SET_LANGUAGE",

    PROCESS_ACTIVITIES:"PROCESS_ACTIVITIES",
    IS_PROCESS_ACTIVITY_LOAD_ERROR: "IS_PROCESS_ACTIVITY_LOAD_ERROR",
};
