export default {
    UPDATE_SUBMISSION_SORT_PARAMS:"UPDATE_SUBMISSION_SORT_PARAMS",
    UPDATE_SUBMISSION_PAGE: "UPDATE_SUBMISSION_PAGE",
    UPDATE_SUBMISSION_LIMIT: "UPDATE_SUBMISSION_LIMIT",
    UPDATE_SUBMISSION_DATE_RANGE: "UPDATE_SUBMISSION_DATE_RANGE",
};
