
export default {
UPDATE_SUBMISSION_SORT_PARAMS:"UPDATE_SUBMISSION_SORT_PARAMS",
UPDATE_SUBMISSION_PAGE: "UPDATE_SUBMISSION_PAGE",
UPDATE_SUBMISSION_LIMIT: "UPDATE_SUBMISSION_LIMIT",
SET_TENANT_DATA: "SET_TENANT_DATA",
}