/* eslint-disable max-len */
export const RESOURCE_BUNDLES_EN = {
  "Access restricted by its designer..!": "Access restricted by its designer..!",
  "and you will no longer have the access to this form in bundles": "and you will no longer have the access to this form in bundles",
  "You will no longer have the access to this form in bundles": "You will no longer have access to this form in bundles",
  "Bad Request":"Bad Request",
  "Select the form to be displayed based on the  above criteria":"Select the form to be displayed based on the  above criteria",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component":"Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component",
  "Select form version":"Select form version",
  "Please remove the special characters...!":"Please remove the special characters...!",
  "No histories found":"No histories found",
  "Continue":"Continue",
  "This will create a new version of the form without changing the path name but with new form id.":"This will create a new version of the form without changing the path name but with new form id.",
  "Save as a new version":"Save as a new version",
  "Save New Version":"Save New Version",
  "Do you want to save a new version of this form?":"Do you want to save a new version of this form?",
  "Do you want to create a duplicate form and associated workflow from existing form ?":"Do you want to create a duplicate form and associated workflow from existing form ?",
  "New version created":"New version created",
  "Create a duplicate form":"Create a duplicate form",
  "Show more":"Show more",
  "Modified By":"Modified By",
  "Created On" : "Created On",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.":"Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.",
  "Duplicate Form":"Duplicate Form",
  "Form History":"Form History",
  "No file chosen":"No file chosen",
  "Choose File":"Choose File",
  "Choose any":"Choose any",
  "Sort by form name":"Sort by form name",
  "select form type":"select form type",
  "Draft Deleted Successfully":"Draft Deleted Successfully",
  "Saved to Applications/Drafts":"Saved to Applications/Drafts",
  "Unfinished applications will be saved to Applications/Drafts.":"Unfinished applications will be saved to Applications/Drafts.",
  "Discard Draft":"Discard Draft",
  "Are you sure you wish to delete the draft":"Are you sure you wish to delete the draft",
  "with ID":"with ID",
  "Please change the selected filters to view Forms":"Please change the selected filters to view Forms",
  "Search by form name":"Search by form name",
  "Click to search":"Click to search",
  "No submissions found":"No submissions found",
  "No submission avaliable in the selected date. Please select another date range":"No submission avaliable in the selected date. Please select another date range",
  "Form field":"Form field",
  "Enter Label":"Enter Label",
  "Select form field":"Select form field",
  "Add form fields to display in task list":"Add form fields to display in task list",
  "Latest Version":"Latest Version",
  "Submission Status":"Submission Status",
  "No submission status":"No submission status",
  "No Public url found":"No Public url found",
  "Show in list":"Show in list",
  "Select Task Variable":"Select Task Variable",
  "Enter your Label":"Enter your Label",
  "Please select from one of the following workflows.":"Please select from one of the following workflows.",
  "Select Key":"Select Key",
  "Create Your Task Variable":"Create Your Task Variable",
  "No task variable selected": "No task variable selected",
  "Workflow Associate":"Workflow Associate",
  "Task variable":"Task variable",
  "Enter pathname":"Enter pathname",
  "Name": "Name",
  "Title": "Title",
  "Display as": "Display as",
  "Anonymous Form ": "Anonymous Form",
  "Submission Saved": "Submission Saved.",
  "Error while Submission.": "Error while Submission.",
  "Form saved": "Form saved.",
  "Message": "Please fix the errors before submitting again.",
  "Submission cannot be done.": "Submission cannot be done.",
  "No Process Diagram found": "No Process Diagram found",
  "Are you sure you wish to delete the form": "Are you sure you wish to delete the form",
  "Are you sure you wish to delete the form?":"Are you sure you wish to delete the form?",
  'Forms': "Forms",
  'Form':"Form",
  "Downloaded Successfully":"Downloaded Successfully",
  "Edit": "Edit",
  "Do you want to associate form with a workflow ?": "Do you want to associate form with a workflow ?",
  "Yes": "Yes",
  "No": "No",
  "Form Name": "Form Name ",
  "Workflow Name": "Workflow Name ",
  "Publish this form for Client Users.": "Publish this form for Client Users.",
  "Comments":"Comments",
  "Back":"Back",
  "Edit Form": "Edit Form",
  "Next": "Next",
  "Are you sure you wish to delete this submission?": "Are you sure you wish to delete this submission?",
  "Save": "Save",
  "Back to Form List": "Back to Form List",
  "Submit New": "Submit New",
  "View Submissions": "View Submissions",
  "View/Edit Form": "View/Edit Form",
  "Delete Form": "Delete Form",
  "Delete": "Delete",
  "Print As PDF": "Print As PDF",
  "Applications": "Applications",
  "Tasks": "Tasks",
  "Metrics": "Metrics",
  "Logout": "Logout",
  "No tasks found": "No tasks found",
  "Please change the selected filters to view tasks": "Please change the selected filters to view tasks",
  "Clear all filters": "Clear all filters",
  "Created": "Created",
  "Task Variables": "Task Variables",
  "Process Variables": "Process Variables",
  "Process Definition Name": "Process Definition Name",
  "Assigne": "Assignee",
  "Candidate Group": "Candidate Group",
  "Candidate User": "Candidate User",
  "Description": "Description",
  "Priority": "Priority",
 "Due Date": "Due Date",
  "Follow up Date": "Follow up Date",
 "Task name": "Task name",
  "Remove sorting": "Remove sorting",
  "Ascending": "Ascending",
  "Descending": "Descending",
  "Add sorting": "Add sorting",
  "of the criteria are met.":"of the criteria are met.",
  "For Variable, ignore case of": "For Variable, ignore case of",
  "name": "name",
  "value": "value",
  "No task matching filters found.": "No task matching filters found.",
   "Application ID": "Application ID",
  "Set follow-up Date": "Set follow-up Date",
  "Set Due date": "Set Due date",
  "Add groups": "Add groups",
  "Claim": "Claim",
  "Search By Last Name": "Search By Last Name",
  "Search By First Name": "Search By First Name",
   "Search By Email": "Search By Email",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.",
  "Add a group": "Add a group",
  "Process Name": "Process Name",
  "Set FollowUp Date": "Set FollowUp Date",
  "Groups": "groups",
  "Click to Change Assignee": "Click to Change Assignee",
  "Reset Assignee": "Reset Assignee",
  "Update User": "Update User",
  "Close": "Close",
  "Type": "Type",
  "Remove search": "Remove search",
  "Property": "Property",
  "Operator": "Operator",
  "Total number of results": "Total number of results",
  "Filter Tasks": "Filter Tasks",
  "All": "All",
  "ANY": "ANY",
  "Task assignee": "Task assignee",
  "Application History": "Application History",
 "View Submission": "View Submission",
  "Showing": "Showing",
  "to": "to",
  "Acknowledge": "Acknowledge",
  "View": "View",
  "Select a task in the list.": "Select a task in the list.",
  "No Filters Found": "No Filters Found",
  "Loading": "Loading",
  "Loading...":"Loading...",
  "History": "History",
  "Diagram": "Diagram",
  "Delete Confirmation": "Delete Confirmation",
  "All tasks": "All tasks",
  "Manage Groups": "Manage Groups",
  "Group ID": "Group ID",
  "Due": "Due",
  "Follow-up": "Follow-up",
  "Application Name": "Application Name",
  "Created By": "Created By",
  "Application Status": "Application Status",
  "Request Status": "Request Status",
  "Request Name": "Request Name",
  "Submitted On": "Submitted On",
  "Modified On": "Modified On",
  "No History Found": "No History Found",
  "Process Diagram": "Process Diagram",
  "Details": "Details",
  "Status": "Status",
  "Submissions": "Submissions",
  "No Application History found": "No Application History found",
  "Link To Form Submission": "Link To Form Submission",
  "Last Modified": "Last Modified",
  "Insights": "Insights",
   "No dashboard found": "No dashboard found",
  "of": "of",
  "results": "results",
  "Dashbaord":"Dashboard",
  "Dashboards":"Dashboards",
  "Select Dashboard": "Select Dashboard",
  "Total Submissions": "Total Submissions",
  "Save & Preview": "Save & Preview",
  "Operations": "Operations",
  "Access Groups": "Access Groups",
  "Action": "Action",
  "Add": "Add",
  "Admin": "Admin",
  "Create Form": "Create Form",
  "Upload Form": "Upload Form",
  "Download Form": "Download Form",
  "Upload json form only": "Upload json form only",
  "Select atleast one form": "Select atleast one form",
  "Select All": "Select All",
  "Created Date": "Created Date",
  "Modified Date": "Modified Date",
  "File Upload Status": "File Upload Status",
  "Forms Completed": "Forms Completed",
  "Form Completed": "Form Completed",
  "No forms found": "No forms found",
  "Powered by ": "Powered by ",
  "Press Enter key or click here to search": "Press Enter key or click here to search",
  "Click to clear": "Click to clear",
  "No applications found": "No applications found",
  "Successfully Updated": "Successfully Updated",
  "Failed": "Failed",
  "Submission Failed.": "Submission Failed.",
  "Click here to back": "Click here to back",
  "Path": "Path",
  "Make this form public ?": "Make this form public ?",
  "Design Form": "Design Form",
  "Associate this form with a workflow?": "Associate this form with a workflow?",
  "Preview and Confirm": "Preview and Confirm",
  "All steps completed - you're finished": "All steps completed - you're finished",
  "Enter the form machine name": "Enter the form machine name",
  "Enter the form title": "Enter the form title",
  "Error in JSON file structure":"Error in JSON file structure",
  "example":"example",
  "Please fix the errors before submitting again.":"Please fix the errors before submitting again.",
  "Wizard":"Wizard",
  "Save Form":"Save Form",
  "Confirm":"Confirm",
  "Cancel":"Cancel",
  "Please change the selected filters to view applications":"Please change the selected filters to view applications",
  "No submissions available for the selected date range":"No submissions available for the selected date range",
  "Ok":"Ok",
  "Form not available": "Form not available",
  "Thank you for your response.":"Thank you for your response.",
  "saved successfully":"saved successfully",
  "Copy anonymous form URL":"Copy anonymous form URL",
  "Submitted By":"Submitted By",
  "Confirmation":"Confirmation",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.",
  "Error while saving Form":"Error while saving Form",
  "Click here to go back":"Click here to go back",
  "Are you sure you wish to delete the form ":"Are you sure you wish to delete the form ",
  " Applications are submitted against":" Applications are submitted against",
  " Application is submitted against":" Application is submitted against",
  ". Are you sure want to delete ?":". Are you sure want to delete ?",
  "Save Changes":"Save Changes",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.",
  "Form-Workflow association saved.": "Form-Workflow association saved.",
  "Form-Workflow association failed.": "Form-Workflow association failed.",
  "Form deletion unsuccessful":"Form deletion unsuccessful",
  "Form deleted successfully":"Form deleted successfully",
  "Bundle deleted successfully":"Bundle deleted successfully",
  "Form process failed":"Form process failed",
  "Form unpublishing Failed":"Form unpublishing Failed",
  "All groups have access to the dashboard":"All groups have access to the dashboard",
  "Export PDF":"Export PDF",
  "Something went wrong. Please try again!":"Something went wrong. Please try again!",
  "No Dashboards Found":"No Dashboards Found",
  "Processes":"Processes",
  "Please select an existing workflow.":"Please select an existing workflow.",
  "Create New":"Create New",
  "Or create new workflow or import a workflow from a local directory.":"Or create new workflow or import a workflow from a local directory.",
  "The operation couldn't be completed. Please try after sometime":"The operation couldn't be completed. Please try after sometime",
  "Select...":"Select...",
  "No Drafts Found":  "No Drafts Found",
  "Help":"Help",
  "Draft Id":"Draft Id",
  "Draft Name":"Draft Name",
  "Link To Draft Submission":"Link To Draft Submission",
  "Drafts":"Drafts",
  "You can't submit this form until it is published":"You can't submit this form until it is published",
  "Form not published":"Form not published",
  "Access Denied" : "Access Denied",
  "By default, the tenant key would be prefixed to form":"By default, the tenant key would be prefixed to form",
  "go back":"go back",
  "No Applications Found":"No Applications Found",
  "Submission saved to draft.":"Submission saved to draft.",
  "Saved to draft":"Saved to draft",
  "Saving...":"Saving...",
  "Resource":"Resource",
  "Error in creating form process mapper":"Error in creating form process mapper",
  "Select the date":"Select the date",
  "Diagram deployed":"Diagram deployed",
  "Deployment failed":"Deployment failed",
  "form uploaded":"form uploaded",
  "forms uploaded":"forms uploaded",
  "Failed to upload":"Failed to upload",
  "forms...!":"forms...!",
  "form...!":"form...!",
  "Process name(s) must not be empty":"Process name(s) must not be empty",
  "URL copied":"URL copied",
  "Click Here to Copy":"Click Here to Copy",
  "Resources":"Resources",
  "Duplicate form created successfully":"Duplicate form created successfully",
  "Revert": "Revert",

  "Are you sure you wish to delete the bundle ":"Are you sure you wish to delete the bundle ",
  "Criteria":"Criteria",
  "Select Form":"Select Form",
  "Create Condition":"Create Condition",
  "Enter criteria":"Enter criteria",
  "Make this form public": "Make this form public",
  "Enable bundling":"Enable bundling",
  
  "Bundle Name": "Bundle Name",
  "View/Edit": "View/Edit",  
  "Create Bundle": "Create Bundle",
  "Rows per page": "Rows per page",
  "entries": "entries",
  "Form Bundle": "Form Bundle",
  "No bundles found": "No bundles found",
  "Please change the selected filters to view Bundles": "Please change the selected filters to view Bundles",
  "Select all to download forms": "Select all to download forms",
  "Select for download": "Select for download",
  "Bundle Description": "Bundle Description",
  "Conditions": "Conditions",
  "Enter name": "Enter name",
  "Enter Description": "Enter Description",
  "You can change the form order by drag and drop": "You can change the form order by drag and drop",
  "Form Order": "Form Order",
  "Form Type": "Form Type",
  "Add Forms Launch together": "Add Forms Launch together",
  "Form bundles can save your time by grouping forms together": "Form bundles can save your time by grouping forms together",
  "Add Forms": "Add Forms",
  "Create Conditions":  "Create Conditions",
  " Add Conditions": " Add Conditions",
  "Select Forms": "Select Forms",
  "Insert": "Insert",
  "View Form": "View Form",
  "Publish this Bundle for Client Users.": "Publish this Bundle for Client Users.",
  "Total Forms": "Total Forms",
  "Edit Bundle": "Edit Bundle",
  "Next Form": "Next Form",
  "Previous Form": "Previous Form",
  "Forms included under the package": "Forms included under the package",
  "Submit": "Submit",
  "Reset Zoom": "Reset Zoom",
  "Zoom In": "Zoom In",
  "Zoom Out": "Zoom Out",
  "Deploy": "Deploy",
  "Export": "Export",
  "Overview": "Overview",
  "Design Permission": "Design Permission",
  "Application Permission":"Application Permission",
  "All Designers": "All Designers",
  "Private(only you)": "Private(only you)",
  "Specific Designer Group": "Specific Designer Group",
  "Submission Permission": "Submission Permission",
  "All Users": "All Users",
  "Specific User Group": "Specific User Group",
  "Specific Reviewers":"Specific Reviewers",
  "All Reviewers":"All Reviewers",
  "Permission for application tracking.":"Permission for application tracking.",
  "Design Bundle": "Design Bundle",
  "Workflow": "Workflow",
  "Bundle Name and Description is Required": "Bundle Name and Description is Required",
  "Bundle Description is Required": "Bundle Description is Required",
  "Bundle Create Successfully": "Bundle Create Successfully",
  "Bundle updated successfully": "Bundle updated successfully",
  "Select" : "Select",
  "Unselect" : "Unselect",
  "Applicable for Designer Roled Users only.": "Applicable for Designer Roled Users only.",
  "Applicable for Client and Reviewer Roled Users only.": "Applicable for Client and Reviewer Roled Users only.",
   "Done":"Done",
  "Failed to update permission!":"Failed to update permission!",
  "Failed to fetch roles!":"Failed to fetch roles!",
  "Failed to update role!":"Failed to update role!",
  "Permission updated successfully!":"Permission updated successfully!",
  "Role updated successfully!":"Role updated successfully!",
  "Update failed!":"Update failed!",
  "Clear":"Clear",
  "Are you sure deleting the role":"Are you sure deleting the role",
  "Confirm Delete":"Confirm Delete",
  "All roles":"All roles",
  "Filter By:":"Filter By:",
  "Create":"Create",
  "Eg: Account Manager":"Eg: Account Manager",
  "Search by name, username or email":"Search by name, username or email",
  "No data Found":"No data Found",
  "Dashboard": "Dashboard",
  "Roles": "Roles",
  "Users": "Users",
  "Create New Role": "Create New Role",
  "Search by role name": "Search by role name",
  "Role Name": "Role Name",
  "Actions": "Actions",
  "Create Role": "Create Role",
  "Email": "Email",
  "Role": "Role",
  "Add Role": "Add Role",
  "Role deleted successfully!": "Role deleted successfully!",
  "Failed to delete role!": "Failed to delete role!",
  "Role created successfully!": "Role created successfully!",
  "Failed to create role!": "Failed to create role!",
  "Update success!":"Update success!",
  "No results found":"No results found",
  "Edit Role":"Edit Role",
  "Failed to fetch users!":"Failed to fetch users!",
  "Role names cannot contain special characters except   _ , -": "Role names cannot contain special characters except   _ , -",
  "Role names cannot contain special characters except _ , - , / ": "Role names cannot contain special characters except _ , - , / ",
  "Rules deployed successfully": "Rules deployed successfully",
  "Choose From Template": "Choose From Template",
  "Back to forms": "Back to forms",
  "Choose From Templates": "Choose From Templates",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case",
  "All templates": "All templates",
  "Template count": "Template count",
  "Learn more": "Learn more",
  "Template Details": "Template Details",
  "Template Title": "Template Title",
  "Preview Form": "Preview Form",
  "Connected Workflow": "Connected Workflow",
  "Delete Template": "Delete Template",
  "Use Template": "Use Template",
  "Template created successfully": "Template created successfully",
  "Template deleted successfully": "Template deleted successfully",
  "Template updated successfully": "Template updated successfully",
  "Category": "Category",
  "Search category...": "Search category...",
  "Save as Template": "Save as Template",
  "Create Template": "Create Template",
  "Select or Create Category": "Select or Create Category",
  "Short Intro": "Short Intro",
  "Enter short intro": "Enter short intro",
  "Enter description": "Enter description",
  "Select or create": "Select or create",
  "Update Template": "Update Template",
  "Form created successfully": "Form created successfully",
  "select or create": "Select or create",
  "Update Associated Form": "Update Associated Form",
  "Update Associated Workflow": "Update Associated Workflow",
  "Enter title":"Enter title",
  "No Templates Found": "No Templates Found",
  "No Category Found": "No Category Found",
  "Save Template": "Save Template",
  "You can type and click the": "You can type and click the",
  "to create the category.": " to create the category.",
  "select or type to create": "select or type to create"

};



