/* eslint-disable max-len */
export const RESOURCE_BUNDLES_EN = {
  "Submit Form": "Submit Form",
  "Changes Applied Successfully": "Changes Applied Successfully",
  "Filter Deleted Successfully": "Filter Deleted Successfully",
  "Save Filter": "Save Filter",
  "Filter Name": "Filter Name",
  "Create new filter": "Create new filter",
  "Definition Key": "Definition Key",
  "Permission": "Permission",
  "Enter your text here": "Enter your text here",
  "Accessible for all users": "Accessible for all users",
  "Private (Only You)": "Private (Only You)",
  "Specific Group": "Specific Group",
  "Select Elements": "Select Elements",
  " Task Attributes Selected": " Task Attributes Selected",
  "Delete Filter": "Delete Filter",
  "Add Value": "Add Value",
  "Show only current user assigned task": "Show only current user assigned task",
  "Show task based on logged user roles": "Show task based on logged user roles",
  "Create Filter": "Create Filter",
  "Task Attributes": "Task Attributes",
  "Only selected task attributes will be available on task list view": "Only selected task attributes will be available on task list view",
  "Show undefined variables": "Show undefined variables",
  "Label": "Label",
  "Variables": "Variables",
  "Task Title": "Task Title",
  "List View": "List View",
  "Card View": "Card View",
  "Create New Filter": "Create New Filter",
  "Sort by": "Sort by",
  "Collapse All": "Collapse All",
  "Expand All": "Expand All",
  "Application Id": "Application Id",
  "Back to task": "Back to task",
  "Filters": "Filters",
  "Assignee": "Assignee",
  "Select a user": "Select a user",
  "Create DMN": "Create DMN",
  "Create Process": "Create Process",
  "Edit DMN": "Edit DMN",
  "More options": "More options",
  "Form Description": "Form Description",
  "Saved to Submissions/Drafts": "Saved to Submissions/Drafts",
  "Unfinished submissions will be saved to Submissions/Drafts.": "Unfinished submissions will be saved to Submissions/Drafts.",
  "Edit Process": "Edit Process",
  "Add filter name": "Add filter name",
  "This section is aimed to set the parameters used to filter the tasks": "This section is aimed to set the parameters used to filter the tasks",
  "This section is aimed to set read permissions for the filter": "This section is aimed to set read permissions for the filter",
  "This section is aimed to set select task attributes that will be visible in the task list view": "This section is aimed to set select task attributes that will be visible in the task list view",
  "Task Attribute": "Task Attribute",
  "You can define variables shown in the list": "You can define variables shown in the list",
  "results": "Results",
  "Enter role name": "Enter role name",
  "Public": "Public",
  "View Submitted Form": "View Submitted Form",
  "View Draft Details": "View Draft Details",
  "Edit Draft": "Edit Draft",
  "Draft Title": "Draft Title",
  "Filter": "Filter",
  "Advanced Options": "Advanced Options",
  "Enter the path name": "Enter the path name",
  "Search by form title": "Search by form title",
  "Associate Workflow": "Associate Workflow",
  "Search by workflow name": "Search by workflow name",
  "View Details": "View Details",
  "Visibility": "Visibility",
  "Form Title": "Form Title",
  "Access restricted by its designer..!": "Access restricted by its designer..!",
  "and you will no longer have the access to this form in bundles": "and you will no longer have the access to this form in bundles",
  "You will no longer have the access to this form in bundles": "You will no longer have access to this form in bundles",
  "Bad Request": "Bad Request",
  "Select the form to be displayed based on the  above criteria": "Select the form to be displayed based on the  above criteria",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component",
  "Select form version": "Select form version",
  "Please remove the special characters...!": "Please remove the special characters...!",
  "No histories found": "No histories found",
  "Continue": "Continue",
  "This will create a new version of the form without changing the path name but with new form id.": "This will create a new version of the form without changing the path name but with new form id.",
  "Save as a new version": "Save as a new version",
  "Save New Version": "Save New Version",
  "Do you want to save a new version of this form?": "Do you want to save a new version of this form?",
  "Do you want to create a duplicate form and associated workflow from existing form ?": "Do you want to create a duplicate form and associated workflow from existing form ?",
  "New version created": "New version created",
  "Create a duplicate form": "Create a duplicate form",
  "Show more": "Show more",
  "Modified By": "Modified By",
  "Created On": "Created On",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.",
  "Duplicate Form": "Duplicate Form",
  "Form History": "Form History",
  "No file chosen": "No file chosen",
  "Choose File": "Choose File",
  "Choose any": "Choose any",
  "Sort by form name": "Sort by form name",
  "select form type": "select form type",
  "Draft Deleted Successfully": "Draft Deleted Successfully",
  "Saved to Applications/Drafts": "Saved to Applications/Drafts",
  "Unfinished applications will be saved to Applications/Drafts.": "Unfinished applications will be saved to Applications/Drafts.",
  "Discard Draft": "Discard Draft",
  "with ID": "with ID",
  "Please change the selected filters to view Forms": "Please change the selected filters to view Forms",
  "Search by form name": "Search by form name",
  "Click to search": "Click to search",
  "No submissions found": "No submissions found",
  "No submission avaliable in the selected date. Please select another date range": "No submission avaliable in the selected date. Please select another date range",
  "Form field": "Form field",
  "Enter Label": "Enter Label",
  "Select form field": "Select form field",
  "Add form fields to display in task list": "Add form fields to display in task list",
  "Latest Version": "Latest Version",
  "Submission Status": "Submission Status",
  "No submission status": "No submission status",
  "No Public url found": "No Public url found",
  "Show in list": "Show in list",
  "Select Task Variable": "Select Task Variable",
  "Enter your Label": "Enter your Label",
  "Please select from one of the following workflows.": "Please select from one of the following workflows.",
  "Select Key": "Select Key",
  "Create Your Task Variable": "Create Your Task Variable",
  "No task variable selected": "No task variable selected",
  "Workflow Associate": "Workflow Associate",
  "Task variable": "Task variable",
  "Enter pathname": "Enter pathname",
  "Name": "Name",
  "Title": "Title",
  "Display as": "Display as",
  "Anonymous Form ": "Anonymous Form",
  "Submission Saved": "Submission Saved.",
  "Error while Submission.": "Error while Submission.",
  "Form saved": "Form saved.",
  "Message": "Please fix the errors before submitting again.",
  "Submission cannot be done.": "Submission cannot be done.",
  "No Process Diagram found": "No Process Diagram found",
  'Forms': "Forms",
  'Form': "Form",
  "Downloaded Successfully": "Downloaded Successfully",
  "Edit": "Edit",
  "Do you want to associate form with a workflow ?": "Do you want to associate form with a workflow ?",
  "Yes": "Yes",
  "No": "No",
  "Form Name": "Form Name ",
  "Workflow Name": "Workflow Name ",
  "Publish this form for Client Users.": "Publish this form for Client Users.",
  "Comments": "Comments",
  "Back": "Back",
  "Edit Form": "Edit Form",
  "Next": "Next",
  "Save": "Save",
  "Back to Form List": "Back to Form List",
  "Submit New": "Submit New",
  "View Submissions": "View Submissions",
  "View/Edit Form": "View/Edit Form",
  "Delete Form": "Delete Form",
  "Delete": "Delete",
  "Print As PDF": "Print As PDF",
  "Applications": "Applications",
  "Tasks": "Tasks",
  "Metrics": "Metrics",
  "Logout": "Logout",
  "No tasks found": "No tasks found",
  "Please change the selected filters to view tasks": "Please change the selected filters to view tasks",
  "Clear all filters": "Clear all filters",
  "Created": "Created",
  "Task Variables": "Task Variables",
  "Process Variables": "Process Variables",
  "Process Definition Name": "Process Definition Name",
  "Assigne": "Assignee",
  "Candidate Group": "Candidate Group",
  "Candidate User": "Candidate User",
  "Description": "Description",
  "Priority": "Priority",
  "Due Date": "Due Date",
  "Follow up Date": "Follow up Date",
  "Task name": "Task name",
  "Remove sorting": "Remove sorting",
  "Ascending": "Ascending",
  "Descending": "Descending",
  "Add sorting": "Add sorting",
  "of the criteria are met.": "of the criteria are met.",
  "For Variable, ignore case of": "For Variable, ignore case of",
  "name": "name",
  "value": "value",
  "No task matching filters found.": "No task matching filters found.",
  "Application ID": "Application ID",
  "Set follow-up Date": "Set follow-up Date",
  "Set Due date": "Set Due date",
  "Add groups": "Add groups",
  "Claim": "Claim",
  "Search By Last Name": "Search By Last Name",
  "Search By First Name": "Search By First Name",
  "Search By Email": "Search By Email",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.",
  "Add a group": "Add a group",
  "Process Name": "Process Name",
  "Set FollowUp Date": "Set FollowUp Date",
  "Groups": "groups",
  "Click to Change Assignee": "Click to Change Assignee",
  "Reset Assignee": "Reset Assignee",
  "Update User": "Update User",
  "Close": "Close",
  "Type": "Type",
  "Remove search": "Remove search",
  "Property": "Property",
  "Operator": "Operator",
  "Total number of results": "Total number of results",
  "Filter Tasks": "Filter Tasks",
  "All": "All",
  "ANY": "ANY",
  "Task assignee": "Task assignee",
  "Application History": "Application History",
  "View Submission": "View Submission",
  "Showing": "Showing",
  "to": "to",
  "Acknowledge": "Acknowledge",
  "View": "View",
  "Select a task in the list.": "Select a task in the list.",
  "No Filters Found": "No Filters Found",
  "Loading": "Loading",
  "Loading...": "Loading...",
  "History": "History",
  "Diagram": "Diagram",
  "Delete Confirmation": "Delete Confirmation",
  "All tasks": "All tasks",
  "Manage Groups": "Manage Groups",
  "Group ID": "Group ID",
  "Due": "Due",
  "Follow-up": "Follow-up",
  "Application Name": "Application Name",
  "Created By": "Created By",
  "Application Status": "Application Status",
  "Request Status": "Request Status",
  "Request Name": "Request Name",
  "Submitted On": "Submitted On",
  "Modified On": "Modified On",
  "No History Found": "No History Found",
  "Process Diagram": "Process Diagram",
  "Details": "Details",
  "Status": "Status",
  "Submissions": "Submissions",
  "No Application History found": "No Application History found",
  "Link To Form Submission": "Link To Form Submission",
  "Last Modified": "Last Modified",
  "Insights": "Insights",
  "No dashboard found": "No dashboard found",
  "of": "of",
  "Results": "Results",
  "Dashbaord": "Dashboard",
  "Dashboards": "Dashboards",
  "Select Dashboard": "Select Dashboard",
  "Total Submissions": "Total Submissions",
  "Save & Preview": "Save & Preview",
  "Operations": "Operations",
  "Access Groups": "Access Groups",
  "Action": "Action",
  "Add": "Add",
  "Admin": "Admin",
  "Create Form": "Create Form",
  "Upload Form": "Upload Form",
  "Download Form": "Download Form",
  "Upload json form only": "Upload json form only",
  "Select atleast one form": "Select atleast one form",
  "Select All": "Select All",
  "Created Date": "Created Date",
  "Modified Date": "Modified Date",
  "File Upload Status": "File Upload Status",
  "Forms Completed": "Forms Completed",
  "Form Completed": "Form Completed",
  "No forms found": "No forms found",
  "Powered by ": "Powered by ",
  "Press Enter key or click here to search": "Press Enter key or click here to search",
  "Click to clear": "Click to clear",
  "No applications found": "No applications found",
  "Successfully Updated": "Successfully Updated",
  "Failed": "Failed",
  "Submission Failed.": "Submission Failed.",
  "Click here to back": "Click here to back",
  "Path": "Path",
  "Make this form public ?": "Make this form public ?",
  "Design Form": "Design Form",
  "Associate this form with a workflow?": "Associate this form with a workflow?",
  "Preview and Confirm": "Preview and Confirm",
  "All steps completed - you're finished": "All steps completed - you're finished",
  "Enter the form machine name": "Enter the form machine name",
  "Enter the form title": "Enter the form title",
  "Error in JSON file structure": "Error in JSON file structure",
  "example": "example",
  "Please fix the errors before submitting again.": "Please fix the errors before submitting again.",
  "Wizard": "Wizard",
  "Save Form": "Save Form",
  "Confirm": "Confirm",
  "Cancel": "Cancel",
  "Please change the selected filters to view applications": "Please change the selected filters to view applications",
  "No submissions available for the selected date range": "No submissions available for the selected date range",
  "Ok": "Ok",
  "Form not available": "Form not available",
  "Thank you for your response.": "Thank you for your response.",
  "saved successfully": "saved successfully",
  "Copy anonymous form URL": "Copy anonymous form URL",
  "Submitted By": "Submitted By",
  "Confirmation": "Confirmation",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.",
  "Error while saving Form": "Error while saving Form",
  "Click here to go back": "Click here to go back",
  " Applications are submitted against": " Applications are submitted against",
  " Application is submitted against": " Application is submitted against",
  "Are you sure to delete the":"Are you sure to delete the",
  "Are you sure to delete the draft": "Are you sure you want to delete the draft",
  "Are you sure to delete this submission ?": "Are you sure you want to delete this submission?",
  " Submissions are made against": " Submissions are made against",
  " Submission is made against": " Submission is made against",
  "Save Changes": "Save Changes",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.",
  "Form-Workflow association saved.": "Form-Workflow association saved.",
  "Form-Workflow association failed.": "Form-Workflow association failed.",
  "Form deletion unsuccessful": "Form deletion unsuccessful",
  "Form deleted successfully": "Form deleted successfully",
  "Bundle deleted successfully": "Bundle deleted successfully",
  "Form process failed": "Form process failed",
  "Form unpublishing Failed": "Form unpublishing Failed",
  "All groups have access to the dashboard": "All groups have access to the dashboard",
  "Export PDF": "Export PDF",
  "Something went wrong. Please try again!": "Something went wrong. Please try again!",
  "No Dashboards Found": "No Dashboards Found",
  "Processes": "Processes",
  "Please select an existing workflow.": "Please select an existing workflow.",
  "Create New": "Create New",
  "Or create new workflow or import a workflow from a local directory.": "Or create new workflow or import a workflow from a local directory.",
  "The operation couldn't be completed. Please try after sometime": "The operation couldn't be completed. Please try after sometime",
  "Select...": "Select...",
  "No Drafts Found": "No Drafts Found",
  "Help": "Help",
  "Draft Id": "Draft Id",
  "Draft Name": "Draft Name",
  "Link To Draft Submission": "Link To Draft Submission",
  "Drafts": "Drafts",
  "You can't submit this form until it is published": "You can't submit this form until it is published",
  "Form not published": "Form not published",
  "Access Denied": "Access Denied",
  "By default, the tenant key would be prefixed to form": "By default, the tenant key would be prefixed to form",
  "go back": "go back",
  "No Applications Found": "No Applications Found",
  "Submission saved to draft.": "Submission saved to draft.",
  "Saved to draft": "Saved to draft",
  "Saving...": "Saving...",
  "Resource": "Resource",
  "Error in creating form process mapper": "Error in creating form process mapper",
  "Select the date": "Select the date",
  "Diagram deployed": "Diagram deployed",
  "Deployment failed": "Deployment failed",
  "form uploaded": "form uploaded",
  "forms uploaded": "forms uploaded",
  "Failed to upload": "Failed to upload",
  "forms...!": "forms...!",
  "form...!": "form...!",
  "Process name(s) must not be empty": "Process name(s) must not be empty",
  "URL copied": "URL copied",
  "Click Here to Copy": "Click Here to Copy",
  "Resources": "Resources",
  "Duplicate form created successfully": "Duplicate form created successfully",
  "Revert": "Revert",

  "Criteria": "Criteria",
  "Select Form": "Select Form",
  "Create Condition": "Create Condition",
  "Enter criteria": "Enter criteria",
  "Make this form public": "Make this form public",
  "Enable bundling": "Enable bundling",

  "Bundle Name": "Bundle Name",
  "View/Edit": "View/Edit",
  "Create Bundle": "Create Bundle",
  "Rows per page": "Rows per page",
  "Items per page": "Items per page",
  "entries": "entries",
  "Form Bundle": "Form Bundle",
  "No bundles found": "No bundles found",
  "Please change the selected filters to view Bundles": "Please change the selected filters to view Bundles",
  "Select all to download forms": "Select all to download forms",
  "Select for download": "Select for download",
  "Bundle Description": "Bundle Description",
  "Conditions": "Conditions",
  "Enter name": "Enter name",
  "Enter Description": "Enter Description",
  "You can change the form order by drag and drop": "You can change the form order by drag and drop",
  "Form Order": "Form Order",
  "Form Type": "Form Type",
  "Add Forms Launch together": "Add Forms Launch together",
  "Form bundles can save your time by grouping forms together": "Form bundles can save your time by grouping forms together",
  "Add Forms": "Add Forms",
  "Create Conditions": "Create Conditions",
  " Add Conditions": " Add Conditions",
  "Select Forms": "Select Forms",
  "Insert": "Insert",
  "View Form": "View Form",
  "Publish this Bundle for Client Users.": "Publish this Bundle for Client Users.",
  "Total Forms": "Total Forms",
  "Edit Bundle": "Edit Bundle",
  "Next Form": "Next Form",
  "Previous Form": "Previous Form",
  "Forms included under the package": "Forms included under the package",
  "Submit": "Submit",
  "Reset Zoom": "Reset Zoom",
  "Zoom In": "Zoom In",
  "Zoom Out": "Zoom Out",
  "Deploy": "Deploy",
  "Export": "Export",
  "Overview": "Overview",
  "Design Permission": "Design Permission",
  "Application Permission": "Application Permission",
  "All Designers": "All Designers",
  "Private(only you)": "Private(only you)",
  "Specific Designer Group": "Specific Designer Group",
  "Submission Permission": "Submission Permission",
  "All Users": "All Users",
  "Specific User Group": "Specific User Group",
  "Specific Reviewers": "Specific Reviewers",
  "All Reviewers": "All Reviewers",
  "Permission for application tracking.": "Permission for application tracking.",
  "Design Bundle": "Design Bundle",
  "Workflow": "Workflow",
  "Bundle Name and Description is Required": "Bundle Name and Description is Required",
  "Bundle Description is Required": "Bundle Description is Required",
  "Bundle Create Successfully": "Bundle Create Successfully",
  "Bundle updated successfully": "Bundle updated successfully",
  "Select": "Select",
  "Unselect": "Unselect",
  "Applicable for Designer Roled Users only.": "Applicable for Designer Roled Users only.",
  "Applicable for Client and Reviewer Roled Users only.": "Applicable for Client and Reviewer Roled Users only.",
  "Done": "Done",
  "Failed to update permission!": "Failed to update permission!",
  "Failed to fetch roles!": "Failed to fetch roles!",
  "Failed to update role!": "Failed to update role!",
  "Permission updated successfully!": "Permission updated successfully!",
  "Role updated successfully!": "Role updated successfully!",
  "Update failed!": "Update failed!",
  "Clear": "Clear",
  "Are you sure deleting the role": "Are you sure deleting the role",
  "Confirm Delete": "Confirm Delete",
  "All roles": "All roles",
  "Filter By:": "Filter By:",
  "Create": "Create",
  "Eg: Account Manager": "Eg: Account Manager",
  "Search by name, username or email": "Search by name, username or email",
  "No data Found": "No data Found",
  "Dashboard": "Dashboard",
  "Roles": "Roles",
  "Users": "Users",
  "Create New Role": "Create New Role",
  "Search by role name": "Search by role name",
  "Role Name": "Role Name",
  "Actions": "Actions",
  "Create Role": "Create Role",
  "Email": "Email",
  "Role": "Role",
  "Add Role": "Add Role",
  "Role deleted successfully!": "Role deleted successfully!",
  "Failed to delete role!": "Failed to delete role!",
  "Role created successfully!": "Role created successfully!",
  "Failed to create role!": "Failed to create role!",
  "Update success!": "Update success!",
  "No results found": "No results found",
  "Edit Role": "Edit Role",
  "Failed to fetch users!": "Failed to fetch users!",
  "Role names cannot contain special characters except   _ , -": "Role names cannot contain special characters except   _ , -",
  "Role names cannot contain special characters except _ , - , / ": "Role names cannot contain special characters except _ , - , / ",
  "Rules deployed successfully": "Rules deployed successfully",
  "Choose From Template": "Choose From Template",
  "Back to forms": "Back to forms",
  "Choose From Templates": "Choose From Templates",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case",
  "All templates": "All templates",
  "Template count": "Template count",
  "Learn more": "Learn more",
  "Template Details": "Template Details",
  "Template Title": "Template Title",
  "Preview Form": "Preview Form",
  "Connected Workflow": "Connected Workflow",
  "Delete Template": "Delete Template",
  "Use Template": "Use Template",
  "Template created successfully": "Template created successfully",
  "Template deleted successfully": "Template deleted successfully",
  "Template updated successfully": "Template updated successfully",
  "Category": "Category",
  "Search category...": "Search category...",
  "Save as Template": "Save as Template",
  "Create Template": "Create Template",
  "Select or Create Category": "Select or Create Category",
  "Short Intro": "Short Intro",
  "Enter short intro": "Enter short intro",
  "Enter description": "Enter description",
  "Select or create": "Select or create",
  "Update Template": "Update Template",
  "Form created successfully": "Form created successfully",
  "select or create": "Select or create",
  "Update Associated Form": "Update Associated Form",
  "Update Associated Workflow": "Update Associated Workflow",
  "Enter title": "Enter title",
  "No Templates Found": "No Templates Found",
  "No Category Found": "No Category Found",
  "Save Template": "Save Template",
  "You can type and click the": "You can type and click the",
  "to create the category.": " to create the category.",
  "select or type to create": "select or type to create",
  "BPMN": "BPMN",
  "DMN": "DMN",
  "Advanced Designer": "Advanced Designer",
  "Basic Designer": "Basic Designer",
  "Search": "Search",
  "Key": "Key",
  "No Process Found": "No Process Found",
  "Search workflow": "Search workflow",
  "No Dmn Found": "No Dmn Found",
  "Submission ID": "Submission Id",
  "Submission Name": "Submission Name",
  "Submission History": "Submission History",
  "No Submission History found": "No Submission History found",
  "Error in submission count": "Error in submission count",
  "Permission for submission tracking.": "Permission for submission tracking.",
  "Reviewer permission to view submissions": "Reviewer permission to view submissions",
  "Permission to create new submission": "Permission to create new submission",
  "Back to Bundle List": "Back to Bundle List",
  "Bundle": "Bundle",
  "You can drag these nodes to the pane on the right.": "You can drag these nodes to the pane on the right.",
  "You can delete the element by select and click the backspace": "You can delete the element by select and click the backspace",
  "Workflow Id": "Workflow Id",
  "Enter Workflow Id": "Enter Workflow Id",
  "Back to Submissions": "Back to Submissions",
  "Back to Drafts": "Back to Drafts",
  "Choose Your Workflow Option": "Choose Your Workflow Option",
  "Create New Workflow": "Create New Workflow",
  "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.",
  "Reuse Existing Workflow": "Reuse Existing Workflow",
  "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements",
  "Are you sure you wish to delete the Template?": "Are you sure you wish to delete the Template?",
  "Enter Workflow Name": "Enter Workflow Name",
  "Create Workflow": "Create Workflow",
  "Upload Workflow": "Upload Workflow",
  "Edit Workflow": "Edit Workflow",
  "Published": "Published",
  "Unpublished": "Unpublished",
  "Private": "Private",
  "Anonymous": "Anonymous",
  "Edit Processes": "Edit Processes",
  "Create Processes": "Create Processes",
  "tasks": "tasks",
  "Submission Id": "Submission Id",
  "Clear All Filters": "Clear All Filters",
  "Show results": "Show results",
  "Delete Draft": "Delete Draft",
  "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.",
  "I am": "I am",
  "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'",
  "Enter your prompt here": "Enter your prompt here",
  "Would you like to continue?": "Would you like to continue?",
  "Restart": "Restart",
  "I'm here to provide further assistance. Thank you!": "I'm here to provide further assistance. Thank you!",
  "Generate Form Design": "Generate Form Design",
  "Preview": "Preview",
  "Your form is now ready!": "Your form is now ready!",
  "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description,  hit send.": "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description,  hit send.",
  "Choose template": "Choose template",
  "Search by bundle name": "Search by bundle name",
  "Save Bundle": "Save Bundle",
  "Id": "Id",
  "Enable bundling ?": "Enable bundling?",
  "Select a task in the List.": "Select a task in the List.",
  "Add Date": "Add Date",
  "Assign to Me": "Assign to Me",
  "Filter count:": "Filter count:",
  "Selected Forms": "Selected Forms",
  "Template Used:": "Template Used:",
  "Select a task from the List.": "Select a task from the List.",
  "Choose a task from the list; your selection directs your current activity.": "Choose a task from the list; your selection directs your current activity.",
  "Please change the selected filters to view submissions": "Please change the selected filters to view submissions",
  "Please change the selected filters to view drafts": "Please change the selected filters to view drafts",
  "No drafts found": "No drafts found",
  "Flow-E helps to build faster": "Flow-E helps to build faster",
  "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product",
  "Get in touch with formsflow.ai team": "Get in touch with formsflow.ai team",
  "Premium": "Premium",
  "Select a status":"Select a status",
  "Group":"Group",
  "Form description": "Form description",
  "Select all forms": "Select all forms",
  "Bold": "Bold",
  "Italic": "Italic",
  "Underline": "Underline",
  "Align left": "Align left",
  "Align center": "Align center",
  "Align right": "Align right",
  "Align justify": "Align justify",
  "Insert Link": "Insert Link",
  "Clean": "Clean",
  "Click for task variables": "Click for task variables",
  "Upload DMN": "Upload DMN",
  "DMN Name": "DMN Name",
  "Search by DMN name": "Search by DMN name",
  "Display authorized tasks based on user roles":"Display authorized tasks based on user roles",
  "Select Workflow": "Select Workflow",
  "Select Assignee": "Select Assignee",
  "Click here to select attributes": "Click here to select attributes",
  "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list",
  "Task variables": "Task variables",
  "User Role": "User Role",
  "User Group": "User Group",
  "Select User Role": "Select User Role",
  "Select User Group": "Select User Group"
};



