/* eslint-disable max-len */
export const RESOURCE_BUNDLES_DE = {
  "Filter Created by": "Filter erstellt von",
  "Submit Form": "Formular absenden",
  "Changes Applied Successfully": "Änderungen erfolgreich angewendet",
  "Filter Deleted Successfully": "Filter erfolgreich gelöscht",
  "Save Filter": "Filter speichern",
  "Filter Name": "Filtername",
  "Create new filter": "Neuen Filter erstellen",
  "Definition Key": "Definitionsschlüssel",
  "Permission": "Erlaubnis",
  "Enter your text here": "Gib deinen Text hier ein",
  "Accessible for all users": "Für alle Benutzer zugänglich",
  "Private (Only You)": "Privat (nur Sie)",
  "Specific Group": "Spezifische Gruppe",
  "Select Elements": "Elemente auswählen",
  " Task Attributes Selected": " Ausgewählte Aufgabenattribute",
  "Delete Filter": "Filter löschen",
  "Add Value": "Mehrwert",
  "Show only current user assigned task": "Nur zugewiesene Aufgaben des aktuellen Benutzers anzeigen",
  "Show task based on logged user roles": "Aufgaben basierend auf den Rollen des angemeldeten Benutzers anzeigen",
  "Create Filter": "Filter erstellen",
  "Task Attributes": "Aufgabenattribute",
  "Only selected task attributes will be available on task list view": "Nur ausgewählte Aufgabenattribute sind in der Aufgabenliste sichtbar",
  "Show undefined variables": "Undefinierte Variablen anzeigen",
  "Label": "Etikette",
  "Variables": "Variablen",
  "Task Title": "Aufgabentitel",
  "List View": "Listenansicht",
  "Card View": "Kartenansicht",
  "Create New Filter": "Neuen Filter erstellen",
  "Sort by": "Sortieren nach",
  "Collapse All": "Alle minimieren",
  "Expand All": "Alle maximieren",
  "Application Id": "Anwendungs-ID",
  "Back to task": "Zurück zur Aufgabe",
  "Filters": "Filter",
  "Assignee": "Zugewiesen an",
  "Select a user": "Benutzer auswählen",
  "Create DMN": "DMN erstellen",
  "Create Process": "Prozess erstellen",
  "Edit DMN": "DMN bearbeiten",
  "More options": "Mehr Optionen",
  "Form Description": "Formularbeschreibung",
  "Saved to Submissions/Drafts": "Gespeichert in Einreichungen/Entwürfe",
  "Unfinished submissions will be saved to Submissions/Drafts.": "Unvollständige Einreichungen werden in Einreichungen/Entwürfe gespeichert.",
  "Edit Process": "Prozess bearbeiten",
  "Add filter name": "Filternamen hinzufügen",
  "This section is aimed to set the parameters\nused to filter the tasks": "Dieser Abschnitt soll die Parameter festlegen, die\nzur Filterung der Aufgaben verwendet werden",
  "This section is aimed to set read\npermissions for the filter": "Dieser Abschnitt soll Leseberechtigungen für\nden Filter festlegen",
  "This section is aimed to set select\ntask attributes that will be visible in\nthe task list view": "Dieser Abschnitt soll auswählbare\nAufgabenattribute festlegen, die in der\nAufgabenliste sichtbar sein werden",
  "Task Attribute": "Aufgabenattribut",
  "You can define variables shown in the list": "Sie können Variablen definieren, die in der Liste angezeigt werden",
  "results": "Ergebnisse",
  "Enter role name": "Rollenname eingeben",
  "Public": "Öffentlich",
  "View Submitted Form": "Eingereichtes Formular anzeigen",
  "View Draft Details": "Entwurfsdetails anzeigen",
  "Edit Draft": "Entwurf bearbeiten",
  "Draft Title": "Titel des Entwurfs",
  "Filter": "Filter",
  "Advanced Options": "Erweiterte Optionen",
  "Enter the path name": "Geben Sie den Pfadnamen ein",
  "Search by form title": "Nach Formulartitel suchen",
  "Associate Workflow": "Workflow verknüpfen",
  "Search by workflow name": "Nach Workflow-Namen suchen",
  "View Details": "Details anzeigen",
  "Visibility": "Sichtbarkeit",
  "Form Title": "Formulartitel",
  "Access restricted by its designer..!": "Zugriff durch den Designer eingeschränkt..!",
  "and you will no longer have the access to this form in bundles": "und Sie haben keinen Zugriff mehr auf dieses Formular in Bündeln",
  "You will no longer have the access to this form in bundles": "Sie haben keinen Zugriff mehr auf dieses Formular in Bündel",
  "Bad Request": "Ungültige Anforderung",
  "Select the form to be displayed based on the  above criteria": "Wählen Sie das anzuzeigende Formular basierend auf den oben genannten Kriterien aus.",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "Erstellen Sie die Kriterien unter Verwendung des API-Schlüssels eines beliebigen Formularkomponenten und einer bedingten Notation. Zum Beispiel 'age > 18', wobei 'age' der API-Schlüssel eines Formularkomponenten ist.",
  "Select form version": "Formularversion auswählen",
  "Please remove the special characters...!": "Bitte entfernen Sie die Sonderzeichen...!",
  "No histories found": "Keine Historien gefunden",
  "Continue": "Fortfahren",
  "This will create a new version of the form without changing the path name but with new form id.": "Dadurch wird eine neue Version des Formulars erstellt, ohne den Pfadnamen zu ändern, aber mit einer neuen Formular-ID.",
  "Save as a new version": "Als neue Version speichern",
  "Save New Version": "Neue Version speichern",
  "Do you want to save a new version of this form?": "Möchten Sie eine neue Version dieses Formulars speichern?",
  "Do you want to create a duplicate form and associated workflow from existing form ?": "Möchten Sie ein Duplikat des Formulars und des zugehörigen Workflows aus einem vorhandenen Formular erstellen?",
  "New version created": "Neue Version erstellt",
  "Create a duplicate form": "Erstellen Sie ein Duplikat des Formulars",
  "Show more": "Mehr anzeigen",
  "Modified By": "Verändert von",
  "Created On": "Erstellt am",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "Formsflow speichert automatisch Ihre vorherigen Formulardaten. Jetzt können Sie zur vorherigen Stufe wechseln und bearbeiten.",
  "Duplicate Form": "Doppeltes Formular",
  "Form History": "Formulargeschichte",
  "No file chosen": "Keine Datei ausgewählt",
  "Choose File": "Datei auswählen",
  "Choose any": "Wählen Sie eine aus",
  "Sort by form name": "Nach Formularnamen sortieren",
  "select form type": "Formulartyp auswählen",
  "Draft Deleted Successfully": "Entwurf erfolgreich gelöscht",
  "Saved to Applications/Drafts": "Unter Anwendungen/Entwürfe gespeichert",
  "Unfinished applications will be saved to Applications/Drafts.": " Unfertige Bewerbungen werden unter Bewerbungen/Entwürfe gespeichert.",
  "Discard Draft": "Entwurf verwerfen",
  "with ID": "mit ID",
  "Please change the selected filters to view Forms": "Bitte ändern Sie die ausgewählten Filter, um Formulare anzuzeigen",
  "Search by form name": "Suche nach Formularnamen",
  "Click to search": "Klicken Sie hier, um zu suchen",
  "No submissions found": "Keine Einreichungen gefunden",
  "No submission avaliable in the selected date. Please select another date range": "Für das ausgewählte Datum ist keine Einreichung verfügbar. Bitte wählen Sie einen anderen Zeitraum aus",
  "Form field": "Formularfeld",
  "Enter Label": "Bezeichnung eingeben",
  "Select form field": "Formularfeld auswählen",
  "Latest Version": "Letzte Version",
  "Submission Status": "Statusübersicht",
  "No submission status": "Kein Übermittlungsstatus",
  "No Public url found": "Keine öffentliche URL gefunden",
  "Show in list": "In der Liste anzeigen",
  "Select Task Variable": "Wählen Sie eine Aufgabenvariable aus",
  "Enter your Label": "Bezeichnung eingeben",
  "Please select from one of the following workflows.": "Bitte wählen Sie einen der folgenden Workflows aus.",
  "Select Key": "Wählen Sie einen Identifikationsschlüssel aus",
  "Create Your Task Variable": "Erstellen Sie Ihre Aufgabenvariable",
  "No task variable selected": "Keine Aufgabenvariable ausgewählt",
  "Workflow Associate": "Workflow-Mitarbeiter",
  "Task variable": "Aufgabenvariable",
  "Enter pathname": "Geben Sie den Pfadnamen ein",
  "Name": "Name",
  "Title": "Titel",
  "Display as": "Darstellen als",
  "Anonymous Form ": "Anonymes Formular",
  "Submission Saved": "Einreichung gespeichert.",
  "Error while Submission.": "Fehler beim Senden.",
  "Form saved": "Formular gespeichert.",
  "Message": "Bitte beheben Sie die Fehler, bevor Sie sie es erneut senden.",
  "Submission cannot be done.": "Übermittlungsfehler.",
  "No Process Diagram found": "Kein Prozessdiagramm gefunden",
  "Edit": "Bearbeiten",
  "Do you want to associate form with a workflow ?": "Möchten Sie ein Formular mit einem Workflow verknüpfen?",
  "Yes": "Ja",
  "No": "Nein",
  "Form Name": "Formularname ",
  "Workflow Name": "Workflow-Name",
  "Publish this form for Client Users.": "Veröffentlichen Sie dieses Formular für Clientbenutzer.",
  "Comments": "Bemerkungen",
  "Back": "Zurück",
  "Edit Form": "Formular bearbeiten",
  "Next": "Weiter",
  "Save": "Speichern",
  "Back to Form List": "Zurück zur Formularliste",
  "Submit New": "Neu einreichen",
  "View Submissions": "Einsendungen anzeigen",
  "View/Edit Form": "Formular anzeigen/bearbeiten",
  "Delete Form": "Formular löschen",
  "Delete": "Löschen",
  "Print As PDF": "Als PDF drucken",
  "Applications": "Anwendungen",
  "Tasks": "Aufgaben",
  "Metrics": "Metriken",
  "Dashboard": "Dashboard",
  "Dashboards": "Dashboards",
  "Logout": "Ausloggen",
  "No tasks found": "Keine Aufgaben gefunden",
  "Please change the selected filters to view tasks": "Bitte ändern Sie die ausgewählten Filter, um Aufgaben anzuzeigen",
  "Clear all filters": "Alle Filter löschen",
  "Created": "Erstellt",
  "Task Variables": "Task-Variablen",
  "Process Variables": "Prozessvariablen",
  "Process Definition Name": "Name der Prozessdefinition",
  "Assigne": "Abtretungsempfängerin",
  "Candidate Group": "Gruppe",
  "Candidate User": "Benutzer",
  "Description": "Beschreibung",
  "Priority": "Priorität",
  "Due Date": "Fälligkeitsdatum",
  "Follow up Date": "Wiedervorlagedatum",
  "Task name": "Aufgabennname",
  "Remove sorting": "Sortierung entfernen",
  "Ascending": "Aufsteigend",
  "Descending": "Absteigend",
  "Add sorting": "Sortierung hinzufügen",
  "of the criteria are met.": "der Kriterien erfüllt sind.",
  "For Variable, ignore case of": "Ignorieren Sie für Variable die Groß- und Kleinschreibung",
  "name": "Name",
  "value": "Wert",
  "No task matching filters found.": "Keine Aufgabe gefunden, die mit Filtern übereinstimmt.",
  "Application ID": "Anwendungs-ID",
  "Set follow-up Date": "Wiedervorlagedatum festlegen",
  "Set Due date": "Fälligkeitsdatum festlegen",
  "Add groups": "Gruppen hinzufügen",
  "Claim": "Zuordnen",
  "Search By Last Name": "Suche nach Nachnamen",
  "Search By First Name": "Suche nach Vornamen",
  "Search By Email": "Suche nach E-Mail-Adresse",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Sie können eine Gruppe hinzufügen, indem Sie eine Gruppen-ID in das Eingabefeld eingeben und anschließend auf die Schaltfläche mit dem Pluszeichen klicken.",
  "Add a group": "Gruppe hinzufügen",
  "Process Name": "Prozessname",
  "Set FollowUp Date": "Wiedervorlagedatum festlegen",
  "Groups": "Gruppen",
  "Click to Change Assignee": "Zuordnung ändern",
  "Reset Assignee": "Zuordnung zurücksetzen",
  "Update User": "Benutzer aktualisieren",
  "Close": "Schließen",
  "Type": "Art",
  "Remove search": "Suche entfernen",
  "Property": "Eigenschaft",
  "Operator": "Operator",
  "Total number of results": "Gesamtzahl der Ergebnisse",
  "Filter Tasks": "Aufgaben filtern",
  "All": "Alle",
  "ANY": "IRGENDEIN",
  "Task assignee": "Aufgabenzuständiger",
  "Application History": "Anwendungsgeschichte",
  "View Submission": "Einreichung anzeigen",
  "Showing": "Anzeigen",
  "to": "zu",
  "Results": "Ergebnisse",
  "Acknowledge": "Anerkennen",
  "View": "Anzeigen",
  "Select a task in the list.": "Wählen Sie eine Aufgabe in der Liste aus.",
  "No Filters Found": "Keine Aufgabe gefunden, die mit Filtern übereinstimmt.",
  "Loading": "Wird geladen",
  "Form": "Formular",
  "History": "Historie",
  "Diagram": "Diagramm",
  "Delete Confirmation": "Bestätigung löschen",
  "All tasks": "Alle Aufgaben",
  "Manage Groups": "Gruppen verwalten",
  "Group ID": "Gruppen-ID",
  "Due": "Fällig",
  "Follow-up": "Wiedervorlage",
  "Application Name": "Anwendungsname",
  "Created By": "Erstellt von",
  "Application Status": "Bewerbungsstatus",
  "Request Status": "Anforderungsstatus",
  "Request Name": "Name anfordern",
  "Submitted On": "Eingereicht am",
  "Modified On": "Geändert am",
  "No History Found": "Keine Historie gefunden",
  "Process Diagram": "Prozessdiagramm",
  "Details": "Einzelheiten",
  "Status": "Status",
  "Submissions": "Einreichungen",
  "No Application History found": "Keine Anwendungshistorie gefunden",
  "Link To Form Submission": "Link zur Formularübermittlung",
  "Last Modified": "Zuletzt geändert",
  "I": "Einblicke",
  "No dashboard found": "Kein Dashboard gefunden",
  "of": "von",
  "Select Dashboard": "Wählen Sie Dashboard aus",
  "Total Submissions": "Einreichungen insgesamt",
  "Save & Preview": "Speichern & Vorschau",
  "Operations": "Atkionen",
  "Access Groups": "Nutzergruppen",
  "Action": "Aktion",
  "Add": "Addieren",
  "Admin": "Administrator",
  "Create Form": "Formular erstellen",
  "Upload Form": "Formular hochladen",
  "Download Form": "Formular herunterladen",
  "Upload json form only": "Laden Sie nur das JSON-Formular hoch",
  "Select atleast one form": "Wählen Sie mindestens ein Formular aus",
  "Select All": "Wählen Sie alle",
  "Created Date": "Erstellungsdatum",
  "Modified Date": "Änderungsdatum",
  "File Upload Status": "Datei-Upload-Status",
  "Forms Completed": "Formulare ausgefüllt",
  "Form Completed": "Formular ausgefüllt",
  "No forms found": "Keine Formulare gefunden",
  "Powered by ": "Bereitgestellt von ",
  "Press Enter key or click here to search": "Drücken Sie die Eingabetaste oder klicken Sie hier, um zu suchen",
  "Click to clear": "Zum Löschen klicken",
  "Search...": "Suche...",
  "No applications found": "Keine Anwendungen gefunden",
  "Successfully Updated": "Erfolgreich aktualisiert",
  "Failed": "Gescheitert",
  "Submission Failed.": "Übermittlung fehlgeschlagen.",
  "Click here to back": "Klicken Sie hier, um zurück zu gelangen",
  "path": "Weg",
  "Make this form public ?": "Dieses Formular öffentlich machen?",
  "Design Form": "Formular entwerfen",
  "Associate this form with a workflow?": "Dieses Formular einem Workflow zuordnen?",
  "Preview and Confirm": "Vorschau und bestätigen",
  "All steps completed - you're finished": "Alle Schritte abgeschlossen - Sie sind fertig",
  "Enter the form machine name": "Geben Sie den Maschinennamen ein",
  "Enter the form title": "Geben Sie den Formulartitel ein",
  "Wizard": "Wizard",
  "Text Field": "Textfeld",
  "example": "Beispiel",
  "Forms": "Formulare",
  "Downloaded Successfully": "Erfolgreich heruntergeladen",
  "Error in JSON file structure": "Fehler in der JSON-Dateistruktur",
  "Please fix the errors before submitting again.": "Bitte beheben Sie die Fehler, bevor Sie sie erneut senden.",
  "Loading...": "Wird geladen...",
  "Save Form": "Formular speichern",
  "Confirm": "Bestätigen",
  "Cancel": "Stornieren",
  "Please change the selected filters to view applications": "Wijzig de geselecteerde filters om applicaties te bekijken",
  "No submissions available for the selected date range": "Für den ausgewählten Zeitraum sind keine Einreichungen verfügbar",
  "OK": "OK",
  "Form not available": "Formular nicht verfügbar",
  "Thank you for your response.": "Danke für Ihre Antwort.",
  "saved successfully": "Erfolgreich gespeichert",
  "Copy anonymous form URL": "Kopieren Sie die anonyme Formular-URL",
  "Submitted By": "Eingereicht von",
  "Confirmation": "Bestätigung",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Das Ändern des Formulartitels wirkt sich nicht auf die bestehenden Anwendungen aus. Es wird nur in den neu erstellten Anwendungen aktualisiert. Drücken Sie Änderungen speichern, um fortzufahren oder die Änderungen abzubrechen.",
  "Error while saving Form": "Fehler beim Speichern des Formulars",
  "Click here to go back": "Klicken Sie hier um zurück zu kommen",
  " Applications are submitted against": " Anträge werden dagegen gestellt",
  " Application is submitted against": " Antrag wird dagegen gestellt",
  "Are you sure to delete the": "Sind Sie sicher, dass Sie löschen möchten",
  "Are you sure to delete the draft": "Sind Sie sicher, dass Sie den Entwurf löschen möchten",
  " Submissions are made against": " Einreichungen erfolgen gegen",
  " Submission is made against": " Die Einreichung erfolgt gegen",
  "Are you sure to delete this submission ?": "Sind Sie sicher, dass Sie diesen Eintrag löschen möchten?",
  "Save Changes": "Änderungen speichern",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Das Ändern des Formular-Workflows wirkt sich nicht auf die vorhandenen Anwendungen aus. Es wird nur in den neu erstellten Anwendungen aktualisiert. Drücken Sie Änderungen speichern, um fortzufahren oder die Änderungen abzubrechen.",
  "Form-Workflow association saved.": "Formular-Workflow-Zuordnung gespeichert.",
  "Form-Workflow association failed.": "Die Formular-Workflow-Zuordnung ist fehlgeschlagen.",
  "Form deleted successfully": "Formular erfolgreich gelöscht",
  "Bundle deleted successfully": "Bundle erfolgreich gelöscht",
  "Form deletion unsuccessful": "Formularlöschung fehlgeschlagen",
  "Form process failed": "Formularprozess fehlgeschlagen",
  "Form unpublishing Failed": "Das Aufheben der Veröffentlichung des Formulars ist fehlgeschlagen",
  "All groups have access to the dashboard": "Alle Gruppen haben Zugriff auf das Dashboard",
  "Export PDF": "PDF exportieren",
  "Something went wrong. Please try again!": "Etwas ist schief gelaufen. Bitte versuche es erneut!",
  "No Dashboards Found": "Keine Dashboards gefunden",
  "Processes": "Prozesse",
  "Please select an existing workflow.": "Bitte wählen Sie einen bestehenden Workflow aus.",
  "Create New": "Neu erstellen",
  "Or create new workflow or import a workflow from a local directory.": "Oder erstellen Sie einen neuen Workflow oder importieren Sie einen Workflow aus einem lokalen Verzeichnis.",
  "The operation couldn't be completed. Please try after sometime": "Der Vorgang konnte nicht abgeschlossen werden. Bitte versuchen Sie es nach einiger Zeit erneut",
  "Select...": "Auswählen...",
  "No Drafts Found": "Keine Entwürfe gefunden",
  "Help": "Hilfe",
  "Draft Id": "Entwurfs-ID",
  "Draft Name": "Entwurfsname",
  "Link To Draft Submission": "Link zur Entwurfsübermittlung",
  "Drafts": "Entwürfe",
  "You can't submit this form until it is published": "Sie können dieses Formular erst absenden, wenn es veröffentlicht wurde",
  "Form not published": "Formular nicht veröffentlicht",
  "Access Denied": "Zugriff abgelehnt",
  "By default, the tenant key would be prefixed to form": "Standardmäßig wird dem Mandantenschlüssel form vorangestellt",
  "go back": "zurück",
  "No Applications Found": "Keine Anwendungen gefunden",
  "Submission saved to draft.": "Einsendung als Entwurf gespeichert.",
  "Saved to draft": "Als Entwurf gespeichert",
  "Saving...": "Speichern...",
  "Resource": "Ressource",
  "Error in creating form process mapper": "Fehler beim Erstellen des Formularprozess-Mappers",
  "Select the date": "Wählen Sie das Datum aus",
  "Diagram deployed": "Diagramm bereitgestellt",
  "Deployment failed": "Bereitstellung fehlgeschlagen",
  "form uploaded": "Formular hochgeladen",
  "forms uploaded": "Formulare hochgeladen",
  "Failed to upload": "Hochladen fehlgeschlagen",
  "forms...!": "Formen...!",
  "form...!": "bilden...!",
  "Process name(s) must not be empty": "Prozessname(n) dürfen nicht leer sein",
  "URL copied": "URL kopiert",
  "Click Here to Copy": "Klicken Sie hier, um zu kopieren",
  "Resources": "Bronnen",
  "Duplicate form created successfully": "Doppeltes Formular erfolgreich erstellt",
  "Revert": "Zurückkehren",
  "Overview": "Überblick",
  "Design Permission": "Designgenehmigung",
  "Application Permission": "Anwendungserlaubnis",
  "All Designers": "Alle Designer",
  "Private(only you)": "Privat (nur Sie)",
  "Specific Designer Group": "Spezifische Designergruppe",
  "Submission Permission": "Einreichungserlaubnis",
  "All Users": "Alle Nutzer",
  "Specific User Group": "Spezifische Benutzergruppe",
  "Specific Reviewers": "Spezifische Gutachter",
  "All Reviewers": "Alle Rezensenten",
  "Permission for application tracking.": "Erlaubnis zur Bewerbungsverfolgung.",
  "Applicable for Designer Roled Users only.": "Gilt nur für Benutzer mit Designer-Rolle.",
  "Applicable for Client and Reviewer Roled Users only.": "Gilt nur für Benutzer mit Kunden- und Prüferrollen.",
  "Criteria": "Kriterien",
  "Select Form": "Wählen Sie Formular aus",
  "Create Condition": "Bedingung erstellen",
  "Enter criteria": "Kriterien eingeben",
  "Make this form public": "Machen Sie dieses Formular öffentlich",
  "Enable bundling": "Bündelung aktivieren",
  "Bundle Name": "Bündelname",
  "View/Edit": "Anzeigen/Bearbeiten",
  "Create Bundle": "Bündel erstellen",
  "Rows per page": "Zeilen pro Seite",
  "Items per page": "Elemente pro Seite",
  "entries": "Einträge",
  "Form Bundle": "Formularbündel",
  "No bundles found": "Keine Pakete gefunden",
  "Please change the selected filters to view Bundles": "Bitte ändern Sie die ausgewählten Filter, um Bundles anzuzeigen",
  "Select all to download forms": "Wählen Sie alle aus, um Formulare herunterzuladen",
  "Select for download": "Zum Herunterladen auswählen",
  "Bundle Description": "Bündelbeschreibung",
  "Conditions": "Bedingungen",
  "Enter name": "Name eingeben",
  "Enter Description": "Beschreibung eingeben",
  "You can change the form order by drag and drop": "Sie können die Formularreihenfolge per Drag and Drop ändern",
  "Form Order": "Bestellformular",
  "Form Type": "Formulartyp",
  "Add Forms Launch together": "Fügen Sie Forms Launch zusammen hinzu",
  "Form bundles can save your time by grouping forms together": "Formularbündel können Ihre Zeit sparen, indem Sie Formulare gruppieren",
  "Add Forms": "Formulare hinzufügen",
  "Create Conditions": "Bedingungen schaffen",
  " Add Conditions": "Bedingungen hinzufügen",
  "Select Forms": "Wählen Sie Formulare aus",
  "Insert": "Einfügung",
  "View Form": "Formular anzeigen",
  "Publish this Bundle for Client Users.": "Veröffentlichen Sie dieses Bundle für Client-Benutzer",
  "Total Forms": "Gesamtformen",
  "Edit Bundle": "Bündel bearbeiten",
  "Next Form": "Nächstes Formular",
  "Previous Form": "Vorheriges Formular",
  "Forms included under the package": "Formulare im Paket enthalten",
  "Submit": "Einreichen",
  "Reset Zoom": "Zoom zurücksetzen",
  "Zoom In": "Hineinzoomen",
  "Zoom Out": "Rauszoomen",
  "Deploy": "Einsetzen",
  "Export": "Export",
  "Design Bundle": "Design-Paket",
  "Workflow": "Arbeitsablauf",
  "Bundle Name and Description is Required": "Paketname und -beschreibung sind erforderlich",
  "Bundle Description is Required": "Paketbeschreibung ist erforderlich",
  "Bundle Create Successfully": "Paket erfolgreich erstellt",
  "Bundle updated successfully": "Paket erfolgreich aktualisiert",
  "Select": "Auswählen",
  "Unselect": "Abwählen",
  "Done": "Erledigt",
  "Failed to update permission!": "Berechtigung konnte nicht aktualisiert werden!",
  "Failed to fetch roles!": "Rollen konnten nicht abgerufen werden!",
  "Failed to update role!": "Rolle konnte nicht aktualisiert werden!",
  "Permission updated successfully!": "Berechtigung erfolgreich aktualisiert!",
  "Role updated successfully!": "Rolle erfolgreich aktualisiert!",
  "Update failed!": "Update fehlgeschlagen!",
  "Clear": "Klar",
  "Are you sure deleting the role": "Sind Sie sicher, dass Sie die Rolle löschen",
  "Confirm Delete": "Löschen bestätigen",
  "All roles": "Alle Rollen",
  "Filter By:": "Filtern nach:",
  "Create": "Erstellen",
  "Eg: Account Manager": "Beispiel: Kontomanager",
  "Search by name, username or email": "Suche nach Name, Benutzername oder E-Mail",
  "No data Found": "Keine Daten gefunden",
  "Roles": "Rollen",
  "Users": "Benutzer",
  "Create New Role": "Neue Rolle erstellen",
  "Search by role name": "Suche nach Rollennamen",
  "Role Name": "Rollenname",
  "Actions": "Aktionen",
  "Create Role": "Rolle erstellen",
  "Email": "Email",
  "Role": "Rolle",
  "Add Role": "Rolle hinzufügen",
  "Role deleted successfully!": "Rolle erfolgreich gelöscht!",
  "Failed to delete role!": "Rolle konnte nicht gelöscht werden!",
  "Role created successfully!": "Rolle erfolgreich erstellt!",
  "Failed to create role!": "Rolle konnte nicht erstellt werden!",
  "Update success!": "Update-Erfolg!",
  "No results found": "keine Ergebnisse gefunden",
  "Edit Role": "Rolle bearbeiten",
  "Failed to fetch users!": "Nutzer konnten nicht abgerufen werden!",
  "Role names cannot contain special characters except   _ , -": "Rollennamen dürfen keine Sonderzeichen außer _ , - enthalten.",
  "Role names cannot contain special characters except _ , - , / ": "Rollennamen dürfen keine Sonderzeichen außer _ , - , / enthalten.",
  "Rules deployed successfully": "Regeln erfolgreich bereitgestellt",
  "Choose From Template": "Aus Vorlage auswählen",
  "Back to forms": "Zurück zu den Formularen",
  "Choose From Templates": "Aus Vorlagen auswählen",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Erkunden Sie unsere Vorlagenbibliothek, um die perfekte Kombination aus Formularen und Workflows zu finden. Klicken Sie auf eine Vorlage, um eine Vorschau anzuzeigen, und passen Sie sie nach Ihren Wünschen an. Sobald Sie sie an Ihre speziellen Anforderungen angepasst haben, sind Sie bereit, Ihr Geschäftsszenario zu erstellen",
  "All templates": "Alle Vorlagen",
  "Template count": "Anzahl der Vorlagen",
  "Learn more": "Erfahren Sie mehr",
  "Template Details": "Vorlagendetails",
  "Template Title": "Vorlagentitel",
  "Preview Form": "Formularvorschau",
  "Connected Workflow": "Verbundener Workflow",
  "Delete Template": "Vorlage löschen",
  "Use Template": "Vorlage verwenden",
  "Template created successfully": "Vorlage erfolgreich erstellt",
  "Template deleted successfully": "Vorlage erfolgreich gelöscht",
  "Template updated successfully": "Vorlage erfolgreich aktualisiert",
  "Category": "Kategorie",
  "Search category...": "Kategorie durchsuchen...",
  "Save as Template": "Als Vorlage speichern",
  "Create Template": "Vorlage erstellen",
  "Select or Create Category": "Kategorie auswählen oder erstellen",
  "Short Intro": "Kurze Einleitung",
  "Enter short intro": "Kurze Einleitung eingeben",
  "Enter description": "Beschreibung eingeben",
  "Select or create": "Auswählen oder erstellen",
  "Update Template": "Vorlage aktualisieren",
  "Form created successfully": "Formular erfolgreich erstellt",
  "select or create": "Auswählen oder erstellen",
  "Update Associated Form": "Verknüpftes Formular aktualisieren",
  "Update Associated Workflow": "Verknüpften Workflow aktualisieren",
  "Enter title": "Titel eingeben",
  "No Templates Found": "Keine Vorlagen gefunden",
  "No Category Found": "Keine Kategorie gefunden",
  "Save Template": "Vorlage speichern",
  "You can type and click the": "Sie können tippen und klicken Sie auf die",
  "to create the category.": "um die Kategorie zu erstellen.",
  "select or type to create": "auswählen oder eingeben, um zu erstellen",
  "BPMN": "BPMN",
  "DMN": "DMN",
  "Advanced Designer": "Fortgeschrittener Designer",
  "Basic Designer": "Grundlegender Designer",
  "Search": "Suchen",
  "Key": "Taste",
  "No Process Found": "Kein Prozess Gefunden",
  "Search workflow": "Workflow Suchen",
  "No Dmn Found": "Kein DMN Gefunden",
  "Submission ID": "Einreichungs-ID",
  "Submission Name": "Einreichungsname",
  "Submission History": "Einreichungshistorie",
  "No Submission History found": "Keine Einreichungshistorie gefunden",
  "Error in submission count": "Fehler in der Einreichungszählung",
  "Permission for submission tracking.": "Berechtigung für die Einreichungsverfolgung.",
  "Reviewer permission to view submissions": "Berechtigung des Reviewers zur Ansicht von Einreichungen",
  "Permission to create new submission": "Berechtigung zur Erstellung einer neuen Einreichung",
  "Back to Bundle List": "Zurück zur Bündelliste",
  "Bundle": "Bündel",
  "You can drag these nodes to the pane on the right.": "Sie können diese Knoten auf das Fenster rechts ziehen.",
  "You can delete the element by select and click the backspace": "Sie können das Element auswählen und die Rücktaste drücken, um es zu löschen",
  "Workflow Id": "Workflow-ID",
  "Enter Workflow Id": "Workflow-ID eingeben",
  "Back to Submissions": "Zurück zu den Einreichungen",
  "Back to Drafts": "Zurück zu den Entwürfen",
  "Choose Your Workflow Option": "Wählen Sie Ihre Workflow-Option",
  "Create New Workflow": "Neuen Workflow erstellen",
  "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "Wählen Sie diese Option aus, wenn Sie einen neuen Workflow auf der Grundlage der Vorlage erstellen möchten. Das System generiert und implementiert einen neuen Workflow und verbindet ihn dann mit dem ausgewählten Formular. Entscheiden Sie sich dafür, wenn Ihr Formular eine speziell auf seine Bedürfnisse zugeschnittene Reihe von Workflow-Schritten erfordert.",
  "Reuse Existing Workflow": "Vorhandenen Workflow wiederverwenden",
  "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "Wählen Sie diese Option aus, um das Formular mit einem bereits etablierten Workflow zu verknüpfen. Alle Änderungen am vorhandenen Workflow werden sich automatisch auch in diesem Formular widerspiegeln. Dies ist ideal, wenn Sie den vorhandenen Workflow für die Anforderungen Ihres Formulars nutzen möchten.",
  "Are you sure you wish to delete the Template?": "Sind Sie sicher, dass Sie die Vorlage löschen möchten?",
  "Enter Workflow Name": "Geben Sie den Workflow-Namen ein",
  "Create Workflow": "Workflow erstellen",
  "Upload Workflow": "Workflow hochladen",
  "Edit Workflow": "Workflow bearbeiten",
  "Published": "Veröffentlicht",
  "Unpublished": "Nicht veröffentlicht",
  "Private": "Privat",
  "Anonymous": "Anonym",
  "Edit Processes": "Prozesse bearbeiten",
  "Create Processes": "Prozesse erstellen",
  "tasks": "Aufgaben",
  "Submission Id": "Einreichungs-ID",
  "Clear All Filters": "Alle Filter löschen",
  "Show results": "Ergebnisse anzeigen",
  "Delete Draft": "Entwurf löschen",
  "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "Ich kann Ihnen helfen, Formulare mühelos zu gestalten - alles, was Sie tun müssen, ist mir eine klare und prägnante Beschreibung dessen zu geben, wofür das Formular gedacht ist. Ich werde die Felder und das Layout für Sie erstellen, die Sie weiter anpassen können.",
  "I am": "Ich bin",
  "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "Zum Beispiel 'Geben Sie uns ein Formular, das als Anmeldeformular für Patienten in Walk-In-Kliniken dient'.",
  "Enter your prompt here": "Geben Sie hier Ihren Hinweis ein",
  "Would you like to continue?": "Möchten Sie fortfahren?",
  "Restart": "Neustart",
  "I'm here to provide further assistance. Thank you!": "Ich stehe Ihnen gerne für weitere Unterstützung zur Verfügung. Vielen Dank!",
  "Generate Form Design": "Formulardesign generieren",
  "Preview": "Vorschau",
  "Your form is now ready!": "Ihr Formular ist jetzt bereit!",
  "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description, hit send.": "Bitte geben Sie uns alle Spezifikationen und Anforderungen, die Sie für Ihr Formular im Kopf haben. Nachdem Sie die Beschreibung abgeschlossen haben, drücken Sie die Eingabetaste.",
  "Choose template": "Vorlage auswählen",
  "Search by bundle name": "Nach Bundle-Namen suchen",
  "Save Bundle": "Bundle speichern",
  "Id": "Id",
  "Enable bundling ?": "Bündelung aktivieren?",
  "Select a task in the List.": "Wählen Sie eine Aufgabe in der Liste aus.",
  "Add Date": "Datum hinzufügen",
  "Assign to Me": "Mir zuweisen",
  "Filter count:": "Filteranzahl:",
  "Selected Forms": "Ausgewählte Formulare",
  "Template Used:": "Verwendetes Template:",
  "Select a task from the List.": "Wählen Sie eine Aufgabe aus der Liste aus.",
  "Choose a task from the list; your selection directs your current activity.": "Wählen Sie eine Aufgabe aus der Liste aus; Ihre Auswahl bestimmt Ihre aktuelle Aktivität.",
  "Please change the selected filters to view submissions": "Bitte ändern Sie die ausgewählten Filter, um Einreichungen anzuzeigen",
  "Please change the selected filters to view drafts": "Bitte ändern Sie die ausgewählten Filter, um Entwürfe anzuzeigen",
  "No drafts found": "Keine Entwürfe gefunden",
  "Flow-E helps to build faster": "Flow-E hilft, schneller zu bauen",
  "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "Flow-E steht in der Testinstanz nicht für eine Demonstration zur Verfügung. Sie können Flow-E in einem der Premium-Pakete des Produkts erleben",
  "Get in touch with formsflow.ai team": "Kontaktieren Sie das formsflow.ai-Team",
  "Premium": "Premium",
  "Select a status": "Wählen Sie einen Status",
  "Group": "Gruppe",
  "Form description": "Formularbeschreibung",
  "Select all forms": "Alle Formulare auswählen",
  "Bold": "Fett",
  "Italic": "Kursiv",
  "Underline": "Unterstrichen",
  "Align left": "Links ausrichten",
  "Align center": "Zentriert ausrichten",
  "Align right": "Rechts ausrichten",
  "Align justify": "Blocksatz",
  "Insert Link": "Link einfügen",
  "Clean": "Formatierung entfernen",
  "Click for task variables": "Klicken Sie für Aufgabenvariablen",
  "Upload DMN": "DMN hochladen",
  "DMN Name": "DMN-Name",
  "Search by DMN name": "Nach DMN-Namen suchen",
  "Display authorized tasks based on user roles": "Autorisierte Aufgaben basierend auf Benutzerrollen anzeigen",
  "You are currently using a test instance.The trial period ends in": "Sie verwenden derzeit eine Testinstanz. Die Testphase endet in",
  "days.": "Tage.",
  "Are you sure to delete": "Sind Sie sicher, dass Sie löschen möchten",
  "filter?": "Filter?",
  "Select Workflow": "Arbeitsablauf auswählen",
  "Select Assignee": "Zuweisung auswählen",
  "Click here to select attributes": "Klicken Sie hier, um Attribute auszuwählen",
  "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "Wählen Sie die vordefinierten Attribute und benutzerdefinierten Aufgabenvariablen aus, die im Rahmen der Formularübermittlung erstellt wurden und die Sie in der Aufgabenliste anzeigen möchten",
  "Task variables": "Aufgabenvaiablen",
  "User Role": "Benutzerrolle",
  "User Group": "Benutzergruppe",
  "Select User Role": "Benutzerrolle auswählen",
  "Select User Group": "Benutzergruppe auswählen",
  "To display task variables, select a form as part of the filter": "Um Aufgabenvaiablen anzuzeigen, wählen Sie ein Formular als Teil des Filters aus",
  "select a form": "wähle ein Formular",
  "No task variables found": "Keine Aufgabenvariablen gefunden",
  "Edit filter": "Filter bearbeiten",
  "Select form fields to display in task list": "Wählen Sie die Formularfelder aus, die in der Aufgabenliste angezeigt werden sollen",
  "Select all fields": "Alle Felder auswählen",
  "Edit Label": "Beschriftung bearbeiten",
  "Selecting all form fields may affect performance. For the best performance, just pick the form fields you really need.": "Das Auswählen aller Formularfelder kann sich auf die Leistung auswirken. Wählen Sie für die beste Leistung nur die Formularfelder aus, die Sie wirklich benötigen.",
  "User Added successfully!": "Benutzer erfolgreich hinzugefügt!",
  "Failed to create user!": "Benutzer konnte nicht erstellt werden!",
  "Add Registered Users": "Registrierte Benutzer hinzufügen",
  "Username or Email": "Benutzername oder E-Mail",
  "Add User": "Benutzer hinzufügen",
  "User doesn't exist!": "Benutzer existiert nicht!",
  "Success": "Erfolg",
  "User added": "Benutzer hinzugefügt",
  "From": "Von",
  "To": "Zu",
  "Premium Subscription": "Premium-Abonnement",
  " For further insights on this exclusive premium feature, kindly connect": "Für weitere Einblicke in dieses exklusive Premium-Feature, verbinden Sie sich bitte",
  " with our dedicated marketing team for detailed information.": "mit unserem engagierten Marketingteam für detaillierte Informationen.",
  "Get Connected With Us Now!": "Jetzt mit uns verbinden!",
  "Visit our": "Besuchen Sie unsere",
  "Pricing page": "Preisseite",
  "for more details.": "für weitere Details.",
  "Integration": "Integration",
  "Recipes": "Rezepte",
  "Connected Apps": "Verbundene Apps",
  "Library": "Bibliothek",
  "Add group": "Gruppe hinzufügen",
  "Add task label": "Aufgabenbezeichnung hinzufügen",
  "Integrations": "Integrationen",
  "We facilitate hundreds of native integrations via our ‘Native Integrations Pro’ package.": "Wir ermöglichen Hunderte von nativen Integrationen über unser Paket „Native Integrations Pro“.",
  " This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "Diese Funktion ist standardmäßig nicht im 14-Tage-Test verfügbar. Wenn Ihr Test diese Funktion erfordert, können Sie uns dies mitteilen, und wir können dies für Sie aktivieren.",
  "Upgrade to unlock Native Integrations Pro": "Upgrade, um Native Integrations Pro freizuschalten",
  "We facilitate hundreds of native integrations via our ": "Wir ermöglichen Hunderte von nativen Integrationen über unsere ",
  "Native Integrations Pro": "Native Integrations Pro",
  " package. This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "-Paket. Diese Funktion ist standardmäßig nicht in der 14-Tage-Testversion verfügbar. Wenn Ihre Testversion diese Funktion erfordert, können Sie uns dies mitteilen, und wir können sie für Sie aktivieren.",
  "To learn more about Native Integrations Pro": "Weitere Informationen zu Native Integrations Pro finden Sie unter",
  "Check out Integrations Feature": "Überprüfen Sie die Integrationen-Funktion",
  "Connect with": "Wenden Sie sich an",
  "team for requests or queries.": "das Team für Anfragen oder Fragen.",
  "Learn more about the feature": "Erfahren Sie mehr über das Feature",
  " team.": "Team.",
  "Connect with formsflow.ai team.": "Verbinden Sie sich mit dem formsflow.ai-Team.",
  "You don't have permission to access this page.": "Sie haben keine Berechtigung, diese Seite zu betreten.",
  "Please contact your administrator or try again later.": "Bitte wenden Sie sich an Ihren Administrator oder versuchen Sie es später erneut.",
  "Return to login": "Zurück zum Login",
  "Default filter removed": "Standardfilter entfernt",
  "Set default filter": "Standardfilter festlegen",
  "added as default filter": "als Standardfilter hinzugefügt",
  "Are you sure you wish to delete the draft": "Möchten Sie den Entwurf wirklich löschen",
  "Are you sure you wish to delete the form ": "Möchten Sie das Formular wirklich löschen ",
  "Are you sure you wish to delete the form?": "Möchten Sie das Formular wirklich löschen? ",
  ". Are you sure want to delete ?": ". Möchten Sie wirklich löschen?",
  "Add form fields to display in task list": "Fügen Sie Antragsfelder hinzu, die in der Aufgabenliste angezeigt werden sollen",
  "Version": "Version",
  "Insights": "Einblicke",
  "Task": "Aufgaben",
  "Path": "Pfad",
  "Error in getting Workflow Process.": "Fehler beim Abrufen des Workflow-Prozesses.",
  "Error while saving Form.": "Fehler beim Speichern des Formulars.",
  "Are you sure you wish to delete the form": "Möchten Sie das Formular wirklich löschen?",
  "Are you sure you wish to delete this submission?": "Möchten Sie diesen Beitrag wirklich löschen?",
  "AsCending": "Aufsteigend",
  " Diagram": " Diagramm",
  "Drag and Drop a form component": "Ziehen Sie eine Formularkomponente per Drag-and-Drop",
  "Text Area": "Textbereich",
  "Number": "Anzahl",
  "Password": "Passwort",
  "Checkbox": "Kontrollkästchen",
  "Select Boxes": "Wählen Sie Boxen aus",
  "Radio": "Radio",
  "Button": "Button",
  "Text Area With Analytics": "Textbereich mit Analytics",
  "Data": "Daten",
  "Display": "Anzeige",
  "on": "an",
  "Url": "URL",
  "Phone Number": "Telefonnummer",
  "Tags": "Stichworte",
  "Address": "Adresse",
  "Date / Time": "Terminzeit",
  "Day": "Tag",
  "Time": "Zeit",
  "Currency": "Währung",
  "Survey": "Umfrage",
  "Signature": "Unterschrift",
  "HTML": "HTML",
  "Content": "Inhalt",
  "Columns": "Spalten",
  "Field Set": "Feldsatz",
  "Panel": "Feld",
  "Table": "Tabelle",
  "Tabs": "Registerkarten",
  "Well": "Gut!",
  "Hidden": "Versteckt",
  "Container": "Container",
  "Data Map": "Datenkarte",
  "Data Grid": "Datenraster",
  "Edit Grid": "Raster bearbeiten",
  "Tree": "Baum",
  "reCAPTCHA": "reCaptcha",
  "File": "Datei",
  "Nested": "Verschachtelt",
  "Custom": "Benutzerdefiniert",
  "Basic": "Basic",
  "Advanced": "Fortschrittlich",
  "Layout": "Layout",
  "The minimum length requirement this field must meet.": "Die Mindestlänge, die dieses Feld erfüllen muss.",
  "The label for this field that will appear next to it.": "Die Bezeichnung für dieses Feld, die daneben angezeigt wird.",
  "Label Position": "Bezeichnungsposition",
  "Position for the label for this field.": "Position für die Beschriftung dieses Feldes.",
  "Placeholder": "Platzhalter",
  "The placeholder text that will appear when this field is empty.": "Der Platzhaltertext, der angezeigt wird, wenn dieses Feld leer ist.",
  "The description is text that will appear below the input field.": "Die Beschreibung ist Text, der unter dem Eingabefeld erscheint.",
  "Tooltip": "Kurzinfo",
  "Adds a tooltip to the side of this field.": "Fügt eine Kurzinformation an der Seite dieses Felds hinzu.",
  "To add a tooltip to this field, enter text here.": "Um diesem Feld eine Kurzinformation hinzuzufügen, geben Sie hier Text ein.",
  "Description for this field.": "Beschreibung für dieses Feld.",
  "Prefix": "Präfix",
  "Suffix": "Suffix",
  "Widget": "Widget",
  "The widget is the display UI used to input the value of the field.": "Das Widget ist die Anzeige-UI, die verwendet wird, um den Wert des Felds einzugeben.",
  "Right (Left-aligned)": "Rechts (linksbündig)",
  "Left (Left-aligned)": "Links (linksbündig)",
  "Left (Right-aligned)": "Links (rechtsbündig)",
  "Right (Right-aligned)": "Rechts (rechtsbündig)",
  "Bottom": "Unten",
  "Component": "Komponente",
  "Top": "oben",
  "Label Width": "Beschriftungsbreite",
  "The width of label on line in percentages.": "Die Breite der Beschriftung auf der Linie in Prozent.",
  "Label Margin": "Beschriftungsrand",
  "The width of label margin on line in percentages.": "Die Breite der Beschriftung auf der Linie in Prozent.",
  "Rows": "Reihen",
  "Input Field": "Eingabefeld",
  "Calendar Picker": "Kalenderauswahl",
  "Select a widget": "Wählen Sie ein Widget aus",
  "Input Mask": "Eingabemaske",
  "Widget Settings": "Widget-Einstellungen",
  "Allow Multiple Masks": "Mehrere Masken zulassen",
  "Input Masks": "Eingabemasken",
  "Mask": "Maske",
  "Add Another": "Neue hinzufügen",
  "Custom CSS Class": "Benutzerdefinierte CSS-Klasse",
  "Custom CSS class to add to this component.": "Benutzerdefinierte CSS-Klasse, die dieser Komponente hinzugefügt werden soll.",
  "Tab Index": "Tab-Index",
  "Sets the tabindex attribute of this component to override the tab order of the form. See the MDN documentation on tabindex for more information.": "Legt das tabindex-Attribut dieser Komponente fest, um die Tab-Reihenfolge des Formulars zu überschreiben. Weitere Informationen finden Sie in der MDN-Dokumentation auf tabindex.",
  "Autocomplete": "Automatische Vervollständigung",
  "Indicates whether input elements can by default have their values automatically completed by the browser. See the MDN documentation on autocomplete for more information.": "Gibt an, ob die Werte von Eingabeelementen standardmäßig automatisch vom Browser vervollständigt werden können. Weitere Informationen finden Sie in der MDN-Dokumentation zur automatischen Vervollständigung.",
  "A hidden field is still a part of the form, but is hidden from view.": "Ein ausgeblendetes Feld ist immer noch Teil des Formulars, aber nicht sichtbar.",
  "Hide Label": "Beschriftung ausblenden",
  "Show Word Counter": "Wortzähler anzeigen",
  "Show a live count of the number of words.": "Zeigen Sie eine Live-Zählung der Anzahl der Wörter an.",
  "Hide the label (title, if no label) of this component. This allows you to show the label in the form builder, but not when it is rendered.": "Blenden Sie die Bezeichnung (Titel, falls keine Bezeichnung) dieser Komponente aus. Dadurch können Sie die Beschriftung im Form Builder anzeigen, aber nicht, wenn es gerendert wird.",
  "Show Character Counter": "Zeichenzähler anzeigen",
  "Show a live count of the number of characters.": "Zeigen Sie eine Live-Zählung der Anzahl der Zeichen an.",
  "Hide Input": "Eingabe ausblenden",
  "Hide the input in the browser. This does not encrypt on the server. Do not use for passwords.": "Hide the input in the browser. This does not encrypt on the server. Do not use for passwords.",
  "Initial Focus": "Anfänglicher Fokus",
  "Make this field the initially focused element on this form.": "Machen Sie dieses Feld zum anfänglich fokussierten Element in diesem Formular.",
  "Allow Spellcheck": "Rechtschreibprüfung zulassen",
  "Disabled": "Deaktiviert",
  "Disable the form input.": "Deaktivieren Sie die Formulareingabe.",
  "Table View": "Tabellenansicht",
  "Shows this value within the table view of the submissions.": "Zeigt diesen Wert in der Tabellenansicht der Übermittlungen an.",
  "Modal Edit": "Modale Bearbeitung",
  "Opens up a modal to edit the value of this component.": "Öffnet ein Modal zum Bearbeiten des Werts dieser Komponente.",
  "Multiple Values": "Mehrere Werte",
  "Allows multiple values to be entered for this field.": "Ermöglicht die Eingabe mehrerer Werte für dieses Feld.",
  "Default Value": "Standardwert",
  "The will be the value for this field, before user interaction. Having a default value will override the placeholder text.": "Dies ist der Wert für dieses Feld vor der Benutzerinteraktion. Ein Standardwert überschreibt den Platzhaltertext.",
  "Persistent": "Persistent",
  "A persistent field will be stored in database when the form is submitted.": "Beim Absenden des Formulars wird ein persistentes Feld in der Datenbank gespeichert.",
  "None": "Keiner",
  "Server": "Server",
  "Client": "Kunde",
  "Input Format": "Eingabeformat",
  "Force the output of this field to be sanitized in a specific format.": "Erzwingen Sie, dass die Ausgabe dieses Felds in einem bestimmten Format bereinigt wird.",
  "Plain": "Einfach",
  "Type to search": "Tippe um zu suchen",
  "Raw (Insecure)": "Roh (unsicher)",
  "Protected": "gesichert",
  "A protected field will not be returned when queried via API.": "Ein geschütztes Feld wird nicht zurückgegeben, wenn es über die API abgefragt wird.",
  "Database Index": "Datenbankindex",
  "Set this field as an index within the database. Increases performance for submission queries.": "Legen Sie dieses Feld als Index innerhalb der Datenbank fest. Erhöht die Leistung für Übermittlungsabfragen.",
  "Text Case": "Textfall",
  "When data is entered, you can change the case of the value.": "Wenn Daten eingegeben werden, können Sie die Groß-/Kleinschreibung des Werts ändern.",
  "Mixed (Allow upper and lower case)": "Gemischt (Groß- und Kleinschreibung zulassen)",
  "Uppercase": "Großbuchstaben",
  "Lowercase": "Kleinbuchstaben",
  "Encrypted (Enterprise Only)": "Verschlüsselt (nur Enterprise)",
  "Encrypt this field on the server. This is two way encryption which is not suitable for passwords.": "Verschlüsseln Sie dieses Feld auf dem Server. Dies ist eine Zwei-Wege-Verschlüsselung, die für Passwörter nicht geeignet ist.",
  "Redraw On": "Neuzeichnen an",
  "Redraw this component if another component changes. This is useful if interpolating parts of the component like the label.": "Zeichnen Sie diese Komponente neu, wenn sich eine andere Komponente ändert. Dies ist nützlich, wenn Teile der Komponente wie die Beschriftung interpoliert werden.",
  "Any Change": "Jede Änderung",
  "Clear Value When Hidden": "Wert löschen, wenn ausgeblendet",
  "When a field is hidden, clear the value.": "Wenn ein Feld ausgeblendet ist, löschen Sie den Wert.",
  "The following variables are available in all scripts.": "Die folgenden Variablen sind in allen Skripten verfügbar.",
  "Custom Default Value": "Benutzerdefinierter Standardwert",
  "The complete form JSON object": "Das vollständige Formular-JSON-Objekt",
  "submission": "Einreichung",
  "The complete submission object.": "Das vollständige Einreichungsobjekt.",
  "data": "Daten",
  "The complete submission data object.": "Das vollständige Einreichungsdatenobjekt.",
  "row": "Reihe",
  "Contextual \"row\" data, used within DataGrid, EditGrid, and Container components": "Kontextbezogene „Zeilen“-Daten, die in DataGrid-, EditGrid- und Container-Komponenten verwendet werden",
  "component": "Komponente",
  "The current component JSON": "Die aktuelle Komponenten JSON",
  "instance": "Instanz",
  "The current component instance.": "Die aktuelle Komponenteninstanz.",
  "Value": "Wert",
  "The current value of the component.": "Der aktuelle Wert der Komponente.",
  "moment": "Moment",
  "The moment.js library for date manipulation.": "Die moment.js-Bibliothek zur Datumsmanipulation.",
  "utils": "Dienstprogramme",
  "util": "Dienst",
  "An alias for \"utils\".": "Ein Alias für \"utils\".",
  "JavaScript": "JavaScript",
  "Enter custom javascript code.": "Geben Sie einen benutzerdefinierten Javascript-Code ein.",
  "Example:": "Beispiel:",
  "JSONLogic": "JSON-Logik",
  "Execute custom logic using ": "Führen Sie benutzerdefinierte Logik aus",
  "support is provided using an \"_\" before each operation, such as {\"_sum\": {var: \"data.a\"}}": "Unterstützung wird durch ein \"_\" vor jeder Operation bereitgestellt, z. B. {\"_sum\": {var: \"data.a\"}}",
  "Full": "Voll",
  "Calculated Value": "Berechneter Wert",
  "token": "Zeichen",
  "The decoded JWT token for the authenticated user.": "Das entschlüsselte JWT-Token für den authentifizierten Benutzer.",
  "Calculate Value on server": "Wert auf dem Server berechnen",
  "Checking this will run the calculation on the server. This is useful if you wish to override the values submitted with the calculations performed on the server.": "Wenn Sie dies aktivieren, wird die Berechnung auf dem Server ausgeführt. Dies ist nützlich, wenn Sie die übermittelten Werte mit den auf dem Server durchgeführten Berechnungen überschreiben möchten.",
  "Allow Manual Override of Calculated Value": "Manuelles Überschreiben des berechneten Werts zulassen",
  "When checked, this will allow the user to manually override the calculated value.": "Wenn diese Option aktiviert ist, kann der Benutzer den berechneten Wert manuell überschreiben.",
  "Remove": "Entfernen",
  "Validate On": "Validierung ein",
  "Determines when this component should trigger front-end validation.": "Legt fest, wann diese Komponente die Front-End-Validierung auslösen soll.",
  "Change": "Ändern",
  "Blur": "Verwischen",
  "Required": "Erforderlich",
  "A required field must be filled in before the form can be submitted.": "Ein Pflichtfeld muss ausgefüllt werden, bevor das Formular abgeschickt werden kann..",
  "Unique": "Einzigartig",
  "Makes sure the data submitted for this field is unique, and has not been submitted before.": "Stellt sicher, dass die für dieses Feld übermittelten Daten einzigartig sind und noch nie zuvor übermittelt wurden.",
  "Minimum Length": "Minimale Länge",
  "The maximum length requirement this field must meet.": "Die maximale Länge, die dieses Feld erfüllen muss.",
  "Maximum Length": "Maximale Länge",
  "Minimum Word Length": "Minimale Wortlänge",
  "The minimum amount of words that can be added to this field.": "Die Mindestanzahl an Wörtern, die diesem Feld hinzugefügt werden können.",
  "Maximum Word Length": "Maximale Wortlänge",
  "The maximum amount of words that can be added to this field.": "Die maximale Anzahl an Wörtern, die diesem Feld hinzugefügt werden können.",
  "Regular Expression Pattern": "Reguläres Ausdrucksmuster",
  "The regular expression pattern test that the field value must pass before the form can be submitted.": "Der Mustertest für reguläre Ausdrücke, den der Feldwert bestehen muss, bevor das Formular gesendet werden kann.",
  "Error Label": "Fehlerbeschriftung",
  "The label for this field when an error occurs.": "Die Bezeichnung für dieses Feld, wenn ein Fehler auftritt.",
  "Custom Error Message": "Benutzerdefinierte Fehlermeldung",
  "Error message displayed if any error occurred.": "Fehlermeldung, die angezeigt wird, wenn ein Fehler aufgetreten ist.",
  "Custom Validation": "Benutzerdefinierte Validierung",
  "input": "Eingabe",
  "The value that was input into this component": "Der Wert, der in diese Komponente eingegeben wurde",
  "Enter custom validation code.": "Geben Sie einen benutzerdefinierten Validierungscode ein.",
  "You must assign the valid variable as either true or an error message if validation fails.": "Sie müssen die gültige Variable entweder als wahr oder als Fehlermeldung zuweisen, wenn die Validierung fehlschlägt.",
  "Secret Validation": "Geheime Validierung",
  "Check this if you wish to perform the validation ONLY on the server side. This keeps your validation logic private and secret.": "Aktivieren Sie dies, wenn Sie die Validierung NUR serverseitig durchführen möchten. Dadurch bleibt Ihre Validierungslogik privat und geheim.",
  "JSONLogic Validation": "JSON-Logik-Validierung",
  "Execute custom logic using": "Führen Sie benutzerdefinierte Logik mit aus",
  "Validation": "Validierung",
  "API": "API",
  "Property Name": "Eigenschaftsname",
  "The name of this field in the API endpoint.": "Der Name dieses Felds im API-Endpunkt.",
  "Field Tags": "Feldstichworte",
  "Tag the field for use in custom logic.": "Stichwort des Felds für benutzerdefinierte Logik",
  "Custom Properties": "Benutzerdefinierte Eigenschaften",
  "This allows you to configure any custom properties for this component.": "Auf diese Weise können Sie beliebige benutzerdefinierte Eigenschaften für diese Komponente konfigurieren.",
  "Conditional": "Bedingt",
  "Simple": "Einfach",
  "This component should Display:": "Diese Komponente sollte Folgendes anzeigen:",
  "True": "Wahr",
  "False": "Falsch",
  "When the form component:": "Wenn die Formularkomponente:",
  "Submit (submit)": "Absenden (submit)",
  "Has the value:": "Hat den Wert:：",
  "Advanced Conditions": "Erweiterte Bedingungen",
  "Advanced Logic": "Erweiterte Logik",
  "Advanced Logic Configured": "Erweiterte Logik konfiguriert",
  "Logic": "Logik",
  "Add Logic": "Logik hinzufügen",
  "Trigger": "Auslöser",
  "JSON Logic": "JSON-Logik",
  "\"row\", \"data\", and \"component\" variables are available. Return \"result\".": "Die Variablen \"row\", \"data\" und \"component\" sind verfügbar. Geben Sie \"result\" zurück.",
  "Action Name": "Aktionsname",
  "Schema Defenition": "Schema-Definition",
  "\"row\", \"data\", \"component\", and \"result\" variables are available. Return the schema.": "Die Variablen \"row\", \"data\", \"component\" und \"result\" sind verfügbar. Geben Sie das Schema zurück.",
  "Merge Component Schema": "Komponentenschema zusammenführen",
  "Custom Action": "Benutzerdefinierte Aktion",
  "You must assign the show variable a boolean result.": "Sie müssen der Show-Variablen ein boolesches Ergebnis zuweisen.",
  "Note: Advanced Conditional logic will override the results of the Simple Conditional logic.": "Hinweis: Die erweiterte bedingte Logik überschreibt die Ergebnisse der einfachen bedingten Logik.",
  "\"row\", \"data\", \"component\" and \"_\" variables are available. Return the result to be passed to the action if truthy.": "Die Variablen \"row\", \"data\", \"component\" und \"_\" sind verfügbar. Gibt das an die Aktion zu übergebende Ergebnis zurück, wenn es wahr ist.",
  "Add Action": "Aktion hinzufügen",
  "Save Logic": "Logik speichern",
  "Logic Name": "Logikname",
  "Event": "Ereignis",
  "The event that will trigger this logic. You can trigger events externally or via a button.": "Das Ereignis, das diese Logik auslöst. Sie können Ereignisse extern oder über eine Schaltfläche auslösen.",
  "Save Action": "Aktion speichern",
  "HTML Attributes": "HTML-Attribute",
  "Attribute Name": "Attributname",
  "Attribute Value": "Attributwert",
  "Add Attribute": "Attribute hinzufügen",
  "The settings inside apply only to the PDF forms.": "Die darin enthaltenen Einstellungen gelten nur für die PDF-Formulare.",
  "PDF Overlay": "PDF-Überlagerung",
  "Style": "Stil",
  "Custom styles that should be applied to this component when rendered in PDF.": "Benutzerdefinierte Stile, die auf diese Komponente angewendet werden sollen, wenn sie in PDF gerendert werden.",
  "Page": "Seite",
  "The PDF page to place this component.": "Die PDF-Seite zum Platzieren dieser Komponente.",
  "Left": "Links",
  "The left margin within a page to place this component.": "Der linke Rand innerhalb einer Seite, um diese Komponente zu platzieren.",
  "The top margin within a page to place this component.": "Der obere Rand innerhalb einer Seite, um diese Komponente zu platzieren.",
  "Width": "Breite",
  "The width of the component (in pixels).": "Die Breite der Komponente (in Pixel).",
  "Height": "Höhe",
  "The height of the component (in pixels).": "Die Höhe der Komponente (in Pixel).",
  "Use Thousands Separator": "Verwenden Sie das Tausendertrennzeichen",
  "Separate thousands by local delimiter.": "Trennen Sie Tausender durch lokales Trennzeichen.",
  "Decimal Places": "Nachkommastellen",
  "The maximum number of decimal places.": "Die maximale Anzahl von Dezimalstellen.",
  "Require Decimal": "Dezimalzahl erforderlich",
  "Always show decimals, even if trailing zeros.": "Dezimalstellen immer anzeigen, auch bei nachgestellten Nullen.",
  "Minimum Value": "Mindestwert",
  "The minimum value this field must have before the form can be submitted.": "Der Mindestwert, den dieses Feld haben muss, bevor das Formular gesendet werden kann.",
  "Maximum Value": "Maximaler Wert",
  "The maximum value this field can have before the form can be submitted.": "Der maximale Wert, den dieses Feld haben kann, bevor das Formular gesendet werden kann.",
  "Editor": "Editor",
  "Select the type of WYSIWYG editor to use for this text area.": "Wählen Sie den Typ des WYSIWYG-Editors aus, der für diesen Textbereich verwendet werden soll.",
  "ACE": "ACE",
  "Save As": "Speichern als",
  "This setting determines how the value should be entered and stored in the database.": "Diese Einstellung legt fest, wie der Wert eingegeben und in der Datenbank gespeichert werden soll.",
  "String": "String",
  "JSON": "JSON",
  "Input Type": "Eingabetyp",
  "This is the input type used for this checkbox.": "Dies ist der Eingabetyp, der für dieses Kontrollkästchen verwendet wird.",
  "Shortcut": "Abkürzung",
  "Shortcut for this component.": "Abkürzung für diese Komponente.",
  "Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API.": "Passwortfelder werden automatisch mit 1-Way-Salted-Bcrypt-Hashes verschlüsselt. Diese Hashes sind ebenfalls geschützt und werden nicht in der API zurückgegeben.",
  "Options Label Position": "Position der Optionsbeschriftung",
  "Position for the label for options for this field.": "Position für die Bezeichnung für Optionen für dieses Feld.",
  "Right": "Rechts",
  "Inline Layout": "Inline Layout",
  "Displays the checkboxes/radios horizontally.": "Zeigt die Kontrollkästchen/Radios horizontal an.",
  "Allow only available values": "Nur verfügbare Werte zulassen",
  "Minimum checked number": "Mindest ausgewählte Anzahl",
  "Minimum checkboxes required before form can be submitted.": "Mindestens Kontrollkästchen erforderlich, bevor das Formular gesendet werden kann.",
  "Maximum checked number": "Maximal ausgewählte Anzahl",
  "Maximum checkboxes possible before form can be submitted.": "Maximale Anzahl der möglichen Kontrollkästchen, bevor das Formular gesendet werden kann.",
  "Minimum checked error message": "Minimum geprüfte Fehlermeldung",
  "Error message displayed if minimum number of items not checked.": "Fehlermeldung wird angezeigt, wenn die Mindestanzahl von Artikeln nicht angekreuzt ist.",
  "Maximum checked error message": "Maximal überprüfte Fehlermeldung",
  "Error message displayed if maximum number of items checked.": "Fehlermeldung wird angezeigt, wenn die maximale Anzahl von Elementen überprüft wird.",
  "ChoicesJS": "ChoicesJS",
  "HTML 5": "HTML55",
  "Unique Options": "Einzigartige Optionens",
  "Display only unique dropdown options.": "Nur einzigartige Dropdown-Optionen anzeigen",
  "Data Source Type": "Datenquellentyp",
  "The source to use for the select data. Values lets you provide your own values and labels. JSON lets you provide raw JSON data. URL lets you provide a URL to retrieve the JSON data from.": "Die Quelle, die für die ausgewählten Daten verwendet werden soll. Mit Werte können Sie Ihre eigenen Werte und Labels bereitstellen. Mit JSON können Sie JSON-Rohdaten bereitstellen. Mit URL können Sie eine URL angeben, von der die JSON-Daten abgerufen werden.",
  "Values": "Werte",
  "Raw JSON": "Rohes JSON",
  "IndexedDB": "IndexedDB",
  "Database name": "Name der Datenbank",
  "The name of the indexeddb database.": "Der Name der Indexeddb-Datenbank.",
  "Storage Type": "Speichertyp",
  "The type to store the data. If you select something other than autotype, it will force it to that type.": "Der Typ zum Speichern der Daten. Wenn Sie etwas anderes als Autotyp auswählen, wird dieser Typ erzwungen.",
  "Autotype": "Autotyp",
  "Boolean": "Boolesch",
  "Object": "Objekt",
  "ID Path": "ID-Pfad",
  "Path to the select option id.": "Pfad zur ausgewählten Options-ID.",
  "Table name": "Tabellenname",
  "The name of table in the indexeddb database.": "Der Name der Tabelle in der Indexeddb-Datenbank.",
  "Row Filter": "Zeilenfilter",
  "Filter table items that match the object.": "Filtern Sie Tabellenelemente, die mit dem Objekt übereinstimmen.",
  "Item Template": "Elementvorlage",
  "The HTML template for the result data items.": "Die HTML-Vorlage für die Ergebnisdatenelemente.",
  "Enable Static Search ": "Statische Suche aktivieren",
  "When checked, the select dropdown will allow for searching within the static list of items provided.": "Wenn diese Option aktiviert ist, ermöglicht die Auswahl-Dropdown-Liste die Suche in der statischen Liste der bereitgestellten Elemente.",
  "Search Threshold": "Suchschwelle",
  "At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match, a threshold of 1.0 would match anything.": "An welchem Punkt gibt der Match-Algorithmus auf? Ein Schwellenwert von 0,0 erfordert eine perfekte Übereinstimmung, ein Schwellenwert von 1,0 würde alles abgleichen.",
  "Read Only Value": "Schreibgeschützter Wert",
  "Check this if you would like to show just the value when in Read Only mode.": "Aktivieren Sie dies, wenn Sie im schreibgeschützten Modus nur den Wert anzeigen möchten.",
  "Choices.js options": "Choices.js-Optionen",
  "A raw JSON object to use as options for the Select component (Choices JS).": "Ein rohes JSON-Objekt, das als Optionen für die Select-Komponente (Choices JS) verwendet werden soll.",
  "Use exact search": "Verwenden Sie die exakte Suche",
  "Disables search algorithm threshold.": "Deaktiviert den Schwellenwert für den Suchalgorithmus.",
  "Theme": "Thema",
  "The color theme of this button.": "Das Farbthema dieser Schaltfläche.",
  "Size": "Größe",
  "The size of this button": "Die Größe dieser Schaltfläche",
  "Block Button": "Sperrtaste",
  "This control should span the full width of the bounding container.": "Dieses Steuerelement sollte sich über die gesamte Breite des Begrenzungscontainers erstrecken.",
  "Left Icon": "Linkes Symbol",
  "This is the full icon class string to show the icon.": "Dies ist die vollständige Symbolklassenzeichenfolge zum Anzeigen des Symbols.",
  "Right Icon": "Rechtes Symbol",
  "This is the full icon class string to show the icon. Example:": "Dies ist die vollständige Symbolklassenzeichenfolge zum Anzeigen des Symbols. Beispiel:",
  "Primary": "Primär",
  "Secondary": "Sekundär",
  "Info": "Info",
  "Danger": "Achtung",
  "Warning": "Warnung",
  "The size of this button.": "Die Größe dieser Schaltfläche.",
  "Medium": "Mittel",
  "Extra Small": "Extra klein",
  "Small": "Klein",
  "Large": "Groß",
  "Disable on Form Invalid": "Deaktivieren bei ungültigem Formular",
  "This will disable this field if the form is invalid.": "Dadurch wird dieses Feld deaktiviert, wenn das Formular ungültig ist.",
  "Key topics for Sentiment Analysis": "Schlüsselthemen für die Stimmungsanalyse",
  "Enter topics to use in sentiment Analysis": "Geben Sie Themen ein, die in der Stimmungsanalyse verwendet werden sollen",
  "Kickbox": "Kick-Box",
  "Enable": "Aktivierenr",
  "Enable Kickbox validation for this email field.": "Kickbox-Validierung für dieses E-Mail-Feld aktivieren.",
  "Validate this email using the Kickbox email validation service.": "Validieren Sie diese E-Mail mit dem Kickbox-E-Mail-Validierungsdienst.",
  "Input Mask Placeholder Char": "Eingabemaske Platzhalterzeichen",
  "Enable Manual Mode": "Manuellen Modus aktivieren",
  "Should Manual Mode be enabled for that component or not.": "Soll der manuelle Modus für diese Komponente aktiviert sein oder nicht.",
  "Switch To Manual Mode Label": "Wechseln Sie zur Beschriftung für den manuellen Modus",
  "The label for the checkbox used to switch to manual mode.": "Die Bezeichnung für das Kontrollkästchen zum Umschalten in den manuellen Modus.",
  "Disable Clear Icon": "Deaktivieren Sie das Löschsymbol",
  "Clear Icon allows easily clear components value.": "Löschsymbol ermöglicht das einfache Löschen des Komponentenwerts.",
  "Provider": "Anbieter",
  "Which address search service should be used.": "Welcher Adresssuchdienst soll verwendet werden.",
  "Manual Mode View String": "Zeichenfolge für die Ansicht im manuellen Modus",
  "Specify template which should be when quering view string for the component value entered in manual mode. This string is used in table view, CSV export and email rendering. When left blank combined value of all components joined with comma will be used.": "Geben Sie die Vorlage an, die beim Abfragen der Ansichtszeichenfolge für den im manuellen Modus eingegebenen Komponentenwert verwendet werden soll. Diese Zeichenfolge wird in der Tabellenansicht, beim CSV-Export und beim Rendern von E-Mails verwendet. Wenn das Feld leer gelassen wird, wird der kombinierte Wert aller mit Komma verbundenen Komponenten verwendet.",
  "Azure Maps": "Azure-Karten",
  "Google Maps": "Google Maps",
  "API Key": "API-Schlüssel",
  "Use your Google API key here.": "Verwenden Sie hier Ihren Google-API-Schlüssel.",
  "Provider options": "Anbieteroptionen",
  "Delimiter": "Trennzeichen",
  "What is used to separate the tags.": "Was wird verwendet, um die Tags zu trennen.",
  "Max Tags": "Max-Tags",
  "The maximum amount of tags that can be added. 0 for infinity.": "Die maximale Anzahl an Tags, die hinzugefügt werden können. 0 für unendlich.",
  "Store As": "Speichern als",
  "String (CSV)": "Zeichenfolge (CSV)",
  "Array of Tags": "Array von Tags",
  "Display in Timezone": "Anzeige in Zeitzone",
  "This will display the captured date time in the select timezone.": "Dadurch wird die erfasste Datumszeit in der ausgewählten Zeitzone angezeigt.",
  "of Viewer": "des Betrachters",
  "of Submission": "der Einreichung",
  "of Location": "des Standorts",
  "UTC": "UTC",
  "Use Locale Settings": "Verwenden Sie Gebietsschemaeinstellungen",
  "Use locale settings to display date and time.": "Verwenden Sie Gebietsschemaeinstellungen, um Datum und Uhrzeit anzuzeigen.",
  "Allow Manual Input": "Manuelle Eingabe zulassen",
  "Check this if you would like to allow the user to manually enter in the date.": "Aktivieren Sie dies, wenn Sie dem Benutzer erlauben möchten, das Datum manuell einzugeben.",
  "Format": "Format",
  "The date format for displaying the datetime value.": "Das Datumsformat zum Anzeigen des datetime-Werts.",
  "Shortcut Buttons": "Shortcut-Schaltflächen",
  "You can specify few buttons which will be shown above the calendar. Use Label to specify the name of the button and onClick to specify which date/time will be set when user clicks the button. ": "Sie können einige Schaltflächen angeben, die über dem Kalender angezeigt werden. Verwenden Sie Label, um den Namen der Schaltfläche anzugeben, und onClick, um anzugeben, welches Datum/welche Uhrzeit festgelegt wird, wenn der Benutzer auf die Schaltfläche klickt.",
  "onClick": "onClick",
  "Enable Date Input": "Datumseingabe aktivieren",
  "Enables date input for this field.": "Aktiviert die Datumseingabe für dieses Feld.",
  "Use Input to add moment.js for minDate": "Verwenden Sie Input, um moment.js für minDate hinzuzufügen",
  "Enables to use input for moment functions instead of calendar.": "Ermöglicht die Verwendung von Eingaben für Momentfunktionen anstelle des Kalenders.",
  "Use calendar to set minDate": "Verwenden Sie den Kalender, um minDate festzulegen",
  "Enables to use calendar to set date.": "Ermöglicht die Verwendung des Kalenders zum Festlegen des Datums.",
  "Use Input to add moment.js for maxDate": "Verwenden Sie Input, um moment.js für maxDate hinzuzufügen",
  "Use calendar to set maxDate": "Verwenden Sie den Kalender, um maxDate festzulegen",
  "Disable specific dates or dates by range": "Deaktivieren Sie bestimmte Daten oder Daten nach Bereich",
  "Add dates that you want to blacklist. For example:": "Fügen Sie Daten hinzu, die Sie auf die schwarze Liste setzen möchten. Zum Beispiel:",
  "Custom Disabled Dates": "Benutzerdefinierte deaktivierte Daten",
  "date": "Datum",
  "The date object.": "Das Datumsobjekt.",
  "Data Format": "Dateiformat",
  "The moment.js format for saving the value of this field.": "Das moment.js-Format zum Speichern des Werts dieses Felds.",
  "HTML5 Time Input": "HTML5-Zeiteingabe",
  "Text Input with Mask": "Texteingabe mit Maske",
  "Disable weekends": "Wochenenden deaktivieren",
  "Disable weekdays": "Wochentage deaktivieren",
  "Check to disable weekends": "Aktivieren Sie diese Option, um Wochendtage zu deaktivieren",
  "Check to disable weekdays": "Aktivieren Sie diese Option, um Wochentage zu deaktivieren",
  "Enable Time Input": "Zeiteingabe aktivieren",
  "Enables time input for this field": "Aktiviert die Zeiteingabe für dieses Feld",
  "Hour Step Size": "Stundenschrittgröße",
  "The number of hours to increment/decrement in the time picker.": "Die Anzahl der Stunden, um die in der Zeitauswahl erhöht/verringert werden soll.",
  "Minute Step Size": "Minute Schrittgröße",
  "The number of minutes to increment/decrement in the time picker.": "Die Anzahl der Minuten, um die in der Zeitauswahl erhöht/verringert werden soll.",
  "Display time in 12 hour time with AM/PM.": "Anzeigezeit im 12-Stunden-Format mit AM/PM.",
  "12 Hour Time (AM/PM)": "12-Stunden-Zeit (AM/PM)",
  "Default Date": "Standarddatum",
  "You can use Moment.js functions to set the default value to a specific date. For example:": "Sie können moment.js-Funktionen verwenden, um den Standardwert auf ein bestimmtes Datum festzulegen. Zum Beispiel:",
  "Flatpickr options": "Flatpickr-Optionen",
  "HTML Tag": "HTML-Tag",
  "The tag of this HTML element.": "Das Tag dieses HTML-Elements.",
  "CSS Class": "CSS-Klasse",
  "Attributes": "Attribute",
  "The attributes for this HTML element. Only safe attributes are allowed, such as src, href, and title.": "Die Attribute für dieses HTML-Element. Nur sichere Attribute sind erlaubt, wie src, href und title.",
  "Attribute": "Attribut",
  "Refresh On Change": "Bei Änderung aktualisieren",
  "HTML Element": "HTML-Element",
  "Column Properties": "Spalteneigenschaften",
  "The width, offset, push, and pull settings for each column.": "Die Einstellungen für Breite, Offset, Push und Pull für jede Spalte.",
  "Offset": "Versatz",
  "Push": "Drücken",
  "Pull": "Ziehen",
  "Auto adjust columns": "Spalten automatisch anpassen",
  "Will automatically adjust columns based on if nested components are hidden.": "Passt Spalten automatisch an, je nachdem, ob verschachtelte Komponenten ausgeblendet sind.",
  "Hide Column when Children Hidden": "Spalte ausblenden, wenn untergeordnete Elemente ausgeblendet sind",
  "Check this if you would like to hide any column when the children within that column are also hidden": "Aktivieren Sie dies, wenn Sie eine Spalte ausblenden möchten, wenn die untergeordneten Elemente in dieser Spalte ebenfalls ausgeblendet sind",
  "Legend": "Legende",
  "The legend for this Fieldset.": "Die Legende für dieses Fieldset.",
  "Default": "Standard",
  "Collapsible": "zusammenklappbar",
  "If checked, this will turn this Panel into a collapsible panel.": "Wenn diese Option aktiviert ist, wird dieses Panel zu einem zusammenklappbaren Panel.",
  "Number of Rows": "anzahl der Zeilen",
  "Enter the number or rows that should be displayed by this table.": "Geben Sie die Anzahl oder Zeilen ein, die von dieser Tabelle angezeigt werden sollen.",
  "Number of Columns": "Anzahl der Spalten",
  "Enter the number or columns that should be displayed by this table.": "Geben Sie die Anzahl oder Spalten ein, die von dieser Tabelle angezeigt werden sollen.",
  "Clone Row Components": "Linienkomponenten klonen",
  "Check this if you would like to": "Überprüfen Sie dies, wenn Sie möchten",
  "Cell Alignment": "Zellausrichtung",
  "Horizontal alignment for cells of the table.": "Horizontale Ausrichtung für Zellen der Tabelle.",
  "Center": "Zentriert",
  "Striped": "Gestreift",
  "This will stripe the table if checked.": "Wenn dies aktiviert ist, wird die Tabelle gestreift.",
  "Bordered": "Abgegrenzt",
  "This will border the table if checked.": "Wenn dies aktiviert ist, wird die Tabelle umrandet.",
  "Hover": "Hover",
  "Highlight a row on hover.": "Markieren Sie eine Zeile beim Hover.",
  "Condensed": "Zusammengefasst",
  "Condense the size of the table.": "Fassen Sie die Größe der Tabelle zusammen.",
  "Label for Key column": "Beschriftung für die Schlüsselspalte",
  "Provide a label text for Key column (otherwise Key will be used)": "Geben Sie einen Beschriftungstext für die Schlüsselspalte an (andernfalls wird der Schlüssel verwendet)",
  "Disable Adding / Removing Rows": "Deaktivieren Sie das Hinzufügen/Entfernen von Zeilen",
  "Check if you want to hide Add Another button and Remove Row button": "Stellen Sie sicher, dass Sie die Schaltflächen „Andere hinzufügen“ und „Zeile entfernen“ ausblenden möchten",
  "Show key column before value": "Schlüsselspalte vor Wert anzeigen",
  "Check if you would like to show the Key before the Value column.": "Aktivieren Sie, ob Sie den Schlüssel vor der Spalte Wert anzeigen möchten.",
  "Type of event": "Ereignistyp",
  "Specify type of event that this reCAPTCHA would react to": "Geben Sie den Ereignistyp an, auf den dieses reCAPTCHA reagieren würde",
  "Form Load": "Formular laden",
  "Button Click": "Schaltfläche Klicken",
  "The form to load within this form component.": "Das Formular, das in diese Formularkomponente geladen werden soll.",
  "Form Revision": "Formularüberarbeitung",
  "You can lock the nested form to a specific revision by entering the revision number here.": "Sie können das verschachtelte Formular für eine bestimmte Revision sperren, indem Sie hier die Revisionsnummer eingeben.",
  "Use Original Revision while Submissions Viewing": "Verwenden Sie die Originalbewertung, wenn Sie sich Einsendungen ansehen",
  "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission.": "Wenn Sie diese Option verwenden, lädt das Formular beim Anzeigen einer Einreichung die ursprüngliche Revision (die zum Erstellen einer Einreichung verwendet wurde).",
  "Save as reference": "Als Referenz speichern",
  "Using this option will save this field as a reference and link its value to the value of the origin record.": "Mit dieser Option wird dieses Feld als Referenz gespeichert und sein Wert mit dem Wert des Quelldatensatzes verknüpft.",
  "Select Fields": "Felder auswählen",
  "The properties on the resource to return as part of the options. If left blank, all properties will be returned.": "Die Eigenschaften der Ressource, die als Teil der Optionen zurückgegeben werden sollen. Wenn das Feld leer gelassen wird, werden alle Eigenschaften zurückgegeben.",
  "Search Fields": "Suchfelder",
  "Filter Query": "Filterabfrage",
  "Use this to provide additional filtering using query parameters.": "Verwenden Sie dies, um eine zusätzliche Filterung mithilfe von Abfrageparametern bereitzustellen.",
  "The filter query for results.": "Die Filterabfrage für Ergebnisse.",
  "Sort Query": "Abfrage sortieren",
  "Use this to provide additional sorting using query parameters": "Verwenden Sie dies, um eine zusätzliche Sortierung mithilfe von Abfrageparametern bereitzustellen",
  "The sort query for results": "Die Sortierabfrage für Ergebnisse",
  "Add Resource": "Ressource hinzufügen",
  "Allows to create a new resource while entering a submission.": "Ermöglicht das Erstellen einer neuen Ressource während der Eingabe einer Einreichung.",
  "Add Resource Label": "Ressourcenbezeichnung hinzufügen",
  "Set the text of the Add Resource button.": "Legen Sie den Text für die Funktionsschaltfläche hinzufügen fest.",
  "Auto Expand": "Automatisch erweitern",
  "Diagram Deployed": "Diagramm bereitgestellt",
  "Deployment Failed": "Bereitstellung fehlgeschlagen",
  "Unfinished Submissions will be saved to Submissions/Drafts.": "Unvollständige Einreichungen werden in Einreichungen/Entwürfe gespeichert.",
  "Changing the form workflow will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Die Änderung des Formular-Workflows wird die bestehenden Einreichungen nicht beeinflussen. Es wird nur in den neu erstellten Einreichungen aktualisiert. Drücken Sie Speichern Sie die Änderungen, um fortzufahren oder die Änderungen abzubrechen.",
  "Submissions are made against": "Einreichungen werden gemacht gegen",
  "Submission is made against": "Einreichung wird gemacht gegen",
  "Changing the form title will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Die Änderung des Formulartitels wird die bestehenden Einreichungen nicht beeinflussen. Es wird nur in den neu erstellten Einreichungen aktualisiert. Drücken Sie Speichern Sie die Änderungen, um fortzufahren oder die Änderungen abzubrechen.",
  "No submissions Found": "Keine Einreichungen gefunden",
  "Asignee": "Bevollmächtigter",
  "Include Assigned Task": "Zugewiesene Aufgabe einschließen",
  "Variable": "Variable",
  "Name of variable": "Name der Variablen",
  "Readable name": "Lesbarer Name",
  "Specific User/ Group": "Bestimmter Benutzer/Gruppe",
  "User": "Benutzer",
  "Identifier": "Kennung",
  "Enter role ID": "Geben Sie die Rollen-ID ein",
  "Select a task in the List": "Wählen Sie eine Aufgabe in der Liste aus",
  "Select a specific task from the provided list of options. Your selection will determine the task you will be working on or interacting with.": "Wählen Sie eine bestimmte Aufgabe aus der bereitgestellten Optionsliste aus. Ihre Auswahl bestimmt die Aufgabe, an der Sie arbeiten oder mit der Sie interagieren."
}
