name: Build and push artifacts to s3
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "forms-flow-nav/**"
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
        working-directory: ./forms-flow-nav
      - run: npm run build:webpack
        working-directory: ./forms-flow-nav
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
          aws-bucket: ${{ secrets.BUCKET }}
      - run: npm ci
        working-directory: ./scripts
      - run: node index forms-flow-nav
        working-directory: ./scripts
