name: Build and push artifacts to s3
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "forms-flow-nav/**"
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
        working-directory: ./forms-flow-nav
      - run: npm run build:webpack
        working-directory: ./forms-flow-nav
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: ${{secrets.BUCKET}}
          REGION: ${{secrets.REGION}}
      - run: npm ci
        working-directory: ./scripts
      - run: node index forms-flow-nav
        working-directory: ./scripts
        
      