name: forms-flow-components-CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - release/*
    paths:
      - "forms-flow-components/**"
      - "VERSION"
  push:
    branches:
      - main
      - develop
      - release/*
    paths:
      - "forms-flow-components/**"
      - "VERSION"
defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-components
jobs:
  Forms-Flow-Components-CI:
    name: Run Tests and Lint Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'
      - name: Install dependencies
        run: |
          npm ci --force
      - name: Run Tests
        run: |
          npm run test
