name: PR Notification to Google Chat

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.repository == 'AOT-Technologies/forms-flow-ai-micro-front-ends'

    steps:
      - name: Send notification to Google Chat
        uses: fjogeleit/http-request-action@v1.1.0
        with:
          url: ${{ secrets.WEBHOOK }}
          method: POST
          contentType: application/json
          data: '{
            "cards": [
              {
                "header": {
                  "title": "Micro front-ends: Pull Request Opened by ${{ github.event.pull_request.user.login }}",
                  "subtitle": "Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}",
                  "imageUrl": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "textParagraph": {
                          "text": "Repository: ${{ github.repository }}"
                        }
                      },
                      {
                        "textParagraph": {
                          "text": "Status: ${{ github.event.action == 'opened' ? '🟢 Open' : github.event.action == 'closed' ? '🔴 Closed' : '🟣 Merged' }}"
                        }
                      },
                      {
                        "buttons": [
                          {
                            "textButton": {
                              "text": "View Pull Request",
                              "onClick": {
                                "openLink": {
                                  "url": "${{ github.event.pull_request.html_url }}"
                                }
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }'
