name: PR Review Agent

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - develop
      - main
      - release/**
  issue_comment:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    if: |
      (github.event_name == 'pull_request_target') || 
      (github.event_name == 'issue_comment' && github.event.sender.type != 'Bot')
    runs-on: ubuntu-latest
    name: Run PR Agent on every PR event or issue comment
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action_config.auto_review: "true" # enable\disable auto review
          github_action_config.auto_describe: "true" # enable\disable auto describe
          github_action_config.auto_improve: "true" # enable\disable auto improve
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested", "synchronize"]'
