/* eslint-disable max-len */
//Bulgarian
export const RESOURCE_BUNDLES_BG = {
  "Latest Submission": "Последно подаване",
  "Filter Created by": "Филтър Създаден от",
  "Submit Form": "Изпращане на Формуляр",
  "Changes Applied Successfully": "Промените са успешно приложени",
  "Filter Deleted Successfully": "Филтърът е успешно изтрит",
  "Save Filter": "Запази Филтър",
  "Filter Name": "Име на филтъра",
  "Create new filter": "Създайте нов филтър",
  "Definition Key": "Ключ за дефиниция",
  "Permission": "разрешение",
  "Enter your text here": "Въведете своя текст тук",
  "Accessible for all users": "Достъпен за всички потребители",
  "Private (Only You)": "Лично (само ти)",
  "Specific Group": "Конкретна Група",
  "Select Elements": "Изберете Елементи",
  " Task Attributes Selected": " Избрани Атрибути на Задачата",
  "Delete Filter": "Изтрийте Филтър",
  "Add Value": "Добави стойност",
  "Show only current user assigned task": "Показване само на задачите, възложени на текущия потребител",
  "Show task based on logged user roles": "Показване на задачи въз основа на ролите на влезналия потребител",
  "Create Filter": "Създаване на филтър",
  "Task Attributes": "Атрибути на Задачата",
  "Only selected task attributes will be available on task list view": "Само избраните атрибути на задачата ще бъдат достъпни в изгледа на списъка със задачи",
  "Show undefined variables": "Показване на недефинирани променливи",
  "Label": "Етикет",
  "Variables": "Променливи",
  "Task Title": "Заглавие на Задачата",
  "List View": "Преглед в списък",
  "Card View": "Преглед на карти",
  "Create New Filter": "Създай нов филтър",
  "Sort by": "Сортирай по",
  "Collapse All": "Свий всичко",
  "Expand All": "Разшири всичко",
  "Application Id": "Идентификационен номер на заявлението",
  "Back to task": "Назад към задачата",
  "Filters": "Филтри",
  "Assignee": "Цесионер",
  "Select a user": "Изберете потребител",
  "Create DMN": "Създайте DMN",
  "Create Process": "Създайте процес",
  "Edit DMN": "Редактиране на DMN",
  "More options": "Повече опции",
  "Form Description": "Описание на формуляра",
  "Saved to Submissions/Drafts": "Запазено в Подавания/Чернови",
  "Unfinished submissions will be saved to Submissions/Drafts.": "Незавършените представяния ще бъдат запазени в Представяния/Чернови.",
  "Edit Process": "Редактиране на процеса",
  "Add filter name": "Добави име на филтър",
  "This section is aimed to set the parameters\nused to filter the tasks": "Този раздел има за цел да зададе параметрите,\nизползвани за филтриране на задачите",
  "This section is aimed to set read\npermissions for the filter": "Този раздел има за цел да зададе\nправата за четене на филтъра",
  "This section is aimed to set select\ntask attributes that will be visible in\nthe task list view": "Този раздел има за цел да\nзададе избраните атрибути на\nзадачата, които ще бъдатвидими\nв изгледа на списъка с задачи",
  "Task Attribute": "Атрибут на задачата",
  "You can define variables shown in the list": "Можете да дефинирате променливи, показани в списъка",
  "results": "pезултати",
  "Enter role name": "Въведете името на ролята",
  "Public": "Публичен",
  "View Submitted Form": "Преглед на представен формуляр",
  "View Draft Details": "Преглед на детайлите на черновата",
  "Edit Draft": "Редактиране на черновата",
  "Draft Title": "Заглавие на черновата",
  "Filter": "Филтър",
  "Advanced Options": "Разширени опции",
  "Enter the path name": "Въведете името на пътя",
  "Search by form title": "Търсене по заглавие на формуляра",
  "Associate Workflow": "Свързване с работен процес",
  "Search by workflow name": "Търсене по име на работен процес",
  "View Details": "Преглед на детайлите",
  "Visibility": "Видимост",
  "Form Title": "Заглавие на формуляра",
  "Access restricted by its designer..!": "Достъпът е ограничен от дизайнера..!",
  "and you will no longer have the access to this form in bundles": "и няма да имате достъп до тази форма в пакети",
  "You will no longer have the access to this form in bundles": "Вече няма да имате достъп до тази форма в пакети",
  "Bad Request": "Неправилна заявка",
  "Select the form to be displayed based on the  above criteria": "Изберете формуляра, който да се показва въз основа на горепосочените критерии.",
  "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component": "Създайте критериите, използвайки API ключа на който и да е компонент на формуляр и условна нотация. Например, 'age > 18', където 'age' е API ключът на компонент на формуляр.",
  "Select form version": "Изберете версия на формуляра",
  "Please remove the special characters...!": "Моля, премахнете специалните символи...!",
  "No histories found": "Няма намерени истории",
  "Continue": "продължи",
  "This will create a new version of the form without changing the path name but with new form id.": "Това ще създаде нова версия на формуляра без промяна на името на пътя, но с нов идентификатор на формуляра.",
  "Save as a new version": "Запазете като нова версия",
  "Save New Version": "Запазване на новата версия",
  "Do you want to save a new version of this form?": "Искате ли да запазите нова версия на този формуляр?",
  "Do you want to create a duplicate form and associated workflow from existing form ?": "Искате ли да създадете дублиран формуляр и свързан работен процес от съществуващ формуляр?",
  "New version created": "Създадена е нова версия",
  "Create a duplicate form": "Създайте дублиран формуляр",
  "Show more": "Покажи повече",
  "Modified By": "Променен от",
  "Created On": "Създадено на",
  "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.": "Formsflow автоматично запазва предишните ви данни за формуляри. Сега можете да преминете към предишния етап и да редактирате.",
  "Duplicate Form": "Дублиран формуляр",
  "Form History": "История на формуляра",
  "No file chosen": "Няма избран файл",
  "Choose File": "Изберете файл",
  "Choose any": "Изберете всяка",
  "Sort by form name": "Сортиране по име на формуляр",
  "select form type": "изберете тип формуляр",
  "Draft Deleted Successfully": "Черновата е изтрита успешно",
  "Saved to Applications/Drafts": "Запазено в Приложения/Чернови",
  "Unfinished applications will be saved to Applications/Drafts.": " Незавършените приложения ще бъдат запазени в Приложения/Чернови.",
  "Discard Draft": "Отхвърлете черновата",
  "with ID": "с лична карта",
  "Please change the selected filters to view Forms": "Моля, променете избраните филтри, за да видите формуляри",
  "Search by form name": "Tŭrsene po ime na formulyara",
  "Click to search": "Щракнете за търсене",
  "No submissions found": "Няма намерени заявки",
  "No submission avaliable in the selected date. Please select another date range": "Няма налично подаване на избраната дата. Моля, изберете друг период от време",
  "Dashboards": "Табла за управление",
  "Form field": "Поле за формуляр",
  "Enter Label": "Въведете етикет",
  "Select form field": "Изберете поле на формуляра",
  "Latest Version": "Последна версия",
  "Submission Status": "Състояние на подаване",
  "No submission status": "Няма състояние на подаване",
  "No Public url found": "Не е намерен публичен URL адрес",
  "Show in list": "Показване в списъка",
  "Select Task Variable": "Изберете променлива на задачата",
  "Enter your Label": "Въведете своя етикет",
  "Select Key": "Изберете Ключ",
  "Create Your Task Variable": "Създайте своята променлива на задачата",
  "No task variable selected": "Няма избрана променлива на задачата",
  "Workflow Associate": "Работен сътрудник",
  "Task variable": "Променлива на задачата",
  "Enter pathname": "Въведете име на път",
  "Submission Saved": "Изпращането е запазено.",
  "Form saved": "Формулярът е запазен.",
  "Error while Submission.": "Грешка при изпращане.",
  "Message": "Моля, поправете грешките, преди да изпратите отново.",
  "Submission cannot be done.": "Подаването не може да се извърши.",
  "Edit": "редактиране",
  "Text Field": "текстово поле",
  "Do you want to associate form with a workflow ?": "Искате ли да свържете формата с работен поток?",
  "Yes": "да",
  "No": "Не",
  "Please select from one of the following workflows.": "Моля, изберете един от следните работни потоци.",
  "Form Name": "Име на формуляра",
  "Workflow Name": "Име на работния процес",
  "Publish this form for Client Users.": "Публикувайте този формуляр за Клиентски потребители.",
  "Comments": "Коментари",
  "Back": "обратно",
  "Edit Form": "Редактиране на формуляр",
  "Next": "Следващия",
  "Save": "Запазете",
  "Back to Form List": "Назад към списъка с формуляри",
  "Submit New": "Изпратете ново",
  "View Submissions": "Преглед на подадените материали",
  "View/Edit Form": "Преглед/Редактиране на формуляр",
  "Delete Form": "Изтриване на формуляр",
  "Delete": "Изтрий",
  "Print As PDF": "Печат като PDF",
  "Applications": "Приложения",
  "Tasks": "Задачи",
  "Metrics": "Метрика",
  "Dashboard": "Табло",
  "Logout": "Излез от профила си",
  "No tasks found": "Няма намерени задачи",
  "Please change the selected filters to view tasks": "Моля, променете избраните филтри, за да видите задачите",
  "Clear all filters": "Изчистете всички филтри",
  "Created": "Създаден",
  "Task Variables": "Променливи на задачата",
  "Process Variables": "Променливи на процеса",
  "Process Definition Name": "Име на дефиниция на процеса",
  "Assigne": "Цесионер",
  "Candidate Group": "Кандидатска група",
  "Candidate User": "Кандидат потребител",
  "Name": "име",
  "Description": "Описание",
  "Priority": "Приоритет",
  "Due Date": "Краен срок",
  "Follow up Date": "Дата на проследяване",
  "Task name": "Име на задачата",
  "Remove sorting": "Премахване на сортирането",
  "Ascending": "Възходящ",
  "Descending": "Низходящо",
  "Add sorting": "Добавете сортиране",
  "of the criteria are met.": "от критериите са изпълнени.",
  "For Variable, ignore case of": "За променлива, пренебрегвайте регистъра на",
  "value": "стойност",
  "No task matching filters found.": "Няма намерени филтри за съвпадение на задачи.",
  "Application ID": "Идентификационен номер на заявление",
  "Set follow-up Date": "Задайте дата за проследяване",
  "Set Due date": "Задайте крайна дата",
  "Add groups": "Добавете групи",
  "Claim": "Претенция",
  "Search By Last Name": "Търсене по фамилно име",
  "Search By First Name": "Търсене по собствено име",
  "Search By Email": "Търсене по имейл",
  "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Можете да добавите група, като въведете идентификатор на групата в полето за въвеждане и след това щракнете върху бутона със знака плюс.",
  "Add a group": "Добавете група",
  "Process Name": "Име на процеса",
  "Set FollowUp Date": "Задайте дата на последващо действие",
  "Groups": "групи",
  "Click to Change Assignee": "Щракнете, за да промените правоприемника",
  "Reset Assignee": "Нулиране на назначения",
  "Update User": "Актуализирайте потребителя",
  "Close": "Близо",
  "Type": "Тип",
  "Remove search": "Премахнете търсенето",
  "Property": "Имот",
  "Operator": "Оператор",
  "Total number of results": "Общ брой резултати",
  "Filter Tasks": "Филтриране на задачи",
  "All": "ВСИЧКО",
  "ANY": "ВСЕКИ",
  "Task assignee": "Възложител на задачата",
  "Application History": "История на приложенията",
  "View Submission": "Вижте подаване",
  "Showing": "Показване",
  "to": "да се",
  "Results": "pезултати",
  "Acknowledge": "Признайте",
  "View": "Преглед",
  "Select a task in the list.": "Изберете задача от списъка.",
  "No Filters Found": "Няма намерени филтри",
  "Loading": "Зареждане",
  "Form": "Формуляр",
  "History": "История",
  "Diagram": "Диаграма",
  "Delete Confirmation": "Изтриване на потвърждение",
  "All tasks": "Всички задачи",
  "Manage Groups": "Управление на групи",
  "Group ID": "ID на групата",
  "Due": "В следствие",
  "Follow-up": "Проследяване",
  "Application Name": "Име на приложението",
  "Created By": "Създадено от",
  "Application Status": "Състояние на приложението",
  "Request Status": "Състояние на заявката",
  "Request Name": "Име на заявката",
  "Submitted On": "Изпратено на",
  "Modified On": "Променено Включено",
  "No History Found": "Няма намерена история",
  "Process Diagram": "Диаграма на процеса",
  "Details": "Подробности",
  "Status": "Състояние",
  "Submissions": "Подавания",
  "No Application History found": "Няма намерена история на приложения",
  "Link To Form Submission": "Връзка към подаване на формуляр",
  "Last Modified": "Последно модифициран",
  "Insights": "Прозрения",
  "No dashboard found": "Няма намерено табло",
  "of": "на",
  "Select Dashboard": "Изберете Табло за управление",
  "Total Submissions": "Общо представяне",
  "Operations": "Операции",
  "Access Groups": "Групи за достъп",
  "Action": "Действие",
  "Add": "Добавете",
  "Admin": "Админ",
  "Create Form": "Създайте формуляр",
  "Upload Form": "Формуляр за качване",
  "Download Form": "Изтеглете формуляр",
  "Upload json form only": "Качете само json формуляр",
  "Select atleast one form": "Изберете поне един формуляр",
  "Select All": "Избери всички",
  "Created Date": "Дата на създаване",
  "Modified Date": "Дата на промяна",
  "File Upload Status": "Състояние на качване на файл",
  "Forms Completed": "Формулярите са попълнени",
  "Form Completed": "Формулярът е попълнен",
  "No forms found": "Няма намерени формуляри",
  "Powered by ": "Задвижвани от ",
  "No Process Diagram found": "Не е намерена диаграма на процеса",
  "No applications found": "Няма намерени приложения",
  "Successfully Updated": "Актуализирано успешно",
  "Failed": "Се провали",
  "Press Enter key or click here to search": "Натиснете клавиша Enter или щракнете тук, за да търсите",
  "Click to clear": "Щракнете, за да изчистите",
  "Search...": "Търсене...",
  "Click here to back": "Щракнете тук, за да се върнете назад",
  "Enter the form title": "Въведете заглавието на формуляра",
  "Enter the form machine name": "Въведете името на машината за формуляра",
  "Display as": "Показване като",
  "Path": "пътека",
  "example": "пример",
  "Title": "Заглавие",
  "Anonymous Form ": "анонимен формуляр",
  "Make this form public ?": "Да се ​​направи ли този формуляр публичен?",
  "Save & Preview": "Запазване и визуализация",
  "Design Form": "Формуляр за проектиране",
  "Associate this form with a workflow?": "Да се ​​свърже ли този формуляр с работен поток?",
  "Preview and Confirm": "Преглед и потвърждение",
  "All steps completed - you're finished": "Всички стъпки завършени - сте готови",
  "Forms": "Форми",
  "Downloaded Successfully": "Изтеглено успешно",
  "Error in JSON file structure": "Грешка във файловата структура на JSON",
  "Please fix the errors before submitting again.": "Моля, поправете грешките, преди да изпратите отново.",
  "Loading...": "Зареждане...",
  "Wizard": "Магьосник",
  "Save Form": "Запазване на формуляр",
  "Confirm": "Потвърдете",
  "Cancel": "Отмяна",
  "Please change the selected filters to view applications": "Моля, променете избраните филтри, за да видите приложения",
  "No submissions available for the selected date range": "Няма налични заявки за избрания период от време",
  "OK": "Добре",
  "Form not available": "Формулярът не е наличен",
  "Thank you for your response.": "Благодаря ви за отговора.",
  "saved successfully": "Запазено успешно",
  "Copy anonymous form URL": "Копирайте URL на анонимен формуляр",
  "Submitted By": "Изпратено от",
  "Confirmation": "Потвърждение",
  "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Промяната на заглавието на формуляра няма да засегне съществуващите приложения. Той ще се актуализира само в новосъздадените приложения. Натиснете Запазване на промените, за да продължите или отмените промените.",
  "Error while saving Form": "Грешка при запазване на формуляра",
  "Click here to go back": "Щракнете тук, за да се върнете",
  " Applications are submitted against": " Заявленията се подават срещу",
  " Application is submitted against": " Заявлението се подава срещу",
  "Are you sure to delete the": "Сигурни ли сте, че искате да изтриете",
  "Are you sure to delete the draft": "Сигурни ли сте, че искате да изтриете черновата",
  "Are you sure to delete this submission ?": "Сигурни ли сте, че искате да изтриете този запис?",
  " Submissions are made against": " Подаванията се правят срещу",
  " Submission is made against": " Подаването се прави срещу",
  "Save Changes": "Запазите промените",
  "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.": "Промяната на работния процес на формуляра няма да засегне съществуващите приложения. Той ще се актуализира само в новосъздадените приложения. Натиснете Запазване на промените, за да продължите или отмените промените.",
  "Form-Workflow association saved.": "Асоциацията на формуляр-работен процес е запазена.",
  "Form-Workflow association failed.": "Неуспешно свързване на формуляр-работен процес.",
  "Form deletion unsuccessful": "Изтриването на формуляра е неуспешно",
  "Form deleted successfully": "Формулярът е изтрит успешно",
  "Bundle deleted successfully": "Пакетът е изтрит успешно",
  "Form process failed": "Обработката на формуляра не бе успешно",
  "Form unpublishing Failed": "Прекратяването на публикуването на формуляра не бе успешно",
  "All groups have access to the dashboard": "Всички групи имат достъп до таблото",
  "Export PDF": "Експортиране на PDF",
  "Something went wrong. Please try again!": "Нещо се обърка. Моля, опитайте отново!",
  "No Dashboards Found": "Няма намерени табла за управление",
  "Processes": "процеси",
  "Please select an existing workflow.": "Моля, изберете съществуващ работен процес.",
  "Create New": "Създай нов",
  "Or create new workflow or import a workflow from a local directory.": "Или създайте нов работен поток или импортирайте работен поток от локална директория.",
  "The operation couldn't be completed. Please try after sometime": "Операцията не можа да бъде завършена. Моля, опитайте след известно време",
  "Select...": "Изберете...",
  "No Drafts Found": "Няма намерени чернови",
  "Help": "Помогне",
  "Draft Id": "Чернова на ID",
  "Draft Name": "Име на черновата",
  "Link To Draft Submission": "Връзка към изпращане на чернова",
  "Drafts": "Чернови",
  "You can't submit this form until it is published": "Не можете да изпратите този формуляр, докато не бъде публикуван",
  "Form not published": "Формулярът не е публикуван",
  "Access Denied": "Отказан достъп",
  "By default, the tenant key would be prefixed to form": "По подразбиране ключът на клиента ще има префикс за форма",
  "go back": "Върни се",
  "No Applications Found": "Няма намерени приложения",
  "Submission saved to draft.": "Изпращането е запазено в чернова.",
  "Saved to draft": "Запазено в чернова",
  "Saving...": "Запазва се...",
  "Resource": "Ресурс",
  "Error in creating form process mapper": "Грешка при създаването на картограф на процес на формуляр",
  "Select the date": "Изберете датата",
  "Diagram deployed": "Диаграмата е разгърната",
  "Deployment failed": "Неуспешно внедряване",
  "form uploaded": "качен формуляр",
  "forms uploaded": "качени формуляри",
  "Failed to upload": "Неуспешно качване",
  "forms...!": "форми...!",
  "form...!": "форма...!",
  "Process name(s) must not be empty": "Името(ата) на процесите не трябва да са празни",
  "URL copied": "URL адресът е копиран",
  "Click Here to Copy": "Щракнете тук, за да копирате",
  "Resources": "Ресурси",
  "Duplicate form created successfully": "Дублираният формуляр е създаден успешно",
  "Revert": "Връщане",
  "Criteria": "Критерии",
  "Select Form": "Изберете Формуляр",
  "Create Condition": "Създаване на условие",
  "Enter criteria": "Въведете критерии",
  "Make this form public": "Направете този формуляр публичен",
  "Enable bundling": "Активиране на групирането",
  "Bundle Name": "Име на пакета",
  "View/Edit": "Преглед/редактиране",
  "Create Bundle": "Създаване на пакет",
  "Rows per page": "Редове на страница",
  "Items per page": "Елементи на страница",
  "entries": "записи",
  "Form Bundle": "Пакет формуляри",
  "No bundles found": "Няма намерени пакети",
  "Please change the selected filters to view Bundles": "Моля, променете избраните филтри, за да видите пакети",
  "Select all to download forms": "Изберете всички, за да изтеглите формуляри",
  "Select for download": "Изберете за изтегляне",
  "Bundle Description": "Описание на пакета",
  "Conditions": "Условия",
  "Enter name": "Въведи име",
  "Enter Description": "Въведете описание",
  "You can change the form order by drag and drop": "Можете да промените реда на формуляра чрез плъзгане и пускане",
  "Form Order": "Форма за поръчка",
  "Form Type": "Тип формуляр",
  "Add Forms Launch together": "Добавете Forms Launch заедно",
  "Form bundles can save your time by grouping forms together": "Пакетите формуляри могат да ви спестят време чрез групиране на формуляри заедно",
  "Add Forms": "Добавете формуляри",
  "Create Conditions": "Създаване на условия",
  " Add Conditions": "Добавяне на условия",
  "Select Forms": "Изберете Формуляри",
  "Insert": "Поставете",
  "View Form": "Преглед на формуляра",
  "Publish this Bundle for Client Users.": "Публикувайте този пакет за клиентски потребители",
  "Total Forms": "Общо формуляри",
  "Edit Bundle": "Редактиране на пакет",
  "Next Form": "Следваща форма",
  "Previous Form": "Предишна форма",
  "Forms included under the package": "Формуляри, включени в пакета",
  "Submit": "Изпращане",
  "Reset Zoom": "Нулиране на мащаба",
  "Zoom In": "Увеличавам",
  "Zoom Out": "Отдалечавам",
  "Deploy": "Разположете",
  "Export": "Експортиране",
  "Overview": "Преглед",
  "Design Permission": "Разрешение за проектиране",
  "Application Permission": "Разрешение за приложение",
  "All Designers": "Всички дизайнери",
  "Private(only you)": "Лично (само ти)",
  "Specific Designer Group": "Специфична дизайнерска група",
  "Submission Permission": "Разрешение за подаване",
  "All Users": "Всички потребители",
  "Specific User Group": "Конкретна потребителска група",
  "Specific Reviewers": "Конкретни рецензенти",
  "All Reviewers": "Всички рецензенти",
  "Permission for application tracking.": "Разрешение за проследяване на приложения.",
  "Design Bundle": "Дизайн пакет",
  "Workflow": "Работен процес",
  "Bundle Name and Description is Required": "Името и описанието на пакета са задължителни",
  "Bundle Description is Required": "Изисква се описание на пакета",
  "Bundle Create Successfully": "Пакетът е създаден успешно",
  "Bundle updated successfully": "Пакетът е актуализиран успешно",
  "Select": "избирам",
  "Unselect": "Отмени избора",
  "Applicable for Designer Roled Users only.": "Приложимо само за потребители с права на дизайнер.",
  "Applicable for Client and Reviewer Roled Users only.": "Приложимо само за потребители с права на клиент и рецензент.",
  "Roles": "роли",
  "Users": "потребители",
  "Done": "Свършен",
  "Failed to update permission!": "Неуспешно актуализиране на разрешението!",
  "Failed to fetch roles!": "Неуспешно извличане на роли!",
  "Failed to update role!": "Неуспешно актуализиране на ролята!",
  "Permission updated successfully!": "Неуспешно актуализиране на ролята!!",
  "Role updated successfully!": "Ролята е актуализирана успешно!",
  "Update failed!": "Неуспешна актуализация!",
  "Clear": "ясно",
  "Are you sure deleting the role": "Сигурни ли сте, че изтривате ролята",
  "Confirm Delete": "Потвърдете Изтриване",
  "All roles": "Всички роли",
  "Filter By:": "Филтриране по:",
  "Create": "Създавайте",
  "Eg: Account Manager": "Например: Мениджър на акаунти",
  "Search by name, username or email": "Търсете по име, потребителско име или имейл",
  "No data Found": "Няма намерени данни",
  "Create New Role": "създайте нова роля",
  "Search by role name": "търсене по име на роля",
  "Role Name": "име на ролята",
  "Actions": "действие",
  "Create Role": "създайте роля",
  "Email": "електронна поща",
  "Role": "Роля",
  "Add Role": "Добавяне на роля",
  "Role deleted successfully!": "Ролята е изтрита успешно!",
  "Failed to delete role!": "Неуспешно изтриване на роля!",
  "Role created successfully!": "Ролята е създадена успешно!",
  "Failed to create role!": "Неуспешно създаване на роля!",
  "Update success!": "Успешна актуализация!",
  "No results found": "Няма намерени резултати",
  "Edit Role": "Редактиране на роля",
  "Failed to fetch users!": "Неуспешно извличане на потребители!",
  "Role names cannot contain special characters except   _ , -": "Имената на ролите не могат да съдържат специални знаци освен _, -",
  "Role names cannot contain special characters except _ , - , / ": "Имената на ролите не могат да съдържат специални знаци освен _, -, /",
  "Rules deployed successfully": "Правилата са внедрени успешно",
  "Choose From Template": "Изберете от шаблона",
  "Back to forms": "Обратно към формите",
  "Choose From Templates": "Изберете от шаблоните",
  "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Разгледайте нашата библиотека с шаблони, за да намерите идеалната комбинация от форми и работни потоци. Щракнете, за да прегледате шаблон, и ако той отговаря на вашите нужди, персонализирайте го по свой вкус. След като го адаптирате към конкретните си изисквания, сте готови да създадете вашето делово предложение",
  "All templates": "Всички шаблони",
  "Template count": "Брой шаблони",
  "Learn more": "Научете повече",
  "Template Details": "Детайли за шаблона",
  "Template Title": "Заглавие на шаблона",
  "Preview Form": "Преглед на формуляра",
  "Connected Workflow": "Свързан работен процес",
  "Delete Template": "Изтриване на шаблона",
  "Use Template": "Използване на шаблона",
  "Template created successfully": "Успешно създаден шаблон",
  "Template deleted successfully": "Успешно изтрит шаблон",
  "Template updated successfully": "Успешно актуализиран шаблон",
  "Category": "Категория",
  "Search category...": "Търсене в категория...",
  "Save as Template": "Запазване като шаблон",
  "Create Template": "Създаване на шаблон",
  "Select or Create Category": "Избор или създаване на категория",
  "Short Intro": "Кратко представление",
  "Enter short intro": "Въведете кратко представление",
  "Enter description": "Въведете описание",
  "Select or create": "Избор или създаване",
  "Update Template": "Актуализиране на шаблона",
  "Form created successfully": "Успешно създадена форма",
  "select or create": "Избор или създаване",
  "Update Associated Form": "Актуализиране на свързан формуляр",
  "Update Associated Workflow": "Актуализиране на свързан работен процес",
  "Enter title": "Въведете заглавие",
  "No Templates Found": "Не са намерени шаблони",
  "No Category Found": "Не са намерени категории",
  "Save Template": "Запазване на Шаблона",
  "You can type and click the ": "Можете да пишете и щракнете върху",
  "to create the category.": " за създаване на категорията.",
  "select or type to create": "изберете или въведете, за да създадете",
  "BPMN": "BPMN",
  "DMN": "DMN",
  "Advanced Designer": "Напреднал Дизайнер",
  "Basic Designer": "Основен Дизайнер",
  "Search": "Търсене",
  "Key": "ключ",
  "No Process Found": "Няма Намерен Процес",
  "Search workflow": "Търсене на Работен Процес",
  "No Dmn Found": "Няма Намерен DMN",
  "Submission ID": "Идентификационен Номер на Подаване",
  "Submission Name": "Име на Подаване",
  "Submission History": "История на Подаването",
  "No Submission History found": "Няма Намерен История на Подаването",
  "Error in submission count": "Грешка в броя на Подаванията",
  "Permission for submission tracking.": "Разрешение за проследяване на Подаванията.",
  "Reviewer permission to view submissions": "Право на рецензент да преглежда представяния",
  "Permission to create new submission": "Право на създаване на ново представяне",
  "Back to Bundle List": "Обратно към списъка с пакети",
  "Bundle": "Пакет",
  "You can drag these nodes to the pane on the right.": "Можете да влачете тези възли в дясната панел.",
  "You can delete the element by select and click the backspace": "Можете да изтриете елемента, като го изберете и натиснете клавиша за връщане",
  "Workflow Id": "Идентификатор на работния процес",
  "Enter Workflow Id": "Въведете идентификатор на работния процес",
  "Back to Submissions": "Обратно към предаванията",
  "Back to Drafts": "Обратно към черновите",
  "Choose Your Workflow Option": "Изберете своята опция за работния процес",
  "Create New Workflow": "Създаване на нов работен процес",
  "Choose this option when you want to create a fresh workflow based on the template. System will generate and deploy a new workflow, then connect it to the selected form. Opt for this if your form requires a distinct set of workflow steps tailored to its specific needs.": "Изберете тази опция, когато искате да създадете нов работен процес, базиран на шаблона. Системата ще генерира и разгърне нов работен процес, след което ще го свърже с избрания формуляр. Изберете тази опция, ако вашият формуляр изисква различен набор от стъпки в работния процес, подходящи за конкретните му нужди.",
  "Reuse Existing Workflow": "Използване на съществуващ работен процес",
  "Select this option to link the form with an already established workflow. Any modifications made to the existing workflow will automatically reflect in this form as well. This is ideal when you want to leverage the existing workflow for your form's requirements.": "Изберете тази опция, за да свържете формуляра с вече установения работен процес. Всякакви модификации, направени върху съществуващия работен процес, автоматично ще се отразят и в този формуляр. Това е идеално, когато искате да използвате вече съществуващия работен процес за нуждите на вашия формуляр",
  "Are you sure you wish to delete the Template?": "Сигурни ли сте, че искате да изтриете шаблона?",
  "Enter Workflow Name": "Въведете името на работния процес",
  "Create Workflow": "Създайте работен процес",
  "Upload Workflow": "Качете работен процес",
  "Edit Workflow": "Редактирайте работен процес",
  "Published": "Публикувано",
  "Unpublished": "Непубликувано",
  "Private": "Частен",
  "Anonymous": "Анонимен",
  "Edit Processes": "Редактирайте процесите",
  "Create Processes": "Създайте процеси",
  "tasks": "задачи",
  "Submission Id": "Идентификационен Номер на Подаване",
  "Clear All Filters": "Изчисти всички филтри",
  "Show results": "Покажи резултатите",
  "Delete Draft": "Изтрий черновата",
  "I can help you design forms effortlessly- all you have to do is give me a clear and concise description of what the form is meant to do. I will build out the fields and layout for you,which you can further customize.": "Мога да ви помогна да проектирате формуляри без усилие - всичко, което трябва да направите, е да ми дадете ясно и кратко описание на това, за какво е предназначена формата. Аз ще изградя полетата и оформлението за вас, което можете да персонализирате допълнително.",
  "I am": "Аз съм",
  "For example 'Give us a form that will serve as a patient intake form for walk-in clinics'": "Например 'Дайте ни формуляр, който ще служи като формуляр за прием на пациенти за клиники без предварително записване'.",
  "Enter your prompt here": "Въведете вашето подсигуряване тук",
  "Would you like to continue?": "Искате ли да продължите?",
  "Restart": "Рестартирай",
  "I'm here to provide further assistance. Thank you!": "Аз съм тук, за да предоставя допълнителна помощ. Благодаря ви!",
  "Generate Form Design": "Генерирай дизайн на формуляра",
  "Preview": "предварителен преглед",
  "Your form is now ready!": "Вашият формуляр вече е готов!",
  "Please tell me all the specifications and requirements you have in mind for your form. After you have finished the description, hit send.": "Моля, кажете ми всички спецификации и изисквания, които имате предвид за вашия формуляр. След като завършите описанието, натиснете Изпрати.",
  "Choose template": "Изберете шаблон",
  "Search by bundle name": "Търсене по име на пакета",
  "Save Bundle": "Запази Bundle",
  "Id": "Id",
  "Enable bundling ?": "Включи опаковане?",
  "Select a task in the List.": "Изберете задача от списъка.",
  "Add Date": "Добавяне на дата",
  "Assign to Me": "Възложи на мен",
  "Filter count:": "Брой филтри:",
  "Selected Forms": "Избрани формуляри",
  "Template Used:": "Използван шаблон:",
  "Select a task from the List.": "Изберете задача от списъка.",
  "Choose a task from the list; your selection directs your current activity.": "Изберете задача от списъка; вашият избор определя текущата ви дейност.",
  "Please change the selected filters to view submissions": "Моля променете избраните филтри, за да видите представянията",
  "Please change the selected filters to view drafts": "Моля променете избраните филтри, за да видите черновите",
  "No drafts found": "Не са намерени чернови",
  "Flow-E helps to build faster": "Flow-E помага за по-бързо строене",
  "Flow-E is not available for demonstration in the trial instance. You can experience Flow-E in any of the premium packages of the product": "Flow-E не е наличен за демонстрация в пробния инстанс. Можете да изпробвате Flow-E в някои от премиум пакетите на продукта",
  "Get in touch with formsflow.ai team": "Свържете се с екипа на formsflow.ai",
  "Premium": "Високо качество",
  "Select a status": "Изберете статус",
  "Group": "Група",
  "Form description": "Описание на формуляра",
  "Select all forms": "Изберете всички форми",
  "Bold": "Удебелен",
  "Italic": "Курсив",
  "Underline": "Подчертан",
  "Align left": "Подравняване вляво",
  "Align center": "Центрирано подравняване",
  "Align right": "Подравняване вдясно",
  "Align justify": "Двустранно подравняване",
  "Insert Link": "Вмъкни връзка",
  "Clean": "Изчисти",
  "Click for task variables": "Кликнете за преглед на променливите на задачата",
  "Upload DMN": "Качване на DMN",
  "DMN Name": "Име на DMN",
  "Search by DMN name": "Търсене по име на DMN",
  "Display authorized tasks based on user roles": "Показване на разрешени задачи въз основа на ролите на потребителя",
  "You are currently using a test instance.The trial period ends in": "В момента използвате тестова инстанция. Пробният период изтича след",
  "days.": "дни.",
  "Are you sure to delete": "Сигурни ли сте, че искате да изтриете",
  "filter?": "филтър?",
  "Select Workflow": "Изберете работен процес",
  "Select Assignee": "Изберете назначен",
  "Click here to select attributes": "Кликнете тук, за да изберете атрибути",
  "Select the predefined attributes and custom task variables created as part of form submission you wish to display in the task list": "Изберете предварително дефинираните атрибути и персонализирани променливи на задачата, създадени като част от подадената форма, които искате да покажете в списъка със задачи",
  "Task variables": "Променливи на задачата",
  "User Role": "Роля на потребителя",
  "User Group": "Група на потребителя",
  "Select User Role": "Изберете роля на потребителя",
  "Select User Group": "Изберете група на потребителя",
  "To display task variables, select a form as part of the filter": "За да покажете променливите на задачата, изберете формуляр като част от филтъра",
  "select a form": "изберете формуляр",
  "No task variables found": "Не са намерени променливи за задачи",
  "Edit filter": "Редактиране на филтър",
  "Select form fields to display in task list": "Изберете полета на формуляра, които да се показват в списъка със задачи",
  "Select all fields": "Изберете всички полета",
  "Edit Label": "Редактиране на етикета",
  "Selecting all form fields may affect performance. For the best performance, just pick the form fields you really need.": "Избирането на всички полета на формуляра може да окаже влияние върху производителността. За най-добри резултати, изберете само полетата на формуляра, които наистина ви трябват.",
  "User Added successfully!": "Потребителят е успешно добавен!",
  "Failed to create user!": "Неуспешно създаване на потребител!",
  "Add Registered Users": "Добави Регистрирани Потребители",
  "Username or Email": "Потребителско име или Имейл",
  "Add User": "Добави Потребител",
  "User doesn't exist!": "Потребителят не съществува!",
  "Success": "успех",
  "User added": "Потребителят е добавен",
  "From": "От",
  "To": "До",
  "Premium Subscription": "Премиум Абонамент",
  " For further insights on this exclusive premium feature, kindly connect": "За допълнителни прозрения относно тази изключителна премиум функция, моля, свържете се",
  " with our dedicated marketing team for detailed information.": "с нашия отдел маркетинг за подробна информация.",
  "Get Connected With Us Now!": "Свържете се с нас сега!",
  "Visit our": "Посетете нашия",
  "Pricing page": "страница с цени",
  "for more details.": "за повече подробности.",
  "Integration": "Интеграция",
  "Recipes": "Рецепти",
  "Connected Apps": "Свързани приложения",
  "Library": "Библиотека",
  "Add group": "Добави група",
  "Add task label": "Добавяне на етикет за задача",
  "Integrations": "Интеграции",
  "We facilitate hundreds of native integrations via our ‘Native Integrations Pro’ package.": "Ние улесняваме стотици местни интеграции чрез нашия пакет „Професионални нативни интеграции“.",
  " This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "Тази функция по подразбиране не е налична в 14-дневната проба. Ако вашата проба изисква тази функция, можете да ни информирате, и ние можем да я активираме за вас.",
  "Upgrade to unlock Native Integrations Pro": "Надстройте, за да отключите Нативни интеграции Pro",
  "We facilitate hundreds of native integrations via our ": "Ние предлагаме стотици нативни интеграции чрез нашия ",
  " package. This feature is not available by default in the 14 day trial. If your trial requires this feature, you can let us know and we can enable this for you.": "пакет. Тази функционалност не е достъпна по подразбиране в 14-дневната проба. Ако вашата проба изисква тази функция, може да ни уведомите и ние можем да я активираме за вас.",
  "To learn more about Native Integrations Pro": "За да научите повече за Нативни интеграции Pro",
  "Check out Integrations Feature": "Проверете функцията Интеграции",
  "Connect with": "Свържете се с",
  "team for requests or queries.": "екипа за заявки или въпроси.",
  "Learn more about the feature": "Научете повече за функцията",
  "Native Integrations Pro": "Нативни Интеграции Про",
  " team.": "екип.",
  "Connect with formsflow.ai team.": "Свържете се с екипа на formsflow.ai.",
  "You don't have permission to access this page.": "Нямате разрешение за достъп до тази страница.",
  "Please contact your administrator or try again later.": "Моля, свържете се с вашия администратор или опитайте по-късно.",
  "Return to login": "Върнете се към вход",
  "Default filter removed": "Филтърът по подразбиране е премахнат",
  "Set default filter": "Задаване на филтър по подразбиране",
  "added as default filter": "добавен като филтър по подразбиране",
  "Are you sure you wish to delete the draft": "Сигурни ли сте, че искате да изтриете черновата",
  ". Are you sure want to delete ?": ". Наистина ли искате да изтриете?",
  "Are you sure you wish to delete the form ": "Сигурни ли сте, че искате да изтриете формуляра",
  "Are you sure you wish to delete the form?": "Сигурни ли сте, че искате да изтриете формуляра?",
  "Add form fields to display in task list": "Добавете полета на формуляра за показване в списъка със задачи",
  "Version": "Версия",
  "Ok": "Добре",
  "Are you sure you wish to delete the form": "Сигурни ли сте, че искате да изтриете формуляра",
  "Are you sure you wish to delete this submission?": "Наистина ли искате да изтриете това изпращане?",
  "Task": "Задачи",
  "Error in getting Workflow Process.": "Грешка при получаване на процеса на работния процес.",
  "Error while saving Form.": "Грешка при запазване на формуляра.",
  "Text Area": "текстова област",
  "Number": "номер",
  "Password": "парола",
  "Select Boxes": "поле за избор",
  "Radio": "радио",
  "Button": "бутон",
  "Text Area With Analytics": "текстова област с анализ",
  "Data": "данни",
  "Display": "експонат",
  "on": "На",
  "Url": "URL",
  "Phone Number": "телефонен номер",
  "Tags": "Етикет",
  "Address": "адрес",
  "Date / Time": "Време за среща",
  "Day": "ден",
  "Time": "време",
  "Currency": "валута",
  "Survey": "анкети",
  "Signature": "знак",
  "HTML": "HTML",
  "Content": "съдържание",
  "Columns": "Списък",
  "Field Set": "поле набор",
  "Panel": "контролен панел",
  "Table": "маса",
  "Tabs": "Етикет",
  "Well": "добре",
  "Hidden": "скрит",
  "Container": "контейнер",
  "Data Map": "карта с данни",
  "Data Grid": "решетка с данни",
  "Edit Grid": "Редактиране на мрежата",
  "Tree": "Дърво",
  "reCAPTCHA": "код за потвърждение",
  "File": "документ",
  "Nested": "вложени",
  "Custom": "персонализиран",
  "Basic": "основен",
  "Advanced": "напреднал",
  "Layout": "оформление",
  "Drag and Drop a form component": "Плъзнете и пуснете компоненти на формуляра",
  "The minimum length requirement this field must meet.": "Изисквания за минимална дължина, на които трябва да отговаря това поле",
  "The label for this field that will appear next to it.": "Етикетът, който ще се появи до това поле.",
  "Label Position": "позиция на етикета",
  "Position for the label for this field.": "Позицията на етикета за това поле.",
  "Placeholder": "Заместител",
  "The placeholder text that will appear when this field is empty.": "Текст за място, който ще се показва, когато това поле е празно.",
  "The description is text that will appear below the input field.": "Описанието е текстът, който ще се появи под полето за въвеждане.",
  "Tooltip": "подсказка",
  "Adds a tooltip to the side of this field.": "Добавете подсказка отстрани на това поле.",
  "To add a tooltip to this field, enter text here.": "За да добавите подсказка към това поле, въведете текст тук.",
  "Description for this field.": "Описание на това поле.",
  "Prefix": "префикс",
  "Suffix": "наставка",
  "Widget": "малки инструменти",
  "The widget is the display UI used to input the value of the field.": "Уиджетът е потребителски интерфейс на дисплея за въвеждане на стойности на полета.",
  "Right (Left-aligned)": "дясно (подравнено вляво)",
  "Left (Left-aligned)": "Ляво (подравнено вляво)",
  "Left (Right-aligned)": "Ляво (подравнено вдясно)",
  "Right (Right-aligned)": "дясно (подравнено вдясно)",
  "Bottom": "дъно",
  "Component": "Компоненти",
  "Top": "оптимален",
  "Label Width": "ширина на етикета",
  "The width of label on line in percentages.": "Ширината на онлайн етикета (в проценти).",
  "Label Margin": "Поле на раздела",
  "The width of label margin on line in percentages.": "Ширината на полето на етикета на реда, изразена като процент.",
  "Rows": "Ред",
  "Input Field": "поле за въвеждане",
  "Calendar Picker": "Инструмент за избор на календар",
  "Select a widget": "Изберете джаджа",
  "Input Mask": "маска за въвеждане",
  "Widget Settings": "Настройки на притурката",
  "Allow Multiple Masks": "Разрешете няколко маски",
  "Input Masks": "маска за въвеждане",
  "Mask": "маска",
  "Add Another": "плюс още един",
  "Custom CSS Class": "персонализиран CSS клас",
  "Custom CSS class to add to this component.": "Персонализиран CSS клас за добавяне към този компонент.",
  "Tab Index": "Индекс на маркери",
  "Sets the tabindex attribute of this component to override the tab order of the form. See the MDN documentation on tabindex for more information.": "Задайте свойството tabindex на този компонент да отменя реда на разделите на формуляра. За повече информация вижте документацията на MDN за tabindex.",
  "Autocomplete": "автоматично завършване",
  "Indicates whether input elements can by default have their values automatically completed by the browser. See the MDN documentation on autocomplete for more information.": "Показва дали входният елемент може автоматично да довършва стойността си от браузъра по подразбиране. За повече информация вижте документацията на MDN относно автоматичното довършване.",
  "A hidden field is still a part of the form, but is hidden from view.": "Скритите полета все още са част от формуляра, но са скрити от погледа.",
  "Hide Label": "скрий раздела",
  "Show Word Counter": "Показване на брояча на думи",
  "Show a live count of the number of words.": "Показва броя на думите в реално време.",
  "Hide the label (title, if no label) of this component. This allows you to show the label in the form builder, but not when it is rendered.": "Скрийте етикета (заглавие, ако няма етикет) за този компонент. Това ви позволява да покажете етикета в конструктора на формуляри, но не и когато е изобразен",
  "Show Character Counter": "Показване на брояча на знаците",
  "Show a live count of the number of characters.": "Показва броя на знаците в реално време.",
  "Hide Input": "скрит вход",
  "Hide the input in the browser. This does not encrypt on the server. Do not use for passwords.": "Скриване на въвеждане в браузъра. Това не е криптирано на сървъра. Не използвайте за пароли.",
  "Initial Focus": "първоначален фокус",
  "Make this field the initially focused element on this form.": "Направете това поле първоначално фокусиран елемент в този формуляр.",
  "Allow Spellcheck": "Разрешете проверка на правописа",
  "Disabled": "хора с увреждания",
  "Disable the form input.": "Деактивирайте въвеждането на формуляр.",
  "Table View": "изглед на таблицата",
  "Shows this value within the table view of the submissions.": "Покажете тази стойност в изпратения изглед на таблица.",
  "Modal Edit": "Модално редактиране",
  "Opens up a modal to edit the value of this component.": "Отваря модална програма за редактиране на стойността на този компонент.",
  "Multiple Values": "множество стойности",
  "Allows multiple values to be entered for this field.": "За това поле са разрешени множество стойности.",
  "Default Value": "По подразбиране",
  "The will be the value for this field, before user interaction. Having a default value will override the placeholder text.": "ще бъде стойността на това поле преди взаимодействието с потребителя. Наличието на стойност по подразбиране ще замени текста на заместителя.",
  "Persistent": "постоянен",
  "A persistent field will be stored in database when the form is submitted.": "Постоянните полета ще се съхраняват в базата данни, когато формулярът бъде изпратен.",
  "None": "Не всеки",
  "Server": "сървър",
  "Client": "клиент",
  "Input Format": "входен формат",
  "Force the output of this field to be sanitized in a specific format.": "Принуждава изхода на това поле да бъде дезинфекциран в определен формат.",
  "Plain": "ясно",
  "Type to search": "въведете търсене",
  "Raw (Insecure)": "суров (опасно)",
  "Protected": "защитени",
  "A protected field will not be returned when queried via API.": "Защитените полета не се връщат при запитване през API.",
  "Database Index": "индекс на базата данни",
  "Set this field as an index within the database. Increases performance for submission queries.": "Задайте това поле като индекс в базата данни. Подобрете ефективността на изпратените заявки.",
  "Text Case": "текстов случай",
  "When data is entered, you can change the case of the value.": "Когато въвеждате данни, можете да промените главния регистър на стойността.",
  "Mixed (Allow upper and lower case)": "смесено (разрешени случаи)",
  "Uppercase": "капитал",
  "Lowercase": "малки букви",
  "Encrypted (Enterprise Only)": "Шифроване (само за предприятия)",
  "Encrypt this field on the server. This is two way encryption which is not suitable for passwords.": "Това поле е криптирано на сървъра. Това е двупосочно криптиране, което не е подходящо за пароли.",
  "Redraw On": "преначертавам",
  "Redraw this component if another component changes. This is useful if interpolating parts of the component like the label.": "Ако друг компонент се промени, преначертайте този компонент. Това е полезно при вмъкване на части от компоненти като етикети.",
  "Any Change": "Всякакви промени",
  "Clear Value When Hidden": "Изчистване на стойността, когато е скрита",
  "When a field is hidden, clear the value.": "Когато полето е скрито, изчистете стойността.",
  "The following variables are available in all scripts.": "Следните променливи са налични във всички скриптове.",
  "Custom Default Value": "персонализирано подразбиране",
  "The complete form JSON object": "Пълен JSON обект",
  "submission": "Изпращане",
  "The complete submission object.": "Пълният обект за извършване.",
  "data": "данни",
  "The complete submission data object.": "Пълният обект с данни за подаване.",
  "row": "Ред",
  "Contextual \"row\" data, used within DataGrid, EditGrid, and Container components": "Контекстни \"редови\" данни, използвани в компонентите DataGrid, EditGrid и Container",
  "component": "Компоненти",
  "The current component JSON": "Текущ компонент JSON",
  "instance": "пример",
  "The current component instance.": "Текущият екземпляр на компонента.",
  "The current value of the component.": "Текущата стойност на компонента.",
  "moment": "момент",
  "The moment.js library for date manipulation.": "moment.js библиотека за манипулиране на дати.",
  "utils": "полезност",
  "util": "полезност",
  "An alias for \"utils\".": "Псевдоним за \"utils\".",
  "JavaScript": "JavaScript",
  "Enter custom javascript code.": "Въведете персонализиран JavaScript код.",
  "Example:": "пример:",
  "JSONLogic": "JSON логика",
  "Execute custom logic using ": "Изпълнете персонализирана логика с помощта на",
  "support is provided using an \"_\" before each operation, such as {\"_sum\": {var: \"data.a\"}}": "Използвайте \"_\" преди всяка операция, за да осигурите поддръжка, напр. {\"_sum\": {var: \"data.a\"}}",
  "Full": "пълен",
  "Calculated Value": "Изчислено",
  "token": "токен",
  "The decoded JWT token for the authenticated user.": "Декодираният JWT маркер на удостоверения потребител.",
  "Calculate Value on server": "Изчислете стойността на сървъра",
  "Checking this will run the calculation on the server. This is useful if you wish to override the values submitted with the calculations performed on the server.": "Поставете отметка в това, за да стартирате изчислението на сървъра. Това е полезно, ако искате да замените подадената стойност с изчисление, извършено на сървъра.",
  "Allow Manual Override of Calculated Value": "Разрешете ръчно отмяна на изчислените стойности",
  "When checked, this will allow the user to manually override the calculated value.": "Когато е отметнато, това ще позволи на потребителя ръчно да отмени изчислената стойност.",
  "Remove": "премахване",
  "Validate On": "Удостоверяването е включено",
  "Determines when this component should trigger front-end validation.": "Определя кога този компонент трябва да задейства проверка на интерфейса.",
  "Change": "Промяна",
  "Blur": "Неясно",
  "Required": "задължително",
  "A required field must be filled in before the form can be submitted.": "Задължителните полета трябва да бъдат попълнени, преди формулярът да може да бъде изпратен.",
  "Unique": "Уникален",
  "Makes sure the data submitted for this field is unique, and has not been submitted before.": "Уверете се, че данните, изпратени за това поле, са уникални и не са били изпращани преди.",
  "Minimum Length": "Минимална дължина",
  "The maximum length requirement this field must meet.": "Изискването за максимална дължина, на което трябва да отговаря това поле.",
  "Maximum Length": "Максимална дължина",
  "Minimum Word Length": "Минимална дължина на думата",
  "The minimum amount of words that can be added to this field.": "Минималният брой думи, които могат да бъдат добавени към това поле.",
  "Maximum Word Length": "максимална дължина на думата",
  "The maximum amount of words that can be added to this field.": "Максималният брой думи, които могат да бъдат добавени към това поле.",
  "Regular Expression Pattern": "модел на регулярни изрази",
  "The regular expression pattern test that the field value must pass before the form can be submitted.": "Тест за модел на регулярен израз, който стойностите на полетата трябва да преминат, преди да бъде изпратен формулярът.",
  "Error Label": "грешен етикет",
  "The label for this field when an error occurs.": "Етикетът за това поле, когато е възникнала грешката.",
  "Custom Error Message": "персонализирано съобщение за грешка",
  "Error message displayed if any error occurred.": "Ако възникнат грешки, ще се покаже съобщение за грешка.",
  "Custom Validation": "персонализирано валидиране",
  "input": "въведете",
  "The value that was input into this component": "Въведете стойност за този компонент",
  "Enter custom validation code.": "Въведете персонализиран код за потвърждение.",
  "You must assign the valid variable as either true or an error message if validation fails.": "Въведете персонализиран код за потвърждение.",
  "Secret Validation": "тайна проверка",
  "Check this if you wish to perform the validation ONLY on the server side. This keeps your validation logic private and secret.": "Отметнете това, ако искате да извършите валидиране само от страна на сървъра. Това запазва вашата логика за валидиране поверителна и поверителна.",
  "JSONLogic Validation": "JSON логическа проверка",
  "Execute custom logic using": "Изпълнете персонализирана логика с помощта на",
  "Validation": "проверете",
  "API": "API",
  "Property Name": "име на собственост",
  "The name of this field in the API endpoint.": "Името на това поле в крайната точка на API.",
  "Field Tags": "етикет на полето",
  "Tag the field for use in custom logic.": "Маркирайте полета за използване в персонализирана логика.",
  "Custom Properties": "персонализирани свойства",
  "This allows you to configure any custom properties for this component.": "Това ви позволява да конфигурирате всякакви персонализирани свойства за този компонент.",
  "Value": "стойност",
  "Conditional": "Условно",
  "Simple": "просто",
  "This component should Display:": "Компонентът трябва да показва:",
  "True": "истински",
  "False": "Неправилно",
  "When the form component:": "Когато компонентът на формуляра:",
  "Submit (submit)": "подавам (предоставям)",
  "Has the value:": "Има стойност:",
  "Advanced Conditions": "Разширени условия",
  "Advanced Logic": "Разширена логика",
  "Advanced Logic Configured": "Разширена логическа конфигурация",
  "Logic": "логика",
  "Add Logic": "добавете логика",
  "Trigger": "спусък",
  "JSON Logic": "JSON логика",
  "\"row\", \"data\", and \"component\" variables are available. Return \"result\".": "Налични са променливи за ред, данни и компонент. Връща \"резултат\".",
  "Action Name": "Име на действието",
  "Schema Defenition": "дефиниция на схемата",
  "\"row\", \"data\", \"component\", and \"result\" variables are available. Return the schema.": "Налични са променливи за ред, данни, компонент и резултат. Схема за връщане.",
  "Merge Component Schema": "Обединяване на архитектура на компонентите",
  "Custom Action": "персонализирано действие",
  "You must assign the show variable a boolean result.": "Трябва да присвоите булев резултат на променливата show.",
  "Note: Advanced Conditional logic will override the results of the Simple Conditional logic.": "Забележка: Разширената условна логика ще отмени резултата от проста условна логика.",
  "Example": "пример",
  "\"row\", \"data\", \"component\" and \"_\" variables are available. Return the result to be passed to the action if truthy.": "Налични са променливите \"ред\", \"данни\", \"компонент\" и \"_\". Ако е вярно, връща резултата, който трябва да бъде предаден на операцията.",
  "Add Action": "Добавете действие",
  "Save Logic": "запазете логиката",
  "Logic Name": "логическо име",
  "Event": "събитие",
  "The event that will trigger this logic. You can trigger events externally or via a button.": "Събитието, което ще задейства тази логика. Можете да задействате събития външно или чрез бутони.",
  "Save Action": "операция за запазване",
  "HTML Attributes": "HTML атрибути",
  "Attribute Name": "име на собственост",
  "Attribute Value": "стойност на атрибута",
  "Add Attribute": "добавяне на свойства",
  "The settings inside apply only to the PDF forms.": "Настройките вътре важат само за PDF формуляри.",
  "PDF Overlay": "PDF наслагване",
  "Style": "стил",
  "Custom styles that should be applied to this component when rendered in PDF.": "Персонализирани стилове, които трябва да се прилагат към този компонент при изобразяване в PDF.",
  "Page": "Страница",
  "The PDF page to place this component.": "PDF страницата, където е поставен този компонент.",
  "Left": "остават",
  "The left margin within a page to place this component.": "Лявото поле на страницата, където е поставен този компонент.",
  "The top margin within a page to place this component.": "Горното поле на страницата, където е поставен този компонент.",
  "Width": "ширина",
  "The width of the component (in pixels).": "Ширината на компонента в пиксели.",
  "Height": "Високо",
  "The height of the component (in pixels).": "Височината на компонента в пиксели.",
  "Use Thousands Separator": "Използвайте разделител за хиляди",
  "Separate thousands by local delimiter.": "Разделете хиляди с локален разделител.",
  "Decimal Places": "Десетични знаци",
  "The maximum number of decimal places.": "Максимален брой десетични знаци.",
  "Require Decimal": "нужда от десетичен знак",
  "Always show decimals, even if trailing zeros.": "Винаги показвайте десетични знаци, дори и с нули в края.",
  "Minimum Value": "минимум",
  "The minimum value this field must have before the form can be submitted.": "Минималната стойност, която това поле трябва да има, преди да изпратите формуляра.",
  "Maximum Value": "максимална стойност",
  "The maximum value this field can have before the form can be submitted.": "Максималната стойност, която това поле може да има преди изпращане на формуляра.",
  "Editor": "редактиране",
  "Select the type of WYSIWYG editor to use for this text area.": "Изберете типа WYSIWYG редактор, който да използвате за тази текстова област.",
  "ACE": "майстор",
  "Save As": "Запази като",
  "This setting determines how the value should be entered and stored in the database.": "Тази настройка определя как стойността трябва да бъде въведена и съхранена в базата данни.",
  "String": "низ",
  "JSON": "JSON",
  "Input Type": "тип вход",
  "This is the input type used for this checkbox.": "Това е типът на въвеждане, използван за това квадратче за отметка.",
  "Shortcut": "пряк път",
  "Shortcut for this component.": "Пряк път за този компонент.",
  "Password fields are automatically encrypted using 1-way salted bcrypt hashes. These hashes are also protected and not returned in the API.": "Полетата за парола се криптират автоматично с помощта на еднопосочен осолен bcrypt хеш. Тези хешове също са защитени от връщане в API.",
  "Options Label Position": "позиция на етикета на опцията",
  "Position for the label for options for this field.": "Местоположението на етикета на опцията за това поле.",
  "Right": "право",
  "Inline Layout": "вградено оформление",
  "Displays the checkboxes/radios horizontally.": "Показвайте хоризонтално квадратчетата за отметка/радио.",
  "Allow only available values": "Разрешени са само налични стойности",
  "Minimum checked number": "Минимален брой проверки",
  "Minimum checkboxes required before form can be submitted.": "Преди изпращане на формуляра са необходими минимални квадратчета за отметка.",
  "Maximum checked number": "Максимален брой проверки",
  "Maximum checkboxes possible before form can be submitted.": "Най-голямото възможно квадратче за отметка преди изпращане на формуляра.",
  "Minimum checked error message": "Съобщение за грешка при минимална проверка",
  "Error message displayed if minimum number of items not checked.": "Ако минималният брой елементи не е отметнат, се показва съобщение за грешка.",
  "Maximum checked error message": "съобщение за грешка при проверка на максималната стойност",
  "Error message displayed if maximum number of items checked.": "Ако е отметнат максималният брой елементи, ще се покаже съобщение за грешка.",
  "ChoicesJS": "изберете JS",
  "HTML 5": "HTML 5",
  "Unique Options": "уникален избор",
  "Display only unique dropdown options.": "Показват се само уникалните падащи опции.",
  "Data Source Type": "тип източник на данни",
  "The source to use for the select data. Values lets you provide your own values and labels. JSON lets you provide raw JSON data. URL lets you provide a URL to retrieve the JSON data from.": "Източникът, използван за избор на данните. Стойността ви позволява да предоставите своя собствена стойност и етикет. JSON ви позволява да предоставите необработени JSON данни. URL ви позволява да предоставите URL за извличане на JSON данни.",
  "Values": "стойности",
  "Raw JSON": "необработен JSON",
  "IndexedDB": "индексна база данни",
  "Database name": "База данни с имена",
  "The name of the indexeddb database.": "Името на базата данни indexeddb.",
  "Storage Type": "тип съхранение",
  "The type to store the data. If you select something other than autotype, it will force it to that type.": "Типът на съхраняваните данни. Ако изберете нещо различно от автоматично въвеждане, то ще го принуди да използва този тип.",
  "Autotype": "копие",
  "Boolean": "Булева стойност",
  "Object": "Предназначение",
  "ID Path": "Идентифицирайте пътя",
  "Path to the select option id.": "Изберете пътя за идентификатора на опцията.",
  "Table name": "Име на таблицата",
  "The name of table in the indexeddb database.": "Името на таблицата в базата данни indexeddb.",
  "Row Filter": "редов филтър",
  "Filter table items that match the object.": "Филтрирайте записи, които съответстват на обект.",
  "Item Template": "шаблон на артикул",
  "The HTML template for the result data items.": "HTML шаблон за получения елемент от данни.",
  "Enable Static Search ": "Активирайте статичното търсене",
  "When checked, the select dropdown will allow for searching within the static list of items provided.": "Когато е отметнато, падащото меню за избор ще позволи търсене в списъка с предоставени статични елементи.",
  "Search Threshold": "праг на търсене",
  "At what point does the match algorithm give up. A threshold of 0.0 requires a perfect match, a threshold of 1.0 would match anything.": "Кога алгоритъмът за съвпадение се отказва. Праг от 0.0 изисква перфектно съвпадение, праг от 1.0 отговаря на всичко.",
  "Read Only Value": "стойност само за четене",
  "Check this if you would like to show just the value when in Read Only mode.": "Отметнете това, ако искате да покажете стойността само в режим само за четене.",
  "Choices.js options": "Опции за Choices.js",
  "A raw JSON object to use as options for the Select component (Choices JS).": "Необработен JSON обект, използван като опции за Избор на компонент (Choices JS).",
  "Use exact search": "Използвайте точно търсене",
  "Disables search algorithm threshold.": "Деактивирайте праговете на алгоритъма за търсене.",
  "Theme": "тема",
  "The color theme of this button.": "Цветна тема за този бутон.",
  "Size": "размер",
  "The size of this button": "размера на този бутон",
  "Block Button": "Бутон за блокиране",
  "This control should span the full width of the bounding container.": "Тази контрола трябва да обхваща цялата ширина на ограничаващия контейнер.",
  "Left Icon": "лява икона",
  "This is the full icon class string to show the icon.": "Това е пълният низ за клас на икона за показване на иконата. пример:",
  "Right Icon": "дясна икона",
  "This is the full icon class string to show the icon. Example:": "Това е пълният низ за клас на икона за показване на иконата. пример:",
  "Primary": "основен",
  "Secondary": "средно училище",
  "Info": "информация",
  "Danger": "Опасност",
  "Warning": "предупреди",
  "The size of this button.": "Размерът на този бутон.",
  "Medium": "умерено",
  "Extra Small": "много малко",
  "Small": "малък",
  "Large": "голям",
  "Disable on Form Invalid": "Формулярът за деактивиране не работи",
  "This will disable this field if the form is invalid.": "Това ще деактивира това поле, ако формулярът е невалиден.",
  "Key topics for Sentiment Analysis": "Ключови теми в анализа на настроенията",
  "Enter topics to use in sentiment Analysis": "Въведете теми, които да използвате в анализа на настроенията",
  "Kickbox": "Таекуондо",
  "Enable": "активиране",
  "Enable Kickbox validation for this email field.": "Активирайте проверката на Kickbox за това поле за имейл.",
  "Validate this email using the Kickbox email validation service.": "Потвърдете този имейл с помощта на услугата за проверка на имейл Kickbox.",
  "Input Mask Placeholder Char": "символ на заместващ символ на маска за въвеждане",
  "Enable Manual Mode": "Активирайте ръчния режим",
  "Should Manual Mode be enabled for that component or not.": "Дали ръчният режим трябва да бъде активиран за този компонент.",
  "Switch To Manual Mode Label": "Превключете към раздела за ръчен режим",
  "The label for the checkbox used to switch to manual mode.": "Етикет за квадратчето за отметка, за да преминете към ръчен режим.",
  "Disable Clear Icon": "Деактивирайте иконата за изчистване",
  "Clear Icon allows easily clear components value.": "Иконата за изчистване улеснява изчистването на стойността на компонента.",
  "Provider": "доставчик",
  "Which address search service should be used.": "Коя услуга за търсене на адреси трябва да се използва.",
  "Manual Mode View String": "Преглед на низове в ръчен режим",
  "Azure Maps": "Azure карта",
  "Google Maps": "Гугъл карта",
  "API Key": "API ключ",
  "Use your Google API key here.": "Използвайте своя ключ за API на Google тук.",
  "Provider options": "опции на доставчика",
  "Specify template which should be when quering view string for the component value entered in manual mode. This string is used in table view, CSV export and email rendering. When left blank combined value of all components joined with comma will be used.": "Указва шаблона, който трябва да се използва при запитване на низове на изглед за стойности на компонента, въведени в ръчен режим. Този низ се използва за изглед на таблица, CSV експортиране и изобразяване на имейл. Когато се остави празно, ще се използва комбинираната стойност на всички компоненти, свързани със запетаи.",
  "Delimiter": "разделител",
  "What is used to separate the tags.": "Какво се използва за разделяне на етикетите.",
  "Max Tags": "макс. етикет",
  "The maximum amount of tags that can be added. 0 for infinity.": "Максималният брой тагове, които могат да бъдат добавени. 0 означава безкрайност.",
  "Store As": "Запази като",
  "String (CSV)": "низ (CSV)",
  "Array of Tags": "масив от етикети",
  "Display in Timezone": "Показване в часова зона",
  "This will display the captured date time in the select timezone.": "Това ще покаже заснетата дата и час в избраната часова зона.",
  "of Viewer": "Зрителите",
  "of Submission": "подаден",
  "of Location": "Място",
  "UTC": "UTC",
  "Use Locale Settings": "Използвайте локал",
  "Use locale settings to display date and time.": "Показване на дата и час с помощта на локални настройки.",
  "Allow Manual Input": "Разрешете ръчно въвеждане",
  "Check this if you would like to allow the user to manually enter in the date.": "Поставете отметка в това, ако искате да позволите на потребителите да въвеждат ръчно дати.",
  "Format": "Форматиране",
  "The date format for displaying the datetime value.": "Форматът на датата, използван за показване на стойности за дата и час.",
  "Shortcut Buttons": "бутон за бърз достъп",
  "You can specify few buttons which will be shown above the calendar. Use Label to specify the name of the button and onClick to specify which date/time will be set when user clicks the button. ": "Можете да посочите няколко бутона, които ще се показват над календара. Използвайте Label, за да посочите името на бутона и onClick, за да посочите датата/часа, който ще бъде зададен, когато потребителят щракне върху бутона.",
  "onClick": "щракнете",
  "Enable Date Input": "Активирайте въвеждането на дата",
  "Enables date input for this field.": "Активирайте въвеждането на дата за това поле.",
  "Use Input to add moment.js for minDate": "Добавете moment.js за minDate с въвеждане",
  "Enables to use input for moment functions instead of calendar.": "Позволява въвеждането да се използва за времеви функции вместо за календари.",
  "Use calendar to set minDate": "Задайте minDate с помощта на календар",
  "Enables to use calendar to set date.": "Позволява използването на календар за задаване на дати.",
  "Use Input to add moment.js for maxDate": "Добавете moment.js за maxDate с въвеждане",
  "Use calendar to set maxDate": "Задайте maxDate с Календар",
  "Disable specific dates or dates by range": "Деактивирайте конкретни дати или дати по диапазон",
  "Add dates that you want to blacklist. For example:": "Добавете дати, които да бъдат в черния списък. Например:",
  "Custom Disabled Dates": "персонализирана дата за деактивиране",
  "date": "дата",
  "The date object.": "обект за дата.",
  "Data Format": "Формат на данни",
  "The moment.js format for saving the value of this field.": "Форматът moment.js, използван за запазване на стойността на това поле.",
  "HTML5 Time Input": "Въвеждане на време в HTML5",
  "Text Input with Mask": "Маскирано въвеждане на текст",
  "Disable weekends": "Деактивирайте почивните дни",
  "Disable weekdays": "Деактивирайте делничните дни",
  "Check to disable weekends": "Поставете отметка, за да деактивирате уикенда",
  "Check to disable weekdays": "Поставете отметка, за да деактивирате делничните дни",
  "Enable Time Input": "Активирайте въвеждането на време",
  "Enables time input for this field": "Активирайте въвеждането на време за това поле",
  "Hour Step Size": "Часова стъпка",
  "The number of hours to increment/decrement in the time picker.": "Часове за увеличаване/намаляване в инструмента за избор на време.",
  "Minute Step Size": "минута стъпка",
  "The number of minutes to increment/decrement in the time picker.": "Броят минути за увеличаване/намаляване в инструмента за избор на време.",
  "Display time in 12 hour time with AM/PM.": "Показва часа в AM/PM 12-часово време.",
  "12 Hour Time (AM/PM)": "12-часов часовник (AM/PM)",
  "Default Date": "дата по подразбиране",
  "You can use Moment.js functions to set the default value to a specific date. For example:": "Можете да използвате функциите Moment.js, за да зададете стойности по подразбиране на конкретни дати. Например:",
  "Flatpickr options": "Flatpickr Настроики ",
  "HTML Tag": "HTML Етикет",
  "The tag of this HTML element.": "Маркировката за този HTML елемент.",
  "CSS Class": "CSS клас",
  "Attributes": "Атрибути",
  "The attributes for this HTML element. Only safe attributes are allowed, such as src, href, and title.": "Атрибути на този HTML елемент. Разрешени са само безопасни атрибути като src, href и title.",
  "Attribute": "Атрибути",
  "Refresh On Change": "освежете при промяна",
  "HTML Element": "HTML елемент",
  "Column Properties": "свойства на колоната",
  "The width, offset, push, and pull settings for each column.": "Настройки за ширина, изместване, натискане и изтегляне за всяка колона.",
  "Offset": "изместване",
  "Push": "натискам",
  "Pull": "дръпнете",
  "Auto adjust columns": "Автоматизирани колони",
  "Will automatically adjust columns based on if nested components are hidden.": "Колоната ще бъде автоматично коригирана в зависимост от това дали вложеният компонент е скрит или не.",
  "Hide Column when Children Hidden": "Скриване на колоните, когато децата са скрити",
  "Check this if you would like to hide any column when the children within that column are also hidden": "Отметнете това, ако искате да скриете колона, когато децата в тази колона също са скрити",
  "Legend": "легенда",
  "The legend for this Fieldset.": "Легендата за този набор от полета.",
  "Default": "по подразбиране",
  "Collapsible": "сгъваем",
  "If checked, this will turn this Panel into a collapsible panel.": "Ако е отметнато, това ще превърне този панел в сгъваем панел.",
  "Number of Rows": "Редове",
  "Enter the number or rows that should be displayed by this table.": "Въведете броя или броя на редовете, които тази таблица трябва да показва.",
  "Number of Columns": "брой колони",
  "Enter the number or columns that should be displayed by this table.": "Въведете числата или колоните, които тази таблица трябва да показва.",
  "Clone Row Components": "Компонент за клониране на ред",
  "Check this if you would like to": "Проверете това, ако желаете",
  "Cell Alignment": "подравняване на клетките",
  "Horizontal alignment for cells of the table.": "Хоризонтално подравняване на клетките на таблицата. заедно",
  "Center": "център",
  "Striped": "райе",
  "This will stripe the table if checked.": "Ако е отметнато, това ще очертае масата.",
  "Bordered": "граничеща",
  "This will border the table if checked.": "Ако е отметнато, това ще активира границите на таблицата.",
  "Hover": "скитащи се",
  "Highlight a row on hover.": "Маркирайте ред при задържане на курсора.",
  "Condensed": "концентриран",
  "Condense the size of the table.": "Размерът на компресираната маса.",
  "Label for Key column": "етикет на ключова колона",
  "Provide a label text for Key column (otherwise Key will be used)": "Предоставете текста на етикета за колоната Ключ (в противен случай ще се използва „Ключ“)",
  "Disable Adding / Removing Rows": "Деактивирайте добавянето/изтриването на редове",
  "Check if you want to hide Add Another button and Remove Row button": "Проверете дали искате да скриете добавяне на друг бутон и изтриване на бутони за редове",
  "Show key column before value": "Показване на ключовата колона преди стойността",
  "Check if you would like to show the Key before the Value column.": "Отметнете дали искате да покажете ключа преди колоната Стойност.",
  "Type of event": "вид дейност",
  "Specify type of event that this reCAPTCHA would react to": "Определя типа събития, на които ще реагира това reCAPTCHA",
  "Form Load": "зареждане на формуляра",
  "Button Click": "щракване върху бутона",
  "The form to load within this form component.": "Формулярът за зареждане в този компонент на формуляр.",
  "Form Revision": "Ревизия на формуляра",
  "You can lock the nested form to a specific revision by entering the revision number here.": "Можете да заключите вложен формуляр към конкретна ревизия, като въведете номера на ревизията тук.",
  "Use Original Revision while Submissions Viewing": "Използвайте оригиналната ревизия, когато преглеждате комита",
  "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission.": "Използването на тази опция ще накара формуляра да зареди оригиналната ревизия (ревизия за подаване) при преглед на подаването.",
  "Save as reference": "Запазване като справка",
  "Using this option will save this field as a reference and link its value to the value of the origin record.": "Използването на тази опция запазва това поле като препратка и свързва стойността му със стойността на оригиналния запис.",
  "Select Fields": "изберете поле",
  "The properties on the resource to return as part of the options. If left blank, all properties will be returned.": "Свойства на ресурса, върнати като част от опции. Ако се остави празно, всички свойства ще бъдат върнати.",
  "Search Fields": "поле за търсене",
  "Filter Query": "филтърна заявка",
  "Use this to provide additional filtering using query parameters.": "Използвайте това, за да осигурите допълнително филтриране с помощта на параметри на заявката.",
  "The filter query for results.": "Резултатът от заявката за филтър.",
  "Sort Query": "Заявка за сортиране",
  "Use this to provide additional sorting using query parameters": "Използвайте това, за да осигурите допълнително сортиране с помощта на параметри на заявката",
  "The sort query for results": "Заявка за сортиране за резултати",
  "Add Resource": "Добавете ресурси",
  "Allows to create a new resource while entering a submission.": "Позволява създаване на нови ресурси при въвеждане на запис.",
  "Add Resource Label": "Добавете маркери за ресурси",
  "Set the text of the Add Resource button.": "Задава текста за бутона Добавяне на ресурс.",
  "Auto Expand": "Автоматично разширяване",
  "Diagram Deployed": "Разгърната диаграма",
  "Deployment Failed": "Неуспешно внедряване",
  "Unfinished Submissions will be saved to Submissions/Drafts.": "Незавършените Подавания ще бъдат запазени в Подавания/Чернови.",
  "Changing the form workflow will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Промяната на работния процес на формуляра няма да засегне съществуващите подавания. Това ще се актуализира само в новосъздадените подавания. Натиснете Запазване на промените, за да продължите или отмените промените.",
  "Submissions are made against": "Подаванията се правят срещу",
  "Submission is made against": "Подаването се прави срещу",
  "Changing the form title will not affect the existing submissions. It will only update in the newly created submissions. Press Save Changes to continue or cancel the changes.": "Промяната на заглавието на формуляра няма да засегне съществуващите подавания. Това ще се актуализира само в новосъздадените подавания. Натиснете Запазване на промените, за да продължите или отмените промените.",
  "No submissions Found": "Няма Намерени Подавания",
  "Asignee": "Цесионер",
  "Include Assigned Task": "Включете възложена задача",
  "Variable": "Променлива",
  "Name of variable": "Име на променлива",
  "Readable name": "Четено име",
  "Specific User/ Group": "Конкретен потребител/група",
  "User": "Потребител",
  "Identifier": "Идентификатор",
  "Enter role ID": "Въведете ID на ролята",
  "Select a task in the List": "Изберете задача от списъка",
  "Select a specific task from the provided list of options. Your selection will determine the task you will be working on or interacting with.": "Изберете конкретна задача от предоставения списък с опции. Вашият избор ще определи задачата, върху която ще работите или с която ще взаимодействате.",
  "Create Form, workflow designs": "Създаване на формуляр, проекти на работни потоци",
  "Access to design": "Достъп до дизайн",
  "Create submissions": "Създаване на подавания",
  "Access to submissions": "Достъп до подавания",
  "Access to dashboards": "Достъп до табла",
  "Access to tasks": "Достъп до задачи",
  "Can claim and work on tasks": "Може да заявява и работи по задачи",
  "Manage all filters": "Управление на всички филтри",
  "Access to create filters": "Достъп до създаване на филтри",
  "Access to view filters": "Достъп до преглед на филтри",
  "Access to Integrations": "Достъп до интеграции",
  "Manage Dashboard Authorization": "Управление на разрешенията за табло",
  "Manage Users": "Управление на потребители",
  "Manage Roles": "Управление на роли" ,
  "Permissions": "Разрешения",
  "Edit Permissions": "Редактиране на разрешения",
  "Select Permissions": "Избор на разрешения", 
  "Proceed to Sign In": "Продължете към Вход",
  "Contact formsflow.ai support": "Свържете се с поддръжката на formsflow.ai",
  "Please provide your tenant name to sign in": "Моля, предоставете името на вашата аренда, за да влезете",
  "Tenant not found":"Наемателят не е намерен",
  "Access Roles": "Роли за достъп",
  "Description of the new form": "Описание на новата форма",
  "Name of the form": "Име на формуляра",
  "Duplicate": "Дублирай",
  "New Form Name": "Ново име на формуляра",
  "New Form Description": "Ново описание на формуляра",
  "Save and Edit form": "Запазване и редактиране на формуляра",
  "Build New Form": "Създай нов формуляр",
  "Settings": "Настройки",
  "Live": "На живо",
  "Draft": "Чернова",
  "Publish": "Публикувай",
  "Unpublish": "Оттегляне на публикация",
  "Save Layout": "Запази оформлението",
  "Discard Changes": "Отхвърли промените",
  "Flow": "Поток",
  "You Have Unsaved Changes": "Имате незапазени промени",
  "You have made changes that are not saved yet. The unsaved changes could be either on the Layout or the Flow side.": "Вие сте направили промени, които все още не са запазени. Незапазените промени могат да бъдат както в оформлението, така и в потока.",
  "Note": "Забележка",
  "Stay in the Editor": "Останете в редактора",
  "Discard Changes and Leave the Page": "Отхвърлете промените и напуснете страницата",
  "Confirm Unpublish": "Потвърдете оттеглянето на публикацията",
  "This form is currently live. To save changes to form edits, you need to unpublish it first. By Unpublishing this form, you will make it unavailable for new submissions to those who currently have access to it. You can republish the form after making your edits.": "Тази форма е в момента активна. За да запазите промените в редакциите на формата, трябва първо да оттеглите публикацията. С оттеглянето на публикацията, формата ще стане недостъпна за нови подавания за тези, които в момента имат достъп до нея. Можете да публикувате формата отново след редактирането.",
  "Unpublish and Edit This Form": "Оттеглете публикацията и редактирайте тази форма",
  "Cancel, Keep This Form Unpublished": "Отказ, оставете тази форма непубликувана",
  "Confirm Publish": "Потвърдете публикуването",
  "Publishing will save any unsaved changes and lock the entire form, including the layout and the flow. To perform any additional changes you will need to unpublish the form again.": "Публикуването ще запази всички незапазени промени и ще заключи цялата форма, включително оформлението и потока. За да направите допълнителни промени, ще трябва да премахнете публикацията на формата отново.",
  "Publish This Form": "Публикувайте тази форма",
  "Import": "Импортиране",
  "Allowing the addition of multiple pages in a single form will prevent you from using this form in a bundle later.": "Позволяването на добавянето на множество страници в една форма ще ви попречи да използвате тази форма в пакет по-късно.",
  "Allow adding multiple pages in this form": "Позволете добавяне на множество страници в тази форма",
  "Who Can View/Edit This Form": "Кой може да разглежда/редактира тази форма",
  "Only You": "Само вие",
  "You and specified roles": "Вие и посочените роли",
  "Who Can Create Submissions": "Кой може да създава подавания",
  "Anonymous users": "Анонимни потребители",
  "Registered users": "Регистрирани потребители",
  "Specific roles": "Специфични роли",
  "Who Can View Submissions": "Кой може да разглежда подаванията",
  "Submitter": "Подател",
  "Submitter and specified roles": "Подател и посочените роли",
  "Link for this form": "Линк към тази форма",
  "Making changes to your form URL will make your form inaccessible from your current URL.": "Промяната на URL адреса на вашата форма ще направи формата ви недостъпна от текущия URL адрес.",
  "Save Your Changes": "Запазете вашите промени",
  "Saving as an incremental version will affect previous submissions. Saving as a new full version will not affect previous submissions.": "Запазването като инкрементална версия ще засегне предишните подавания. Запазването като нова пълна версия няма да засегне предишните подавания.",
  "Save as Version": "Запазете като версия",
  "Discard Layout Changes?": "Да изхвърлите ли промените в оформлението?",
  "Are you sure you want to discard all the changes to the layout of the form?": "Сигурни ли сте, че искате да изхвърлите всички промени в оформлението на формуляра?",
  "This action cannot be undone.": "Това действие не може да бъде отменено.",
  "Yes, Discard Changes": "Да, изхвърлете промените",
  "No, Keep My Changes": "Не, запазете моите промени",
  "Save Flow": "Запазете потока",
  "Revert To This": "Върнете към това",
  "Last Edit On": "Последна редакция на",
  "Last Edit By": "Последна редакция от",
  "Variables for Flow, Submissions, and Tasks": "Променливи за поток, подавания и задачи",
  "To use variables in the flow, as well as sorting by them in the submissions and tasks you need to specify which variables you want to import from the layout. Variables get imported into the system at the time of the submission, if the variables that are needed are not selected prior to the form submission THEY WILL NOT BE AVAILABLE in the flow, submissions, and tasks.": "За да използвате променливи в потока, както и за да ги сортирате в подаванията и задачите, трябва да посочите кои променливи искате да импортирате от оформлението. Променливите се импортират в системата по време на подаването, ако необходимите променливи не са избрани преди подаването на формуляра, ТЕ НЯМА ДА БЪДАТ НАЛИЧНИ в потока, подаванията и задачите.",
  "Selected Variables": "Избрани променливи",
  "Pick variables below": "Изберете променливи по-долу",
  "Select a form field on the left": "Изберете поле на формуляра отляво",
  "Discard Flow Changes?": "Да изхвърлите ли промените в потока?",
  "Are you sure you want to discard all unsaved changes to the flow of the form?": "Сигурни ли сте, че искате да изхвърлите всички незапазени промени в потока на формуляра?",
  "Yes, Discard All Unsaved Changes": "Да, изхвърлете всички незапазени промени",
  "No, Keep The Changes": "Не, запазете промените",
  "Import File": "Импортиране на файл",
  "Click or drag a file to this area to import (form, layout or bpmn)": "Кликнете или плъзнете файл в тази област, за да импортирате (форма, оформление или BPMN)",
  "Support for a single .json, .bpmn file upload. Maximum file size 20MB.": "Поддържа се качване на един .json или .bpmn файл. Максимален размер на файла: 20MB.",
  "Confirm And Replace": "Потвърдете и заменете",
  "Export Form": "Експортиране на форма",
  "Export in Progress": "Експортирането е в ход",
  "Export Successful": "Експортирането беше успешно",
  "Are You Sure You Want to Delete This Form?": "Сигурни ли сте, че искате да изтриете тази форма?",
  "No, Keep This Form": "Не, запазете тази форма",
  "Yes, Delete the Form": "Да, изтрийте формата",
  "Importing and deleting is not available when the form is published. You must unpublish the form first if you wish to make any changes.": "Импортирането и изтриването не са налични, когато формата е публикувана. Трябва първо да я оттеглите, ако искате да направите промени.",
  "Search Form Name and Description": "Търсене на име и описание на формуляра",
  "New Form": "Нова форма",
  "Add Form": "Добави форма",
  "Build": "Изграждане",
  "Create the form from scratch": "Създайте формуляр от нулата",
  "Upload form from a file": "Качете формуляр от файл",
  "Last Edited": "Последно редактирано",
  "ID": "ИД",
  "New BPMN": "Нов BPMN",
  "Create the BPMN from scratch": "Създайте BPMN от нулата",
  "Upload BPMN from a file": "Качете BPMN от файл",
  "Search BPMN Name": "Търсене на име на BPMN",
  "New DMN": "Ново DMN",
  "Search Decision Table": "Търсене на таблица за решения",
  "Create the DMN from scratch": "Създайте DMN от нулата",
  "Upload DMN from a file": "Качете DMN от файл",
  "Create And Edit BPMN": "Създаване и редактиране на BPMN",
  "Create And Edit DMN": "Създаване и редактиране на DMN",
  "Import New Form": "Импортиране на нова форма",
  "Confirm and Edit form": "Потвърдете и редактирайте формата",
  "Click or drag a file to this area to import": "Щракнете или плъзнете файл в тази област, за да го импортирате",
  "Import New": "Импортиране на ново",
  "Search DMN Name": "Търсене на име DMN",
  "cancel": "Отмени",
  "previous": "Предишна",
  "next": "Следваща", 
  "Month": "Месец", 
  "Year": "Година",
  "Sort": "Сортирай",
  "Sort Results": "Резултати от сортирането",
  "Sort By": "Сортиране по",
  "In a": "В",
  "Sort By Dropdown": "Раздел Сортиране по",
  "Sort By Input": "Вход Сортиране по",
  "Order Dropdown": "Раздел Ред",
  "Order Input": "Вход Ред",
  "Apply sorting": "Приложи сортиране",
  "build new form with AI": "Създайте нова форма с AI",
  "Flow-E": "Flow-E",
  "Message Flow-E": "Съобщение до Flow-E",
  "Select this Layout": "Изберете този дизайн",
  "Your form is now ready": "Вашият формуляр е готов",
  "For further customization, please provide specifications.": "За допълнително персонализиране, моля, предоставете спецификации.",
  "Regenerate": "Генерирай отново",
  "Start Over": "Започнете отначало",
  "Undo": "Отмяна",
  "I am Flow-E.": "Аз съм Flow-E.",
  "I can help you design forms effortlessly. I will build out the fields and layout for you, which you can further customize or you can": "Мога да ви помогна да създавате формуляри с лекота. Ще изградя полетата и оформлението за вас, които можете допълнително да персонализирате, или можете",
  "Try an Example Prompt": "Опитайте примерен подкана",
  "Select Template For New Form": "Изберете шаблон за нова форма",
  "Select This Template": "Изберете този шаблон",
  "form": "форма",
  "flow": "поток",
  "all templates": "всички шаблони",
  "Nothing is found. Please try again.": "Нищо не беше намерено. Моля, опитайте отново.",
  "Search ...": "Търсене ...",
  "Use AI": "Използвайте AI",
  "Build form using Flow-E AI chatbot": "Създайте форма с помощта на Flow-E AI чатбот",
  "Start off from a template": "Започнете с шаблон",
  "Export Failed": "Неуспешен износ",
  "Create Duplicate": "Създаване на дубликат",
  "Are you sure you want to duplicate the current BPMN?": "Сигурни ли сте, че искате да дублирате текущия BPMN?",
  "Yes, Duplicate This BPMN": "Да, дублирайте този BPMN",
  "No, Do Not Duplicate This BPMN": "Не, не дублирайте този BPMN",
  "Export BPMN": "Експортиране на BPMN",
  "Publish This BPMN": "Публикувайте този BPMN",
  "Are you sure you want to duplicate the current DMN?": "Сигурни ли сте, че искате да дублирате текущия DMN?",
  "Yes, Duplicate This DMN": "Да, дублирайте този DMN",
  "No, Do Not Duplicate This DMN": "Не, не дублирайте този DMN",
  "Publish This DMN": "Публикувайте този DMN",
  "Publishing will lock the {{type}}. To save changes on further edits, you will need to unpublish the {{type}} first.": "Публикуването ще заключи {{type}}. За да запишете промените при бъдещи редакции, ще трябва първо да отмени публикуването на {{type}}.",
  "Unpublish and Edit This BPMN": "Отменете публикуването и редактирайте този BPMN",
  "Cancel, Keep This BPMN published": "Откажете, оставете този BPMN публикуван",
  "This {{type}} is currently live. To save changes to {{type}} edits, you need to unpublish it first.": "Този {{type}} в момента е онлайн. За да запишете промените в редакциите на {{type}}, трябва първо да го отмените.",
  "Unpublish and Edit This DMN": "Отменете публикуването и редактирайте този DMN",
  "Cancel, Keep This DMN published": "Откажете, запазете този DMN публикуван",
  "You Cannot Delete This Form": "Не можете да изтриете тази форма",
  "But you may unpublish it if you wish to not receive any more submissions.": "Но можете да я отмените, ако не желаете да получавате повече подадени заявки.",
  "You may not delete a form that has submissions associated with it.": "Не можете да изтриете форма, свързана с подадени заявки.",
  "Keep This Form": "Запазете тази форма",
  "Unpublish This Form": "Отменете публикуването на тази форма",
  "A system error occurred during export. Please try again.": "По време на експортиране възникна системна грешка. Моля, опитайте отново.",
  "Try Again": "Опитайте отново",
  "No forms have been found. Create a new form by clicking the \"New Form\" button in the top right.": "Не са намерени формуляри. Създайте нов формуляр, като щракнете върху бутона „Нов формуляр“ в горния десен ъгъл.",
  "No subflows have been found. Create a new subflow by clicking \"New BPMN\" button in the top right.": "Не са намерени подпотоци. Създайте нов подпоток, като щракнете върху бутона „Нов BPMN“ в горния десен ъгъл.",
  "No decision tables have been found. Create a new decision table by clicking \"New DMN\" button in the top right.": "Не са намерени таблици за решения. Създайте нова таблица за решения, като щракнете върху бутона „Нов DMN“ в горния десен ъгъл.",
  "Form Submitted": "Формулярът е изпратен",
  "Sample form submitted": "Изпратен е примерен формуляр",
  "Type of Block to Add": "Тип блок за добавяне",
  "Blocks that do something": "Блокове, които правят нещо",
  "Condition": "Условие",
  "Decision making expression": "Израз за вземане на решение",
  "Send email": "Изпрати имейл",
  "Sends a pre-defined email": "Изпраща предварително дефиниран имейл",
  "Action: send Email": "Действие: изпращане на имейл",
  "Recipient": "Получател",
  "Subject": "Тема",
  "Body": "Съдържание",
  "Select a Variable": "Изберете променлива",
  "Search Available Variable": "Търсене на налична променлива",
  "More Variables from Form’s Layout": "Още променливи от оформлението на формуляра",
  "Use This Variable": "Използвайте тази променлива",
  "Use integration": "Използвайте интеграция",
  "Sends or gets data from an integration through a recipe (workato)": "Изпраща или получава данни от интеграция чрез рецепта (Workato)",
  "Action: Use Integration Modal": "Действие: Използване на интеграционен модул",
  "Recipe": "Рецепта",
  "Exclude Fields": "Изключване на полета",
  "Create task": "Създаване на задача",
  "Creates a task for a specific user or a user role": "Създава задача за конкретен потребител или роля на потребител",
  "Action: Create Task": "Действие: Създаване на задача",
  "Create a task for": "Създаване на задача за",
  "Specific Roles": "Специфични роли",
  "Set/update variable value": "Задаване/актуализиране на стойност на променлива",
  "Assigns value to a specified variable": "Присвоява стойност на посочената променлива",
  "Action: Set/Update Variable Value": "Действие: Задаване/Актуализиране на стойност на променлива",
  "Variable to update": "Променлива за актуализиране",
  "New value for the variable": "Нова стойност за променливата",
  "Variable to update is required.": "Необходимо е да се зададе променлива за актуализиране.",
  "Action Name is required": "Името на действието е задължително",
  "Action Name is required.": "Името на действието е задължително.",
  "New value for the variable is required.": "Необходима е нова стойност за променливата.",
  "Condition Name": "Име на условието",
  "Expression": "Израз",
  "Expression Builder": "Създател на изрази",
  "Condition Name is required": "Необходимо е име на условието",
  "Pick Variable": "Изберете променлива",
  "Form variable": "Променлива на формата",
  "Custom Value": "Персонализирана стойност",
  "Empty Expression": "Празен израз",
  "Search Form Variable": "Търсене на променлива на формата",
  "Set Value": "Задайте стойност",
  "Enter Custom Value": "Въведете персонализирана стойност",
  "Pick An Operator": "Изберете оператор",
  "(add) Adds values together": "(събиране) Събира стойности заедно",
  "(subtract) Subtracts values": "(изваждане) Изважда стойности",
  "(divide) Divides values": "(делене) Деление на стойности",
  "(multiply) Multiplies values": "(умножение) Умножава стойности",
  "(or) Evaluates true if value on the left OR on the right is not empty": "(или) Оценява като вярно, ако стойността отляво ИЛИ отдясно не е празна",
  "(and) Evaluates true if value on the left AND on the right is not empty": "(и) Оценява като вярно, ако стойностите отляво И отдясно не са празни",
  "(less than) Evaluates true if the value on the left is less than value on the right": "(по-малко от) Оценява като вярно, ако стойността отляво е по-малка от тази отдясно",
  "(larger than) Evaluates true if the value on the left is larger than value on the right": "(по-голямо от) Оценява като вярно, ако стойността отляво е по-голяма от тази отдясно",
  "(less than or equal) Evaluates true if the value on the left is less than or equal to the value on the right": "(по-малко или равно) Връща вярно, ако стойността отляво е по-малка или равна на стойността отдясно",
  "(larger than or equal) Evaluates true if the value on the left is larger than or equal to the value on the right": "(по-голямо или равно) Връща вярно, ако стойността отляво е по-голяма или равна на стойността отдясно",
  "(equals) Evaluates true if the value on the left is equal to the value on the right": "(равно) Връща вярно, ако стойността отляво е равна на стойността отдясно",
  "(contains) Evaluates true if text contains some specified text (not case sensitive)": "(съдържа) Връща вярно, ако текстът съдържа определен текст (без чувствителност към главни и малки букви)",
  "Add your condition": "Добавете вашето условие",
  "Are you sure you want to Delete the Node ?": "Сигурни ли сте, че искате да изтриете възела?",
  "If you delete this node , you won't be able to undo this action. Are you sure you want to proceed?": "Ако изтриете този възел, няма да можете да отмените това действие. Сигурни ли сте, че искате да продължите?",
  "No, Keep This Node": "Не, запазете този възел",
  "Yes, Delete the Node": "Да, изтрийте възела",
  "Recipient is required.": "Получателят е задължителен.",
  "Switch to BPMN ": "Превключване към BPMN",
  "Switch to Bpmn": "Превключване към BPMN",
  "Keep Editing My Flow in No-Code": "Продължете да редактирате моя поток в No-Code",
  "Pick No-code version": "Изберете версията без код",
  "Return to No-code": "Върнете се към No-Code",
  "Delete All Changes and Pick No-Code Version": "Изтрийте всички промени и изберете версията без код",
  "Stay in BPMN": "Останете в BPMN",
  "This will copy the flow from Version 1.1 overwriting your existing flow.": "Това ще копира потока от версия 1.1, като презапише съществуващия ви поток.",
  "Use Flow from Version 1.1": "Използвайте потока от версия 1.1",
  "Keep Current Flow": "Запазете текущия поток",
  "Replace Current flow": "Заменете текущия поток",
  "Load More": "Зареди още",
  "Invalid Expression": "Невалиден израз",
}
