/* eslint-disable max-len */
export const RESOURCE_BUNDLES_BG = {
    "Access restricted by its designer..!": "Достъпът е ограничен от дизайнера..!",
    "and you will no longer have the access to this form in bundles": "и няма да имате достъп до тази форма в пакети",
    "You will no longer have the access to this form in bundles": "Вече няма да имате достъп до тази форма в пакети",
    "Bad Request":"Неправилна заявка",
    "Select the form to be displayed based on the  above criteria":"Изберете формуляра, който да се показва въз основа на горепосочените критерии.",
    "Create the criteria using the API key of any form component and a conditional notation. For example, 'age > 18' where 'age' is the API key of a form component":"Създайте критериите, използвайки API ключа на който и да е компонент на формуляр и условна нотация. Например, 'age > 18', където 'age' е API ключът на компонент на формуляр.",
    "Select form version":"Изберете версия на формуляра",
    "Please remove the special characters...!":"Моля, премахнете специалните символи...!",
    "No histories found":"Няма намерени истории",
    "Continue":"продължи",
    "This will create a new version of the form without changing the path name but with new form id.":"Това ще създаде нова версия на формуляра без промяна на името на пътя, но с нов идентификатор на формуляра.",
    "Save as a new version":"Запазете като нова версия",
    "Save New Version":"Запазване на новата версия",
    "Do you want to save a new version of this form?":"Искате ли да запазите нова версия на този формуляр?",
    "Do you want to create a duplicate form and associated workflow from existing form ?":"Искате ли да създадете дублиран формуляр и свързан работен процес от съществуващ формуляр?",
    "New version created":"Създадена е нова версия",
    "Create a duplicate form":"Създайте дублиран формуляр",
    "Show more":"Покажи повече",
    "Modified By":"Променен от",
    "Created On" :"Създадено на",
    "Formsflow automatically saves your previous form data. Now you can switch to the previous stage and edit.":"Formsflow автоматично запазва предишните ви данни за формуляри. Сега можете да преминете към предишния етап и да редактирате.",
    "Duplicate Form":"Дублиран формуляр",
    "Form History":"История на формуляра",
    "No file chosen":"Няма избран файл",
    "Choose File":"Изберете файл",
    "Choose any":"Изберете всяка",
    "Sort by form name":"Сортиране по име на формуляр",
    "select form type":"изберете тип формуляр",
    "Draft Deleted Successfully":"Черновата е изтрита успешно",
    "Saved to Applications/Drafts":"Запазено в Приложения/Чернови",
    "Unfinished applications will be saved to Applications/Drafts.":" Незавършените приложения ще бъдат запазени в Приложения/Чернови.",
    "Discard Draft":"Отхвърлете черновата",
    "Are you sure you wish to delete the draft":"Сигурни ли сте, че искате да изтриете черновата",
    "with ID":"с лична карта",
    "Please change the selected filters to view Forms":"Моля, променете избраните филтри, за да видите формуляри",
    "Search by form name":"Tŭrsene po ime na formulyara",
    "Click to search":"Щракнете за търсене",
    "No submissions found":"Няма намерени заявки",
    "No submission avaliable in the selected date. Please select another date range":"Няма налично подаване на избраната дата. Моля, изберете друг период от време",
    "Dashboards":"Табла за управление",
    "Form field":"Поле за формуляр",
    "Enter Label":"Въведете етикет",
    "Select form field":"Изберете поле на формуляра",
    "Add form fields to display in task list":"Добавете полета на формуляра за показване в списъка със задачи",
    "Latest Version":"Последна версия",
    "Submission Status":"Състояние на подаване",
    "No submission status":"Няма състояние на подаване",
    "No Public url found":"Не е намерен публичен URL адрес",
    "Show in list":"Показване в списъка",
    "Select Task Variable":"Изберете променлива на задачата",
    "Enter your Label":"Въведете своя етикет",
    "Select Key":"Изберете Ключ",
    "Create Your Task Variable":"Създайте своята променлива на задачата",
    "No task variable selected": "Няма избрана променлива на задачата",
    "Workflow Associate":"Работен сътрудник",
    "Task variable":"Променлива на задачата",
    "Enter pathname":"Въведете име на път",
    "Submission Saved": "Изпращането е запазено.",
    "Form saved": "Формулярът е запазен.",
    "Error while Submission.": "Грешка при изпращане.",
    "Message": "Моля, поправете грешките, преди да изпратите отново.",
    "Submission cannot be done.": "Подаването не може да се извърши.",
    "Are you sure you wish to delete the form": "Сигурни ли сте, че искате да изтриете формуляра",
    "Edit": "редактиране",
    "Text Field": "текстово поле",
    "Do you want to associate form with a workflow ?": "Искате ли да свържете формата с работен поток?",
    "Yes": "да",
    "No": "Не",
    "Please select from one of the following workflows.": "Моля, изберете един от следните работни потоци.",
    "Form Name": "Име на формуляра",
    "Workflow Name": "Име на работния процес",
    "Publish this form for Client Users.": "Публикувайте този формуляр за Клиентски потребители.",
    "Comments": "Коментари",
    'Back': "обратно",
    "Edit Form": "Редактиране на формуляр",
    "Next": "Следващия",
    "Are you sure you wish to delete this submission?": "Наистина ли искате да изтриете това изпращане?",
    "Save": "Запазете",
    "Back to Form List": "Назад към списъка с формуляри",
    "Submit New": "Изпратете ново",
    "View Submissions": "Преглед на подадените материали",
    "View/Edit Form": "Преглед/Редактиране на формуляр",
    "Delete Form": "Изтриване на формуляр",
    "Delete": "Изтрий",
    "Print As PDF": "Печат като PDF",
    "Applications": "Приложения",
    "Tasks": "Задачи",
    "Metrics": "Метрика",
    "Dashboard": "Табло",
    "Logout": "Излез от профила си",
    "No tasks found": "Няма намерени задачи",
    "Please change the selected filters to view tasks": "Моля, променете избраните филтри, за да видите задачите",
    "Clear all filters": "Изчистете всички филтри",
    "Created": "Създаден",
    "Task Variables": "Променливи на задачата",
    "Process Variables": "Променливи на процеса",
    "Process Definition Name": "Име на дефиниция на процеса",
    "Assigne": "Цесионер",
    "Candidate Group": "Кандидатска група",
    "Candidate User": "Кандидат потребител",
    "Name": "име",
    "Description": "Описание",
    "Priority": "Приоритет",
   "Due Date": "Краен срок",
    "Follow up Date": "Дата на проследяване",
   "Task name": "Име на задачата",
    "Remove sorting": "Премахване на сортирането",
    "Ascending": "Възходящ",
    "Descending": "Низходящо",
    "Add sorting": "Добавете сортиране",
    "of the criteria are met.": "от критериите са изпълнени.",
    "For Variable, ignore case of": "За променлива, пренебрегвайте регистъра на",
    "value": "стойност",
    "No task matching filters found.": "Няма намерени филтри за съвпадение на задачи.",
     "Application ID": "Идентификационен номер на заявление",
    "Set follow-up Date": "Задайте дата за проследяване",
    "Set Due date": "Задайте крайна дата",
    "Add groups": "Добавете групи",
    "Claim": "Претенция",
    "Search By Last Name": "Търсене по фамилно име",
    "Search By First Name": "Търсене по собствено име",
     "Search By Email": "Търсене по имейл",
    "You can add a group by typing a group ID into the input field and afterwards clicking the button with the plus sign.": "Можете да добавите група, като въведете идентификатор на групата в полето за въвеждане и след това щракнете върху бутона със знака плюс.",
    "Add a group": "Добавете група",
    "Process Name": "Име на процеса",
    "Set FollowUp Date": "Задайте дата на последващо действие",
    "Groups": "групи",
    "Click to Change Assignee": "Щракнете, за да промените правоприемника",
    "Reset Assignee": "Нулиране на назначения",
    "Update User": "Актуализирайте потребителя",
    "Close": "Близо",
    "Type": "Тип",
    "Remove search": "Премахнете търсенето",
    "Property": "Имот",
    "Operator": "Оператор",
    "Total number of results": "Общ брой резултати",
    "Filter Tasks": "Филтриране на задачи",
    "All": "ВСИЧКО",
    "ANY": "ВСЕКИ",
    "Task assignee": "Възложител на задачата",
    "Application History": "История на приложенията",
   "View Submission": "Вижте подаване",
    'Showing': "Показване",
    "to": "да се",
    "results": "pезултати",
    "Acknowledge": "Признайте",
    'View': "Преглед",
    "Select a task in the list.": "Изберете задача от списъка.",
    "No Filters Found": "Няма намерени филтри",
    "Loading": "Зареждане",
    "Form": "Формуляр",
    "History": "История",
    "Diagram": "Диаграма",
    "Delete Confirmation": "Изтриване на потвърждение",
    "All tasks": "Всички задачи",
    "Manage Groups": "Управление на групи",
    "Group ID": "ID на групата",
    "Due": "В следствие",
    "Follow-up": "Проследяване",
    "Application Name": "Име на приложението",
    "Created By": "Създадено от",
    "Application Status": "Състояние на приложението",
    "Request Status": "Състояние на заявката",
    "Request Name": "Име на заявката",
    "Submitted On": "Изпратено на",
    "Modified On": "Променено Включено",
    "No History Found": "Няма намерена история",
    "Process Diagram": "Диаграма на процеса",
    "Details": "Подробности",
    "Status": "Състояние",
    "Submissions": "Изявления",
    "No Application History found": "Няма намерена история на приложения",
    "Link To Form Submission": "Връзка към подаване на формуляр",
    "Last Modified": "Последно модифициран",
    "Insights": "Прозрения",
    "No dashboard found": "Няма намерено табло",
    "of": "на",
    "Select Dashboard": "Изберете Табло за управление",
    "Total Submissions": "Общо представяне",
    "Operations": "Операции",
    "Access Groups": "Групи за достъп",
    "Action": "Действие",
    "Add": "Добавете",
    "Admin": "Админ",
    "Create Form": "Създайте формуляр",
    "Upload Form": "Формуляр за качване",
    "Download Form": "Изтеглете формуляр",
    "Upload json form only": "Качете само json формуляр",
    "Select atleast one form": "Изберете поне един формуляр",
    "Select All": "Избери всички",
    "Created Date": "Дата на създаване",
    "Modified Date": "Дата на промяна",
    "File Upload Status": "Състояние на качване на файл",
    "Forms Completed": "Формулярите са попълнени",
    "Form Completed" : "Формулярът е попълнен",
    "No forms found": "Няма намерени формуляри",
    "Powered by ": "Задвижвани от ",
    "No Process Diagram found": "Не е намерена диаграма на процеса",
    "No applications found": "Няма намерени приложения",
    "Successfully Updated": "Актуализирано успешно",
    "Failed": "Се провали",
    "Press Enter key or click here to search": "Натиснете клавиша Enter или щракнете тук, за да търсите",
    "Click to clear": "Щракнете, за да изчистите",
    "Search...": "Търсене...",
    "Click here to back": "Щракнете тук, за да се върнете назад",
    "Enter the form title": "Въведете заглавието на формуляра",
    "Enter the form machine name": "Въведете името на машината за формуляра",
    "Display as": "Показване като",
    "Path": "пътека",
    "example": "Exemplo",
    "Title": "Заглавие",
    "Anonymous Form ": "Анонимен формуляр",
    "Make this form public ?": "Да се ​​направи ли този формуляр публичен?",
    "Save & Preview": "Запазване и визуализация",
    "Design Form": "Формуляр за проектиране",
    "Associate this form with a workflow?": "Да се ​​свърже ли този формуляр с работен поток?",
    "Preview and Confirm": "Преглед и потвърждение",
    "All steps completed - you're finished": "Всички стъпки завършени - сте готови",
    "Forms": "Форми",
    "Downloaded Successfully":"Изтеглено успешно",
    "Error in JSON file structure":"Грешка във файловата структура на JSON",
    "Please fix the errors before submitting again.":"Моля, поправете грешките, преди да изпратите отново.",
    "Loading...":"Зареждане...",
    "Wizard":"Магьосник",
    "Save Form":"Запазване на формуляр",
    "Confirm":"Потвърдете",
    "Cancel":"Отмяна",
    "Please change the selected filters to view applications":"Моля, променете избраните филтри, за да видите приложения",
    "No submissions available for the selected date range":"Няма налични заявки за избрания период от време",
    "OK":"Добре",
    "Form not available":"Формулярът не е наличен",
    "Thank you for your response.":"Благодаря ви за отговора.",
    "saved successfully":"Запазено успешно",
    "Copy anonymous form URL":"Копирайте URL на анонимен формуляр",
    "Submitted By":"Изпратено от",
    "Confirmation":"Потвърждение",
    "Changing the form title will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"Промяната на заглавието на формуляра няма да засегне съществуващите приложения. Той ще се актуализира само в новосъздадените приложения. Натиснете Запазване на промените, за да продължите или отмените промените.",
    "Error while saving Form":"Грешка при запазване на формуляра",
    "Click here to go back":"Щракнете тук, за да се върнете",
    " Applications are submitted against":" Заявленията се подават срещу",
    " Application is submitted against":" Заявлението се подава срещу",
    ". Are you sure want to delete ?":". Наистина ли искате да изтриете?",
    "Are you sure you wish to delete the form ":"Сигурни ли сте, че искате да изтриете формуляра",
    "Are you sure you wish to delete the form?":"Сигурни ли сте, че искате да изтриете формуляра?",
    "Save Changes":"Запазите промените",
    "Changing the form workflow will not affect the existing applications. It will only update in the newly created applications. Press Save Changes to continue or cancel the changes.":"Промяната на работния процес на формуляра няма да засегне съществуващите приложения. Той ще се актуализира само в новосъздадените приложения. Натиснете Запазване на промените, за да продължите или отмените промените.",
    "Form-Workflow association saved.":
    "Асоциацията на формуляр-работен процес е запазена.",
    "Form-Workflow association failed.":
      "Неуспешно свързване на формуляр-работен процес.",
    "Form deletion unsuccessful":"Изтриването на формуляра е неуспешно",
    "Form deleted successfully":"Формулярът е изтрит успешно",
    "Bundle deleted successfully":"Пакетът е изтрит успешно",
    "Form process failed":"Обработката на формуляра не бе успешно",
    "Form unpublishing Failed":"Прекратяването на публикуването на формуляра не бе успешно",
    "All groups have access to the dashboard":"Всички групи имат достъп до таблото",
    "Export PDF": "Експортиране на PDF",
    "Something went wrong. Please try again!":"Нещо се обърка. Моля, опитайте отново!",
    "No Dashboards Found":"Няма намерени табла за управление",
    "Processes":"процеси",
    "Please select an existing workflow.":"Моля, изберете съществуващ работен процес.",
    "Create New":"Създай нов",
    "Or create new workflow or import a workflow from a local directory.":"Или създайте нов работен поток или импортирайте работен поток от локална директория.",
    "The operation couldn't be completed. Please try after sometime":"Операцията не можа да бъде завършена. Моля, опитайте след известно време",
    "Select...":"Изберете...",
    "No Drafts Found":  "Няма намерени чернови",
    "Help":"Помогне",
    "Draft Id":"Чернова на ID",
    "Draft Name":"Име на черновата",
    "Link To Draft Submission":"Връзка към изпращане на чернова",
    "Drafts":"Чернови",
    "You can't submit this form until it is published":"Не можете да изпратите този формуляр, докато не бъде публикуван",
    "Form not published":"Формулярът не е публикуван",
    "Access Denied" : "Отказан достъп",
    "By default, the tenant key would be prefixed to form":"По подразбиране ключът на клиента ще има префикс за форма",
    "go back":"Върни се",
    "No Applications Found":"Няма намерени приложения",
    "Submission saved to draft.":"Изпращането е запазено в чернова.",
    "Saved to draft":"Запазено в чернова",
    "Saving...":"Запазва се...",
    "Resource":"Ресурс",
    "Error in creating form process mapper":"Грешка при създаването на картограф на процес на формуляр",
    "Select the date":"Изберете датата",
    "Diagram deployed":"Диаграмата е разгърната",
    "Deployment failed":"Неуспешно внедряване",
    "form uploaded":"качен формуляр",
    "forms uploaded":"качени формуляри",
    "Failed to upload":"Неуспешно качване",
    "forms...!":"форми...!",
    "form...!":"форма...!",
    "Process name(s) must not be empty":"Името(ата) на процесите не трябва да са празни",
    "URL copied":"URL адресът е копиран",
    "Click Here to Copy":"Щракнете тук, за да копирате",
    "Resources":"Ресурси",
    "Duplicate form created successfully":"Дублираният формуляр е създаден успешно",
    "Revert": "Връщане",
    "Are you sure you wish to delete the bundle ": "Сигурни ли сте, че искате да изтриете пакета ",
    "Criteria":"Критерии",
    "Select Form":"Изберете Формуляр",
    "Create Condition":"Създаване на условие",
    "Enter criteria":"Въведете критерии",
    "Make this form public":"Направете този формуляр публичен",
    "Enable bundling":"Активиране на групирането",
    "Bundle Name": "Име на пакета",
    "View/Edit": "Преглед/редактиране",
    "Create Bundle": "Създаване на пакет",
    "Rows per page": "Редове на страница",
    "entries": "записи",
    "Form Bundle": "Пакет формуляри",
    "No bundles found": "Няма намерени пакети",
    "Please change the selected filters to view Bundles": "Моля, променете избраните филтри, за да видите пакети",
    "Select all to download forms": "Изберете всички, за да изтеглите формуляри",
    "Select for download": "Изберете за изтегляне",
    "Bundle Description": "Описание на пакета",
    "Conditions": "Условия",
    "Enter name": "Въведи име",
    "Enter Description": "Въведете описание",
    "You can change the form order by drag and drop": "Можете да промените реда на формуляра чрез плъзгане и пускане",
    "Form Order": "Форма за поръчка",
    "Form Type": "Тип формуляр",
    "Add Forms Launch together": "Добавете Forms Launch заедно",
    "Form bundles can save your time by grouping forms together": "Пакетите формуляри могат да ви спестят време чрез групиране на формуляри заедно",
    "Add Forms": "Добавете формуляри",
    "Create Conditions": "Създаване на условия",
    " Add Conditions": "Добавяне на условия",
    "Select Forms": "Изберете Формуляри",
    "Insert": "Поставете",
    "View Form": "Преглед на формуляра",
    "Publish this Bundle for Client Users.": "Публикувайте този пакет за клиентски потребители",
    "Total Forms": "Общо формуляри",
    "Edit Bundle": "Редактиране на пакет",
    "Next Form": "Следваща форма",
    "Previous Form": "Предишна форма",
    "Forms included under the package": "Формуляри, включени в пакета",
    "Submit": "Изпращане",
    "Reset Zoom": "Нулиране на мащаба",
    "Zoom In": "Увеличавам",
    "Zoom Out": "Отдалечавам",
    "Deploy": "Разположете",
    "Export": "Експортиране",
    "Overview": "Преглед",
    "Design Permission": "Разрешение за проектиране",
    "Application Permission":"Разрешение за приложение",
    "All Designers": "Всички дизайнери",
    "Private(only you)": "Лично (само ти)",
    "Specific Designer Group": "Специфична дизайнерска група",
    "Submission Permission": "Разрешение за подаване",
    "All Users": "Всички потребители",
    "Specific User Group": "Конкретна потребителска група",
    "Specific Reviewers":"Конкретни рецензенти",
    "All Reviewers":"Всички рецензенти",
    "Permission for application tracking.":"Разрешение за проследяване на приложения.",
    "Design Bundle": "Дизайн пакет",
    "Workflow": "Работен процес",
    "Bundle Name and Description is Required": "Името и описанието на пакета са задължителни",
    "Bundle Description is Required": "Изисква се описание на пакета",
    "Bundle Create Successfully": "Пакетът е създаден успешно",
    "Bundle updated successfully": "Пакетът е актуализиран успешно",
    "Select": "Избери",
    "Unselect": "Отмени избора",
    "Applicable for Designer Roled Users only.": "Приложимо само за потребители с права на дизайнер.",
    "Applicable for Client and Reviewer Roled Users only.": "Приложимо само за потребители с права на клиент и рецензент.",    "Roles": "роли",
    "Users": "потребители",
    "Done":"Свършен",
    "Failed to update permission!":"Неуспешно актуализиране на разрешението!",
    "Failed to fetch roles!":"Неуспешно извличане на роли!",
    "Failed to update role!":"Неуспешно актуализиране на ролята!",
    "Permission updated successfully!":"Неуспешно актуализиране на ролята!!",
    "Role updated successfully!":"Ролята е актуализирана успешно!",
    "Update failed!":"Неуспешна актуализация!",
    "Clear":"ясно",
    "Are you sure deleting the role":"Сигурни ли сте, че изтривате ролята",
    "Confirm Delete":"Потвърдете Изтриване",
    "All roles":"Всички роли",
    "Filter By:":"Филтриране по:",
    "Create":"Създавайте",
    "Eg: Account Manager":"Например: Мениджър на акаунти",
    "Search by name, username or email":"Търсете по име, потребителско име или имейл",
    "No data Found":"Няма намерени данни",
    "Create New Role": "създайте нова роля",
    "Search by role name": "търсене по име на роля",
    "Role Name": "име на ролята",
    "Actions": "действия",
    "Create Role": "създайте роля",
    "Email": "електронна поща",
    "Role": "Роля",
    "Add Role": "Добавяне на роля" ,
    "Role deleted successfully!": "Ролята е изтрита успешно!",
    "Failed to delete role!": "Неуспешно изтриване на роля!",
    "Role created successfully!": "Ролята е създадена успешно!",
    "Failed to create role!": "Неуспешно създаване на роля!",
    "Update success!":"Успешна актуализация!",
    "No results found":"Няма намерени резултати",
    "Edit Role":"Редактиране на роля",
    "Failed to fetch users!":"Неуспешно извличане на потребители!",
    "Role names cannot contain special characters except   _ , -": "Имената на ролите не могат да съдържат специални знаци освен _, -",
    "Role names cannot contain special characters except _ , - , / ": "Имената на ролите не могат да съдържат специални знаци освен _, -, /",
    "Rules deployed successfully": "Правилата са внедрени успешно",
    "Choose From Template": "Изберете от шаблона",
    "Back to forms": "Обратно към формите",
    "Choose From Templates": "Изберете от шаблоните",
    "Explore our Template Library to find the perfect combination of forms and workflows. Click to preview a template and, if it fits your needs, customize it to your liking. Once you've tailored it to your specific requirements, you're all set to create your business case": "Разгледайте нашата библиотека с шаблони, за да намерите идеалната комбинация от форми и работни потоци. Щракнете, за да прегледате шаблон, и ако той отговаря на вашите нужди, персонализирайте го по свой вкус. След като го адаптирате към конкретните си изисквания, сте готови да създадете вашето делово предложение",
    "All templates": "Всички шаблони",
    "Template count": "Брой шаблони",
    "Learn more": "Научете повече",
    "Template Details": "Детайли за шаблона",
    "Template Title": "Заглавие на шаблона",
    "Preview Form": "Преглед на формуляра",
    "Connected Workflow": "Свързан работен процес",
    "Delete Template": "Изтриване на шаблона",
    "Use Template": "Използване на шаблона",
    "Template created successfully": "Успешно създаден шаблон",
    "Template deleted successfully": "Успешно изтрит шаблон",
    "Template updated successfully": "Успешно актуализиран шаблон",
    "Category": "Категория",
    "Search category...": "Търсене в категория...",
    "Save as Template": "Запазване като шаблон",
    "Create Template": "Създаване на шаблон",
    "Select or Create Category": "Избор или създаване на категория",
    "Short Intro": "Кратко представление",
    "Enter short intro": "Въведете кратко представление",
    "Enter description": "Въведете описание",
    "Select or create": "Избор или създаване",
    "Update Template": "Актуализиране на шаблона",
    "Form created successfully": "Успешно създадена форма",
    "select or create": "Избор или създаване",
    "Update Associated Form": "Актуализиране на свързан формуляр",
    "Update Associated Workflow": "Актуализиране на свързан работен процес",
    "Enter title": "Въведете заглавие",
    "No Templates Found": "Не са намерени шаблони",
    "No Category Found": "Не са намерени категории",
    "Save Template": "Запазване на Шаблона",
    "You can type and click the ": "Можете да пишете и щракнете върху",
    "to create the category.": " за създаване на категорията.",
    "select or type to create": "изберете или въведете, за да създадете"

    

  };
